### ISSUE TITLE
ReferenceError: jsoneditor is not defined

### ISSUE THREAD

**Issue by drveresh** [josdejong/jsoneditor#100]
Hi,

It just started throwing this error message "ReferenceError: jsoneditor is not defined" on screen upon loading, in lastest Chrome browser..  I did clear all its cookies etc, but issue remains same.  But, it is working in Incognito mode.

Why this weird behavior?

Here is the screenshot - http://prntscr.com/3p23vz

**Comment by 3330222** [comment]
Hi there:

I have this problem in angular2 and typescript. I do a "npm install tsd -g" and then I do a  "tsd install jsoneditoronline" (reference http://definitelytyped.org/tsd/) and then I included it in my project. here is my code this is the view    <h1>Try Json Editor</h1>

    <p>
    <button (click)="setJSON()">Set JSON</button>
    <button (click)="getJSON()">Get JSON</button>
    </p>
    <div id="jsoneditor" >
    </div>
this is the Component class

    @Component({
    selector: 'json',
    templateUrl: './app/components/jsoneditor/json.html',
    styleUrls: ["./app/components/jsoneditor/json.css"],
    directives: [RouterOutlet]
    })

    @RouteConfig([
    { path: '/', component: StartComponent, as: 'Start', useAsDefault: true },
    { path: '/View/:id', component: ConfigurationViewerComponent, as: 'View' },
    { path: '/Create/*parentId', component: ConfigurationEditorComponent, as: 'Create', data: { action:      'Create' } },
    { path: '/Edit/:id', component: ConfigurationEditorComponent, as: 'Edit', data: { action: 'Edit' } }
    ])

    export class JsonComponent implements OnInit{
    elementRef: ElementRef;
    container: HTMLElement;
    editor1: JSONEditor;
    options;
    json;

    constructor(public router: Router, @Inject(ElementRef) elementRef: ElementRef) {
       this.elementRef = elementRef;           
       this.container = this.elementRef.nativeElement.querySelector('#jsoneditor');       //define the container of the json editor                          
    }                  
   
    setJSON() {        
        this.options = { "mode": "tree", "search": true };           
        this.json = { "Array": [1, 2, 3], "Boolean": true, "Null": null, "Number": 123, "Object": { "a": "b", "c":    "d" }, "String": "Hello World" };       
        alert("now is fine")
       
        var abc = new JSONEditor(this.container, this.options);
        alert("now is not fine")//NOW THERE IS AN ERROR
       //this.editor1.set(json);
       //this.editor1.expandAll();
       
    }

    getJSON() {
        alert("getJson");
    }
    ngOnInit() {
        console.log(this.elementRef.nativeElement.querySelector('#jsoneditor'));//this line is to get the element in html
    }

    }

the error is JSONEditor is not defined

I tried clear the cache and all the way you told in this thread but still not working. 
I also do a "npm install jsoneditor"
any idea would be help? 

great thanks

**Comment by 3330222** [comment]
the is the my detailed error:

Uncaught EXCEPTION: Error during evaluation of "click"
ORIGINAL EXCEPTION: ReferenceError: JSONEditor is not defined
ORIGINAL STACKTRACE:
ReferenceError: JSONEditor is not defined
    at JsonComponent.setJSON (http://localhost:1337/app/components/jsoneditor/json-view.component.js:29:23)
    at AbstractChangeDetector.ChangeDetector_JsonComponent_0.handleEventInternal (eval at <anonymous> (unknown source), <anonymous>:29:32)
    at AbstractChangeDetector.handleEvent (http://localhost:1337/jspm_packages/npm/angular2@2.0.0-beta.0/src/core/change_detection/abstract_change_detector.js:57:20)
    at AppView.dispatchEvent (http://localhost:1337/jspm_packages/npm/angular2@2.0.0-beta.0/src/core/linker/view.js:164:37)
    at AppView.dispatchRenderEvent (http://localhost:1337/jspm_packages/npm/angular2@2.0.0-beta.0/src/core/linker/view.js:159:17)
    at DefaultRenderView.dispatchRenderEvent (http://localhost:1337/jspm_packages/npm/angular2@2.0.0-beta.0/src/core/render/view.js:75:51)
    at eventDispatcher (http://localhost:1337/jspm_packages/npm/angular2@2.0.0-beta.0/src/core/render/view_factory.js:22:19)
    at http://localhost:1337/jspm_packages/npm/angular2@2.0.0-beta.0/src/core/render/view_factory.js:93:14
    at http://localhost:1337/jspm_packages/npm/angular2@2.0.0-beta.0/src/platform/dom/dom_renderer.js:311:32
    at http://localhost:1337/jspm_packages/npm/angular2@2.0.0-beta.0/src/platform/dom/events/dom_events.js:43:16
ERROR CONTEXT:
[object Object]

**Comment by josdejong** [comment]
@3330222 I think this is a different issue, the original one was about opening the webapplication http://jsoneditoronline.org in your browser, your issue is about loading the component JSONEditor in your own application.

Looking at the [TypeScript definition](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/jsoneditoronline) I see it's completely outdated, 2 years old. I guess you have to use it with [JSONEditor v2.3.6](https://github.com/josdejong/jsoneditor/tree/v2.3.6) as that was the latest version at the moment of writing of the TypeScript definition.

**Comment by kumarmuthaiah** [comment]
Hi I'm using Internet explorer version 8. Please let me know why JSONEditor undedfined is coming?

**Comment by kumarmuthaiah** [comment]
Im using json editor 5.13.2. When i run the jsp it is having issue. While run separately as html it is running fine.

**Comment by josdejong** [comment]
> Hi I'm using Internet explorer version 8.

IE 8 is not supported by JSONEditor. Really, you have to upgrade your browser. IE8 isn't maintained since about two years (!), no security updates, you put yourself at risk. http://www.allyncs.com/docs/lifecyclesupport.html 

> Im using json editor 5.13.2. When i run the jsp it is having issue. While run separately as html it is running fine.

Sounds like you have some debugging to do to figure out why the version in html is working and your jsp version not. I can't help you there.

**Comment by User0816** [comment]
I still have this issue with Chrome Version 64.0.3282.167 (Offizieller Build) (64-Bit):
JSONEditor.js:11 Uncaught ReferenceError: require is not defined
    at JSONEditor.js:11

None of the mentioned steps worked for me though..

Interesting:
It works in Firefox

**Comment by josdejong** [comment]
@User0816 how I can I reproduce your issue? Can you create a jsbin/jsfiddle to demonstrate the issue? Are the examples that come with the editor working for you?
