### ISSUE TITLE
Htmls in example dont work

### ISSUE THREAD

**Issue by syedafirdaus06** [josdejong/jsoneditor#1001]
Htmls in examples folder doesnt show up as per description. PFA screenshot for example. As I am trying this for first time, please advise. I have run "npm install jsoneditor" as well. And routed the files in html
`<link href="../src/scss/jsoneditor.scss" rel="stylesheet" type="text/css">
  <script src="../src/js/JSONEditor.js"></script>
`

please advise
<img width="1069" alt="Screenshot 2020-05-29 at 11 40 19 AM" src="https://user-images.githubusercontent.com/13406485/83227276-6c7a9180-a1a1-11ea-9cf8-db4d24f6b672.png">

**Comment by josdejong** [comment]
@syedafirdaus06 you have to load the bundled version of JSONEditor. Please have a look at any of the provided examples in the examples folder or the README.

**Comment by nvomedia** [comment]
If you downloaded the files (or cloned the repo) you need to follow the instructions in misc\how_to_publish about how to generate the files which are needed for the examples.

**Comment by josdejong** [comment]
You indeed have to build the library first. You can follow the readme: 

https://github.com/josdejong/jsoneditor/blob/develop/README.md#build

**Comment by syedafirdaus06** [comment]
Sorry for late response, The problem with me was, i was routing /src/js/JSONEditor.js this file which is wrong. I should have added which comes under node_modules. Once I changed, it started working. 
Thanks for everyone here who helped :)

**Comment by josdejong** [comment]
👍 thanks for reporting back @syedafirdaus06
