### ISSUE TITLE
Crash with "color-hex" format

### ISSUE THREAD

**Issue by eeyshen** [josdejong/jsoneditor#1004]
I found jsoneditor crash if input json like:
```
"color": {
      "format": "color-hex",
      "type": "string"
}
```

**Comment by josdejong** [comment]
Thanks for reporting. I loaded your JSON example in https://jsoneditoronline.org/ but can't reproduce your issue, I do not see a crash. How to reproduce this exactly?

**Comment by eeyshen** [comment]
The json is schema. I get the crash when use it to validate input json.

<img width="930" alt="截屏2020-06-05 下午6 12 10" src="https://user-images.githubusercontent.com/31716017/83864980-1b960a80-a758-11ea-9710-096bf191606f.png">

**Comment by josdejong** [comment]
Can you share your JSON schema and JSON document?

**Comment by eeyshen** [comment]
Schema:
```
{
    "format": "color-hex",
    "type": "string"
}
```
Example:
{
    "color": "red"
}

**Comment by josdejong** [comment]
Thanks now that's a very minimal example 👍 

JSONEditor makes use of `ajv`. The formats that are supported are listed here: https://github.com/ajv-validator/ajv#formats. I do not see `color-hex` listed there. Is this supposed to be an official format of JSON Schema?

**Comment by eeyshen** [comment]
I found it is not an official format in JSON Schema draft 7. Thanks.

**Comment by josdejong** [comment]
:+1:
