### ISSUE TITLE
Feature Request: Show length of an Array

### ISSUE THREAD

**Issue by suraj-ppp** [josdejong/jsoneditor#1005]
Please add a preview for length of an array.
It becomes difficult to get length of an array. I need to use different tool to get length of an array.
I think this feature was there in earlier version.

**Comment by josdejong** [comment]
I'm not sure what you mean: right from an array you see square brackets with the length of the array in between?

**Comment by suraj-ppp** [comment]
yes this is what I ment

**Comment by josdejong** [comment]
The array length _is_ displayed. What is your question then?

**Comment by suraj-ppp** [comment]
[
![Screenshot 2020-06-06 at 5 46 28 PM](https://user-images.githubusercontent.com/62291421/83943972-cae8e500-a81d-11ea-92a8-c7391ff58b7b.png)
](url)

I verified this. It's working on chrome but not on Safari.
Screen shot attached

**Comment by josdejong** [comment]
The screenshot you're showing is in `code` mode. This mode doesn't show array size. If you switch to `tree` mode (left most toggle in the orange/brown menu), you'll see the array sizes.

**Comment by suraj-ppp** [comment]
Got it. Thanks I wasn't aware about this. I was struggling since few days

**Comment by josdejong** [comment]
Yeah, this switch can be confusing indeed. Still thinking if there is another way to make this simpler.
