### ISSUE TITLE
Can you support 'function' type in value ?

### ISSUE THREAD

**Issue by daeunan** [josdejong/jsoneditor#1010]
Hi,
I want to use 'function' type in value.
for Example, field: function() { [value] }
Do you happen to support function type in value? 

Thank you for reading my issues.

**Comment by josdejong** [comment]
Functions are not part of the [JSON data format](https://www.json.org/json-en.html), and therefore are not supported in JSON Editor.

**Comment by josdejong** [comment]
Can you explain why you need this?

**Comment by daeunan** [comment]
I wanted to binding callback function after getting JSON value.
ex) var json = editor.get(); elem.click(json.clickFunction);
If it is impossible, then I will find another ways.
Thank you for give me doc link.

**Comment by josdejong** [comment]
ok clear. Unfortunately functions are not supported in JSON so I guess you'll have to be creative.
