### ISSUE TITLE
JSON Editor not opening

### ISSUE THREAD

**Issue by garimaagarwal-a10** [josdejong/jsoneditor#1012]
Getting below error on -
Google Chrome : Version 83.0.4103.61 (Official Build) (64-bit)
OS: Ubuntu 16

![image](https://user-images.githubusercontent.com/56290060/84623947-06f70680-aefe-11ea-855e-fa3ab325ebc5.png)

**Comment by josdejong** [comment]
The error message give a clear explanation with possible reasons and what to do to resolve this. 

What is exactly your question Garima?

**Comment by garimaagarwal-a10** [comment]
None of the listed works for me.
Just wanted to check is it something to with Google chrome version,?

**Comment by josdejong** [comment]
The JSONEditor application itself didn't change recently. I doubt that it could be related to an updated version of Chrome (if Chrome would lose localStorage data after an update hell would break lose on the internet, we would have heard about it for sure...). I'm not sure how I can help you further with this :(.

**Comment by garimaagarwal-a10** [comment]
Ya Ok Thanks. No issues.
I will look for another editor until then for my work. :)

**Comment by josdejong** [comment]
?

@garimaagarwal-a10 you can simply click the "New" button in the green panel menu's to open a new, empty document.

**Comment by garimaagarwal-a10** [comment]
It worked. Thanks.

**Comment by garimaagarwal-a10** [comment]
closing the issue.

**Comment by josdejong** [comment]
👍
