### ISSUE TITLE
Polyfills affect array 'for in' loop in IE11

### ISSUE THREAD

**Issue by flydyk** [josdejong/jsoneditor#1027]
Hi,

I have in dependency 3rd party modules that use `for (let i in array)` syntax. It works okay except IE11.

See:
```javascript
let arr=['a','b']; 
for(let i in arr) {
  console.log(i);
}

Actual result:
0
1
find

Expected result:
0
1
```

This is because of polyfills coming from **jsoneditor**. Arrays are iterated incorrectly if you define polyfills like:
```javascript
Array.prototype.find = function (e) {
          for (var t = 0; t < this.length; t++) {
            var i = this[t]
            if (e.call(this, i, t, this)) return i
          }
        }
```

Could you please update all your polyfills to a syntax with `Object.defineProperty` construction. This should fix the problem.
```javascript
  Object.defineProperty(Array.prototype, 'find', {
      value: function (e) {
        for (var t = 0; t < this.length; t++) {
          var i = this[t]
          if (e.call(this, i, t, this)) return i
        }
      },
      configurable: true,
      writable: true
    })
```

Thanks!

**Comment by josdejong** [comment]
Sure, I've made a fix for this in b6235a8.

The polyfills that JSONEditor creates are not full fledged. If you depend on these functions in other parts of your application too, it may be a good idea to first load a battle-tested polyfill library like es-shim and es-sham and _after_ that load your libraries.

Please note that using `for...in` to iterate over an Array is a no-go, you should use `for...of` instead, see for example https://stackoverflow.com/questions/3010840/loop-through-an-array-in-javascript

> `for...in` shouldn't be used for array-like objects because:
>
> - The order of iteration is not guaranteed; the array indexes may not be visited in numeric order.
> - Inherited properties are also enumerated.
