### ISSUE TITLE
Ace editor breaks code mode, after setting JSON.

### ISSUE THREAD

**Issue by tomalec** [josdejong/jsoneditor#103]
Hi,
It's hard for me to isolate the issue as ace code is minified.
I'm trying to Web Componentize jsoneditor http://juicy.github.io/juicy-jsoneditor/
It went pretty well, except `mode: "code"` and Ace editor in general.
It seems that after `editor.set( json )` Ace performs sequence of calls that set value to `""` which leads failure, when I `.get()` it on change callback, as it breaks on parsing `""` as JSON.

Example here: http://juicy.github.io/juicy-jsoneditor/bug.html
Maybe it's somehow affected by issue I mentioned at #87. This time I workaround it by loading ace once again on main document.

**Comment by josdejong** [comment]
@tomalec what's the status of this issue?
