### ISSUE TITLE
how to programmablely change header color

### ISSUE THREAD

**Issue by hoogw** [josdejong/jsoneditor#1040]
Yes, you can simply override the color with your own CSS. Just open your developer console and have a look at the class names used for background and border colors, and override it with your own color schema.

_Originally posted by @josdejong in https://github.com/josdejong/jsoneditor/issues/879#issuecomment-571960194_

**Comment by hoogw** [comment]
I need programmable change color, for example:


       `       jsoneditor.option = {

         header: black
         border:  red

      }
`


`.jsoneditor .value[style*="color: green;"] {
    color: lime !important;
}

.jsoneditor .value[style*="color: red;"] {
    color: rgb(75, 193, 255) !important;
}`


But I can't find document talk about this, only some issue talk about color change by update css.

How to do it programmablely?

**Comment by hoogw** [comment]
`var options = {
            header-color : 'yellow',
            theme: 'dark',


          };`

Can we set options to change color when initialize json-editor?

**Comment by josdejong** [comment]
Maybe this helps? 

https://stackoverflow.com/questions/1720320/how-to-dynamically-create-css-class-in-javascript-and-apply

**Comment by hoogw** [comment]
dynamic create css and apply is not what I want. 

I want create 2 json-editor with different color at the same time. 

One json-editor header is blue (default) color

secon json-editor header is green color

Both editor show on same page side by side, just like [your demo](https://jsoneditoronline.org) 

Can you make your demon 2 editor with 2 different header color?

**Comment by josdejong** [comment]
What you can do is give the containers where you attach the JSONEditors different classes:

```html
<div class="editor1"></div>
<div class="editor2"></div>
```

then create different styling for the different containers:

```css
div.editor1 div.jsoneditor-menu {
  background-color: red;
}

div.editor2 div.jsoneditor-menu {
  background-color: blue;
}

```

**Comment by hoogw** [comment]
@josdejong  it perfectly fit my need. works great !

I customize ,  selector by  id 
jsoneditor_list ,  jsoneditor_info_list


<img width="794" alt="image" src="https://user-images.githubusercontent.com/419582/87057307-8e612e00-c1bb-11ea-9ce1-8c30698bdd9b.png">
 
This is result:

same page, with 2 tab,  each tab has different color

first tab
<img width="1444" alt="image" src="https://user-images.githubusercontent.com/419582/87057868-3ecf3200-c1bc-11ea-90e7-250d353d8f77.png">

second tab
<img width="1394" alt="image" src="https://user-images.githubusercontent.com/419582/87057946-57d7e300-c1bc-11ea-91aa-8ec11b1bcde1.png">
