### ISSUE TITLE
Custom click on createMenu does not have access to node context

### ISSUE THREAD

**Issue by Experiment8** [josdejong/jsoneditor#1043]
Hello there,

I have an issue with the custom menu creation through `onCreateMenu`.

Basically I'm building it following some configuration of mine, no problem with it, my problem is that the `click` method that you can setup, has no clue about what node is calling it.

This is problematic when you want to add things to the tree with custom methods, because you have no context of where the click handler was called from.

Now it looks like this:

```
click: () => { [No context about the place which was called from] }
```

I believe it makes much more sense if we add the node to know the path and other important elements:

```
click: (node) => { [No context about the place which was called from] }
```

Is possible indeed to put handlers in each item with the context coming from my methods, but this would drastically help reusability of the code and one central point to balance the events from.

Maybe there is already a solution I'm not aware of, but I couldn't find any.

Thanks a lot!

**Comment by josdejong** [comment]
Thanks for your input Roberto.

The `onCreateMenu` is invoked with the following arguments:

```js
onCreateMenu: function (items, node) { 
  // ...
}
```
So I think when creating the click callbacks you can utilize the `node` argument passed along with `onCreateMenu`. Does that solve your issue?

**Comment by Experiment8** [comment]
Ehy there,

Yep makes sense, in my case I had a static configuration interfacing with onCreateMenu, but I can make it dynamic then.
Thanks a lot!
