### ISSUE TITLE
Detect syntax error fix

### ISSUE THREAD

**Issue by saroad2** [josdejong/jsoneditor#1047]
When using the json editor and a sytax error is occurring, I'm detecting it using the "error" event, which disables my "accept" button of the json editor, preventing the user from accepting incorrect json.

I need some way to detect that the error was fixed in order to reenable the "accept" button.
Is there a nice way of doing it?

I tried to use the "onChange" handler, but it keeps triggering all the time, even when the content is still broken. I can't use "onChangeJSON" since it's not available in "code" mode, which I'm using.

Any help would be much appreciated.

**Comment by josdejong** [comment]
You can check whether the text contents contain valid JSON by running `JSON.parse(text)`, which throws an exception when the text is no valid JSON. Is that what you mean?

**Comment by saroad2** [comment]
It is what I mean, but I managed to find a solution which I think is a little bit better.
Here is the example in my code, using Vuetify and JsonEditor:

```vue
<template>
    <v-card>
        <v-card-title>
            Content
        </v-card-title>
        <v-card-text>
            <v-jsoneditor :options="jsonEditorOptions" v-model="jsonContent" @error="jsonContentError">
            </v-jsoneditor>
        </v-card-text>
        <v-card-actions>
            <v-spacer></v-spacer>
            <v-btn
                    color="primary"
                    text
                    @click="cancelTextArea"
            >
                Cancel
            </v-btn>
            <v-btn
                    color="primary"
                    text
                    @click="acceptTextArea"
                    :disabled="acceptDisabled"
            >
                Accept
            </v-btn>
        </v-card-actions>
    </v-card>
</template>

<script>
    import {mapActions, mapGetters} from "vuex";
    import {cloneDeep} from "lodash";

    export default {
        name: "JsonContentEditor",
        data() {
            return {
                jsonContent: {},
                acceptDisabled: false,
            }
        },
        computed: {
            ...mapGetters({savedJsonContent: "jsonContent"}),
            jsonEditorOptions() {
                return {
                    onValidate: this.jsonContentFix,
                    mode: "code"
                }
            }
        },
        methods: {
            ...mapActions(["loadJsonContent"]),
            cancelTextArea() {
                this.$emit("cancelJsonEditor");
            },
            acceptTextArea() {
                this.loadJsonContent(this.jsonContent);
                this.$emit("acceptJsonEditor");
            },
            jsonContentFix() {
                this.acceptDisabled = false;
            },
            jsonContentError() {
                this.acceptDisabled = true;
            }
        },
        created() {
            this.jsonContent = cloneDeep(this.savedJsonContent);
        }
    }
</script>

<style scoped>

</style>
```

As you can see, when an error event is fired, I call `jsonContentError` which disables the "accept" button. When the json content is fixed, the `onValidate` method is called and reenable the "accept" button. It works very nicely.

However, I think you should consider adding a "fix" event additionally to the "error" event, which indicates that the json syntax error was fixed.

If you disagree, feel free to close the issue. If you agree, please let me know and I'll move forward and implement it.

**Comment by josdejong** [comment]
I think `onValidationError` is what you're looking for. It reports validation errors when you're using JSON schema or custom validation, but also reports when a parse error occurs and when it is resolved.

See example: https://github.com/josdejong/jsoneditor/blob/develop/examples/22_on_validation_event.html

**Comment by josdejong** [comment]
Will close this issue now, feel free to reopen if not yet resolved.
