### ISSUE TITLE
An error occurs Promise in IE 11 .

### ISSUE THREAD

**Issue by daeunan** [josdejong/jsoneditor#1054]
Hi,

'Promise undefined. Please load a Promise polyfill in the browser in order to use JSONEditor' An error occurs Promise in IE 11.
How to fix it?

![error](https://user-images.githubusercontent.com/64052701/88004139-5b1a8980-cb41-11ea-99e6-7eeb79ae17ce.PNG)

**Comment by josdejong** [comment]
The error explains what to do to solve this: before loading the JSONEditor, you have to load a polyfill for `Promise`. For example https://www.npmjs.com/package/promise-polyfill.

**Comment by daeunan** [comment]
I solved it.
Thank you for your kind answer.

**Comment by josdejong** [comment]
👍
