### ISSUE TITLE
save to url is not working

### ISSUE THREAD

**Issue by mocklets-tech** [josdejong/jsoneditor#1056]
previously, for saving to URL
we can read the request body, but after the UI update, the request body is always coming as `{}`.

in request header, content-type is set as `text/plain,` instead of `application/json`
`Content-Type: text/plain;charset=UTF-8`

is it intended?

**Comment by josdejong** [comment]
Thanks for reporting @mocklets-tech . The content-type is not on purpose like this, should indeed be `application/json`. Will fix this asap.

**Comment by josdejong** [comment]
This is fixed now in https://jsoneditoronline.org v5.5.9 (you can find the version in the "About" popup)
