### ISSUE TITLE
Uncaught ReferenceError: JSONEditor is not defined

### ISSUE THREAD

**Issue by Alcampopiano** [josdejong/jsoneditor#1058]
Hello,

I am a Python programmer but I'm fairly new to the web side of things. I would like to use jsoneditor in my web application.

I pasted the [basic usage](https://github.com/josdejong/jsoneditor/blob/develop/examples/01_basic_usage.html) example into [this JS fiddle](https://jsfiddle.net/sv9cx1b8/1/) and I get the error `Uncaught ReferenceError: JSONEditor is not defined` (Chrome 83.0.4103.61). As I'm pretty new to this kind of programming, I wondered if you could help me to understand why this error occurs (probably due to my lack of understanding about how to use jsoneditor).

Any guidance would be greatly appreciated.

**Comment by Alcampopiano** [comment]
My apologies. I have learned that I need to built the JS and put it in a folder called dist, or use cdnjs to get the JS.

This tool is absolutely amazing. I really appreciate all of the incredible work here.

**Comment by josdejong** [comment]
👍 good to hear you figured it out. Enjoy exploring the JavaScript universe 😄 .
