### ISSUE TITLE
specify schema as a url

### ISSUE THREAD

**Issue by Alcampopiano** [josdejong/jsoneditor#1059]
Hello,

Is there a way to specify the schema as a url? 

In the [schema validation example](https://github.com/josdejong/jsoneditor/blob/develop/examples/07_json_schema_validation.html), the schema is given directly in text, and this of course works perfectly. 

I am using the schema from the [vega lite library](https://vega.github.io/schema/vega-lite/v2.json) which is quite large and was hoping to point jsoneditor to its schema via url.

I am new to this kind of programming so apologies if I'm missing something obvious. Any pointer in the right direction would be greatly appreciated.

**Comment by josdejong** [comment]
Yes you can load the JSON document and/or a JSON schema from a url. This functionality however is not built in the library itself. What you normally do is 

1. Show a "loading..." message in your webpage 
1. Fetch the JSON schema from a url using [`fetch`](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch) or your favorite fetch library (maybe with authorization and everything).
2. Remove the "loading..." message, create JSONEditor with the fetched schema.

**Comment by Alcampopiano** [comment]
Thanks very much for the kind pointers. I have a feeling that the loading message you suggested may be a necessary step as my simple example does not show an error, but fails to include the validation. My basic thought was to assign the fetched JSON to a variable and pass that to the options array.

I'm just learning about promises and fetch in general so it is slow going at the moment. Is my failure here due to the schema not being loaded by the time the editor is shown?

```javascript
var schema
  
fetch('https://vega.github.io/schema/vega-lite/v2.json')
  	.then(res => res.json())
  	.then(data => schema = data)
  
const json = {
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "description": "A simple bar chart with embedded data.",
  "data": {
    "values": [
      {"a": "A", "b": 28}, {"a": "B", "b": 55}, {"a": "C", "b": 43}]
  },
  "mark": "bar",
  "encoding": {
    "x": {"field": "a", "type": "nominal"},
    "y": {"field": "b", "type": "quantitative"}
  }
}

const options = {
    schema: schema,
    mode: 'tree',
    modes: ['code', 'text', 'tree', 'preview']
  }

// create the editor
const container = document.getElementById('jsoneditor')
const editor = new JSONEditor(container, options, json)
```

**Comment by Alcampopiano** [comment]
Ah! Success! 

I failed to account for the asynchronous nature of fetch and promises. Once I put the call to JSONEditor insise the `then` method, everything worked as expected!

I hope this is an acceptable way to accomplish this. Thanks again for all your help.

```javascript
let schema = {};

let make_editor = function() {

    const json = {
    "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
    "description": "A simple bar chart with embedded data.",
    "data": {
      "values": [
        {"a": "A", "b": 28}, {"a": "B", "b": 55}, {"a": "C", "b": 43}]
    },
    "mark": "bar",
    "encoding": {
      "x": {"field": "a", "type": "nominal"},
      "y": {"field": "b", "type": "quantitative"}
    	}
    }

    const options = {
      schema: schema,
      mode: 'tree',
      modes: ['code', 'text', 'tree', 'preview']
    }

    // create the editor
    const container = document.getElementById('jsoneditor')
    const editor = new JSONEditor(container, options, json)
};
  

fetch('https://vega.github.io/schema/vega-lite/v2.json')
  	.then(function(resp) {
    	return resp.json();
  	})
  	.then(function(data) {
        schema=data
        make_editor();
       });
```

**Comment by josdejong** [comment]
💪 

Thats indeed a good solution, though I would pass `schema` as an argument of your function `make_editor` instead of defining a global variable.
