### ISSUE TITLE
Build: minimalist only

### ISSUE THREAD

**Issue by kczx3** [josdejong/jsoneditor#1063]
Would it be possible to add an npm script that only builds the minimalist versions?  I use the minimalist version but the total build time is almost doubled by running all the tasks instead of being able to just specify the minimalist.

If there's a simple way for me to do this on my end that's fine.  I'm just not familiar at all with gulp.  Thanks!

**Comment by josdejong** [comment]
I suppose you have a fork of the project and some customizations? You can have a look at the bottom of the gulp file where you see the `default` script defined. You can copy that and name it `minimalist` or so, and remove the full build there.

**Comment by kczx3** [comment]
Nope, no fork or customizations at all.  I just want to use the minimalist build.

I suppose the other option is to have this repo provide the builds.  We don't currently use a build system at all.  Very much a traditionally website.  This is the only front-end dependency that I have to manually install the dependencies and run the build task.  All the others come with dists already.

**Comment by josdejong** [comment]
Ok. The builds are available on npm and various cdn's, there should be no need to build anything yourself.

**Comment by kczx3** [comment]
My legacy codebase that I took over uses Bower and it doesn't appear there is any dist directory so I've been building it myself.

**Comment by josdejong** [comment]
The repository indeed only contains the source code. Bower has been deprecated for years already. I hope you can find a solution. Maybe you can gradually migrate you legacy code base towards npm.

**Comment by kczx3** [comment]
Alright thanks.  Will do!  I don't think it should be too hard. :)
