### ISSUE TITLE
schema validation - "Error: unknown format"

### ISSUE THREAD

**Issue by Alcampopiano** [josdejong/jsoneditor#1064]
Hello,

When I use jsoneditor to validate a schema from the visualization library [vega lite](https://github.com/vega/schema), I get the error `"Error: unknown format "color-hex" is used in schema at path "#/definitions/HexColor"`. If I switch to an older specification from that group, I do not get that error. I've reported this to them in their slack channel but I have not gotten a response (which is totally fine, and could be simply because they feel it is not their issue).

Does this seem like strictly a vega lite issue to you?

Any intuition you might have would be sincerely appreciated.

**Comment by josdejong** [comment]
Thanks for reporting. 

This sounds similar to #1004, is it the same issue?

**Comment by Alcampopiano** [comment]
Yes. It is exactly the same. Thank you for pointing me to that post.

I think I understand the broad strokes here: The Vega lite folks likely do not use avj to validate their specs since the schema works in [their online editor](https://vega.github.io/editor/#/). 

The avj folks appear to be [working on issues](https://github.com/ajv-validator/ajv/issues/1198) related to JSON schema draft 7 AFAICT.

I don't know much about this level of schema validation; however, I'm hoping I can just delete the incompatible sections from the vega lite schema and, for now, lose validation in certain areas (which I believe I'm fine with).

Does this sound reasonable to you?

**Comment by josdejong** [comment]
I do not know the underlying issue, but removing the incompatible sections for now sounds like a pragmatic solution.

**Comment by josdejong** [comment]
Will close this issue now
