### ISSUE TITLE
Question: Can we see more than 20k characters in preview mode.

### ISSUE THREAD

**Issue by rameshwar-jadhav** [josdejong/jsoneditor#1070]
In **preview mode** we can see **upto 20000 characters** of the json and then ellipses(...) gets appended to the json. 
In our scenario we need to block users to edit json but allow to copy complete json thats why we can not use **code mode** here and preview mode will work. 

As I checked it passes through a check from constant.js 
MAX_PREVIEW_CHARACTERS = 20000;
One way is we can increase this limit but as we are using `npm install` approach it will not work.

Is there any way available to see complete json in **preview** mode?

**Comment by josdejong** [comment]
The preview mode is intended for very large JSON documents, too large to render. The 20000 characters limit is a bit arbitrary, it was chosen such that it at least fills the whole screen. 

If you're not working with very large documents and you simply want readonly access, you can use the `view` mode, or maybe use the `tree` mode in combination with a custom `onEditable` handler which gives you fine grained control over what fields are editable and which fields not.

**Comment by rameshwar-jadhav** [comment]
@josdejong Thanks for quick response and yes I agree with you.
Actually I have custom generated dashboard's JSON which can vary in length. I tried with `view` mode but here user can not copy JSON. 
I didn't understand the point that In `code` mode we are showing whole JSON (I checked upto 78000 characters) then can we make preview mode also configurable like flag based PREVIEW_COMPLETE_JSON = true/false. 

If you think this approach is ok then I can create a Pull Request of it, Or If you have any other suggestion that is also fine.

**Comment by rameshwar-jadhav** [comment]
> @josdejong Thanks for quick response and yes I agree with you.
> Actually I have custom generated dashboard's JSON which can vary in length. I tried with `view` mode but here user can not copy JSON.
> I didn't understand the point that In `code` mode we are showing whole JSON (I checked upto 78000 characters) then can we make preview mode also configurable like flag based PREVIEW_COMPLETE_JSON = true/false.
> 
> If you think this approach is ok then I can create a Pull Request of it, Or If you have any other suggestion that is also fine.

@josdejong Any update on this will be helpful.

**Comment by josdejong** [comment]
Again:

> The preview mode is intended for very large JSON documents, too large to render. 

Large as in up to 500 GB documents. An option like `PREVIEW_COMPLETE_JSON` feels to me like duplicating functionality that is already there: you can use code or text mode, and use the option `onEditable` to make text and code mode readonly too (just let the function return `false` for the root node or just always return `false`).
