### ISSUE TITLE
Custom code editor

### ISSUE THREAD

**Issue by micky7s** [josdejong/jsoneditor#1071]
Hi, 
Is it possible to use custom code editor?
I mean other than ace.

Thanks

**Comment by josdejong** [comment]
It is not possible to drop in a replacement for the built-in Ace editor. It possible though to create your own mode. This will require some work though. 

Creating a new mode is not documented but you can look in the code how this is done with the existing modes. Each mode is a sort of a mixin, which is supposed to have certain required methods like `get()`, `set(json)`, `getText()`, `setText(jsonText)`, `update(json)`, etc. It may be possible to create a new mode mixin which extends the existing `code` mixin, not sure though if that will actually make things easier or not.

Here some pointers to the code:

https://github.com/josdejong/jsoneditor/blob/develop/src/js/JSONEditor.js#L474
https://github.com/josdejong/jsoneditor/blob/develop/src/js/textmode.js#L1045-L1059

**Comment by micky7s** [comment]
Great, thanks. I will try to create my own mode. Dodn't thought of that.

Meanwhile I have succeeded to use CodeMirror in 'code' mode.

I have added this in options:

`onModeChange: function(newMode, oldMode){
     if (newMode === 'code'){
		var codeEditor = CodeMirror.fromTextArea(document.getElementsByClassName("jsoneditor-text")[0], {
            name: "javascript",
            json: true,
            styleActiveLine: true,
            lineNumbers: true,
        });
	}
}`

Maybe it'll be usefull to somebody

**Comment by josdejong** [comment]
👍  thanks for sharing your solution.
