### ISSUE TITLE
No default jsDelivr CDN file set

### ISSUE THREAD

**Issue by ultrageek** [josdejong/jsoneditor#1077]
[This package](https://www.jsdelivr.com/package/npm/jsoneditor) doesn't have a [default file](https://www.jsdelivr.com/features#publishing-packages) set. You can set it via `jsdelivr`, `browser`, or `main` field in `package.json`

**Comment by josdejong** [comment]
Thanks for reporting, I've changed the field `main` to point to the actual bundled file instead of to a node.js index file.

**Comment by josdejong** [comment]
Should be fixed now in `v9.0.4`
