### ISSUE TITLE
menu on top bar

### ISSUE THREAD

**Issue by inVisement** [josdejong/jsoneditor#1089]
It might be a question. How can I put the menu on top bar instead of next to each field?

**Comment by josdejong** [comment]
There is no option for that, having a context menu per node is baked in the core of the editor.

I'm working on a completely new version of the JSONEditor where I try a different approach though, making the editor more similar to a regular text/code editor. The context menu buttons are removed and all actions are done via a menu on top (or maybe it can become a floating menu right above the selection or a right click context menu). This is in very early stage but I'm very exited about it. Here a screenshot:

![afbeelding](https://user-images.githubusercontent.com/568626/90600614-2f99c600-e1f7-11ea-86a3-ca7635b093d4.png)
