### ISSUE TITLE
Disable all editing (i.e. read-only mode)

### ISSUE THREAD

**Issue by drpepper** [josdejong/jsoneditor#109]
Great project! We're using it for https://github.com/CyberCRI/RedWire and loving it!

I have seen a few related discussions around making specific fields read-only, but I am looking for something simpler, just a global "read-only" toggle. Any tricks would be helpful...

**Comment by rupeshfend** [comment]
How can I disable the json-editor with keeping the mode as 'code' ?

**Comment by josdejong** [comment]
@rupeshfend there is no readOnly option for `code` mode. You can do two things:

- Do some hacking around the editor: apply `editor.aceEditor.setReadOnly(true)`, and disable or hide the buttons of the main menu with some CSS. Disabling keyboard shortcuts to for example format/compact the code is more tricky, that requires intercepting a keydown event handler in the editor. Not sure if that is easy to do.
- Switch to the successor of this library, [`svelte-jsoneditor`](https://github.com/josdejong/svelte-jsoneditor/): it has a `readOnly` option for every mode.
