### ISSUE TITLE
"Cannot read property 'type' of null" from passing blank name

### ISSUE THREAD

**Issue by joshkel** [josdejong/jsoneditor#1096]
If a JSONEditor instance is constructed with an empty string as the name, then the constructor throws with the following error:

> Cannot read property 'type' of null

Demo: https://codesandbox.io/s/jsoneditor-blank-name-9db9p

The error is thrown by [this line](https://github.com/josdejong/jsoneditor/blob/b48ec899538af3ffd32da369a3997d45c40e98d6/src/js/Node.js#L1856) of Node._updateDomField, although I haven't familiarized myself enough with JSONEditor to know what the correct fix is.

**Comment by josdejong** [comment]
Thanks for reporting this bug Josh! The line of the code that you're pointing can very well be the cause.

**Comment by josdejong** [comment]
That was indeed the cause. I've created a fix in b214915 (not yet published)

**Comment by joshkel** [comment]
Thanks for the quick reply!

**Comment by josdejong** [comment]
The fix has been published now in `v9.0.5`. Sorry for the delay.

**Comment by joshkel** [comment]
No problem. Thanks again.
