### ISSUE TITLE
Long int overflows on format

### ISSUE THREAD

**Issue by tonci14** [josdejong/jsoneditor#1106]
`{"some_id": 2009000000000135983}`

and when I click on "Format JSON data..." 

```
{
  "some_id": 2009000000000136000
}
```

**Comment by josdejong** [comment]
Thanks for reporting Anton. The reason is that JSONEditor uses the built-in JavaScript JSON parser, which uses number, which cannot hold values with as much digits as in your example.

It's a long standing wish to get this fixed: #231
