### ISSUE TITLE
Behaviour change in "copy left" or "copy right"

### ISSUE THREAD

**Issue by tonysamperi** [josdejong/jsoneditor#1107]
**Steps to reproduce**

1. Paste a plain javascript object (non-quoted)
2. Click "copy right" (A valid tree representation of the left panel appears)
3. Click "copy left"

**What happens now**

Nothing hapens

**What used to happen**

A well-formatted version of the json appeared on the left panel

It there any chance to restore the previous behaviour? It was very handy to format JSON files on the fly...

**Comment by josdejong** [comment]
Thanks for reporting. I understand. The new web application is a bit more lazy, it figures that when you just copy from left to right and back, nothing did change. I noticed some other edge cases where this lazy behavior gives unexpected results, so I would like to address that.

Please note that there is a special button to format the code: 

![afbeelding](https://user-images.githubusercontent.com/568626/92998816-79d34600-f51c-11ea-850e-e42908991e1c.png)

Those buttons do have quickkeys too, but those seem not to work anymore. I'll look into that

**Comment by tonysamperi** [comment]
@josdejong thanks for the reply!
Yes, I just tried the format button and it does nothing...that could also be an option, to autofix the json (when possible, of course) without copying from one pane to another.

**Comment by josdejong** [comment]
> Yes, I just tried the format button and it does nothing...

That's odd, format and compact should work, except for the quick-keys:

![format-compact-json](https://user-images.githubusercontent.com/568626/93249566-c83d4a80-f791-11ea-8588-a0830dc3fac4.gif)

**Comment by tonysamperi** [comment]
![jsoneditor-test](https://user-images.githubusercontent.com/5957244/93342146-47cd2700-f82f-11ea-9138-97d8d0268f68.gif)

Sorry, I meant that the button does nothing when an invalid json is provided.

In the older version which I have as chrome extension on my browser, it used to fix and format the json!

![old-jsoneditor-test](https://user-images.githubusercontent.com/5957244/93342400-98dd1b00-f82f-11ea-864a-e43df1d6c494.gif)

**Comment by josdejong** [comment]
Ah, you mean the repair button?

![afbeelding](https://user-images.githubusercontent.com/568626/93362956-e7e27a80-f846-11ea-9459-2102056bb859.png)

I still have plans to proactively show a message on top when there is a broken json which is repairable, that should make it easier. And as discussed already I want to address the "lazyness" that's currently between the two panels.

**Comment by tonysamperi** [comment]
Ok I didn't notice the repair button. That actually fixes the json.
But I still prefer the old behaviour: I it could try repairing automatically when clicking the format button...
I'm lazy and prefer 1 click instead of 2 😂
Anyway I think I can now do everything without any problems...I just have to use the button
![image](https://user-images.githubusercontent.com/5957244/93363696-e4032800-f847-11ea-886f-4d1b3435f1e1.png)

Thanks Jos!

**Comment by josdejong** [comment]
👍 Thanks for your inputs, I've a pretty good idea how to improve this further. Will close this issue now, the improvements are on my list.
