### ISSUE TITLE
unexpected escape characters

### ISSUE THREAD

**Issue by kishore036dev** [josdejong/jsoneditor#1118]
Hi,
My issue is similar to #115

I have loaded the editor with a JSON string passed down from server to html page and I noticed that all the quote characters received an extra escape character.  In java script, I am not converting into JSON object and stringify. Still facing issue.

When I use alert() and view data using javascript, I can see with out backslash, but editor I can see

I have tried lot of ways, but still unable to remove it..

Please help me..

![issue](https://user-images.githubusercontent.com/71698647/93904683-ba4e7300-fd17-11ea-801d-0ebf323fdd11.jpeg)

**Comment by josdejong** [comment]
@kishore036dev you're probably loading your data as text. You can either:

-   load as text when your data is text: 
    ```js
    editor.setText(response)`
    ```
-   parse your data as JSON and load it:
    ```js
    editor.set(JSON.parse(response))
    ```

**Comment by kishore036dev** [comment]
Thank you so much @josdejong . It's working now..

**Comment by josdejong** [comment]
👍
