### ISSUE TITLE
Unable to scroll the on the list of keys of the object.

### ISSUE THREAD

**Issue by techhandler** [josdejong/jsoneditor#1119]
Click on treepath breadcrumb, 

![image](https://user-images.githubusercontent.com/25566724/94368745-81d9db00-0103-11eb-8ca4-10cad9627d65.png)

List of all the keys in the object shows up, from where we can navigate to a particular key of that JSON, but unable to scroll when there are more keys:

The following screenshot shows object having around 50 keys but only 22 items are accessible and others are hidden.

![image](https://user-images.githubusercontent.com/25566724/94368626-c618ab80-0102-11eb-83af-98e94cbde06f.png)

**Comment by josdejong** [comment]
Thanks for reporting! We should give the menu a max height and scroll bar in those cases.
