### ISSUE TITLE
onEvent function not firing over boolean value [checkbox]

### ISSUE THREAD

**Issue by kkodor** [josdejong/jsoneditor#1126]
Hi jsoneditor devs folks,

I am having an issues to get a trigger or callback from:

`{function} onEvent({ field, path, value? }, event)`

it works fine when I hover over an field but as soon as I try a click or mouseover over an boolean checkbox it does not fire. 
It only fires when I move the mouse over textfield that indicates true or false or the key identifier text field.
In case a user is clicking here I will miss the event.
Any ideas? Thanks for spending time for development of the jsoneditor, I appreciate it and also thanks for your respone

Best 
kko

**Comment by josdejong** [comment]
That's an interesting case, thanks for bringing this up.

Currently the events only fire when you're doing something in the `field` input or the `value` input. Makes sense to also have it trigger on a boolean checkbox, and an enum dropdown.

**Comment by josdejong** [comment]
This is fixed now in `v9.1.2`
