### ISSUE TITLE
How to disable drag and other actions

### ISSUE THREAD

**Issue by vigneswarandavarapu** [josdejong/jsoneditor#1134]

**Comment by josdejong** [comment]
Have you seen the modes 'form' and 'view'? Is that what you mean?

**Comment by vigneswarandavarapu** [comment]
thanks for your information, 
below change is working for mr

`        this.editorOptions.mode = 'form';
`

**Comment by vigneswarandavarapu** [comment]
thanks for your information, 
below change is working for me

`        this.editorOptions.mode = 'form';
`
