### ISSUE TITLE
customising insert options

### ISSUE THREAD

**Issue by vivissj3** [josdejong/jsoneditor#116]
I would like to use the editor to modify some fairly large JSON objects, for this it would be useful for me to define my own insert options, for example:
- inserting objects with pre-defined sub-fields
- drafts for a whole object, with variable names but no data 
etc.

If it's possible at the moment, could you point me in the right direction?
Or will it be possible with future updates (plugins)?

**Comment by dhughes-xumak** [comment]
See #438.
