### ISSUE TITLE
Disable JSON parsing/validation

### ISSUE THREAD

**Issue by micky7s** [josdejong/jsoneditor#1163]
Hi all,

Is it possible to disable JSON validation?

Thanks

**Comment by josdejong** [comment]
Which JSON validation do you mean? What editor mode?

**Comment by micky7s** [comment]
In text mode I'm receiving or entering QBE(query by example) JSON like so :

```
{ "$and" : [
 \{ "code" : "11" },
 \{ "number" : 23 }
 ]
}
```
Of course there is an error message on bottom saying "Parse error on line .... + details", because of the backslashes.
So if possible, I want to disable somehow JSON parsing/validation

**Comment by josdejong** [comment]
Having valid JSON and knowing whether your JSON is valid or not is kind of essential to the JSON editor. If you don't want to see it you could hide the error message with some custom CSS. 

It feels to me though that you're trying to use the JSONEditor for a data format (QBE) which is simply not supported. I'm not sure if that's a good idea in the first place. JSONEditor is probably not adding much value in such a case, and maybe it's easier to use an other code editor which does support QBE?

**Comment by micky7s** [comment]
Ok, guess you're right. I'll think about it.
Thanks

**Comment by josdejong** [comment]
👍
