### ISSUE TITLE
Feature Request - Not able to build jsoneditor in Angular Universal SSR - ReferenceError window not defined

### ISSUE THREAD

**Issue by Aravin** [josdejong/jsoneditor#1177]
Hi Team,

I am trying to deploy my angular application as SSR.

I am getting the following error,

```
\code\client\dist\epix-io\server\main.js:178727
!function(e,t){ true?module.exports=t():undefined}(window,function(){return n={},r.m=i=[function(e,t,i){"use strict";i.r(t),i.d(t,"parse",function(){return d}),i.d(t,"trySimpleJsonRepair",function(){return u}),i.d(t,"escapeUnicodeChars",function(){return g}),i.d(t,"validate",function(){return p}),i.d(t,"extend",function(){return m}),i.d(t,"clear",function(){return f}),i.d(t,"getType",function(){return C}),i.d(t,"isUrl",function(){return v}),i.d(t,"isArray",function(){return A}),i.d(t,"getWindow",function(){return b}),i.d(t,"getAbsoluteLeft",function(){return y}),i.d(t,"getAbsoluteTop",function(){return w}),i.d(t,"addClassName",function(){return S}),i.d(t,"removeAllClassNames",function(){return x}),i.d(t,"removeClassName",function(){return k}),i.d(t,"stripFormatting",function(){return E}),i.d(t,"setEndOfContentEditable",function(){return R}),i.d(t,"selectContentEditable",function(){return T}),i.d(t,
"getSelection",function(){return _}),i.d(t,"
```

It happens only by building as SSR. Working fine when I build/run as an angular application.

I know that window, the document was not available for the node server.

**Workaround 1:**  using isPlatformBrowser
https://fireship.io/snippets/angular-universal-ssr-cookbook/

**Workaround 2:** using  domino

https://github.com/angular/universal/issues/830#issuecomment-345228799

Kindly suggest any workaround for this.

**Comment by josdejong** [comment]
I'm not sure whether JSONEditor can be rendered server side at all, it's not build for that.

**Comment by Aravin** [comment]
It is Angular Universal SSR (Server Side Rendering).

It will render the page on the server and push it to the client (browser).

**Comment by josdejong** [comment]
Yes I understand you're trying to render the JSONEditor server side. It's just that JSONEditor is not build for that. JSONEditor relies on a real DOM being available. It would be great if it would work server side of course, I just don't know.

**Comment by josdejong** [comment]
Anyone interested in figuring out whether it's possible to get JSONEditor rendered server side? Help would be welcome.

**Comment by Aravin** [comment]
@josdejong 

I made it working using the above workaround 1 in the bug description.

I have wrapped all the jsoneditor references within isBrowser parameter.

and Thank you @josdejong  for the wonderful tool. I love your JSON editor.

I have implemented and it's live: https://www.epix.io/json/editor

**Comment by josdejong** [comment]
Nice to hear it's actually working with this `isBrowser` parameter 👍
