### ISSUE TITLE
JSON Schema enum dropdown not working for integer types

### ISSUE THREAD

**Issue by speedakovic** [josdejong/jsoneditor#1185]
See this jsbin: https://jsbin.com/fitikeqaxo/1/edit?html,output

or do I something wrong?

**Comment by josdejong** [comment]
Thanks for reporting Tomas and for the clear example, fixed via https://github.com/josdejong/jsoneditor/commit/7cce2805b1b7b47d3ce032c310c0d401275d0441 (not yet published).

**Comment by josdejong** [comment]
Fixed now in `v9.1.5`

**Comment by speedakovic** [comment]
Thank You for this great tool.
