### ISSUE TITLE
Providing ajv instance breaks the editor

### ISSUE THREAD

**Issue by magom001** [josdejong/jsoneditor#1191]
Providing user defined Ajv instance as an option breaks on validation.

The problem is with dataPath. Ajv uses some  weird notation with slashes (e.g. `root/object/with/array/0/value`). [This](https://github.com/josdejong/jsoneditor/blob/5fd3edb196964baa8c16998a7be2a24233ef0933/src/js/util.js#L575) thing expects a valid JsonPath.

I do not know on whose side is the problem.

For now I patched json editor to transform ajv notation to jsonpath notation:

```
/**
 * Parse a JSON path like '.items[3].name' into an array
 * @param {string} jsonPath
 * @return {Array}
 */
export function parsePath (p) {
  let jsonPath = p;
  if (jsonPath.include('/')) {
     jsonPath = jsonPath.replace(/\//g, '.').replace(/\.(\d)\./g, '[$1].');
  }
  ...
```

**Comment by josdejong** [comment]
Thanks for reporting. How can I reproduce your issue? And which versions of Ajv and JSONEditor are you using?

**Comment by magom001** [comment]
versions:
```
"jsoneditor": "9.1.5",
"ajv": "6.12.6",
"ajv-errors": "1.0.1",
"ajv-keywords": "3.5.2",
```

code snippet:
```
const ajv = new Ajv({
      allErrors: true,
      jsonPointers: true,
      coerceTypes: 'array',
      nullable: true,
      strictDefaults: true,
      strictKeywords: true,
      strictNumbers: true,
      useDefaults: true,
      $data: true,
    });
...
    const uniquenessChecker: SchemaValidateFunction = function(
      scheme,
      data,
      parentSchema,
      dataPath,
      parentData: BackOfficeApplication,
    ) {
     ...

      return false;
    };
...

ajv.addKeyword('uniquenessChecker', {
    validate: uniquenessChecker,
});
```

In my schema I add 
```
uniquenessChecker: true
```

to some type array property. Although I do not think it is strictly necessary (it just guarantees to produce an error).

JsonEditor is instantiated with 
```
...
options={
    ajv: ajv
}
...
```
where ajv is an insance of Ajv created earllier.

I hope it is enough. We use JsonEditor inside a React app. But those are the steps I used to break JsonEditor today.

**Comment by josdejong** [comment]
I guess it's a conflict caused by the option `jsonPointers: true` that you're setting. JSONEditor is assuming paths in the errors use the the default (JavaScript property access notation) and not JSON pointers.

**Comment by magom001** [comment]
Hi! Thanks a lot for your feedback. I checked it out and indeed removing this option fixes the issue. Maybe a warning in jsdoc in case someone else runs into the same problem?

**Comment by josdejong** [comment]
Good idea, I've added some documentation, see this commit: 0cb51ef
