### ISSUE TITLE
example missing dict folder

### ISSUE THREAD

**Issue by davidWeiZhou** [josdejong/jsoneditor#1194]
example missing dict folder

**Comment by josdejong** [comment]
Thanks for your message. What do you mean exactly?

**Comment by zhaoyao-ciandt** [comment]
I found you lost dist folder,then the js script can't run.
I had found the reason,it had been ignored in .gitignore https://github.com/josdejong/jsoneditor/blob/develop/.gitignore
like this
.idea
*.iml
.vscode
build
dist
downloads
node_modules
*.zip
npm-debug.log
/.vs

I find this question in version v9.1.9.
the zip didn't have this folder too.
zip file https://github.com/josdejong/jsoneditor/archive/v9.1.9.zip

**Comment by josdejong** [comment]
The generated bundles are not commited in the source code repo. 

To generate the files in the `dist` folder, you can follow the description here: https://github.com/josdejong/jsoneditor#build. Does that help?

**Comment by zhaoyao-ciandt** [comment]
> The generated bundles are not commited in the source code repo.
> 
> To generate the files in the `dist` folder, you can follow the description here: https://github.com/josdejong/jsoneditor#build. Does that help?

The old version we used is 5.29.1,now we want use the latest version v9.1.9
we used this module in composer.json like 
`{
    "type": "package",
    "package": {
        "name": "josdejong/jsoneditor",
        "version": "v5.29.1",
        "type": "drupal-library",
        "dist": {
            "url": "https://github.com/josdejong/jsoneditor/archive/v5.29.1.zip",
            "type": "zip"
        },
        "source": {
            "url": "https://github.com/josdejong/jsoneditor",
            "type": "git",
            "reference": "v5.29.1"
        }
    }
}`

when I update the dist as https://github.com/josdejong/jsoneditor/archive/v9.1.9.zip ,the image js css not found after I composer install.
So my question is how can I use composer json to update the latest version?

**Comment by zhaoyao-ciandt** [comment]
Finally we use a script to run npm,like 
cd /xxx/xxx/library
npm ***
then dist folder created,then js css image can be used.
Thanks!

**Comment by josdejong** [comment]
👍
