### ISSUE TITLE
Selenium SendKey is not working in JSON editor box

### ISSUE THREAD

**Issue by dhawalthakre** [josdejong/jsoneditor#1199]
Hi
I m using Selenium with java for Automation and my requirement is to enter value in JSON editor box using SendKey method which is present in Selenium

**Comment by josdejong** [comment]
Is this "SendKey method" a REST request?

**Comment by dhawalthakre** [comment]
Thanks for your reply 

void sendKeys(CharSequence... keysToSend);

  /**
   * If this element is a text entry element, this will clear the value. Has no effect on other
   * elements. Text entry elements are INPUT and TEXTAREA elements.
   *
   * Note that the events fired by this event may not be as you'd expect.  In particular, we don't
   * fire any keyboard or mouse events.  If you want to ensure keyboard events are fired, consider
   * using something like {@link #sendKeys(CharSequence...)} with the backspace key.  To ensure
   * you get a change event, consider following with a call to {@link #sendKeys(CharSequence...)}
   * with the tab key.
   */

**Comment by josdejong** [comment]
Can you elaborate a bit? Would you like to load/save some json data via https://jsoneditoronline.org to your own backend? Or would you like to build JSONEditor in your own frontend?

**Comment by dhawalthakre** [comment]
My JSON data is in excel sheet and I want to add JSON data in JSON editor box through Selenium Automation script for that Selenium provide a method SenKey

**Comment by josdejong** [comment]
The online editor (https://jsoneditoronline.org) is not suitable as part of an automated continuous integration pipeline or something like that, it's meant for developers to fiddle around with some JSON data. With the online editor you can manually load a certain JSON document from disk or from a (public) url though.
