### ISSUE TITLE
key order

### ISSUE THREAD

**Issue by testjohnhello** [josdejong/jsoneditor#1205]
if i want to display such json: {"a":1,"d":1,"c":1,"80":1}

but i can't get such order a > d > c > 80 

because in chrome js dict order it  as:  80  > a  > d  > c  (integer save in elements , strings save in properties)

demo:
let x = {'a':1,'80':80}
console.log(x)

output:
{ '80': 80, a: 1 }

so, how can i display the right order？ thank you 

![image](https://user-images.githubusercontent.com/6904249/103204603-a9bf2180-4932-11eb-918c-a6ed36801a87.png)

**Comment by josdejong** [comment]
> so, how can i display the right order

I'm sorry it's not possible. Object keys are loaded in the order they are serialized, only keys which are a number will be ordered first. This is standardized behavior of `JSON.parse` which is built in in every browser.

In general though, the idea of an object is that it contains an unsorted set of key/values. When order is important, you may be able to use an array instead.
