### ISSUE TITLE
Calling setText() does not change tree

### ISSUE THREAD

**Issue by tormozit** [josdejong/jsoneditor#1210]
How to set text in tree mode? If I call setText(), nothing happening.

**Comment by josdejong** [comment]
In both modes, you can call either `set` or `setText` to load JSON:

```js
editor.set({ hello: 'world' })
editor.setText('{ "hello": "world" }')
```

See docs: https://github.com/josdejong/jsoneditor/blob/develop/docs/api.md

**Comment by tormozit** [comment]
I'm sorry. It was my mistake. Call setText() works correct in all modes.

**Comment by josdejong** [comment]
👍
