### ISSUE TITLE
I want use JSONEditor instance in onChange. But after I initialize the instance,  I get null in onChange. 

### ISSUE THREAD

**Issue by ConanZZ** [josdejong/jsoneditor#1214]
import React, { useRef, useEffect, useState } from 'react';
import JSONEditor from 'jsoneditor';
import 'jsoneditor/dist/jsoneditor.css';

interface Props {
  onChange?: (...args: any[]) => any;
}

const JsonEditor = (props: Props) => {
  const { onChange } = props;
  const ref = useRef(null);
  const [editorInstance, setEditorInstance] = useState(null);

  const handleChange = () => {
 // this console always print null
    console.log( editorInstance)
    let value = editorInstance?.get();
    onChange?.(value);
    editorInstance?.set(value);
  };

  const handleError = err => {
    console.log(err)
  };

  const initJsonEditor = () =>
    new JSONEditor(ref.current, {
      mode: 'code',
      history: true,
      onChange: handleChange,
      onValidationError: handleError,
    });

  useEffect(() => {
    setEditorInstance(initJsonEditor());
    console.log('initial');
  }, []);

  useEffect(() => {
// this console can print the instance normally
    console.log('effect', editorInstance);
  }, [editorInstance]);

  return (
    <div>
      <div className="jsoneditor-react-container" ref={ref} />
    </div>
  );
};

export default JsonEditor;

**Comment by josdejong** [comment]
About `onChange`, see docs: https://github.com/josdejong/jsoneditor/blob/develop/docs/api.md -> search for `onChange`. See also `onChangeJSON` and `onChangeText`.

There is a React example in the examples section, though this is not with hooks but classes. I guess you'll have to do a bit more debugging. `new JSONEditor(...)` does need a real, rendered DOM element (typically a div), I don't see that in your code (`ref.current` is just null I guess?).

**Comment by ConanZZ** [comment]
> About `onChange`, see docs: https://github.com/josdejong/jsoneditor/blob/develop/docs/api.md -> search for `onChange`. See also `onChangeJSON` and `onChangeText`.
> 
> There is a React example in the examples section, though this is not with hooks but classes. I guess you'll have to do a bit more debugging. `new JSONEditor(...)` does need a real, rendered DOM element (typically a div), I don't see that in your code (`ref.current` is just null I guess?).

there is a div in return() ,but github doesn't show the html element. 
like this: 
 ` <div>
      <div className="jsoneditor-react-container" ref={ref} />
    </div>
  );
`
and I use console.log to print ref.current ,  it can print the html element.

**Comment by josdejong** [comment]
O ok.

I think this question is not about JSONEditor but about React hooks. Maybe you have a stale closure in your React code? Like described here: https://dmitripavlutin.com/react-hooks-stale-closures/

**Comment by ConanZZ** [comment]
> O ok.
> 
> I think this question is not about JSONEditor but about React hooks. Maybe you have a stale closure in your React code? Like described here: https://dmitripavlutin.com/react-hooks-stale-closures/
> 
> EDIT: here a more extensive article about common pitfalls with React hooks: https://dmitripavlutin.com/react-hooks-mistakes-to-avoid/

Thanks for your help.  I will check my code again.

**Comment by josdejong** [comment]
👍 I hope you can figure it out
