### ISSUE TITLE
jsoneditor-minimalist.js Size has changed in 9.1.6 and after

### ISSUE THREAD

**Issue by cbmgit** [josdejong/jsoneditor#1224]
Hi, I have been using jsoneditor-minimalist.js from cdn and in latest version it's been as the almost similar as the main jsoneditor.js.

![image](https://user-images.githubusercontent.com/40800907/105357036-3a2f1000-5c1a-11eb-8509-414d62d11246.png)

![image](https://user-images.githubusercontent.com/40800907/105358236-eae9df00-5c1b-11eb-9158-0c8ecd63d4eb.png)

diff: https://github.com/josdejong/jsoneditor/commit/70ba3f73c605422fd65d01c0636a39a8fc16a40e

even I can see the same issue at https://cdnjs.com/libraries/jsoneditor/ 's generated js files.

I think the gulp webpack ignore is not working after 9.1.6 due some syntax change. 

I have spent 1 or 2 hr to find the solution but not able to do so.

Let me know how can I use npm run build to reduce the size of the lib file size.

gulp version: 4.0.2
node: 14.15.4
npm: 6.14.10
Windows 10

Thank you.

**Comment by cbmgit** [comment]
Created a PR which fixes this issue.  https://github.com/cbmgit/jsoneditor/commit/38ef0c1ec160ce309ac6aa25c8225eb3f55a62a5

**Comment by josdejong** [comment]
Fix published in `v9.1.9`, thanks!
