### ISSUE TITLE
[Discussion][Question][Why] typescript and web component ?

### ISSUE THREAD

**Issue by c0ncentus** [josdejong/jsoneditor#1229]
# In a nutshell 

why not typescript ?  (as I say, you can TS -> JS)
why don't make web component ?( is the same because is document.getElementByID)
why don't React ? (as I say, you can React -> HTML and keep your js logic [or whatever framework friendly component])  

# long story why javascript and why that package is not friendly at all but is all about result
Js allow to do anything you want, not typescript.
## why I think the package is bad (what I think)
I think many user want jsoneditor as typescript library ->and then allow Javascript because you can Typescript -> Javascript .

+ plus your package is not friendly as package because in your css there are many "image/... .svg"
=> Why make many small image and make data URI ? such bundle as mine is broken because of this ...

You not be able to make Javascript -> Typescript here 

(I test the react advanced demo, finnaly i withdraw it because to many bullshit on it) . ===> i spend 2 days for this for none result .

You can build maybe in jsx with "luck" but typescript "tsx" is not "luck". we ar in react 17 not 16.2 (package jasoneditor-react totally not work for me maybe because is js like package ... ... again ...) 

Typescript indicate the way properly you shall code ... Typescript say you for exemple " don't make windows.editorLeft = new JsonEditor(). because it dont exist (or is very silly to do this)" 

other exemple in the react demo advance in your wrapper you make "onChange" and another "on..." but it dont exist as props in your basic component, so ... dont make react if you don't understand what you code ... back to the basics ... if you don't things properly and need to learn react like me ... go ts ... or make lint your code (as minimum) . 

Typescript when you achieve youre code, as normal way, when you build it you have not type issues but **Logic** issues and very very small "luck" to have bug because it force you to respect the rule and doing things LIKE IS WRITTEN. 

why such hate for typescript ? (my code editor is screaming like something is heretic (all the code of JSONEditorReact is red because have issues in each word))
some people do typings but not necessery in package because don't work at all (react 17/16.14) :) .
## proposition
If you have suche hate of ts, why you didn't make web component version ? (is fondammentally what is react but that's a secret :) )    

Making webComponent or react allow to understing the logic the lifeCycle of Component, update, didMount or a custom function ...
if your package is fine with this logic then webComponent, react component is not hard to make it . it can help to make cleaner code.  Basicly I have 5 minutes to spend converting (html js css) to React/WebComponent  (and allow me to understand what is the correct way to make Component -> html-js), what I do on codepenio every day, but here maybe a year is not enought for this package who knows ?
  

 ## why I want to learn
Morever ... because make function ...( htmlElement, option) is silly versus
(webcomponent)<jsonEditor opt="{}">  => i think because that the same but webComponent is the way you want to achieve because that's the logic of it and is shareable.

I have not another choice making like you doing in html-js like with my react. I don't want force anyone but i want to understand your choice, why pure javascript ?

https://josdejong.com/posts/2020-06-17-how-to-keep-your-code-simple-and-maintainable/

I read this ... ok. 
1. Youre package is not simple, if not I already make work your package on react logic because " Component logic"
2. https://www.youtube.com/watch?v=PV_cFx29Xz0  and many thought in that direction=> elvoved javascript is a NEED. don't get stuck in 2009 (es5).
3.  If you keep your thought to the reality then learn to make ts package, with tsc you can generate automatcly typings and javascript for whatever javascript library (es5, es2019 ... ) you want .

why do you not ?

I'm beginer engeneer so I really want to understand what is really guide you for making this package ?

**Comment by josdejong** [comment]
Thanks for your questions @c0ncentus . You sound quite offensive here and there but I assume that's not your intention.

Trying to answer all your questions:

1. I do not hate TypeScript at all. I work a lot with Typescript. I do see TS as a trade-off with pros and cons though, not as a silver bullet solving all our problems at zero cost.
2. JSONEditor was created more then 9 years ago. TypeScript and React did not even exist at that time.
3. JSONEditor is a spare time project, there is simply limited amount of time and you can't "just" refactor the whole code base and stuff like that.
4. Web components are a standard but aren't really mainstream. Yet?
5. The code base of this project is indeed not simple at all, I'm very unhappy with it. Things I describe for example in https://josdejong.com/posts/2020-06-17-how-to-keep-your-code-simple-and-maintainable/ are the results of years of learning, often figuring things out the hard way 😉. 
6. On the upside: I'm working hard on a completely new JSONEditor, see #1223. It's built with Svelte (not React). TypeScript is still missing but I'm planning to add this. Question: why did I not add TypeScript rightaway? Answer: there was no TypeScript support for Svelte at the time I started this editor. Now there is.

**Comment by c0ncentus** [comment]
ok thanks

**Comment by josdejong** [comment]
You're welcome 👍
