### ISSUE TITLE
JSON Keys suggestion based in JSON schema

### ISSUE THREAD

**Issue by juansalazargenius** [josdejong/jsoneditor#1240]
HI!, I wanted to know if this feature is allowed in the json editor and how is used. In case this feature is not implemented, is possible to do it? what ideas you can give me to make this possible?

I add the way visual studio code does it for reference:
![Screenshot from 2021-02-10 15-00-04](https://user-images.githubusercontent.com/57112407/107564674-b6c96480-6bb0-11eb-8e63-80b3c01daa01.png)

**Comment by josdejong** [comment]
That is a great idea Juan! It's not implemented yet. This code mode is powered by Ace editor, so whether this is possible depends on whether Ace editor supports custom auto completion like this.

Anyone interested in looking into this?

**Comment by krishnagopinath** [comment]
Are you still looking to develop this feature,  @josdejong? If so, I could definitely help!
