### ISSUE TITLE
How to change the code mode selection color?

### ISSUE THREAD

**Issue by himel951** [josdejong/jsoneditor#1241]
I have been trying to change the code mode selection color. can anyone help me to solve this issue
![image](https://user-images.githubusercontent.com/13064291/107611782-b77cfc00-6c7f-11eb-9500-f8f2f63dd5d2.png)

**Comment by josdejong** [comment]
This is styling of the Ace editor. The theme loaded by JSONEditor is here:

https://github.com/josdejong/jsoneditor/blob/develop/src/js/ace/theme-jsoneditor.js

A short look in the DOM tree shows that the color of the selected text is determined by the class:

```
.ace-jsoneditor .ace_marker-layer .ace_selected-word
```

**Comment by himel951** [comment]
@josdejong  thanks a lot for your answer. It solved my problem.
