### ISSUE TITLE
JSON Validator seems unnecessarily strict

### ISSUE THREAD

**Issue by tai-flywire** [josdejong/jsoneditor#1260]
The JSON validator requires double quotes around around all name and value strings.  I understand that this is strictly according to the JSON spec, but the JSON that most people use in this tool will come from Javascript where it will often omit double-quotes or use single-quotes.  That means a good portion of users cannot use tree mode without manually fixing their JSON.  Perhaps a compromise would be to offer to auto-correct/convert missing double-quotes.

**Comment by josdejong** [comment]
JSONEditor has a "Repair" button which can fix this for you (Wrench icon in code mode). 

In the new beta ([click here to try out](https://jsoneditoronline.org/beta)), the repair button is replaced with a proactive error message, i.e. when the JSON is invalid, the parse error is displayed, and if it is possible to automatically repair it for you a button "Auto repair" will be displayed.

Is that what you mean?

**Comment by tai-flywire** [comment]
That's perfect, exactly what I meant!  And I learned two things today: 1) that I should really check out new betas before submitting issues and 2) that there was already a repair button in the interface (never even thought to wonder what the wrench icon was for).

**Comment by josdejong** [comment]
👍  

I think you're not the only one not knowing what the repair button was about, I expect the solution in the new beta is more helpful in that regard.

**Comment by chenxiaochun** [comment]
How to show the auto fix button? Is there any demo? Thanks very much.

**Comment by josdejong** [comment]
I guess you mean the red auto repair button at the bottom? Like the picture here in the docs about repair: https://jsoneditoronline.org/docs/index.html#repair? That is a feature of the successor of this library: [svelte-jsoneditor](https://github.com/josdejong/svelte-jsoneditor/).
