### ISSUE TITLE
Installation and usage without npm

### ISSUE THREAD

**Issue by gstabel** [josdejong/jsoneditor#1269]
Hi guys! Good work.

I dont use npm or nodejs currently. I'm prety much working with Java Spring Boot now, and doing a simple backoffice system using Thymeleaf. So, I wasn't straigth forward for me do use de jsoneditor. Even to run the examples.

Maybe I could try add some lines in the documentation or readme to help people in the same situation?

Thanks.
Gabriel

**Comment by josdejong** [comment]
Good point, thanks Gabriel.

Does the explanation I added in the following commit help? 

Commit: https://github.com/josdejong/jsoneditor/commit/a7291b6e4126ebe2ddd9a934ddfb3cb3f78d3733

**Comment by gstabel** [comment]
Thank you @josdejong!

Yes, I think it helps a lot.
Now anyone can easily use it, or try some examples, as stand alone application from CDN.

**Comment by josdejong** [comment]
👍
