### ISSUE TITLE
Custom "Insert"-Action based on context

### ISSUE THREAD

**Issue by mbeekhuis** [josdejong/jsoneditor#1281]
Hi Jos

Instead of defining templates I went with "21_customize_context_menu"  to have specific Insert-Arrays based on the context (node.path).  Is there an "Insert Array"-Function which I can call? (I'm searching the docs for this but could not find some informations so far ...).

Thanks
Marc

**Comment by josdejong** [comment]
Hi Marc, the function behind the "Insert array" button in the context menu is not exposed. If you're implementing a custom button in the context menu, you typically do `editor.get()` to get the current JSON, apply your change (depending on `node.path`), and then update the JSON in the editor via `editor.update(...)`.

**Comment by mbeekhuis** [comment]
Hi Jos, thanks a lot, I'll do it this way then.
