### ISSUE TITLE
JSON schema enum dropdown not working for conditionals like oneOf, anyOf, allOf

### ISSUE THREAD

**Issue by on8** [josdejong/jsoneditor#1282]
See this Jsbin: https://jsbin.com/fufabew/edit?html,output

Are there another ways to define the schema in order for both conditionals and enum dropdowns to work?

Thanks.

**Comment by josdejong** [comment]
Hm yeah, I think this is the same issue as discussed in #473. I'm not aware of a workaround for this.

Help to fix it would be very welcome. @Hagartinger or @maufl this is probably an issue in `Node._findSchema` in which you've been doing improvements some time ago. Would one of you be interested to have a look into this?

**Comment by maufl** [comment]
I think the problem here is that `Node._findSchema` searches in only one sub schema or the root schema because of [this](https://github.com/josdejong/jsoneditor/blob/develop/src/js/Node.js#L4456) line.

**Comment by josdejong** [comment]
Fixed now in `v9.4.0`
