### ISSUE TITLE
onChange suppport at key value level

### ISSUE THREAD

**Issue by vaishak10** [josdejong/jsoneditor#1289]
Not a issue.
Just wanted to know whether it is possible to keep method as a type. Since there's auto ,array , object and string types supported.
Why not add fields where we can write methods such as onChange etc. 
The main objective here is to implement this from the UI as we do in case of array,Objects and strings.

**Comment by josdejong** [comment]
Thanks for your input Vaishak. I'm not sure what you mean, do you mean you would like to have a new callback function for something?

**Comment by vaishak10** [comment]
![newfields](https://user-images.githubusercontent.com/52874416/113296472-23422380-9317-11eb-9860-09f0e6d4effc.JPG)

Just like the four type fields: Array, Object , Auto ,String. Can we add our own Custom fields

**Comment by vaishak10** [comment]
And is it possible to create fields where in the value can be a method type?
Like i created a field ```onChange:function(){ //code here}`` in code mode. But when i go to tree mode i get an error saying that it doesn't accept that type.

**Comment by josdejong** [comment]
You can customize the context menu, add new entries or remove some. There is an example:

https://github.com/josdejong/jsoneditor/blob/develop/examples/21_customize_context_menu.html

In the example, an entry is added to the main context menu, but you will see that the "Type" and "Insert" items contain a `submenu`, I guess in your case you want to add a custom entry there.

**Comment by vaishak10** [comment]
Thank you for the Info.
One more thing i wanted to ask is , i am using json editor in angularJs and the html element is ``` <jsoneditor options="obj.options" json="obj.data"></jsoneditor>.```. i change the obj.data from json editor but the changes are not getting reflected in my json object. Thought that 2 way data binding was possible as it's possible using ngModel.

**Comment by josdejong** [comment]
I guess you'll have to ask any questions related to the angular wrapper of jsoneditor in the repo of the wrapper library.

Will close this issue now.
