### ISSUE TITLE
Expand selected node in 'view' mode reaches uncought error on onDragEnd function

### ISSUE THREAD

**Issue by rianmartins** [josdejong/jsoneditor#1290]
Initial setup:
`const options = {
      mode: "view",
      limitDragging: true,
};
const json = {
  Label: "test",
  Level1: {
    Level2: {
      value: true
    }
  }
} 
const editor = new JSONEditor(container, options, json)`

At some point, if I select the `Level1` node with:
`editor.setSelection({ path: ["Level1" ] });`

And try to expand node `Level2`, I get the error:
`Uncaught TypeError: e[0].dom.menu is undefined
    onDragEnd 0:13933
    mouseup 0:13739
    P 0:17754
    onDragStart 0:13733
    _onEvent 0:16409
    i 0:16164
    _createFrame 0:16184
    create 0:15272
    setMode 0:1262
    _create 0:1161
    C 0:1117`

The error is not reproduced if
1. I don't select the node using setSelection method; or
2. I set the `mode` as "tree"

Obs.: I believe that when `mode` is set to "view", the onDrag event shouldn't be even triggered, right?

![image](https://user-images.githubusercontent.com/14854696/112870101-c267e080-90b5-11eb-8aeb-ed5ce22e1582.png)

**Comment by josdejong** [comment]
Thanks for reporting.

**Comment by josdejong** [comment]
I've made a fix to make the editor robust against this. However, in View mode, having a selection should not be possible at all I think (it's only relevant if you can actually do something with the selection, change the contents). So I think it would be good to disable `setSelection` when in view/form mode. Or are you using this for a specific reason?

**Comment by rianmartins** [comment]
Hello @josdejong thanks for your reply. 

I was using the `setSelection` just to highlight a specific node. In my case I'm working in a diff tool, using two jsoneditor containers to show both sides and navigating in the differences, highlighting the iterated diff of each side.

Oh, and would be great if we could get a node to expand/collapse programmatically it as well.

Suggestion1: I don't know if that's applicable for every case, but at least for me: would be awesome if `setSelection` would:
- Still be available in "view" mode 
- Expand the selected node and its parents recursively
- Call scrollIntoView() on selectedNode.dom.tree to make it visible when there's a scroll and the selected node is not visible

Suggestion2: 
- Create a `editor.getNode({path: ["prop1", "prop2" ] })` method in the API to return the a node instance
- Create a `node.expand()` to expand until the node
- Create a `node.collapse()` to collapse the node

If all in Suggestion1 are not applicable to `setSelection`, I believe it's important to have methods in the API to let developers call a `editor.getNode({path: ["prop1", "prop2" ] })` to perform more actions with the nodes (like expand/collapse) when necessary.

And excellent job on the jsoneditor, btw :)

**Comment by josdejong** [comment]
Thanks 😄 

I think using `setSelection` in mode `view` to achieve some specific highlighting is sort of misusing the feature. I think a proper solution would be to use the `onClassName` callback to do custom highlighting. The example demonstrating `onClassName` is even demoing diffing between two editors ;), see https://github.com/josdejong/jsoneditor/blob/develop/examples/20_custom_css_style_for_nodes.html. The `onClassName` callback has a known issue, see #1088, I hope you will not be limited by this.

Being able to expand/collapse a specific nested path is a good idea indeed, and also a getState/setState as discussed in #1217
