### ISSUE TITLE
No color marking in Diff anymore (Beta)

### ISSUE THREAD

**Issue by igrokit** [josdejong/jsoneditor#1296]
A couple of weeks ago, the beta still showed differences in color. That does not seem to work anymore. In the non-beta version, the color differences are still visible. This is the main feature i am using. I guess I need to switch back to the non-beta for now?

standard:
![image](https://user-images.githubusercontent.com/15889404/113874371-0776cb80-97b6-11eb-8383-af4d113bcfff.png)

beta:
![image](https://user-images.githubusercontent.com/15889404/113874530-30975c00-97b6-11eb-844e-95dab8d16ce2.png)

Dan

**Comment by josdejong** [comment]
Ouch, thanks for reporting @igrokit . It's fixed now in `6.0.0-beta.8` (there was a css name changed, causing the css of the diff highlighting not to work)
