### ISSUE TITLE
Support for JSON Schema

### ISSUE THREAD

**Issue by odedbd** [josdejong/jsoneditor#13]
I'd first like to say this is really a great tool you have built. I've been looking for just such a JSON editor for a long time now, and this is really well done!

One feature which could transform this from a very good tool into something even more useful would be to be able to create templates for new "types". By new types I mean composites of the native JSON types of course.

I think what I mean might be clearer if I give a concrete example-

Say I have the following JSON strucutre

    {
        point1:{
                     x:1,
                     y:1
                   },
        point2:{
                     x:1,
                     y:2
                   }
    }

It would be nice if I could define a "point" type, which will have the template
    {
        x:auto,
        y:auto
    }

(I used auto as that is used for the "change type" button)

and then create the above JSON by doing "change type" to the new point type I created.

I noticed in the wiki that you plan to implement JSON schema validation. I expect it might make more sense to tie the two features together, so that a new type might be implemented as a schema perhaps.

I guess this is could be a heavy feature to implement, but it could really transform the editor into a very powerful tool as it would allow the developer to easliy add and edit domain language objects.

**Comment by gitisz** [comment]
Just wanted to bump this suggestion because it is a REALLY good one!  I've been using the jsoneditor for sometime in my project and really believe extending the context menu to support schema contexts would be a powerful enhancement.  In my opinion, extending the context menu would be more useful than schema validation, only because schema validation can be easily performed by other means, such as callback.  Having a context menu display schema information would bolster usability greatly and allow end users to shape their data in a guided fashion.  Anyway, thanks for such a cool library!

**Comment by josdejong** [comment]
Thanks for your feedback, this will be very powerful indeed. This is now the highest priority for me (last week I finally worked away a lot of small issues).

**Comment by josdejong** [comment]
JSON schema support is now available in v5.1.0. Enjoy :)

**Comment by nehru** [comment]
{
  "outerValue1": 1,
  "outerValue2": 2,
  "objA": {
    "value1": 10,
    "value2": 20,
    "value3": 30,
    "objB": {
      "value4": 40,
      "value5": 50
    }
  }
}


If the append template in jsonEditor contains an object objB as "{} addObj". How to implement a schema validation if objB is attached anywhere in the json then it must show invalid message. objB must be inside object objA. If it is outside objA or any other place, then jsonEditior must show invalid message.

Thanks,

**Comment by josdejong** [comment]
Hm, I'm not sure if you can do that with JSON Schema. 

You could implement your own custom validation though, see this example: https://github.com/josdejong/jsoneditor/blob/master/examples/18_custom_validation.html
