### ISSUE TITLE
Replace \n

### ISSUE THREAD

**Issue by mbeekhuis** [josdejong/jsoneditor#1301]
Hi Jos

I've found several issues concerning how the editor handles new lines, but none of them is adressing my question directly:
I would like to have the editor replacing new lines with html `<br>` instead of \n. What I'm doing now and what works is: editor.get(), replace every \n with `<br>` and update the editor. But this checks the whole JSON-document instead of just the (edited) node.
The editor replaces new lines with \n somehow on blur of the selected field, I couldn't figure out where to call a replace: onChange/onValidate are called immediately and there is no onBlur of selected node?

Thanks a lot
Cheers Marc

**Comment by josdejong** [comment]
So if I understand you correctly you would like to render `\n` as a "real" new line in the browser? It sounds similar to #185?

**Comment by josdejong** [comment]
I don't think there is an easy way to customize this rendering in the current editor unfortunately. 

Customized rendering of keys and values is an open feature request: https://github.com/josdejong/jsoneditor/issues/738

**Comment by mbeekhuis** [comment]
I've built a "CMS"-like application around the editor. The whole content of the website is in a json file and the user can edit the content with the editor. so if a user just types a return to build a new line it should render as <br> a the end. It's not necessary that the editor itself replaces the new lines. I can do this afterwards since I've made a "preview" function where the website loads the edited json. At that point I can just replace all `\n` with `<br>` that's fine. But right know I check the whole json file for '\n', this file could grow over time and becoming quite large. It would be nice to know which nodes are edited and check only these. Like an array of changed nodes that gets updated "on change", on "preview" I could just check these nodes.

**Comment by josdejong** [comment]
Thanks for explaining your context @mbeekhuis . You can give it a try hacking something into the editor (overriding certain classs methods etc), but I'm not sure if it will be doable and work out nicely.

**Comment by mbeekhuis** [comment]
Hi Jos, I think for my purpose it would be best to push an array (selectedNodes) each time a node is edited. Then finally on "preview" replace all `\n` with `<br>` only on each item in that array and update the editor.
I just tried to get the current selection `JSONEditor.getSelection()` onChange, but I get` {"start":null,"end":null}` all the time. Just checked your example "15_selection_api". I don't get anything in tree mode either (?)

**Comment by mbeekhuis** [comment]
A workaround: `onEvent: function({path}, e){
    if (e.type == 'input') {
      selectedNodes.push(path);
    }
  },`
