### ISSUE TITLE
Welcome to try the new version of JSONEditor

### ISSUE THREAD

**Issue by wibetter** [josdejong/jsoneditor#1339]
**JSONEdito**r：Edit json data in the form of a visual form。
  
**Features**：
1. Flexible layout, providing two display modes: large screen and small screen；
2. Support field linkage；
3. Support 12 basic types（input、boolean、 date、date-time、 time、 url、 textarea、number、color、radio、 select、single-select）；
4. Support 11 special types（object、array、json、datasource、dynamic-data、event、 codearea、htmlarea、text-editor、quantity、box-style）；
  
**Github**: https://github.com/wibetter/json-editor
  
**Effect picture**：
![image](https://user-images.githubusercontent.com/11958920/120283671-03ff4c80-c2ee-11eb-995b-014d32d3ab10.png)

**Comment by josdejong** [comment]
Hi @wibetter , I'm not sure is this a question or issue, or just advertising for your JSON editor component? It looks a bit similar to https://github.com/json-editor/json-editor.
