### ISSUE TITLE
Feature Request: Add document via query string

### ISSUE THREAD

**Issue by tai-flywire** [josdejong/jsoneditor#1341]
As a user, I would like to... be able to create a document on the site on-the-fly, by passing a URL-encoded JSON object in the query string.

Use case: Programmatically create a URL which links user to a JSON document on the site, ready to inspect or modify.

Example: The URL https://jsoneditoronline.org/#json=%7B%22foo%22%3A%22bar%22%7D

Will create a document with the following JSON:
```
{
"foo":"bar"
}
```
I understand that there are browser limitations on the maximum length of the URL but this will still be quite helpful for many use cases.

**Comment by josdejong** [comment]
This is actually possible though I see it's not documented anywhere so you can't know about it. I should fix that.

You can use the pattern `#left=json.CONTENTS` and/or `#right=json.CONTENTS` in the url where you replace `CONTENTS` with url encoded JSON contents, for example:

https://jsoneditoronline.org/#left=json.%7B%22foo%22%3A%22bar%22%7D

This will load `{"foo": "bar"}` in the left panel.

Or load something in both left and right panel:

https://jsoneditoronline.org/#left=json.%7B%22foo%22%3A%22bar%22%7D&right=json.%5B1%2C2%2C3%5D

This will load `{"foo": "bar"}` in the left panel and `[1, 2, 3]` in the right panel.

**Comment by tai-flywire** [comment]
Fantastic!  Thanks for this amazing tool!
