### ISSUE TITLE
encoding issue showing weird characters on editor

### ISSUE THREAD

**Issue by jpiquot** [josdejong/jsoneditor#1342]
I am using your very good and useful JSON editor in an Azure DevOps extension. But I have a small encoding issue showing weird characters on :

- the dropdown that switches from tree to text
- the breadcrumb after selecting a node

![image](https://user-images.githubusercontent.com/6775094/121387157-c2544e80-c94a-11eb-9441-1af41ef40bf6.png)

[Issue 7 on ChildTaskTemplate Devops Extension](https://github.com/jpiquot/ChildTasksTemplate/issues/7)

**Comment by josdejong** [comment]
Thanks for reporting. Which language are you using in that case? How can I reproduce this issue?

Can it be that be that the html page is missing utf encoding?

```html
<head>
  <meta charset="utf-8">
  ...
</head>
```

**Comment by kirk-quinbar** [comment]
This is actually running under the context of an Azure DevOps extension, but the html for the devops page is setup like this if it helps. Obviously that isnt something that can be changed.

```
<html xmlns="http://www.w3.org/1999/xhtml" dir="ltr"  lang="en-US" >

<head>
  <meta name="msapplication-config" content="none" />
  <meta http-equiv="X-UA-Compatible" content="IE=11" />
....
```

**Comment by jpiquot** [comment]
As the extensions run in an iframe, maybe I can add the UTF8 meta. I will try and report the result.

**Comment by jpiquot** [comment]
Thanks, @josdejong for the solution. It works well.

**Comment by josdejong** [comment]
👍  good to hear
