### ISSUE TITLE
@change not working i vue js

### ISSUE THREAD

**Issue by swana1337** [josdejong/jsoneditor#1345]
i have just tried to trigger the onChange event but it isn't working

My code: 
<div
    ref="jsoneditor"
    @change="changedEditor"
  ></div>

const changedEditor = (value: any) => {
      console.log("value changed");
    };

can u please help me

**Comment by josdejong** [comment]
@swana1337 I'm not sure how I can reproduce your issue. Are you using the JSONEditor library straight into Vue, or are you using a wrapper library for Vue around it?

**Comment by josdejong** [comment]
What is the name of the library you use exactly?

**Comment by swana1337** [comment]
Of which library? The json editor?

**Comment by josdejong** [comment]
yes, the json editor library. `<json-editor ... >` is not something offered by this library (`jsoneditor`), so I expect that you're using a vue wrapper library.

**Comment by swana1337** [comment]
Oh sorry my bad.
I meant 

<div id='jsoneditor' ref='editor' @change='changedEditor />

**Comment by swana1337** [comment]
<div id='jsoneditor' ref='editor' @change='changedEditor' />

**Comment by josdejong** [comment]
This is Vue syntax, which is not supported by the plain JavaScript JSONEditor.

**Comment by josdejong** [comment]
Maybe you can use this library: https://www.npmjs.com/package/vue-jsoneditor ?

**Comment by swana1337** [comment]
Oh okay I will try thank you :)
