### ISSUE TITLE
Color highlight for differences is wrong

### ISSUE THREAD

**Issue by pallaviuc** [josdejong/jsoneditor#1346]
# As marked for Quantity Units, why different color?
![image](https://user-images.githubusercontent.com/86353930/123083727-f9902880-d43d-11eb-841f-77e692e3b488.png)

**Comment by josdejong** [comment]
So what would you expect to see exactly?

**Comment by josdejong** [comment]
`Material Role` -> changed to `Quantity` (orange)
`Quantity Units` -> inserted (green)

**Comment by josdejong** [comment]
Will close this issue due to lack of response
