### ISSUE TITLE
go to preview/next diff

### ISSUE THREAD

**Issue by mazhenhao** [josdejong/jsoneditor#1347]
I'm trying to implement the function "go to preview/next diff",like this :http://jsoneditoronline.org/
From issue #1178, I  can get the different Array by diff-sequences ( https://www.npmjs.com/package/diff-sequences)
but , how can I implement "go to preview/next diff" ? I didn't found some functions like "focus(node),jump(path)" in APIs.
Can you give me some advice? Thank You Very Much!

**Comment by josdejong** [comment]
I wrote some code (it's not open source at this moment) to compare two JSON documents: a recursive function to compare the properties of two objects, and compare the items of arrays using `diff-sequences`. This function returns a list with changes (create, update, delete).
