### ISSUE TITLE
how to run in the browser ?

### ISSUE THREAD

**Issue by TheRakeshPurohit** [josdejong/jsoneditor#1350]
I cloned the repo, npm I, npm run build. now I want to run it in the browser but nothing happens.

**Comment by josdejong** [comment]
If you mean like whether there is a development server: there isn't really. There is a watcher which can build the (non-minified) version of the bundle, see docs https://github.com/josdejong/jsoneditor#build, and after that you can simply open any of the examples in the `examples` and the `test` folder. You probably need to start a local http-server for that.

**Comment by ducna96** [comment]
I just config nginx for http-server, but not sucess, pleasea recommend for me nginx.conf file to run project in browser.
Many thank.

**Comment by ducna96** [comment]
how to build this repo to local, i cloned the repo , npm install, npm run build, and run nginx point to dir of project,but not sucess.

**Comment by josdejong** [comment]
@ducna96 this project contains a frontend library. It is no application. You'll have to load the library into a frontend application that you have to create yourself, and then you can deploy/host/serve that application some way or another.
