### ISSUE TITLE
Comparing array items by identifier

### ISSUE THREAD

**Issue by reponemec** [josdejong/jsoneditor#1352]
Is it possible to compare array items by specified identifier? For example by id, so left[0] to right[0], left[2] to right[**1**]? (Zero based indexed):
```
var left = [
  {
    "Id": 1,
    "Name": "red"
  },
  {
    "Id": 2,
    "Name": "green"
  },
  {
    "Id": 3,
    "Name": "blue"
  }
];

var right = [
  {
    "Id": 1,
    "Name": "red"
  },
  {
    "Id": 3,
    "Name": "black"
  }
]

```

**Comment by josdejong** [comment]
Thanks, that is an interesting suggestion. Currently the diffing really compares the contents of the array items.

If there is enough interest in such a feature we can think it through. We will for example need a way to specify which field contains the identifier (`Id` in your example), and some way to define this in case of nested arrays maybe.
