### ISSUE TITLE
Example for editing enum field

### ISSUE THREAD

**Issue by kolibaba** [josdejong/jsoneditor#1357]
I would like to edit a field with enum type with DropDownList. Can you provide me the complete example of how to do this?

**Comment by kolibaba** [comment]
if I understand correctly, I need to use the schema and pass it to "options". How to make schema correctly?
In my case Milestones.[*].Type is enum:
"Milestones" : {
            "1" : {
                "Type" : "RunesScrolls",
                "Value" : 15,
                "Difficulty" : 5
            },
            "2" : {
                "Type" : "AmuletScrolls",
                "Value" : 25,
                "Difficulty" : 9
            },

**Comment by josdejong** [comment]
You can achieve that for example with a JSON Schema, see this example: https://github.com/josdejong/jsoneditor/blob/develop/examples/07_json_schema_validation.html. Is that what you mean?

**Comment by kolibaba** [comment]
yes, what I needed, thanks. That example helped so much

**Comment by josdejong** [comment]
👍 you're welcome
