### ISSUE TITLE
Beta: Scrollbar is not visible.

### ISSUE THREAD

**Issue by YassinAJDI** [josdejong/jsoneditor#1359]
I'm having an issue I can't scroll on my large JSON object. Weird it was working a few days ago.

![JSON Editor Online - Google Chrome ](https://user-images.githubusercontent.com/20879597/127759266-4bdb45f5-19e8-4bf7-88d0-03bf0fd453cd.png)

**Comment by josdejong** [comment]
Thanks for reporting Yassin., I hadn't noticed this yet. Will fix it today or tomorrow.

**Comment by YassinAJDI** [comment]
Thanks for the quick reply. The scroll bar is working for code mode "on" but hidden otherwise.

**Comment by josdejong** [comment]
The issue with the scrollbar is fixed now in `v6.0.0-beta.15`. This regression was introduced recently when fixing an issue with the context menu not overflowing the panel. Thanks again.

**Comment by shamseer-ahammed** [comment]
+1
