### ISSUE TITLE
Is there a way to use it with NuxtJs ? 

### ISSUE THREAD

**Issue by Gr0bs** [josdejong/jsoneditor#1362]
Hi, I'm still learning NuxtJs but for my work I would like to use this tools.
But I don't really no how to import it in my project.

Is there a way to do it ? 
Can someone show me how to ? :) 

Thanks you very much !

**Comment by josdejong** [comment]
`jsoneditor` is just a plain JavaScript library so you can use it anywhere. If you want to use it in vue you will probably want to write a wrapper around it. And you'll need to disable server side rendering of the library: it uses `window` when loading.

**Comment by Gr0bs** [comment]
Yes I resolved it. :) 
Thanks anyway
