### ISSUE TITLE
Parsing error contains html caharacters.

### ISSUE THREAD

**Issue by yogeshmahajan-1903** [josdejong/jsoneditor#1363]
When json content has error & user clicks on error sign below message shown - 
`Parse error on line 14:<br>...d" }, "string": "Hello World}<br>---------------------^<br>Expecting 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '[', got 'undefined'`

Html characters <br> are present in error
<img width="526" alt="Screenshot 2021-08-19 at 2 18 19 PM" src="https://user-images.githubusercontent.com/16016019/130038708-ec3ca266-6797-4e01-9b89-51e30d3ef170.png">

**Comment by yogeshmahajan-1903** [comment]
Thank you for a quick fix.

**Comment by josdejong** [comment]
Fixed now in `v9.5.4`
