### ISSUE TITLE
Left Red cross button in error status bar is not functional

### ISSUE THREAD

**Issue by yogeshmahajan-1903** [josdejong/jsoneditor#1366]
<img width="526" alt="Screenshot 2021-08-19 at 2 18 19 PM" src="https://user-images.githubusercontent.com/16016019/130831001-cbe1f992-d4ed-490b-9d4e-750aa54bd9bd.png">
Red cross sign on left side of Ln14 is not functional.

Expecting - Error status bar should close if user click on left red cross sign.

**Comment by josdejong** [comment]
When you click this button or anywhere on the row of the error message, the editor will scroll to the error and put the caret there.

**Comment by josdejong** [comment]
I understand that the cross button may be confusing. It's not closing anything but it's an icon meaning "Parse Error" (there is also an icon "Validation Warning").

**Comment by yogeshmahajan-1903** [comment]
We can close issue.

**Comment by yogeshmahajan-1903** [comment]
Agreed with current behaviour
