### ISSUE TITLE
Utility to unescape a json string

### ISSUE THREAD

**Issue by raju-cimpress** [josdejong/jsoneditor#1368]
Many as time attribute in a json has a string value which is escaped json. It would be good to have utility to unescape the json string and convert it to object.

**Comment by josdejong** [comment]
Thanks for your suggestion. Can you give an example of what you mean?

**Comment by raju-cimpress** [comment]
Many a times a field in the json has a value of escaped json string. Example: field payload in below image.

![image](https://user-images.githubusercontent.com/53940732/134322534-8f5fbc9c-7ac5-4b48-8ce8-8cd29bf40dab.png)

Now, I have to copy that escaped json string and get it unescaped from somewhere else and then replace it back here. Example below image.

In the menu list for the value (grey menu box) if functionality of converting escaped json string to json can be given then I would not require to use other application to unescape it. May be if that option of **{} Object** in (Replace with:) menu can determine if it is a valid json string then it should convert escaped json string to json object like shown in below image.

![image](https://user-images.githubusercontent.com/53940732/134323056-704851c6-8b1e-4b62-a801-57936d7bdb3c.png)

**Comment by josdejong** [comment]
@raju-cimpress I see you're using the new jsoneditoronline beta. In this new editor you can copy the value containing the escaped JSON, then select all contents or open a new, empty document, then paste. This will automatically unescape the contents.

**Comment by raju-cimpress** [comment]
Good to know this. This will solve my problem too.
