### ISSUE TITLE
Option to indent output with real tabs

### ISSUE THREAD

**Issue by Roy-Orbison** [josdejong/jsoneditor#1372]
Ace editor seems to support it. It'd be good to have a checkbox on the _Configure indentation_ dialogue box to control use of real, semantic tabs in code view/prettification.

**Comment by josdejong** [comment]
Thanks for your suggestion, makes sense.

**Comment by xploSEoF** [comment]
This is actually really simple to implement as JSON.stringify accepts a string or number as the third parameter. You'll just need to change the couple of places where you check if it's a number to allowing a string through, too.

**Comment by Roy-Orbison** [comment]
This is done. If I go to _Settings > Configure editor > Indentation_ and set the type to _Tabs_, I get real tabs when formatting, saving & copying.
