### ISSUE TITLE
Beta opinions

### ISSUE THREAD

**Issue by tomihr** [josdejong/jsoneditor#1373]
I like the graphic look,
but I don't like that now I cant move nodes in hierarchy up and down like in the old version.

**Comment by josdejong** [comment]
Thanks for your feedback @tomihr . 

Dragging nodes up and down is indeed not yet implemented in the beta, but it's on the feature list.

**Comment by josdejong** [comment]
I've created the feature request explicitly at https://github.com/josdejong/svelte-jsoneditor/issues/20, will close this issue now.
