### ISSUE TITLE
Caret looses position

### ISSUE THREAD

**Issue by mbeekhuis** [josdejong/jsoneditor#1380]
Hi Jos
when clicking on the actions dropdown the caret positon in the selected node resets to the first position. So my custom function that should insert a predefined textnode at the caret position doesn't work.
The caret resets only when there are special characters in the node. This is cause the editor replaces these characters somewhere (I couldn't find out on which event it is defined). I've hacked this with:
`document.addEventListener('blur', function(e) {
    e.stopPropagation();
  }, true);`
No replace and the caret stays when clicking on the actions menu. But when clicking on the drag icon it still replaces the node-content and resets the caret. So I'd have to stop the replacing somewhere else. Not sure if the replace is defined "on blur" or somewhere else in the editor.
Do you have a better idea rather than this ugly hack to achieve my goal? (editor still works fine even with the hack for my purpose)
BTW: Clicking on the drag icon causes the actions-menu icon to change to clicked/dark icon. Is this supposed to be like this?

Many thanks
Cheers
Marc

**Comment by josdejong** [comment]
> BTW: Clicking on the drag icon causes the actions-menu icon to change to clicked/dark icon. Is this supposed to be like this?

When you click the drag icon, an event is triggered to make sure the closest element on the clicked row is getting focus, so you can use quick keys and edit contents. This doesn't make much sense when clicking, I guess we could improve that (though it also doesn't really do harm).

> Is it really necessary to escape/replace the node content on blur?

The escaping must be done at _some_ moment: the HTML text must be turned into plain, valid JSON text. Do you know of a better moment than onblur?

> causes the action menu to display the dark icon

I suppose you have some custom dark theme or so? It sounds like you have some custom CSS that causes this, in the editor itself there is no dark theme or button or anything.
