### ISSUE TITLE
How to highlight specific node when mouse hover that node?

### ISSUE THREAD

**Issue by hoogw** [josdejong/jsoneditor#1383]
How to highlight specific node when mouse hover that node?

   I know how to use hover event

                    `   const options = {
    mode: 'tree',
    modes: ['code', 'form', 'text', 'tree', 'view', 'preview'], // allowed modes
    name: "jsonContent",
    onEvent: function(node, event) {
      if (node.value !== undefined) {
        console.log(event.type + ' event ' +
          'on value ' + JSON.stringify(node.value) + ' ' +
          'at path ' + JSON.stringify(node.path)
        )
      } else {
        console.log(event.type + ' event ' +
          'on field ' + JSON.stringify(node.field) + ' ' +
          'at path ' + JSON.stringify(node.path)
        )
      }
    }
  }` 

So far when mouse hover a node, onEvent function was fired.   I can get all info, path, field, etc.... 
however I want to highlight that node at same time, so user know which node they were working on. 

when user mouse move away that node, remove highlight. 

How to change CSS backgroud color only for that specific node, when mouse hover?

**Comment by hoogw** [comment]
I made improvement by highlight the whole node instead of highlight only the single property. 

see my code here:  


![Screen Shot 2021-11-02 at 7 52 04 AM](https://user-images.githubusercontent.com/419582/139872214-0d059bfb-3557-4c48-8f5b-cd01339c5a91.png)
![Screen Shot 2021-11-02 at 7 55 00 AM](https://user-images.githubusercontent.com/419582/139872218-3627ba1b-cf09-4bf3-965e-8570002eb123.png)



the result is here
<img width="1521" alt="Screen Shot 2021-11-02 at 7 58 20 AM" src="https://user-images.githubusercontent.com/419582/139872550-54a5a7cc-7bb0-4d87-ab1b-6c03ea8164ec.png">

the live working example is here 

[https://transparentgov.net:3200/googlemaps11/default?layer_id=7&layer=Zoning_Merge&center_lat=33.7216041729596&center_long=-116.29073692373439&center_zoom=17&url=https%3A%2F%2Fgis.la-quinta.org%2Farcgis%2Frest%2Fservices%2FPlanning%2Fzoning%2FMapServer&panto=0&search_data=ct&overlayType=overlayType_none](https://transparentgov.net:3200/googlemaps11/default?layer_id=7&layer=Zoning_Merge&center_lat=33.7216041729596&center_long=-116.29073692373439&center_zoom=17&url=https%3A%2F%2Fgis.la-quinta.org%2Farcgis%2Frest%2Fservices%2FPlanning%2Fzoning%2FMapServer&panto=0&search_data=ct&overlayType=overlayType_none)

**Comment by josdejong** [comment]
Nice!
