### ISSUE TITLE
Hide/ don't build specific property in editor

### ISSUE THREAD

**Issue by mbeekhuis** [josdejong/jsoneditor#1387]
Hi Jos
I have a property in my json which I don't want to show in the editor. (It's a property that stores some information.This property should be hidden in the editor or better not even rendered but should stay in data/json).
Do you have an idea how to do this?

Thanks

**Comment by mbeekhuis** [comment]
to give you a bit more context: since my json file will grow over time and could get really large, I've decided to not perform the error validation on the whole json data. Instead I just validate the edited nodes. However if an error is not solved it wouldn't show after restart. Therefore I write an array (errors) into the json data. I could write this information elsewhere but it's really simple to just append it to the json data. But that array should not show up in the editor ...

**Comment by josdejong** [comment]
That approach makes sense. Not sure, but maybe you could also attach the data to your JSON objects using Symbol.

**Comment by josdejong** [comment]
Thanks for your donation BTW, appreciated!
