### ISSUE TITLE
JSON Schema enum dropdown not working

### ISSUE THREAD

**Issue by shenenya** [josdejong/jsoneditor#1389]
I tried jsoneditor with vega-lite, and found JSON Schema enum dropdown not working:
https://github.com/vega/schema/blob/master/vega-lite/v5.1.0.json
<img width="109" alt="截屏2021-11-10 下午4 44 09" src="https://user-images.githubusercontent.com/31716017/141079756-a579521c-7f9d-44a3-a40f-42f6d486d324.png">
.

**Comment by josdejong** [comment]
Is this a duplicate of #1042? If so let's continue the discussion there

**Comment by josdejong** [comment]
And if not, please share a minimal code example of `jsoneditor` demonstrating the issue

**Comment by shenenya** [comment]
Duplicate of #1042
