### ISSUE TITLE
CSS Bug (Webkit), elements not vertically centered (tr/td)

### ISSUE THREAD

**Issue by mbeekhuis** [josdejong/jsoneditor#1392]
Hi Jos
just a minor issue:
I've discovered that the elements inside tr/td are not vertically centered in Webkit-Browsers. See Screenshot attached
<img width="360" alt="Bildschirmfoto 2021-11-19 um 14 34 01" src="https://user-images.githubusercontent.com/81106559/142632053-066cbdd1-478c-4649-915e-a7b8049aa87f.png">

**Comment by josdejong** [comment]
Yes indeed, there is misalignment in specific browsers/OS's. There is a a some struggle with the `table` cells. But for example on Firefox there is no misalignment. It may depend on the font's that are available on the browser or something like that.

Anyone interested in trying to improve on this?

**Comment by mbeekhuis** [comment]
It doesn't depend on the font, I've changed to a web font and had the same result.

**Comment by mbeekhuis** [comment]
Seems like webkit adds some padding or space on bottom of button elements. I was able to remove this additional space by applying `display: block` on the button elements. Then I had to re-allign the backround-images on the buttons, did this by adding a 1px margin to the top of the parent div. It looks vertically centered now on Mac on FF/Chrome/Safari.

`div.jsoneditor-tree button.jsoneditor-button {
  margin-top: 1px;
}
.jsoneditor-button {
  display: block;
}`

**Comment by josdejong** [comment]
o wow, that easy! The `.jsoneditor-button { display: block; }` indeed solves the issue. I was trying out with `margin-top: 1px` but I doubt that is the right solution: the buttons are now 24px height, and the inputs are 16px height + 2 * 2px padding + 2 * 1px margin = 24px too. However the text is not aligned in the middle. I think we can neatly fix that by adding a line-height: 16px (corresponding to the min-height).

**Comment by josdejong** [comment]
Putting together a PR with a fix: #1398

**Comment by mbeekhuis** [comment]
I've set a line height of 19px to all text fields so they are aligned equaly. The tr and td have a total height of 27 px now, together with the 1px margin everything is in the middle now and text line height is good enough concerning readability. But this may depend on browsers and the font beeing used. Not defining a line height results in different tr/td heights (FF/Chrome render like 26.6667px while Safari rounds it to 27px). Anyway glad to have it solved even it's pretty much details ;-)
<img width="218" alt="Bildschirmfoto 2021-12-06 um 23 40 57" src="https://user-images.githubusercontent.com/81106559/144935697-47d4763e-f041-4aab-b155-1f0bc2a2d1cb.png">
<img width="748" alt="Bildschirmfoto 2021-12-06 um 23 39 29" src="https://user-images.githubusercontent.com/81106559/144935701-2e204e9f-cf7b-43d2-b062-7c3cddcc517d.png">

`.jsoneditor-value.jsoneditor-string,
.jsoneditor-value.jsoneditor-object,
.jsoneditor-value.jsoneditor-number,
div.jsoneditor-field,
.jsoneditor-readonly,
.jsoneditor-separator {
  line-height: 19px;
}`

**Comment by josdejong** [comment]
Thanks, makes sense to use px instead of pt. I'll do some more fiddling!

**Comment by mbeekhuis** [comment]
Yes indeed the monaco is too big with 14px. Probably the Courier or Courier New would be more accurate and available on both platforms.

**Comment by josdejong** [comment]
I've done some more tweaking. I was looking for other Windows mono fonts that look good at 13px, and found a nice, new one: `cascadia mono`: https://www.ctrl.blog/entry/cascadia-system-font.html

I think that is the best of both worlds: 13px monaco (Mac), 13px Cascadia mono (Windows) 👌

**Comment by josdejong** [comment]
Ok I've published the tweaks and deployed `jsoneditor@9.5.8`, and you can see the result for yourself at https://jsoneditoronline.org/

I still find it hard to come up with a font+size that works well for all OS'es and Browsers, so any suggestions for further improvement will be welcome.

Thanks for all the thinking along @mbeekhuis 👍

**Comment by josdejong** [comment]
Ok... so it turns out that 13px cascadia mono on Windows doesn't work well in Ace editor for some reason.

I've now switched to 14px font, with Consolas that looks perfect on Windows. Only it's too large on Mac, I now selected Menlo font which is a bit more "quiet" but still it's not ideal. The only other alternative I saw on Mac is Courier New or Andale Mono, but I really don't like those fonts.

I was thinking about building a switch to choose a different font size on Windows/Mac, but that sounds really tricky. What may make sense though is to make the font size configurable for the end user, so you can pick whatever you like yourself. I'll keep that in mind.

**Comment by mbeekhuis** [comment]
Why not define a web font (Google Fonts or else) for jsoneditoronline.org and let the end users choose their preferences? I've switched to a custom monospace font (@fontface) from a swiss foundry and now have the same appearance on all systems ...

**Comment by josdejong** [comment]
That's a good idea indeed, that will work for jsoneditoronline.org. Still, I would love the editor to have good defaults too (without packing a web font with it).
