### ISSUE TITLE
How can I hide sensitive information using this editor ?

### ISSUE THREAD

**Issue by AgnelRaj2014** [josdejong/jsoneditor#1394]
Hi, 

I have the below JSON, 

{
  "SecretName": "Applogin",   
 "SecretKey": "ABCD1234"    
}

I want it to display in below format. 

{
  "SecretName": "Applogin",   
 "SecretKey": "*********"    
}

Thanks.

**Comment by josdejong** [comment]
There is no solution for that right now. This is an open issue, see #460.
