### ISSUE TITLE
Mode = Code shadow DOM cannot be displayed

### ISSUE THREAD

**Issue by meikang123** [josdejong/jsoneditor#1395]

**Comment by josdejong** [comment]
@meikang123 can you please use English so we can all understand your question.

**Comment by meikang123** [comment]
Mode = Code shadow DOM cannot be displayed

**Comment by josdejong** [comment]
Can you give a minimal example demonstrating your issue?

**Comment by meikang123** [comment]
It's the same situation. Is there a solution
[https://github.com/josdejong/jsoneditor/issues/742](url)

**Comment by meikang123** [comment]
> Can you give a minimal example demonstrating your issue?

[https://codesandbox.io/s/oetyo ](url)  This is a demo

**Comment by josdejong** [comment]
This is indeed a duplicate of #742, which is still an open issue waiting to be addressed. There is also a workaround shared that solves the issue. Let's continue any discussion there.
