### ISSUE TITLE
How to use newer version of Ajv

### ISSUE THREAD

**Issue by Harkort55** [josdejong/jsoneditor#1402]
I have downloaded ajv2020.min.js (assuming that's the newest) from https://cdnjs.cloudflare.com/ajax/libs/ajv/8.8.2/ajv2020.min.js and placed it in my scripts folder.  Added it to my HTML page as:

<script src="Scripts/jsoneditor.js"></script>
<script src="Scripts/ajv2020.min.js"></script>

My script section then creates the global vars:

   var SchemaEditor;
   var Ajv = new ajv2020(); // <-- Ajv is indeed an object when this runs.

Later in the code I try to use it in the options (as seen in your docs):

> var options = {
>                 mode: 'text',
>                 modes: ['text'],
>                 ajv: Ajv({
>                     allErrors: true,
>                     verbose: true,
>                     jsonPointers: false,
>                     $data: true
>                 })
>             }
>             SchemaEditor = new JSONEditor(container, options, schema);

When that runs I get: Uncaught TypeError: Ajv is not a function.

Have I downloaded the incorrect ajv source?  An I missing something?  Is this not how this should be done?
All help would be greatly appreciated!  Thank you.

**Comment by josdejong** [comment]
The `var Ajv = new ajv2020()` part followed by `Ajv({ ... })` with options looks odd to me, aren't you mixing up things there? You sort of construct Ajv twice or so, the second time with options?

**Comment by Harkort55** [comment]
I don't really know.  I was merely following the docs example of how to do it.  Its not very clear.  Are you suggesting I need create the object first with those options, and then just reference it in the editor options to get the editor to use the new version of ajv provided?   Do you have an example of how to properly do this?

**Comment by Harkort55** [comment]
I modified my code to create the Ajv with its options:
`var Ajv = new ajv2020({ allErrors: true, verbose: true, jsonPointers: false, $data: true });`
and then create the jsoneditor like this:
```
var options = {  mode: 'text',  modes: ['text'],  ajv: Ajv  }
var JsonEditor = new JSONEditor(container, options, schema);

```
And that seems to work, at least for http://json-schema.org/draft-07/schema#

I am unable to specify any new draft (like 2019-09 or 2020-12) without jsoneditor throwing the error:
no schema with key or ref "https://json-schema.org/draft/2019-09/schema"

Shouldn't this enable the latest versions?

**Comment by josdejong** [comment]
> And that seems to work

That's indeed the way 👍 

Now your left over issue is a pure Ajv question and not about JSONEditor itself, so please try to get ajv itself working with your JSON schema and JSON document, and then plug it in JSONEditor like you do above. I know that specific drafts require a specific way of loading Ajv, please consult the docs of Ajv about that.

**Comment by Harkort55** [comment]
Ok, thank you so much.

**Comment by josdejong** [comment]
👍
