### ISSUE TITLE
values not selectable in jsoneditoronline (chrome)

### ISSUE THREAD

**Issue by cojito** [josdejong/jsoneditor#1405]
Hi, I like your product a lot, but recently I found that I experience difficulties selecting / copy-pasting values from the code-view in jsoneditoronline.org.

It's not possible to select the value and copy-pasting the 'half selected' values gives an unexpected result. Not sure this description is clear, so I created a short screenrecording.

https://user-images.githubusercontent.com/1318109/147483509-33317d36-1fbd-4723-88ad-7bf420a67a49.mp4

**Comment by josdejong** [comment]
Thanks for reporting Stephan! I tried to reproduce it but without success so far.

This issue sounds similar to #1403

Two questions:
1. Can you double check whether you are using the latest version of the web application, `Version: 5.10.6`? (Click the "About" button top right to find the version number) 
2. What operating system and browser are you using?

**Comment by cojito** [comment]
Yes, very similar to issue #1403, missed that one.

1) Yes:

![image](https://user-images.githubusercontent.com/1318109/147487889-21c77882-a4d9-4be9-bc51-d6eb372f8202.png)

2. Ubuntu 20.04.3 LTS / Version 96.0.4664.110 (Official Build) (64-bit). On Firefox 95.0.1 (64-bit) I experience the same issue.

**Comment by josdejong** [comment]
I think the default mono font in Ubuntu is one that the code editor (Ace) doesn't like, it's the ubuntu mono font I think. I just added "dejavu sans mono" to fix this issue but for some reason it's not yet working, to be continued...

**Comment by cojito** [comment]
Thanks for the swift response. It's related to the Ace font indeed. Changing it didn't work out for me, with other fonts I encounter similar problems. When disabling the class the problem seems to be solved, but I not sure about whether is looks good :)

![image](https://user-images.githubusercontent.com/1318109/147541641-0610c8ca-d0ec-4a3e-bfd0-1667f85278c0.png)

**Comment by josdejong** [comment]
The issue has been fixed now in web application `5.10.8`, library `v9.5.11`. I had to add the "ubuntu mono" font, that works ok in Ace editor.
