### ISSUE TITLE
Difference Next Button Broken

### ISSUE THREAD

**Issue by IceSelkie** [josdejong/jsoneditor#1407]
When using the Diff tool, pressing the next button with some inputs causes the diff tool to act unexpectedly, such as jumping back a large amount on the selected diff.

Expected action: Clicking the next button will jump from difference 27/119 to difference 28/119 (or 7/10 to 8/10 on shortened)  
  Actual action: Clicking the next button will jump from difference 27/119 to difference 10/119 (or 7/10 to 6/10 on reduced)  
  Steps to reproduce: Paste problematic data into left and right sides, enable diff mode, and repeatedly click the jump to next diff button. It will get stuck in a loop if it jumps back instead of forward.

Tested on: release website, beta website, release website in incognito browser (all in chrome on mac); as well as release website in incognito browser (firefox on mac, as well as chrome on windows 10)

shortened test data: [pastebin](https://pastebin.com/qSAWKS16)  
  full test data: [left](https://pastebin.com/raw/0tfHK726) & [right](https://pastebin.com/raw/8EbAmbDS)

Mostly Unrelated:  
  I was looking to use the differencing json objects code for a project I was working on, but couldn't find where that code was before I ran into this issue. I hope this helps! (also, where could I find the differencing json objects code?)

**Comment by josdejong** [comment]
Thanks for reporting, I can indeed reproduce your issue with the JSON examples you provided 👍. Will look into it. 

The diffing code is part of the (non-open source) web application. I may publish it some day as an npm library.

**Comment by josdejong** [comment]
This has been fixed now in the web application, both current and beta version. Thanks again.

**Comment by IceSelkie** [comment]
Yeah, of course!

(Also, could you tag the commit that fixed this?)

**Comment by josdejong** [comment]
The diffing is not part of the open source json library, so there is no commit I can point to, sorry. The issue was related to how the editor tries to keep track on the currently selected difference, which tries to restore itself when you make changes in the mean time (which can change the index of the current difference). That had an issue which is fixed now.
