### ISSUE TITLE
[Feature] Color indicator in view mode

### ISSUE THREAD

**Issue by ChrisAcrobat** [josdejong/jsoneditor#1413]
In `tree` mode we get a color picker, but in `view` mode we don't.
I was going to report this as a bug, but then I realised that a "picker" in a read only environment does not sound right. 🙃

**Comment by josdejong** [comment]
Good idea Christoffer 👍 , thanks. Implemented via ca9009e.

**Comment by ChrisAcrobat** [comment]
Awesome, good job! 😄

**Comment by josdejong** [comment]
Published now in `v9.7.0`
