### ISSUE TITLE
New lines unreliable (Chrome)

### ISSUE THREAD

**Issue by KoalaBear84** [josdejong/jsoneditor#1417]
I'm using the online [beta](https://jsoneditoronline.org/beta/)

I cannot get the line endings to be reliable. I can use it somehow in another JSON, but not get it working in the example JSON.

Example:

https://user-images.githubusercontent.com/5886900/151941421-7fb6d6ad-9454-4d31-8111-24b8f220e145.mp4

I'm using SHIFT + ENTER to add line endings. I would like to see that it always encodes line endings with \n, also multiple lines, do not trim anything. Sometimes it does work when I copy a line ending from like Notepad++ and paste it. Thanks in advance.

**Comment by josdejong** [comment]
Thanks for reporting, I see that this works correct on Firefox but is an issue on Chrome for example.

**Comment by josdejong** [comment]
This has been fixed now in `svelte-jsoneditor@0.3.18`, web application `6.0.0-beta.31`.

**Comment by KoalaBear84** [comment]
This is great, confirmed! Thanks @josdejong!
