### ISSUE TITLE
Transform preview text is blurry on chrome (Ubuntu 20.4)

### ISSUE THREAD

**Issue by dermasmid** [josdejong/jsoneditor#1419]
The text is blurry and really hard to see, when I opened it on Firefox it seemed to be fine, I cannot confirm if this also happens on Chrome on other platforms
![jseditor-blur](https://user-images.githubusercontent.com/47340720/152947048-c68ec54c-0b9d-4ff9-8d97-71fc395f49c1.png)

Note then when I removed the `border-radius` and `padding` from the textarea the text seemed to clear up.

**Comment by KoalaBear84** [comment]
Looks like this is a strange Chrome thing:
https://github.com/vaadin/vaadin-combo-box/issues/299

**Comment by josdejong** [comment]
That is really odd. Thanks for reporting Cheskel. 

Removing the `border-radius` on the `textarea` indeed solves the issue. This feels like a rendering bug in Chrome. I did some searching but cannot find an existing bug report for it.

This is fixed now in `jsoneditor@9.7.2`, web application `v5.10.10`.
