### ISSUE TITLE
blur event problem

### ISSUE THREAD

**Issue by yuanhl1994** [josdejong/jsoneditor#1421]
Hi,Jos
There are two problems with blur event.
First, when i reload page, editor not focus,but click window can trigger editor's blur event.It's not a big problem,but a little confused.
Second,if page has iframe,click iframe doesn't trigger editor's blur event. I wish you can fix this problem.

Many thanks

**Comment by josdejong** [comment]
Thanks for reporting @yuanhl1994 . How can I reproduce the two issues you mention exactly? Can you put together a small demo (for example on https://jsbin.com or https://codesandbox.io)?

**Comment by yuanhl1994** [comment]
> Thanks for reporting @yuanhl1994 . How can I reproduce the two issues you mention exactly? Can you put together a small demo (for example on https://jsbin.com or https://codesandbox.io)?

Thank you for your reply! Here is a example,[https://codesandbox.io/s/unruffled-cloud-djz7ci?file=/index.html](url)

if you focus on input,and then click iframe,there will console "blur:input".But if you focus on editor,and then click iframe,nothing will console.

**Comment by josdejong** [comment]
This issue is fixed now in `v9.7.4`.
