### ISSUE TITLE
setSchema does not work

### ISSUE THREAD

**Issue by qqsea** [josdejong/jsoneditor#1422]
Hi,
I want to dynamic update schema, and use setSchema api which seems not work.
Here is the example: I dynamic insert another enum string 'test' into gender field. the error message show the newly added value 'test', but there is no such 'test' option within drop down.

Thank you very much!

![image](https://user-images.githubusercontent.com/26144247/154183428-66284019-a371-405a-aa4a-b0bd2981d7cb.png)

**Comment by josdejong** [comment]
@qqsea thanks for reporting. Can you share a minimal example demonstrating the issue? Like in https://jsbin.com or https://codesandbox.io or so?

**Comment by qqsea** [comment]
Just based on the example from \examples\07_json_schema_validation.html. 
Here is the code piece I added at the end of js script:

`setTimeout(function(){
    var s = JSON.parse(JSON.stringify(schema))
    s.properties.gender.enum.push('test');
    editor.setSchema(s, {"job": JSON.parse(JSON.stringify(job))});
    editor.refresh();
  }, 1000);`

**Comment by josdejong** [comment]
Thanks, I'm able to reproduce this issue 👍

**Comment by josdejong** [comment]
This is fixed now in `v9.7.3`
