### ISSUE TITLE
Rounding off longer numeric values while formatting

### ISSUE THREAD

**Issue by darshanbutiya** [josdejong/jsoneditor#1425]
When I try to format below JSON string 

`{"xyz":[[{"abc":162274608100147201},{"abc":171281874526666777},{"abc":486653505780583987}]]}`

It is changing Its numeric value and adding zeros at the end of the number.

output after formating : `{"xyz":[[{"abc":162274608100147200},{"abc":171281874526666780},{"abc":486653505780584000}]]}`

**Comment by josdejong** [comment]
This is a known issue, see #231. Will close this issue as a duplicate
