### ISSUE TITLE
 Error: Local document with id "XXXX" not found -> it's useless

### ISSUE THREAD

**Issue by gale93** [josdejong/jsoneditor#1429]
"Open New Document" option should be automatic.
I find myself click on it everytime I open the tool **AND** there's no really other choice

**Comment by josdejong** [comment]
Thanks for reporting. JSONEditor automatically saves the document you where working on in the localStorage of your browser, so you'll not loose any data when closing your browser or something like that. 

Can it be that the localStorage of your browser is disabled, like you're working in incognito mode or something like that?

**Comment by josdejong** [comment]
Or, did you maybe bookmark the link to https://jsoneditoronline.org including the id of a document? In that case it will try to load that document when opening the application. You can fix that by removing the id from the url in your bookmarks.

**Comment by gale93** [comment]
You are right, I bookmarked it wrong. I'm sorry !
P.S.: Great work, very good tool I'm enjoying it soo much !

**Comment by josdejong** [comment]
👍 

> P.S.: Great work, very good tool I'm enjoying it soo much !

Thank you, good to hear! Stay tuned, within one or two weeks a big new version will be be released. You can try it out already on the beta page: https://jsoneditoronline.org/beta/ (feedback welcome 😄)
