### ISSUE TITLE
More advanced sorting of objects and arrays

### ISSUE THREAD

**Issue by gdbtek** [josdejong/jsoneditor#143]
I'm wondering if you can add a feature to pretty json object such as sorting object keys recursively. Let's say normally AWS CloudFormation json file is pretty big and it would be super cool that http://jsoneditoronline.org could sort object recursively instead of I now have to click on individual object keys and sort it manually and it takes a lot of times.

**Comment by josdejong** [comment]
This is supported now for a while via JMESPath.
