### ISSUE TITLE
Missing ace css when used in web components

### ISSUE THREAD

**Issue by Minitiai** [josdejong/jsoneditor#1431]
fix: ace css is build jsoneditor css

or

import jsoneditorCss from 'jsoneditor/dist/jsoneditor.min.css'
import aceCss from 'ace-builds/css/ace.css'

can solve the problem

**Comment by josdejong** [comment]
Thanks for reporting. 

How can I reproduce your issue? When I open any of the examples, there is no need to import ace CSS separately.

**Comment by Minitiai** [comment]
https://developer.mozilla.org/zh-CN/docs/Web/Web_Components
