### ISSUE TITLE
How to make duplicated object editable?

### ISSUE THREAD

**Issue by JonnyLeiZhang** [josdejong/jsoneditor#1432]
Hi team,
I have one array to visualize and edit, like below:
[{name: a, ...otherFields},
{name: b, ...otherFields},
]

I have set 'name' field not editable through 
`              onEditable: function (node) {
                switch (node.field) {
                  case 'name':
                    return false;
                  default:
                    return true;
                }
              },`
, because it should be unique, while other fields should be editable.
But I hope the duplicated one's name can be editable, is it possible ?

I was thinking to fetch previous and current arrays' lengths in onEditable for comparison, but I failed to fetch them. Any suggestions?

BR/Lei

**Comment by josdejong** [comment]
Interesting case, so the question is how to uniquely identify these duplicated fields. The `onEditable` callback passes an object with three properties that you can use: `{ path, field, value }`. If you keep the original version of the JSON you could probably compare comparing against that to see which fields are new (about comparing two JSON documents: [examples/20_custom_css_style_for_nodes.html](https://github.com/josdejong/jsoneditor/blob/develop/examples/20_custom_css_style_for_nodes.html) may be a helpful demo).

**Comment by JonnyLeiZhang** [comment]
Thanks for your reply. I tried several ways, emmm, seems this is not a common case, because I notice that user can drag and change the orders, so it's hard to do this.

**Comment by josdejong** [comment]
Yes it can be tricky. Dragging can be disabled too though, see fields `_id` and `name` in [examples/05_custom_fields_editable.html](https://github.com/josdejong/jsoneditor/blob/develop/examples/05_custom_fields_editable.html).
