### ISSUE TITLE
feature request: Strip to {} and Strip to []

### ISSUE THREAD

**Issue by mvark** [josdejong/jsoneditor#144]
JSON Viewer - http://jsonviewer.codeplex.com/ is a desktop tool that has a feature "Strip to {}" and "Strip to []". This option removes the function name, comments and brackets so that there is no JSON validation error. 

For example, this JSON feed will throw a parsing error with your viewer - https://ajax.googleapis.com/ajax/services/search/news?q=Hyderabad,India&v=1.0&rsz=5&callback=jQuery18205345600936561823_1415180407646&_=1415180677951

I have not seen the feature of stripping JSON to exclude anything outside the main opening and closing braces, in any of the online JSON viewers. Can you please add this feature?

**Comment by JosDet** [comment]
Fuck！！Big Fat liar! Hurry to repay $500000!!!!!
