### ISSUE TITLE
Question: is it possible to setup editor to not accept additional properties?

### ISSUE THREAD

**Issue by pruchay** [josdejong/jsoneditor#1442]
Hi. 
I'm looking for a flag, like `no_additional_properties`, there If true, the whole JSON can contain only properties defined in the JSON schema. Is it possible?

**Comment by josdejong** [comment]
Yes and no:

No: the editor will _not_ disallow the user from typing anything, so the editor can (temporarily) contain either invalid JSON or JSON that is not valid according to a JSON schema. If that is the case, the editor will display warnings and errors, and it is up to the user to correct this. This is a normal state, especially in code mode where you will always temporarily have an invalid JSON document whilst typing new contents.

Yes: when a document contains validation errors, _you_ can choose what you allow a user to do with it: you can disallow submitting a document when there are a validation errors for example, like is normal in regular forms. There are also some (limited) possibilities to disable editing specific fields with `onEditable`, but this is mostly handy to mark specific fields as readonly.

**Comment by pruchay** [comment]
Hi, @josdejong thank you for your answer. 

So instead of having only one JSON Schema, I will need to have a list with possible keys in my JSON and check it manually using `onValidate` function?

For example, I have JSON Schema with `fieldOne`, `fieldTwo`, both integers. If I try to put for that fields some strings it will show an error, but if I will try to add `fieldThatNotExistInJsonSchema` it will accept it.

**Comment by josdejong** [comment]
JSONEditor will accept all input and will show warnings when the document does not adhere to the JSON schema that you have provided. If your JSON schema allows additional fields like `fieldThatNotExistInJsonSchema` then there will be no warning. If your JSON schema forbids additional fields then it will give a validation warning.

You can indeed call `editor.validate()` to get all current warnings/errors (if any), or listen to `onValidate` to keep track. You can use that to determine for example whether or not a Submit button is enabled/disabled.

**Comment by pruchay** [comment]
I forget to set in the json schema `"additionalProperties": false`.

Thank you and sorry for disturbing :)

**Comment by josdejong** [comment]
😄  👍
