### ISSUE TITLE
Keydown event is triggering onChange

### ISSUE THREAD

**Issue by mbeekhuis** [josdejong/jsoneditor#1445]
Hi Jos
I've just noticed that CTRL + C/CMD+C or the oncopy-event is triggering the change event and causing the redo button to appear/change to active. I think that this makes no sense, since at that point there's no change in the document yet.
The change event should trigger on paste event only. 

Cheers Marc

**Comment by josdejong** [comment]
Thanks for reporting Marc. How can I reproduce your issue? Are you sure you're reporting to the right library? The `jsoneditor` doesn't have an oncopy event for example, so I'm not sure.

**Comment by mbeekhuis** [comment]
Hi Jos
I've just checked if this is caused by my own implementation since I've customized a lot ... still not sure about it but I could not find any lines that trigger the change (onChangeJSON) from my side.
I'll search the jsoneditor-code and will report if I find anything. Maybe a key press event (command) that triggers the change? I've discovered that isssue cause I customized the "undo/redo" buttons so that they are hidden by default and visible only if there's a change (and something to "undo").

**Comment by mbeekhuis** [comment]
Just noticed that it's not the "copy" event that triggers the change, it's the command button indeed ...

**Comment by josdejong** [comment]
Is the issue reproducible with just the plain, original `jsoneditor` library?

**Comment by josdejong** [comment]
👍 glad to hear you found the cause
