### ISSUE TITLE
How to detect change of values in json editor

### ISSUE THREAD

**Issue by abhimehta23** [josdejong/jsoneditor#1446]
Hello Jos de Jong,

I wanted to know how is it possible to detect a change of value in Json? Basically if I change a value and revert to original value then the change should not trigger because values were reverted to original version. But if any value in Json has changed then I want to enable/disable a user button on my express web application. Any help would be great!

Thanks,
Abhi

**Comment by josdejong** [comment]
You can listen for any change using the `onChange` callback.

If a user makes a change and after that reverts the change again, the editor will trigger multiple `onChange` events. If you want to know if there are changes compared to some "original" version of the document, you can keep a copy of the original document in a variable named `originalJson` or so, and hold any changed contents you get back from the editor in a variable `updatedJson`. With a deep equality check like `_.isEqual` from lodash you can check whether the latest version of the document is equal to the original one or not, and then enable or disable your user button accordingly.

**Comment by abhimehta23** [comment]
@josdejong sounds good! Can you refer me to some example files from the jsoneditor package? That would indeed be a great help also. Thanks so much!

**Comment by josdejong** [comment]
👍 

The examples are located here: https://github.com/josdejong/jsoneditor/tree/develop/examples

There is no example of your specific case but I'm sure you will figure it out 😁

**Comment by abhimehta23** [comment]
Hi @josdejong ,

yes I was able to figure it out :) Thanks for this wonderful tool!

**Comment by josdejong** [comment]
Good to hear. You're welcome ;)
