### ISSUE TITLE
Add duplicated nodes before the original nodes

### ISSUE THREAD

**Issue by mbeekhuis** [josdejong/jsoneditor#1452]
Hi Jos
I've tried to change the behaviour of "Node.onDuplicate" so that the duplicate node will be added before the original node.
First I thought that this is rather simple and just changed `parent.insertAfter(clone, afterNode);` to `parent.insertBefore(clone, afterNode)`. (Line 14777/minimalist file). This works as expected, but now I'm getting an error on "redo": TypeError: undefined is not an object (evaluating 'node.clone') jsoneditor-minimalist.js:15025) ...

Seems like the cloned node is not added to the nodelist when inserted before. Maybe you can give me a hint on how to solve this.

Cheers Marc

**Comment by mbeekhuis** [comment]
Hi Jos
still don't get this, and what to change ... The returned clone is the right one even when changing to insertBefore. "undo" works, the issue happens only on "redo". So I guess the clone gets deleted on undo. I think I'll rather need to change something on the nodeHistory:

`duplicateNodes: {
        undo: function undo(params) {
          var parentNode = findNode(params.parentPath);
          params.clonePaths.map(findNode).forEach(function (node) {
            parentNode.removeChild(node);
          });
        },
        redo: function redo(params) {
          var parentNode = findNode(params.parentPath);
          var afterNode = findNode(params.afterPath);
          var nodes = params.paths.map(findNode);
          nodes.forEach(function (node) {
            var clone = node.clone();

            if (parentNode.type === 'object') {
              var existingFieldNames = parentNode.getFieldNames();
              clone.field = (0,util.findUniqueName)(node.field, existingFieldNames);
            }

            parentNode.insertAfter(clone, afterNode);
            afterNode = clone;
          });
        }
      },`

**Comment by josdejong** [comment]
After just changing `insertAfter` to `insertBefore`, when you select two or three nodes and then duplicate them you will see that the  duplicated nodes have the opposite order and are inserted before the last of the three selected nodes instead of before the first of the three, so something needs to be changed there.

You're right about the `duplicateNodes` action that needs to be changed too in NodeHistory.js. I guess you'll need to send a property `beforePath` instead of `afterPath` and utilize that.

**Comment by mbeekhuis** [comment]
Hi Jos 
thank's for your suggestions.
I've changed `afterNode` to `beforeNode` and `afterPath` to `beforePath`, reversed orders ... with no luck.
Finally I've changed the nodeslist to `clonePaths` inside duplicateNodes ... and it works now ... ;-) (?)

```
duplicateNodes: {
        undo: function undo(params) {
          var parentNode = findNode(params.parentPath);
          params.clonePaths.map(findNode).forEach(function (node) {
            parentNode.removeChild(node);
          });
        },
        
        redo: function redo(params) {
          var parentNode = findNode(params.parentPath);
          var afterNode = findNode(params.afterPath);
          
          var nodes = params.clonePaths.map(findNode); /// was: params.paths.map(findNode);
          
          nodes.forEach(function (node) {
            var clone = node.clone();

            if (parentNode.type === 'object') {
              var existingFieldNames = parentNode.getFieldNames();
              clone.field = (0,util.findUniqueName)(node.field, existingFieldNames);
            }

            parentNode.insertAfter(clone, afterNode);
            afterNode = clone;
          });
        }
      }
```

**Comment by mbeekhuis** [comment]
Hi Jos

sorry for reopening an old issue. I'll spend you a cup of coffe or a beer anyways as a donation ;-)
I've struggled again over this issue. Either something changed in JsonEditor or inside my implementation, but the previous "solution" does not work anymore, resulting in a complete chaos on "redo" (selecting wrong nodes as duplicates etc.)
So again, this is what I've changed so far:

`Node.onDuplicate = function (nodes) {
  if (!Array.isArray(nodes)) {
    return Node.onDuplicate([nodes]);
  }
  if (nodes && nodes.length > 0) {
    var lastNode = nodes[nodes.length-1];
    var parent = lastNode.parent;
    var editor = lastNode.editor;
    editor.deselect(editor.multiselection.nodes);

    // duplicate the nodes
    var oldSelection = editor.getDomSelection();
    var beforeNode = lastNode; //was afterNode
    var clones = nodes.map(function (node) {
      var clone = node.clone();
      if (node.parent.type === 'object') {
        var existingFieldNames = node.parent.getFieldNames();
        clone.field = (0,util.findUniqueName)(node.field, existingFieldNames);
      }
      parent.insertBefore(clone, beforeNode); // was insertAfter(clone, afterNode)
      beforeNode = clone; // was afterNode = clone;
      return clone;
    });

    // set selection to the duplicated nodes
    if (nodes.length === 1) {
      if (clones[0].parent.type === 'object') {
        // when duplicating a single object property,
        // set focus to the field and keep the original field name
        clones[0].dom.field.innerHTML = nodes[0]._escapeHTML(nodes[0].field);
        clones[0].focus('field');
      } else {
        clones[0].focus();
      }
    } else {
      editor.select(clones);
    }
    var newSelection = editor.getDomSelection();
    editor._onAction('duplicateNodes', {
      paths: nodes.map(getInternalPath),
      clonePaths: clones.map(getInternalPath),
      beforePath: lastNode.getInternalPath(), // was afterPath: ...
      parentPath: parent.getInternalPath(),
      oldSelection: oldSelection,
      newSelection: newSelection
    });
  }
};`

Then in "duplicateNodes":

`duplicateNodes: {
        undo: function undo(params) {
          var parentNode = findNode(params.parentPath);
          params.clonePaths.map(findNode).forEach(function (node) {
            parentNode.removeChild(node);
          });
        },
        redo: function redo(params) {
          var parentNode = findNode(params.parentPath);
          var beforeNode = findNode(params.beforePath); // was var afterNode = findNode(params.afterPath);
          params.paths.map(findNode).forEach(function (node) {
            var clone = node.clone();
            if (parentNode.type === 'object') {
              var existingFieldNames = parentNode.getFieldNames();
              clone.field = (0,util.findUniqueName)(node.field, existingFieldNames);
            }
            parentNode.insertBefore(clone, beforeNode); // was parentNode.insertAfter(clone, afterNode);
            beforeNode = clone; // was afterNode = clone
          });
        }
      },`
      
      This is driving me crazy, I don't get where I''ll have to change the code. 
      Any help very appreciated!
      
      Cheers Marc

**Comment by mbeekhuis** [comment]
Seems like I got it now :-):

`editor._onAction('duplicateNodes', {
      paths: nodes.map(getInternalPath),
      clonePaths: clones.map(getInternalPath),
      beforePath: beforeNode.getInternalPath(),  // get path of beforeNode instead of lastNode
      parentPath: parent.getInternalPath(),
      oldSelection: oldSelection,
      newSelection: newSelection
    });`

then on "duplicateNodes" my old "solution" on redo works again:
`redo: function redo(params) {
          var parentNode = findNode(params.parentPath);
          var beforeNode = findNode(params.beforePath);
          params.clonePaths.map(findNode).forEach(function (node) {` // clonePaths instead of paths, still strange but seems to work ...

**Comment by josdejong** [comment]
Good to hear your managed to solve it already! And thanks a lot for the donation, appreciated! The beer will come in handy on this sunny day 😎.

On a side note: you can make code blocks better readable on github by using thee backticks instead of one before and after the code block. I updated your replies like that, you can check it out by editing them again.
