### ISSUE TITLE
How to customize and control the way of formatting / compressing JSON

### ISSUE THREAD

**Issue by jayt1001** [josdejong/jsoneditor#1457]
After reading the document, I found that I can format or compress the code by using the shortcut keys ctrl+i/ctrl+shift+i：
![image](https://user-images.githubusercontent.com/29675005/180368826-f5d39189-fe20-4c2c-babb-069811a77093.png)
But I want to add a button to control them, but I can't find the corresponding method.

**Comment by josdejong** [comment]
There are two buttons to do formatting and compacting:

![afbeelding](https://user-images.githubusercontent.com/568626/180384738-dbfafa29-9d18-40f6-a94b-9d42d1266e43.png)

Is that what you mean?

Also, there are two methods `.format()` and `.compact()` that you can use to programmatically format/compact your JSON.
