### ISSUE TITLE
mtl para json 

### ISSUE THREAD

**Issue by lucazalves1** [josdejong/jsoneditor#1462]
Estou com um problema de transforma um mtl para json, sabem se eu consigo fazer  isso de uma forma pratica
#vircadia
#metaverse

**Comment by josdejong** [comment]
Can you please ask your question in English, then everyone can follow. Thanks

**Comment by kirilinko** [comment]
His question is in Portuguese. I translated it into English and he says  " I am having a problem transforming a mtl to json, do you know if I can do this in a practical way ". I think that by doing research on sendeyo, he will be able to find an answer to his question.

**Comment by josdejong** [comment]
Yeah I guess so. Thanks for your comment @kirilinko, I'll close this question now.
