### ISSUE TITLE
I want to undisplay these menu, for help

### ISSUE THREAD

**Issue by MichaelPanwenjie** [josdejong/jsoneditor#1465]
When use the templete mode in insert or append menu, i want to just show the templete mode menu and undisplay the others menu
as the screenshot:
![image](https://user-images.githubusercontent.com/34026313/189637913-d4044696-7b1f-4795-9a72-c6e1906cf4f0.png)

How to let the other menus (in red) disappear in insert and append?

**Comment by josdejong** [comment]
I guess the angular wrapper that you use is not up to date with the actual functionality, so I think you should ask over there.

**Comment by MichaelPanwenjie** [comment]
I find the same issue and there is no response.
https://github.com/MaaxGr/ang-jsoneditor/issues/12

**Comment by josdejong** [comment]
So, I guess the angular wrapper that you use is not up to date with the actual functionality, I think you should ask over there.
