### ISSUE TITLE
Not getting editor.aceEditor.setOptions({   maxLines: 10000 })

### ISSUE THREAD

**Issue by HammadAli-WD** [josdejong/jsoneditor#1466]
Hi,
I am facing one problem that in the following file, I am not getting the setoptions. I want to make my editor as autosize but its not working.

`editor.aceEditor.setOptions({   maxLines: 10000 })`

**Comment by HammadAli-WD** [comment]
@josdejong

**Comment by josdejong** [comment]
Using `editor.aceEditor.setOptions({ maxLines: 10000 })` should indeed work. And you have to make sure you do not give the container DIV where you load the editor a fixed height.

**Comment by HammadAli-WD** [comment]
Can I give a min-height, because without that the editor is not showing and collapsing.

**Comment by HammadAli-WD** [comment]
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/63840111/189666953-87879305-4eb5-40ab-aca5-4b42cbc13673.png">

**Comment by HammadAli-WD** [comment]
showing above error @josdejong

**Comment by josdejong** [comment]
> Can I give a min-height, because without that the editor is not showing and collapsing.

well... just try it out. That's probably faster than typing it out as a question 😉 

Accessing `editor.aceEditor` is an unofficial API, and I suppose it's not defined in the type definitions.

**Comment by HammadAli-WD** [comment]
Thats was types error only, other wise its working well. Thanks
