### ISSUE TITLE
Can you provide a adapt angular wrapper to use all the features or apis of jsoneditor

### ISSUE THREAD

**Issue by MichaelPanwenjie** [josdejong/jsoneditor#1468]
Duo to some angular wrapper is not adapt to use all apis from jsoneditor，
Can somebody provide a adapt angular wrapper to use ?

**Comment by josdejong** [comment]
There are a couple of angular wrappers out there, I guess it is best to improve those where needed. You can of course do that yourself, it's mostly open source.
