### ISSUE TITLE
Misspelled option "enableLiveAutocompletion"

### ISSUE THREAD

**Issue by varunarora** [josdejong/jsoneditor#1474]
When trying to load the editor, my console is complaining of:

![image](https://user-images.githubusercontent.com/629203/194914838-55d5d9fe-207b-4e0b-9738-682590fb2caa.png)

Any ideas what might be going on?

This is the "culprit" line:
https://github.com/josdejong/jsoneditor/blob/07239a7501c32f68358495816b6eb87f7f600eff/src/js/textmode.js#L418

**Comment by josdejong** [comment]
👍 

> Then perhaps we could add it to the readme?

Good point, I've added it to the docs (see commit https://github.com/josdejong/jsoneditor/commit/be684487d5f6017a3134c8106fde876f96e7c330)
