### ISSUE TITLE
Weird characters shows on Edge browser

### ISSUE THREAD

**Issue by pastelto** [josdejong/jsoneditor#1477]
Hello, I'm using JsonEditor 9.9.2 on 3 different browsers; Chrome, Edge and Firefox.

JsonEditor works well on Chrome and Firefox but somehow weird letters show up on Edge. 
it shows like this.
![image](https://user-images.githubusercontent.com/80407403/201595110-06b44b0d-03fa-40da-af94-d2a547b2bc1c.png)

I want to use same version for 3 browsers. 
Should I downgrade my jsoneditor version? need help! Thanks

**Comment by josdejong** [comment]
Thanks for reporting. How can I reproduce your issue?

Such an issue may be caused by not having a charset defined in your HTML page: `<meta charset="utf-8">`. Or maybe there is a browser plugin causing problems.

**Comment by pastelto** [comment]
I installed jsoneditor 9.9.2 with npm install. I ran website on Chrome, FireFox and Edge using my local server where I use jsoneditor.
I do have a <meta charset="utf-8"> and jsoneditor works fine on Chrome and Firefox so I guess this isn't about <meta charset="utf-8">. Just some characters doesn't show correctly on Edge. 
![image](https://user-images.githubusercontent.com/80407403/201614678-c6e6ac97-3fac-4896-8303-d92614d27c1f.png)
As you can see in the picture I attached, "object" word shows fine but others, for examples, "select a node...", "tree", "code" and etc. are not showing correctly.

and as you mentioned how can I check browser plugin casuing problems? Thanks!

**Comment by josdejong** [comment]
So, how can I reproduce your issue? Can you demonstrate it in a [CodeSandbox](https://codesandbox.io/) for example?

> how can I check browser plugin casuing problems?

I'm not sure. Maybe in incognito/private mode?

**Comment by pastelto** [comment]
Sorry I fixed it! 
My Edge language default was 'ko(Korean)' that's why it didn't show on Edge. I changed language setting into English and it showed up correctly! 
Sorry for bothering you :( 
Thanks!

**Comment by josdejong** [comment]
👍
