### ISSUE TITLE
how to jump to line with custom key via API?

### ISSUE THREAD

**Issue by Metam** [josdejong/jsoneditor#1480]
need to search variable, scroll and select it
mode: 'code'

**Comment by josdejong** [comment]
This is undocumented and unofficial, but you can access the code editor, Ace, and use all methods that it has:

```js
const lineNumber = 123
const center = true
myJsonEditor.aceEditor.scrollToLine(lineNumber, center)
```

Is that what you mean?

**Comment by Metam** [comment]
> This is undocumented and unofficial, but you can access the code editor, Ace, and use all methods that it has:
> 
> ```js
> const lineNumber = 123
> const center = true
> myJsonEditor.aceEditor.scrollToLine(lineNumber, center)
> ```
> 
> Is that what you mean?

thank you, i will look at aceEditor methods
but its part of problem, how to get line number by key name?
for example, json:
{
	"parent": {
		"a": true,
		"b": "test"
	}
}
i need method: getLine(["parent", "b"]) // return 4
and highlight this line

in other words i need search line in code by path

**Comment by josdejong** [comment]
You can use a library such as https://github.com/epoberezkin/json-source-map/ to find the line/column given a JSON path.
