### ISSUE TITLE
Uncaught TypeError: JSONEditor.AbstractEditor.extend is not a function...

### ISSUE THREAD

**Issue by lebaphi** [josdejong/jsoneditor#1484]
Hi,
I am doing a json-editor upgrade from 1.3.5 to 2.8.0. Everything is fine except that some custom editors no longer work. e.g:
in v1.3.5 I'm using: 
```
JSONEditor.defaults.editors.custom_editor = JSONEditor.AbstractEditor.extend({....}) 
...

JSONEditor.JSONEditor.defaults.resolvers.unshift((schema: any) => {
    if (schema.format === 'custom_editor' && schema.type === 'string') {
      return 'custom_editor'
    }
    return schema
})
```
but now it shows an error `JSONEditor.AbstractEditor.extend is not a function...`

I've tried this
```
export class CustomEditor extends JSONEditor.AbstractEditor {
   constructor(options, defaults) {
      super(options, defaults); 
   }
}
```
but got this error: `Uncaught TypeError: Super expression must either be null or a function`
I don't know how to update the custom editor to match version 2.8.0, can you guys help me. 
Thanks.

**Comment by josdejong** [comment]
I think you're reporting in the wrong repository, this is a different JSON editor.

**Comment by lebaphi** [comment]
ah sorry, let me close this.
