### ISSUE TITLE
How to change the theme for code mode?

### ISSUE THREAD

**Issue by needle1989** [josdejong/jsoneditor#1485]
I've been trying to configure a custom theme for code mode, but i dont know where to start

**Comment by josdejong** [comment]
You can write your own Ace editor theme, similar to the one of JSONEditor:

https://github.com/josdejong/jsoneditor/blob/develop/src/js/ace/theme-jsoneditor.js

Then load this file in your browser, and then set the theme via the option `theme` of JSONEditor (search for `theme` in the docs: https://github.com/josdejong/jsoneditor/blob/develop/docs/api.md)

**Comment by needle1989** [comment]
thank you! that solved it
