### ISSUE TITLE
How to using event in type script

### ISSUE THREAD

**Issue by EfratVardi** [josdejong/jsoneditor#1486]
Hi'
I want to call event in type script
to example:

'<form [formGroup]="form">
    <json-editor [options]="editorOptions" formControlName="data" **(onValidationError)="valid()"**>
    </json-editor>
</form>'

how can i do this?
thanks

**Comment by josdejong** [comment]
Have you seen the example https://github.com/josdejong/jsoneditor/blob/develop/examples/22_on_validation_event.html ?

**Comment by EfratVardi** [comment]
I didnt see this example. the answer was there...
You helped me a lot
thanks!!

**Comment by josdejong** [comment]
Good to hear 👍
