### ISSUE TITLE
JsonEditor with ReactiveForms

### ISSUE THREAD

**Issue by EfratVardi** [josdejong/jsoneditor#1488]
Hi,
I try to use JsonEditor with ReactiveForms according to your example,
but it is'nt worked. 
The data is not kept in the value of the form control.

**my code:**

HTML:

****<form [formGroup]="form">
<json-editor formControlName="data" [options]="editorOptions"></json-editor> </form>****

TypeScript:
  form: FormGroup;
  @ViewChild(JsonEditorComponent, { static: false }) editor!: JsonEditorComponent;
  public editorOptions: JsonEditorOptions;
  constructor(private fb: FormBuilder) { }

  ngOnInit(): void {
    this.editorOptions = new JsonEditorOptions()
    this.editorOptions.modes = ['code'];
    this.editorOptions.mode = 'code'
    this.editorOptions.onChange = () => {
      console.log(this.form)
      this.disabled.emit(!this.editor.isValidJson())
    };

    this.form = this.fb.group({
      data: [JSON.parse(this.data)],
    });

    this.form.controls['data'].valueChanges.subscribe(change => {
      this.saveAction.emit(new Map([["data", JSON.stringify(this.form.get("data").value)]]));
    });
  }

Can you help me to solve this issue?
thanks about this wonderful tool!!
efrat

**Comment by josdejong** [comment]
> thanks about this wonderful tool!!

You're welcome :)

How to reproduce your issue? Can you create a [codesandbox](codesandbox.io/) or so?

**Comment by josdejong** [comment]
ow: and, I guess you're using some React wrapper library around `jsoneditor`? If so, it may be necessary to ask at the repo of that library instead of here.

**Comment by EfratVardi** [comment]
thanks for response,
I am'nt using in any React wrapper
I writed the code in angular.
I prepared a CodeSandbox: **https://codesandbox.io/s/reverent-hoover-7xv4ty?file=/src/app/app.component.html**
I didnt success to caus it run, but you can see the idea:
in the onChange event , printed only orginal value.
thanks,
Efrat

**Comment by josdejong** [comment]
Ok clear. Please ask your question at the the Angular wrapper library that you're using, I can't be of help here.
