### ISSUE TITLE
Switching to code mode creates a new ace worker thread every time

### ISSUE THREAD

**Issue by alechenninger** [josdejong/jsoneditor#149]
Load up switch mode example
Switch back and forth between code and another mode
Observe worker threads increase in dev tools (tested in chrome dev tools)

**Comment by ryoia** [comment]
editor.destroy() doesn't destroy the thread

**Comment by josdejong** [comment]
Thanks for the feedback, I will have a look into it, we should solve this.

**Comment by josdejong** [comment]
This is finally fixed in the `develop` branch.
