### ISSUE TITLE
Getting Error compiling schema &  EvalError: while calling setSchema

### ISSUE THREAD

**Issue by Suraj-Gupta-ML** [josdejong/jsoneditor#1493]
Hi @josdejong, i am using jsoneditor version 9.9.2,

```js
const editorRef = new JSONEditor(this.templateDivRef, options, {})
editorRef.setSchema(schema, schemaRefs)
this.editorRef.set(jsonData);
this.editorRef.expandAll();
```

while setting `editorRef.setSchema(schema, schemaRefs)` gives following errors,

Error compiling schema, function code: var refVal1 = refVal[1];var refVal2 = refVal[2]; var validate = function(data, dataPath, parentData, parentDataProperty, rootData) { 'use strict';  var vErrors = null;  var errors = 0;      if (rootData === undefined) rootData = data;      var errs_1 = errors;    var errs_2 = errors; if ((typeof data !== "number" || (data % 1) || data !== data)) {  var err =  { keyword: 'type' , dataPath: (dataPath || '') + "" , schemaPath: '#/definitions/nonNegativeInteger/type' , params: { type: 'integer' }  , message: 'should be integer'  , schema: refVal[2].type , parentSchema: refVal[2] , data: data  } ;  if (vErrors === null) vErrors = [err]; else vErrors.push(err); errors++;  }  if ((typeof data === "number")) {    if (  data < 0 || data !== data) {  var err =  { keyword: 'minimum' , dataPath: (dataPath || '') + "" , schemaPath: '#/definitions/nonNegativeInteger/minimum' , params: { comparison: '>=', limit: 0, exclusive: false }  , message: 'should be >= 0' , schema:  0         , parentSchema: refVal[2] , data: data  } ;  if (vErrors === null) vErrors = [err]; else vErrors.push(err); errors++;  }   }  var valid2 = errors === errs_2;   var valid1 = errors === errs_1;   validate.errors = vErrors;  return errors === 0;        }; return validate;

ERROR EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "default-src self https: 'unsafe-inline'".

Above code works locally but throws error in the server.

Thanks!

**Comment by josdejong** [comment]
The error about `unsafe-eval` sounds like your production environment is not allowing using JavaScript `eval`. If I'm not mistaken, that is what Ajv uses to compile a schema, that could trigger such an error. If that is indeed the cause, you can either configure your production environment to allow for this, or see if you can generate the Ajv validator code offline: https://ajv.js.org/standalone.html
