### ISSUE TITLE
colorPicker set to false for specific fields?

### ISSUE THREAD

**Issue by cpopolo** [josdejong/jsoneditor#1494]
It seems like certain string fields will invoke the color picker when the field contents can be interpreted as a color code, regardless of whether the field should be considered a color.  See the "customerCode" and "zip" fields below.  

Is there a way to inhibit the color picker on a case-by-case basis?  I don't want to set colorPicker = false because there are certain fields that are truly meant to be hex color values.

![2023-01-25_16-33-58](https://user-images.githubusercontent.com/1153310/214696747-374eefd5-162c-401f-9659-df0a7da64268.png)

**Comment by josdejong** [comment]
Thanks for bringing this up @cpopolo .

Determining whether a value is a color is currently hard-coded, and it is based on trying out if the browser can interpret the value as a color. I've tried out the values `acf` and `01741`, but I can't get the color picker to pop up in those cases. I've tried in Firefox and Chrome. What browser are you using, and are you using the latest version of `jsoneditor`? Can you share a minimal JSON document that reproduces the issue?

**Comment by cpopolo** [comment]
Hi Jos...  Please stay tuned.  I have started with your "01" example and cannot reproduce the problem yet.  I'm slowing adding those pieces of my use case (but my existing use-case is too complicated at this point).  

About the only thing for certain right now is that I'm loading the following in the head: 

- https://cdnjs.cloudflare.com/ajax/libs/jsoneditor/9.9.2/jsoneditor.min.css 
- https://cdnjs.cloudflare.com/ajax/libs/jsoneditor/9.9.2/jsoneditor.min.js
- https://cdnjs.cloudflare.com/ajax/libs/lodash.js/4.17.4/lodash.min.js

I will report back once I have the minimal working example.  I have to run off for a couple of hours but will make this my priority for eod.

**Comment by cpopolo** [comment]
@josdejong 

WOW!  The entire difference is because of the !DOCTYPE declaration at the top of the HTML file.  Your examples includes it, and my application did not.

Below is a slight modification of your 02 example:

- I am pulling CSS and JS from cdjns...
- I changed the mode from 'view' to 'tree' so you could append other strings to see the result of certain string edits in real time.
- In the declaration of the JSON, I added two elements "string2" and "string3" to demonstrate what happens when those particular strings are "acf" and "01741" since we know they provoke the issue.
- So run this example as is - you will see everything is correct...
- Then, edit the HTML and remove the very first line `<!DOCTYPE HTML>`.  Reload, and you will then see the behavior I described yesterday!

```

<!DOCTYPE HTML>
<html lang="en">
<head>
  <meta charset="utf-8">

  <title>JSONEditor | Viewer</title>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jsoneditor/9.9.2/jsoneditor.min.css" integrity="sha512-brXxIa/fpMfluh8HUWyrNssKy/H0oRzA0HhmipgfVwbXPamMUTZn1jEsvoGGwJYCRpSx4idujdul4vFwWgPROA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jsoneditor/9.9.2/jsoneditor.min.js" integrity="sha512-MP2pEPP3BGw032ovuAsX6yTu7O4J6L3YTXuyq3IpR+LuwRun9BBjOeeIKgO3bRiNlI88x3oCVb9I1/1+xmvFIg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/lodash.js/4.17.4/lodash.min.js"></script>

  <style type="text/css">
    body {
      font: 11pt arial;
    }
    #jsoneditor {
      width: 500px;
    }
  </style>
</head>
<body>
<p>
  This editor is read-only (mode='viewer').
</p>
<div id="jsoneditor"></div>

<script>
  const container = document.getElementById('jsoneditor')

  const options = {
    mode: 'tree'
  }

  const json = {
    'array': [1, 2, 3],
    'boolean': true,
    'null': null,
    'number': 123,
    'string1': 'Hello World',
    'string2': 'acf',
    'string3': '01741',
    'object': {'a': 'b', 'c': 'd'},
  }

  const editor = new JSONEditor(container, options, json)
</script>
</body>
</html>
```

To be honest, I never fully understood the direct effect of including/excluding the DOCTYPE declaration, so I'd be curious if you know offhand why that omission causes the color picker to be included.  I'm sure it has to do with the parsing of the HTML document, but it seems to be a very weird way to manifest itself, yet everything else continues to work fine.  Very curious...  

Thanks again for your other help, and I hope this work today might be helpful in some way.

**Comment by josdejong** [comment]
wow 🤯 that is amazing. Thanks for sharing.

I think the reason is that without `<!DOCTYPE HTML>`, the browser uses [an older HTML version](https://stackoverflow.com/questions/23230798/what-happens-if-i-dont-put-a-doctype-html-in-my-code-will-it-make-any-major). Apparently, in this older HTML version, a text like `acf` is seen as a valid color and interpreted as `#acf`, which corresponds with `rgb(170, 204, 255)`.

```js
const element = document.createElement('div')
element.style.color = 'acf'
console.log(element.style.color === 'rgb(170, 204, 255)')
// should output false
// with <!DOCTYPE HTML>, outputs false
// without <!DOCTYPE HTML>, outputs true
```
