### ISSUE TITLE
How to set config option to change JSON parse?

### ISSUE THREAD

**Issue by many2023** [josdejong/jsoneditor#1500]
According to https://jsoneditoronline.org/#right=local.cerire&left=local.fogudi
I found a config that can change JSON parser to LosslessJSON in the "Configure editor". But i can't found api or option config that can change JSON parser for JSONEditor.
Can you tell me how to change the JSON parser. It would be best if you can give a demo.

<img width="346" alt="image" src="https://user-images.githubusercontent.com/3831309/221836546-df5a6865-0f51-469f-aa07-300d9b0ec082.png">
<img width="1014" alt="image" src="https://user-images.githubusercontent.com/3831309/221836673-199b0092-5066-4b76-bd3e-b3026565eb38.png">

**Comment by josdejong** [comment]
The successor of this library has this option, it is named `parser`, see https://github.com/josdejong/svelte-jsoneditor/
