### ISSUE TITLE
Not able to Disable/Hide items form actions menu drop down list.

### ISSUE THREAD

**Issue by RaghvendraGit** [josdejong/jsoneditor#1506]
I am using jsoneditor on my webpage. By default for a node following action items list in action menu.

Type
Sort
Transform
Extract
Append
Insert
Duplicate 
Remove

I don't want all the items to appear, instead some of the items I want to disable/hide. I was able to hide Sort and Transform by using option enableSort and enableTransform. But I could not find similar options for other items. Is there any such option available using which I can also hide Duplicate/Remove etc. ?

**Comment by RaghvendraGit** [comment]
Thanks for your suggestion. Would you please give me reference or some sample code to disable any one item using css so I can replicate the same for other items as well.

**Comment by josdejong** [comment]
There is no example for this, but you can right click the button that you do not want to show, click "Inspect", and check the class name that the button has in the Developer Console. Then you can write some CSS to hide this button, like `display: none`.

**Comment by RaghvendraGit** [comment]
Thank you. I am able to hide these items using CSS. Thank you so much.

**Comment by josdejong** [comment]
👍
