### ISSUE TITLE
Setting large JSON data causes browser to crash

### ISSUE THREAD

**Issue by pavansandeep2910** [josdejong/jsoneditor#1507]
In our application, we have massive data that needs to be shown. but, the browser crashes with massive data when using `jsoneditor`. Is there a solution for this through `jsoneditor` (or) any other solution? Thanks.

**Comment by josdejong** [comment]
How large is your data? 

The library `jsoneditor` can handle files of 10 MB, or maybe up to 50 MB or so. 

The successor of this library, [svelte-jsoneditor](https://github.com/josdejong/svelte-jsoneditor/), can handle files up to 512 MB.

**Comment by pavansandeep2910** [comment]
it may vary accordingly. is there any way to handle any amount of data? or is there any plan to handle this? basically in our application, we just show the data to the user. no editing is provided

**Comment by josdejong** [comment]
Browsers can handle text strings up to 512MB, that is quite a hard limit of the file size you can load in a browser.

If you need to display larger files, you have to create a limited preview in some smart way.

**Comment by pavansandeep2910** [comment]
oh ok, thanks for the info, and one more question -> when handling large files, before loading the text onto the editor, is there any flag to know that the data is loaded (or) not, because for huge data it takes time, right?. with this flag, i can show some loading view

**Comment by josdejong** [comment]
Loading data in the editor is synchronous, and the browser blocks whilst loading data

EDIT: in `svelte-jsoneditor` there are async methods to set or update JSON data, you can await them.

To give you an idea: loading a 415MB JSON file from disk into https://jsoneditoronline.org (tree or table mode) takes about 4 seconds in Chrome and 10 seconds in Firefox on my computer.

**Comment by pavansandeep2910** [comment]
So thanks for immediately replying to my questions

**Comment by josdejong** [comment]
👍  you're welcome.
