### ISSUE TITLE
How to display lines of content and fix filter problems

### ISSUE THREAD

**Issue by baarbaracrr** [josdejong/jsoneditor#1508]
How can I get the lines of code to be displayed to the left of the tree content?
And another thing, when filtering, if I press enter or the down arrow, the results are underlined, but the scroll does not move, and when I click on the option "Previous result (Shift + Enter) " of the filter does the same thing as entering, not what it should do: display previous results. Do you know how I can solve these last two things (scroll and option to show the previous result)?
The options I have are the following:
`const options: JSONEditorOptions = {
      theme: 'tree',
      mode: 'tree',
      search: true,
      mainMenuBar: true,
      statusBar: true,
      enableSort: true,
      enableTransform: true
    };`

Thanks in advance!

**Comment by josdejong** [comment]
> How can I get the lines of code to be displayed to the left of the tree content?

That is simply not supported

> And another thing, when filtering, ...

I think you're referring to the search of text mode. How can I reproduce your issue exactly? Can you share a [CodeSandbox](https://codesandbox.io/) demonstrating the issue?

**Comment by baarbaracrr** [comment]
> > How can I get the lines of code to be displayed to the left of the tree content?
> 
> That is simply not supported
> 
OK :(
> > And another thing, when filtering, ...
> 
> I think you're referring to the search of text mode. How can I reproduce your issue exactly? Can you share a [CodeSandbox](https://codesandbox.io/) demonstrating the issue?

And, about this, I can't upload it.
The thing is that when I do a search, it shows me the first element found, indicating the number of results, so far so good.
When I press enter (or the down arrow) to search for the rest of the elements, they are highlighted, so far so good.
The problem is when I hit the up arrow (the button I'm highlighting for you in the screenshot), which should show the previous element, but instead, it keeps showing me content like the previous button (or pressing enter) does.
<img width="347" alt="image" src="https://user-images.githubusercontent.com/31986084/232015483-6345b20f-3fa6-4869-b662-26dfb374a73d.png">

**Comment by josdejong** [comment]
I tried to reproduce what you describe in [/examples/04_load_and_save.html](https://github.com/josdejong/jsoneditor/blob/develop/examples/04_load_and_save.html) with the latest version of `jsoneditor`, but all works as expected as far as I can see. Can you reproduce your issue in in that example?
