### ISSUE TITLE
Warning: Option "onChangeJSON" is not applicable to modes "text" and "code".

### ISSUE THREAD

**Issue by fgerges** [josdejong/jsoneditor#1514]
JSONEditor includes a property for onChangeJSON and whether it's set or not, a console warning is triggered if the modes array includes "text" or "code". I'm not using onChangeJSON so it's kind of bizarre to be getting that warning.

Option "onChangeJSON" is not applicable to modes "text" and "code". Use "onChangeText" or "onChange" instead.

**Comment by josdejong** [comment]
Thanks for reporting. How can I reproduce your issue? I do not see this happen in [03_switch_mode.html](https://github.com/josdejong/jsoneditor/blob/develop/examples/03_switch_mode.html) for example.

**Comment by fgerges** [comment]
Thanks for your reply.
I'm using ang-jsoneditor which has JSONEditor.s as dependency. A issue was opened on the same subject there :
https://github.com/mariohmol/ang-jsoneditor/issues/90
But the author suggested it must be from JSONEditor

**Comment by josdejong** [comment]
Please provide a minimal example using `jsoneditor` itself (without angular wrapper) demonstrating the issue, so we can reproduce the issue.

I've replied in the thread of the angular wrapper explaining a possible cause.

**Comment by josdejong** [comment]
Should be fixed now in the latest version of `ang-jsoneditor`, see https://github.com/mariohmol/ang-jsoneditor/issues/90
