### ISSUE TITLE
showErrorTable is missing in JSONEditor.VALID_OPTIONS

### ISSUE THREAD

**Issue by Mandy-Lf** [josdejong/jsoneditor#1515]
Since jsoneditor supports the new option showErrorTable now, this option is missing in [JSONEditor.VALID_OPTIONS](https://github.com/josdejong/jsoneditor/blob/develop/src/js/JSONEditor.js). Now a warning is logged in console when this option is used, 'Unknown option "showErrorTable". This option will be ignored'

**Comment by josdejong** [comment]
Thanks for reporting. Fixed now in `v9.10.1`

**Comment by Mandy-Lf** [comment]
Now `showErrorTable ` was appended to VALID_OPTIONS. It should be `showErrorTable` without trailing spaces
