### ISSUE TITLE
How to call JSONEditor.expand()

### ISSUE THREAD

**Issue by mbeekhuis** [josdejong/jsoneditor#1517]
Hi Jos
as far as I've seen, there should be an option to expand a node with a given path (#1441).
I've tried to call it like JSONEditor.expand(node.path, true, false) but with no luck. I guess I'm missing something.
I've set a custom function inside "onCreateMenu(items, node)", a function that inserts a specified template.
On "insert custom template" this node shall expand.
So how to expand a specific node?

Thank's for your help

**Comment by josdejong** [comment]
You can call the expand method on the editor instance, like:

```js
const editor = new JSONEditor(...)

editor.expand({ path, isExpand, recursive })
```

You can read more in the docs: https://github.com/josdejong/jsoneditor/blob/develop/docs/api.md#jsoneditorexpandoptions

**Comment by josdejong** [comment]
Ah, that's not valid JavaScript. I guess you got it working now, will close this question now.
