### ISSUE TITLE
Newline in tree mode

### ISSUE THREAD

**Issue by KoalaBear84** [josdejong/jsoneditor#1519]
I thought I had another ticket here related to newline, but cannot find it. That was having the same issue, but then it was on jsoneditoronline.org/beta at that time, and it was quickly fixed. I did see the other issues here like https://github.com/josdejong/jsoneditor/issues/1160, and I guess when someone doesn't respond for [3 years](https://github.com/josdejong/jsoneditor/issues/936) it might need to be closed :P

Might be related to https://github.com/josdejong/jsoneditor/issues/1340#issuecomment-999722083 ?

Now I'm having the same issue when using it in a website using the latest v9.10.2.

I would like to retain the (new)line breaks exactly as it is working on jsoneditoronline.org.

Online:

https://github.com/josdejong/jsoneditor/assets/5886900/8e1d8d46-ba7b-4f3e-bc5c-177ac1877b93

Own example:

https://github.com/josdejong/jsoneditor/assets/5886900/07288efb-415f-40f7-82cd-cfd346992ac6

When 'blurring' it collapses. Any way to retain the view so it remains readable?

**Comment by KoalaBear84** [comment]
Ahh, I didn't knew that 😅

I didn't RTFM the whole readme, but I see indeed that it has a successor. That is great, I'll try that one 👍😇

**Comment by josdejong** [comment]
👍

Closing this issue now to prevent it from still being open in three years from now 😉
