### ISSUE TITLE
Wrong brace hint and cursor position with redundant spaces.

### ISSUE THREAD

**Issue by rhdtl78** [josdejong/jsoneditor#1520]
There is strange issue i found.

<img width="738" alt="image" src="https://github.com/josdejong/jsoneditor/assets/28679823/ba71d7ab-8633-415e-8a95-ce528b154c75">

I locate my cusor on open brace of array, property "schedule", but editor highlight wrong position.

And move cursor to end of line 11, there is many spaces between cursor and text like screenshot below.
<img width="738" alt="image" src="https://github.com/josdejong/jsoneditor/assets/28679823/125b6ae6-9d17-4f10-b771-e8d847c78125">

And when I hit backspace, the character, end of line, is deleted, but cursor still located wrong position. See below screenshot.
<img width="738" alt="image" src="https://github.com/josdejong/jsoneditor/assets/28679823/99ec4878-0c92-42be-bcd6-47533d4cc30d">

This is how i configure editor.
```html
<link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/jsoneditor/9.10.2/jsoneditor.min.css"
          integrity="sha512-brXxIa/fpMfluh8HUWyrNssKy/H0oRzA0HhmipgfVwbXPamMUTZn1jEsvoGGwJYCRpSx4idujdul4vFwWgPROA=="
          crossorigin="anonymous" referrerpolicy="no-referrer"/>
...

<div id="jsoneditor" ></div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jsoneditor/9.10.2/jsoneditor.min.js"
        integrity="sha512-jhDajNRbXZ4gJ8SVzcuWTHbgSX66Dh98CwmAkhBHWVuEYVgY8G35rbZuRlQwrOcwEB6z5aYzxUptsSjgTGlCbA=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script type="application/javascript">
    document.addEventListener('DOMContentLoaded', async () => {
        const editorContainer = document.getElementById('jsoneditor');
        const options = {
            mode: 'code',
            modes: ['view', 'form', 'code', 'text', 'preview', 'tree'],
            indentation: 4
        };
        const editor = new JSONEditor(editorContainer, options);

        const data = await loadData();
        editor.set(data);
    }, { once: true });
</script>
```

**Comment by josdejong** [comment]
It looks like the editor in your screenshots doesn't have a monospace font. That is required.

**Comment by rhdtl78** [comment]
I tried to add Roboto mono from [google](https://fonts.google.com/specimen/Roboto+Mono).
But there is no effect on editor.

I think it is not related with font. I can select with block by dragging. See my screenshot below.
<img width="738" alt="image" src="https://github.com/josdejong/jsoneditor/assets/28679823/7b11dba3-ca28-4ae7-ac67-7f7b9ea2c76b">

**Comment by josdejong** [comment]
In your screenshots I still see that the font is not monospace. I expect that that is the cause of the issue, and that there is some CSS in your application overriding the font of the code editor.

Does the issue occur in one of the provided examples? Like https://unpkg.com/jsoneditor@9.10.2/examples/03_switch_mode.html

**Comment by rhdtl78** [comment]
You are right!!!
some styles override the fonts. 

After I override my style to use monospace font under jsoneditor in force, the issue is gone!

Thanks!

**Comment by josdejong** [comment]
Good to hear 👍
