### ISSUE TITLE
"expand" method not working (??) Expand only certain field paths

### ISSUE THREAD

**Issue by marcodarko** [josdejong/jsoneditor#1521]
const editor = new JSONEditor(container, options);

            const data = res.data;
            editor.set(data);
            editor.expand({
                path:['returnvalue.response.message.knowledge_graph', 'returnvalue.response.message.results']
            })

but these fields don't expand but providing the paths doesn't seem to work.  I think I followed the docs correctly unless I'm missing something?? 

Thank you!

**Comment by josdejong** [comment]
`path` is a single path, not an array with multiple paths. Looking at your code I _guess_ you want to do the following:

```js
const editor = new JSONEditor(container, options);

const data = res.data;
editor.set(data);
editor.expand({ path: ['returnvalue', 'response', 'message', 'knowledge_graph'] })
editor.expand({ path: ['returnvalue', 'response', 'message', 'results'] })
```

**Comment by marcodarko** [comment]
Hi @josdejong thank you for your speedy response.
I just tried this change but it also doesn't work, even tried a timeout in case it was happening too fast but no changes.
Also tried expanding only the first field but also didn't work. No errors on the console either. Any other advice?

**Comment by josdejong** [comment]
You're welcome :)

Sorry, in my example I forgot to also specify `isExpand: true`, else the node is not actually expanded. I've updated the example.

The `expand` function only expands a single node: the object or array at the end the path (and optionally all of it's children). It is the same function that powers the "Expand" button in the editor that the user can Click or Ctrl+Click.

My guess is that you want to expand all objects along the path, not just the last one. In that case you have to iterate over the path, something like:

```js
const editor = new JSONEditor(container, options)

function expandPath(path) {
  for (let i = 0; i < path.length; i++) {
    const parentPath = path.slice(0, i)
    editor.expand({ path: parentPath, isExpand: true })
  }
}

const data = res.data
editor.set(data)
expandPath(['returnvalue', 'response', 'message', 'knowledge_graph'])
expandPath(['returnvalue', 'response', 'message', 'results'])
```

**Comment by josdejong** [comment]
👍
