### ISSUE TITLE
Angular and jsoneditor migration

### ISSUE THREAD

**Issue by daniela-alves** [josdejong/jsoneditor#1527]
Hi,

I'm  doing the migration of Angular 12 to Angular 13 and I have issues with jsoneditor.

Angular 12 - jsoneditor 5.32.0
Angular 13 - jsoneditor 9.10.2

In the 'ngOnInit', I'm doing this like before:
this.editor = new editor(this.jsonEditorContainer.nativeElement, optionsCopy, this._data);

However, I have this error after migration of Angular:
![image](https://github.com/josdejong/jsoneditor/assets/126074250/913edfdf-6e87-4447-9457-f93397e9631c)

Can someone help me?

Thanks

**Comment by josdejong** [comment]
Are you using the `jsoneditor` library itself, or a wrapper library around it?

How do you import the `JSONEditor`? Can you share the code?

**Comment by daniela-alves** [comment]
I'm using the jsoneditor library.

![image](https://github.com/josdejong/jsoneditor/assets/126074250/2b43a4a9-8021-4c5c-86be-9eb4ece0173e)

![image](https://github.com/josdejong/jsoneditor/assets/126074250/b236626a-8500-47b5-9515-51ee6df55847)

**Comment by josdejong** [comment]
You could try `import editor from 'jsoneditor'` (without `* as ...`). The error sounds like it doesn't understand what it's importing.

Can you create a minimal example on [StackBlitz](https://stackblitz.com/) or [CodeSandbox](https://codesandbox.io/) demonstrating the issue?

**Comment by daniela-alves** [comment]
I did that and I see now the jsoneditor!
I will need to do more tests to check all but seems to work.
Thanks a lot
