### ISSUE TITLE
Prevent autoreplacement to string in Tree mode

### ISSUE THREAD

**Issue by Alan-Fisher** [josdejong/jsoneditor#1530]
Hey! Firstly thanks for this amazing editor 

Let's say I have this json: ```{ "1": 2 }```

If I remove 2 in Tree mode the value of the field automatically becomes an empty string

How can I prevent this behavior? In Code or Text mode it doesn't work like this: it won't trigger onChange and will wait for fixing parse error

Thank you!

**Comment by josdejong** [comment]
Thanks. Unlike the `text` mode, `tree` mode must always hold a valid JSON document, so "nothing" needs to be represented by "something", in this case an empty string. As soon as you type something like `2` again, it will replace the empty string with a number 2.

**Comment by Alan-Fisher** [comment]
@josdejong is there a way to change replacing value or prevent onChange fire?

**Comment by josdejong** [comment]
Before I can answer that question I need to understand your use case. Can you explain why this is important to you?

**Comment by Alan-Fisher** [comment]
Okay

That's because we have very large JSON with scenario and if we update it with empty string field the other logic will fail

I could check if it's valid after change for sure but looking for native solution if that's possible

**Comment by josdejong** [comment]
That makes sense. In general, the user can edit/create/delete anything anywhere in the JSON document, so there are plenty of ways to have an document that cannot be processed by your logic. 

To make sure that your document is valid you can validate the document, And only save/apply/run when the document is valid. JSONEditor has built in support for JSON Schema, you can utilize that. Or you can write your own validation code, run that in `onChange`, and show a warning/error message when the document is not valid. Does that make sense?

**Comment by Alan-Fisher** [comment]
Thank you! Will do that

**Comment by josdejong** [comment]
👍
