### ISSUE TITLE
Identify which node is Duplicated by user

### ISSUE THREAD

**Issue by akshitasinghal1999** [josdejong/jsoneditor#1533]
Hi, currently I want to know user has duplicated which node. I am trying to use onEvent here, but it is not recognizing click on duplicate button

**Comment by josdejong** [comment]
You can maybe replace/wrap the duplicate button with your own using `onCreateMenu`? You'll also have to intercept the quick key Ctrl+D, not sure what the handiest way for that is though.

Or you could hack into the editor to intercept method calls to `onDuplicate`. This is not an official API and you need to deal with undocumented internals. And things may break in the future. But it could look something like:

```js
// Warning: use on your own risk, may break in the future 
const onDuplicateOriginal = editor.node.constructor.onDuplicate
editor.node.constructor.onDuplicate = function (nodes) { 
  console.log('duplicating!', nodes)
  onDuplicateOriginal(nodes)
}
```
