### ISSUE TITLE
Quickkeys for the Format and Compact buttons

### ISSUE THREAD

**Issue by codeowl1** [josdejong/jsoneditor#154]
Hi there,

Thanks for a great product!!  

I use this every day to expand and collapse JSON strings that we use in our project.  

It would be awesome if there was a keyboard shortcut to expand/collapse a node in the text side.  We only use this side and have the object side hidden.  We do a lot of copy and paste between VS and the JSON Editor.  It would be great not to have to use the mouse.  At the moment the only way to expand/collapse the JSON code is with the buttons at the top.  Some keyboard shortcuts for these would be awesome!!  Also the ability to do it for the node that the cursor is at would be great.

Thanks heaps for your time on this project.

Regards,

Scott

**Comment by josdejong** [comment]
Thanks. 

The left panel with code is powered by Ace editor: http://ace.c9.io/. This editor has quite some shortcut keys available: https://github.com/ajaxorg/ace/wiki/Default-Keyboard-Shortcuts. There are shortcut keys available for folding/unfolding. Basically, you can set the cursor on the start or end of an object or array and press `Alt-L`.

From the Ace docs:

| PC (Windows/Linux)             | Mac                            | action                         |
|:-------------------------------|:-------------------------------|:-------------------------------|
| Alt-0 | Command-Option-0 | fold all |
| Alt-L, Ctrl-F1 | Command-Option-L, Command-F1 | fold selection |
| Alt-Shift-L, Ctrl-Shift-F1 | Command-Option-Shift-L, Command-Shift-F1 | unfold |
| Alt-Shift-0 | Command-Option-Shift-0 | unfold all |

**Comment by codeowl1** [comment]
Josdejong,

Thanks heaps for the prompt reply mate.  Those commands are great.  However the main functions I want to do, (I didn't explain it well in my previous post), is what the two buttons at the top left do.  Format, Compact.  When I mouse over these buttons they say:

 - Format JSON data, with proper indentation and line feeds
 - Compact JSON data, remove all whitespaces
Basically we past compacted JSON from our project into the editor, then Format it, edit it, Compact it, and then copy it out, and back into our project.  We do this many times a day, so if I could do this without having to move to the mouse it would be awesome.

Thanks again for your time.

Regards,

Scott

**Comment by josdejong** [comment]
Ah ok, yes there are no quickkeys for these two buttons. They would be very useful. I've been annoyed by this myself too a couple of times now, time to do something about it ;)

**Comment by codeowl1** [comment]
That would be just fantastic mate.  I suffer from RSI so if I can avoid the
mouse as much as possible it is a good thing.

Thanks again for your time.

Regards,

Scott

**Comment by codeowl1** [comment]
Josdejong,

That is brilliant!  Thanks heaps for the implementation of this change mate.  How do I update the Chrome Extension so it includes the change?

Regards,

Scott

**Comment by josdejong** [comment]
Hi Scott, I still have to update the chrome extension, sorry. Will do that tonight or tomorrow. It will then automatically update in your browser.

**Comment by codeowl1** [comment]
ok great.... thanks for your efforts mate... much appreciated!!

Regards,

Scott

**Comment by josdejong** [comment]
The chrome app is updated now, have fun :)

**Comment by codeowl1** [comment]
Jos,

Thanks heaps for you effort in this update mate.  As I use this extension
every day it is going to be a great time saver and relief to my mouse arm.

Much appreciated ;-)

Regards,

Scott

**Comment by josdejong** [comment]
Thanks, you're welcome :)
