### ISSUE TITLE
Using onCreateMenu add ContextMenu items which makes contextmenu overflow page

### ISSUE THREAD

**Issue by SnowWarri0r** [josdejong/jsoneditor#1543]
I only add one item to the menu.
In some case, menu is on the top of the anchor,which is ok.
But in some other case,there is a problem.
here is a example which has problem here.
![image](https://github.com/josdejong/jsoneditor/assets/62747881/13f8cf94-a55a-4176-8ca0-2c598ed740e3)
I have already noticed popupAnchor() function,but i have no idea how to use this function.
Hidden menu is really annoying.
if you could give me a solution,I'll appreciate it.

**Comment by SnowWarri0r** [comment]
I tried to use min-height to root div element,which is seems to solve this problem

**Comment by josdejong** [comment]
The context menu should automatically be displayed above the button when there is not enough space below, is that working correctly in your case? (you can try out a few of the provided examples).

**Comment by SnowWarri0r** [comment]
I tried to add height,which seems to solve this problem.I used 500px in the past,which has problem.and now i'm using 600px.

**Comment by josdejong** [comment]
Ah, that makes sense. Thanks for sharing your solution!
