### ISSUE TITLE
How to clear and set text to searchbox in jsoneditor

### ISSUE THREAD

**Issue by Laxmikantwagh25** [josdejong/jsoneditor#1546]
I have to clear or set the text to search box in jsonEditor on any event.
How can I achieve this?

**Comment by josdejong** [comment]
There is no API for that, but hacking in the editor you could clear the search like:

```js
editor.searchBox.dom.search.value = '' 
editor.searchBox._onSearch(true)
```

Warning: this is an unofficial API, and this may break in the future in case the internals of the editor are refactored.
