### ISSUE TITLE
util.parseString is trimming zero in front of number

### ISSUE THREAD

**Issue by DarkFisk** [josdejong/jsoneditor#1550]
Hello,
I had a problem that when I have array, and even added in schema validation that only strings allowed, jsoneditor always trimming 0 in front of number, after some investigation I found that `parseString` util method is casting value like 0102031234 to number and removes zero in front and making 102031234, that is absolutely wrong. (this number is actually example of CPR number in Denmark, it is like your passport number)
Please, take into consideration my [PR](https://github.com/josdejong/jsoneditor/pull/1549)

**Comment by josdejong** [comment]
Fixed via #1549

**Comment by josdejong** [comment]
Fixed now in `v9.10.3`.
