### ISSUE TITLE
Font size increasing for no reason on mobile Webview

### ISSUE THREAD

**Issue by mureatencio** [josdejong/jsoneditor#1558]
When I try to render an editor and expand a section containing an URL node, the font size increases. 
This behavior only happens on "view" mode.
Reproduced the issue on iOS and Android webviews.
![image](https://github.com/josdejong/jsoneditor/assets/2531394/36dfaa04-3804-48c1-ab03-f890b763eeac)

**Comment by josdejong** [comment]
Thanks for reporting. How can I reproduce this issue?

**Comment by mureatencio** [comment]
I'm just loading this html in a regular WKWebView (iOS):

<!DOCTYPE HTML>
        <html lang="en">
        <meta name='viewport' content='width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no' />
        <head>
            
            <meta charset="utf-8">
            <link href="https://cdnjs.cloudflare.com/ajax/libs/jsoneditor/9.10.2/jsoneditor.min.css" rel="stylesheet" type="text/css">
            <script type="text/javascript" src="https://unpkg.com/jsoneditor@9.10.2/dist/jsoneditor.min.js"></script>
        </head>
        <body>
            <div id="jsoneditor" style="width: 100%; height: 100%;"></div>
            <script>
                // create the editor
                const container = document.getElementById("jsoneditor")
                const options = {
                    onChangeText: function(jsonText){
                        window.webkit.messageHandlers["onChangeText"].postMessage(jsonText);
                    },
                    search: false,
                    mainMenuBar: false,
                    enableTransform: false,
                    limitDragging: true,
                    mode: 'view'
                    }
                    const editor = new JSONEditor(container, options)
            
                    // set json
                    const initialJson = {
                    "a" : "123456789012345678901234567890123456789001234567890",
                    "b" :
                      {
                        "c" : "http://123456789012345678901234567890123456789012345678",
                        "d" : "1234567890123456789012345678901234567890123456789012345",
                      }
                    }
                editor.set(initialJson)
                // get json
                const updatedJson = editor.get()
            </script>
        </body>
        </html>


https://github.com/josdejong/jsoneditor/assets/2531394/9e8bb6dc-e54f-4d20-ad28-1a4048776e92

the json is:
`
{
            "a" : "123456789012345678901234567890123456789001234567890",
            "b" :
              {
                "c" : "http://123456789012345678901234567890123456789012345678",
                "d" : "1234567890123456789012345678901234567890123456789012345",
              }
        }
`

**Comment by mureatencio** [comment]
Also noticed the word wrap is disabled when the json contains a URL, is there any way to avoid it?

**Comment by josdejong** [comment]
Thanks for sharing. 

I can indeed reproduce the issue on Mobile Safari, I tried in the Samsung internet browser too but there I don't see the increased font size.

I guess that Mobile Safari has certain default CSS styles that introduce this larger font. We would have to figure that out, help would be welcome.

> Also noticed the word wrap is disabled when the json contains a URL, is there any way to avoid it?

It should indeed also wrap, we'll have to fix that. It should be possible to look at the CSS for wrapping used in the non-url values, and apply that to the url values too.

**Comment by josdejong** [comment]
For testing: I've put your example on https://jsbin.com/bajilob/edit?html

**Comment by mureatencio** [comment]
I was able to fix the font size changing via CSS with the property: `-webkit-text-size-adjust: 100%;`
Still dealing with the wrap issue.

**Comment by josdejong** [comment]
Thanks for sharing. So where did you apply the CSS property? Will it solve the issue when I add the following CSS to 

```css
.jsoneditor {
  -webkit-text-size-adjust: none;
  text-size-adjust: none;
}
```

**Comment by josdejong** [comment]
I managed to reproduce the issue with the url not wrapping: it only happens in Chrome and when the editor has mode `view`. I haven't yet found the cause.

See https://jsbin.com/bajilob/edit?html,output

**Comment by josdejong** [comment]
This should be fixed now in `v9.10.4`, can you give it a try @mureatencio?

**Comment by mureatencio** [comment]
Works like a charm, thanks a lot!

**Comment by josdejong** [comment]
👍
