### ISSUE TITLE
Code Editor Cursor Misalignment In Firefox

### ISSUE THREAD

**Issue by R-Elias** [josdejong/jsoneditor#1559]
**Description:**
There is a cursor alignment issue in JSONEditor's code editor when used within Firefox. The cursor does not reflect the actual insertion point for characters, resulting in misaligned edits.

**Steps to Reproduce:**

    Open JSONEditor in Firefox.
    Navigate to the code editor.
    Attempt to edit a value by inserting a character at a specific position in any row.

**Expected Behavior:**
The character should be inserted exactly at the designated cursor position.

**Actual Behavior:**
The character is inserted at the (n-6)th position instead of the intended nth position. Occasionally, this issue also leads to the deletion of the character that was initially at that position.

**Environment:**

    Browser: Firefox 119.0 (64-bit)
    Extensions: None
    Operating System: macOS Monterey 12.6

**Additional Notes:**

    The issue is not reproducible in OperaGX and Chrome, where the cursor aligns and functions as expected.

https://github.com/josdejong/jsoneditor/assets/114922778/816496f9-225f-4930-8bf2-7de8e19a6e22

**Comment by josdejong** [comment]
Thanks for the clear description. Looking at the screenshare, you're using a font that is not monospace. The issue will be solved when you use a monospace font.

**Comment by R-Elias** [comment]
You are right. Thanks !
The font settings in my browser were configured to take precedence over website-specified fonts. After adjusting this setting to prioritize website fonts, the issue was resolved.
