### ISSUE TITLE
Feature request - more than one root node

### ISSUE THREAD

**Issue by Madd0g** [josdejong/jsoneditor#156]
I'm mostly using the "View" view (sometimes "Text" for formatting), and I've often wanted to add more expandable objects to the "View" editor, but not under the same root object.

It's not a huge deal, if it's not possible I'll just stuff it all under one object with one more nesting level, I just thought since the UI is already in place and is very capable, why not have more than 1 root node?

In my perfect scenario, I would be able to style each root node individually, maybe name them so I can programatically add and remove them with ease.

What do you think?

Thanks

**Comment by josdejong** [comment]
Thanks for your suggestion. Allowing multiple objects in the same editor will require a much more complicated API (when getting or setting data, or listening for changes, you must also reckon which of the JSON objects it is about). I'm affraid the end result will be confusing and the use case is very specific.

I think you can do two things:
- Create an Array containing multiple Objects like 

  ```
  [{"id":"First node"}, {"id": "Second node"}, ...]
  ```
- Just create multiple JSON Editors above each other, each holding one object.

**Comment by Madd0g** [comment]
Thanks, that's what I assumed, that the API is too complex to allow that.

**First suggestion** - does having a field called "id" do anything in the UI or was that just an example? I need to pass multiple but predefined things, so using an object makes more sense over an array.

**Second suggestion** - I really just wanted the search features to be unified across both objects. I wonder if it would be possible to hide the other toolbar and mirror the searches. 

Thanks again

**Comment by josdejong** [comment]
You're welcome.

1. `id` was just for the example
2. Yes, you can hide the menu by applying some css styles:

    ```css
    .jsoneditor div.menu {
      display: none;
    }
    .jsoneditor div.outer {
      margin-top: 0;
      padding-top: 0;
    }
    ```
