### ISSUE TITLE
How to run it locally without explicitly have to build it, 

### ISSUE THREAD

**Issue by raybittuiq** [josdejong/jsoneditor#1567]
in the root index.js it's pointing to ./dist/jsoneditor but I would like to point it to the main entry point from where the application will work like it is running in local

**Comment by josdejong** [comment]
I don't understand what you mean, sorry.

**Comment by josdejong** [comment]
You don't have to build the library, you can use it from npm or a CDN: https://github.com/josdejong/jsoneditor#install

**Comment by josdejong** [comment]
Closing this issue due to lack of response. Please reopen the issue if needed.
