### ISSUE TITLE
这是为什么

### ISSUE THREAD

**Issue by jianggangsheng** [josdejong/jsoneditor#1569]
browserify ./index.js -o ./jsoneditor.custom.js -s JSONEditor

Error: Can't walk dependency graph: Cannot find module '../config' from

**Comment by jianggangsheng** [comment]
node 20.10.0

**Comment by josdejong** [comment]
Thanks for your input. 

Can yo please change the title of the issue to English?

It looks like browserify is not able to resolve the `require` urls in the bundle that are coming from the Ace editor. There is no need though to bundle the bundle again, so maybe it is possible to exclude double bundling of `jsoneditor` in your project? Or switch to a different bundler like Vite?

**Comment by josdejong** [comment]
Closing this issue due to lack of response, please reopen if needed.
