### ISSUE TITLE
Spanish Grammar corrections in i18n file

### ISSUE THREAD

**Issue by gonchesan** [josdejong/jsoneditor#1570]
Hello Jos!!
I foun some words are missing accent marks and one of the values is still in English.

- [ ] autoType 
- [ ] modeCodeText
- [ ] modeTreeText
- [ ] containsInvalidProperties
- [ ] containsInvalidItems

**Comment by josdejong** [comment]
Thanks for reporting. Can you help provide the right Spanish texts?

**Comment by gonchesan** [comment]
Yes! of course! I have no problem.

**Comment by josdejong** [comment]
Fixed now in `v10.0.1` via #1571.
