### ISSUE TITLE
How to add more options to action menu?

### ISSUE THREAD

**Issue by akshitasinghal1999** [josdejong/jsoneditor#1574]
Hi, 
I need to add more option to the action menu. And assign some onclick event to that option. How can execute this?
<img width="100" alt="Screenshot_1" src="https://github.com/josdejong/jsoneditor/assets/42026449/6498655d-07fa-4316-af98-3b3c13f2727d">

**Comment by josdejong** [comment]
Please read the docs. There is also a full example included in the examples folder.

**Comment by josdejong** [comment]
Docs: https://github.com/josdejong/jsoneditor/blob/develop/docs/api.md then search for `onCreateMenu`
Example:  https://github.com/josdejong/jsoneditor/blob/develop/examples/21_customize_context_menu.html
