### ISSUE TITLE
Question: Hide some of the options in option of 'tree' mode.

### ISSUE THREAD

**Issue by gitsunny404** [josdejong/jsoneditor#1577]
Hey, I want to hide some of the options in the tree mode. I am not able to find the solution. Your help will be highly appreciated please.

**Comment by josdejong** [comment]
Which options? Do you mean options in the context menu, or in the main menu?

**Comment by josdejong** [comment]
Closing this issue due to a lack of response, please reopen if needed.

In general: you can hide menu buttons using CSS.
