### ISSUE TITLE
Feature request: Configurable indentation

### ISSUE THREAD

**Issue by Rokannon** [josdejong/jsoneditor#158]
Please add option to set number of spaces used in indentation.

**Comment by josdejong** [comment]
There is already an option `indentation` (see [API docs](https://github.com/josdejong/jsoneditor/blob/master/docs/api.md)). 

However I saw that the indentation works fine for compacting/formatting, but is not correctly applied to Ace editor (mode code). I've fixed that now in the develop branch.

**Comment by Rokannon** [comment]
Oh... I see. But I meant implementing that option in jsoneditoronline.com site interface. It's not a big deal but I use this site to edit JSON. It's really good as it is always verifies syntax and it is always accessible from any computer.

**Comment by josdejong** [comment]
ah ok, thanks for your suggestion!

**Comment by josdejong** [comment]
I see this issue is still open. Since some time you can actually configure the indentation in the web application. Will close this issue now.
