### ISSUE TITLE
Available Modes Change Dynamically

### ISSUE THREAD

**Issue by nbabaka2023** [josdejong/jsoneditor#1580]
Hey! Thank you so much for such a great library

Is there any way to change available modes on the fly when the editor has already been created and I need to restrict the user to select some modes?

Thank you

**Comment by josdejong** [comment]
You're welcome :)

One way to do that is to create the editor with all modes enabled, and then hide the items from the menu select box using CSS.

Another way is to hide the original mode select box, and replace it with your own where you can dynamically add/remove modes.
