### ISSUE TITLE
Bundling size 

### ISSUE THREAD

**Issue by AbdulTheActivePiecer** [josdejong/jsoneditor#1590]
Hello there guys, much respect for the effort and dedication put into this project :D 

This is more of a question than an issue, basically I only need the view mode of the jsonEditor and therefore don't really need ajv or Ace, so is there a way to have the package without these two dependencies to lower the bundle size ?

**Comment by josdejong** [comment]
Have you tried the provided `minimalist` bundle?

https://github.com/josdejong/jsoneditor/blob/develop/src/docs/which%20files%20do%20I%20need.md#minimalist-version

**Comment by AbdulTheActivePiecer** [comment]
Will do, thanks a lot.

just wondering, maybe I should open this as another issue but I am not sure if it is worth it, in "preview" mode when a value is wrapped or takes multiple lines, the key gets wrapped as well even though it shouldn't like in here: 
![image](https://github.com/josdejong/jsoneditor/assets/106555838/cdb9fb18-57f9-445a-b6c9-2a7a74a82bb0)
![image](https://github.com/josdejong/jsoneditor/assets/106555838/115ab5fa-295a-4554-b972-7d8951e7b394)
Is there anything I can configure to stop that from happening ?

**Comment by josdejong** [comment]
hmm. You can try fiddling some CSS to making the whitespace non breaking.

**Comment by AbdulTheActivePiecer** [comment]
Thanks a lot man, much appreciated, was wondering if I can add a way to make link values configurable, like adding rel attribute and target to make them open in new windows.

**Comment by josdejong** [comment]
That will require changing the source code.

In the successor of this library, [svelte-jsoneditor](https://github.com/josdejong/svelte-jsoneditor/), things like that are possible: it has an option to customize how values are rendered via [`onRenderValue`](https://github.com/josdejong/svelte-jsoneditor/?tab=readme-ov-file#onrendervalue).

**Comment by AbdulTheActivePiecer** [comment]
Thanks a lot @josdejong 🤝
