### ISSUE TITLE
Get node path

### ISSUE THREAD

**Issue by mbeekhuis** [josdejong/jsoneditor#1595]
Hi Jos

I'm using tree mode and custom validation. Since my JSON-file may become pretty large, I've decided to store the edited nodes in an array and validate only the nodes in this array. (onValidate > loop over edited nodes array). So far I've just stored the path info from onEvent/input. But there's an issue when the user changes the order of the nodes (drags or creates a new one). At this point, the stored paths are not getting updated and therefore these nodes won't validate (or the wrong ones do). My solution for now is to pass the whole node reference onEvent as an additional parameter: 

```
key: "_onEvent",
    value: function _onEvent(event) {
      var element = event.target;
      var isField = element === this.dom.field;
      var isValue = element === this.dom.value || element === this.dom.checkbox || element === this.dom.select;
      if (isField || isValue) {
        var info = {
          field: this.getField(),
          path: this.getPath(),
          **node: this**
        };
```
        
I push the "node" reference to the array onEvent/input and I'm able to call node.getPath() onValidate and update the path.
But I'm not sure about performance issues when passing and storing cyclonic objects (node).
What do you think about that?

Thank's a lot 

Cheers
Marc

**Comment by mbeekhuis** [comment]
Update:
Since the order of the node can't have changed on restart, I can simply save the "error-nodes" as simple objects containing only the path. Then onValidate check if the node is an error-node and if so, get the corresponding jsoneditor-node with:
`editor.node.findNodeByPath(node.path);`.

So everything works fine now, but still not sure about performance issues when passing and storing cyclonic objects onEvent ...

**Comment by josdejong** [comment]
If you're worried about performance: just try it out and see if you hit a bottleneck or not.

I'm not sure if you're solution with keeping references to nodes works in all cases, for example when collapsing and expanding an array or object, all nodes are deleted and re-recreated again, right? How do you make sure you're not getting stuck with "orphans"?

If validation is slow, you could also look into a different direction, like memoizing results per node, or evaluating the validation after a small delay or after a button click or so. Not sure if that would be helpful for your case though.

**Comment by mbeekhuis** [comment]
I've found a better way without hardcoding and passing the node reference. I can get the corresponding (editor) node onEvent input with: `editor.node.findNodeByPath(path);`
Then store this node in a (global) array (don't see performance issues so far, have to monitor it though) and onValidate I loop over this array and get the actual path with node.getPath().
Remove the node when not found in data.
Dragging around, collapse and expande works fine so far ...

**Comment by josdejong** [comment]
Good to hear, thanks for sharing your solution, that may help others with a similar challenge. I'll close this issue now.
