### ISSUE TITLE
action menu is not closing

### ISSUE THREAD

**Issue by Karanpal97** [josdejong/jsoneditor#1596]
@josdejong i am using the lib in by code and the action menu is not closing once i open it can u plz tell me what wrong i am doing
this is my code
  {(() => {
                  try {
                    if(data.inputs[inputParam.name]){
                      return (
                        <Editor
                        value={JSON.parse(data.inputs[inputParam.name])} 
                        onChange={(newValue) => (data.inputs[inputParam.name] = JSON.stringify(newValue))}
                        search={false}
                        enableTransform={false}
                        onError={(e) => console.log("error", e)}
                        enableSort={false}
                        navigationBar={false}
                    />)
                    }   
                  } catch (error) {
                    return <div>Error: Invalid JSON format</div>;
                  }
                })()}
                
                
![s5](https://github.com/josdejong/jsoneditor/assets/120642407/bf986878-6aec-49b6-a14a-b45f64446505)

**Comment by josdejong** [comment]
Thanks for reporting. 

If you try out any of the built in examples the menu closes when clicking outside: https://github.com/josdejong/jsoneditor/tree/develop/examples

I suppose it can have to do with iframes or popups or something like that, but it is hard to guess.

How to reproduce your issue with just the library itself? Can you create a minimal example demonstrating the issue?

**Comment by Karanpal97** [comment]
Hi @josdejong 

Thank you for your response.

I understand that the action menu should close when clicking outside of it in the examples provided. However, in my implementation, the menu remains open even when I click elsewhere and even inside. Here's a more detailed description of the issue:

When I open the action menu in the JSON editor, it does not close regardless of where I click outside the menu. This issue persists in my application, which is not using iframes or popups.

Below is a simplified version of my code to help illustrate the problem:

jsx

{(() => {
  try {
    if (data.inputs[inputParam.name]) {
      return (
        <Editor
          value={JSON.parse(data.inputs[inputParam.name])}
          onChange={(newValue) => (data.inputs[inputParam.name] = JSON.stringify(newValue))}
          search={false}
          enableTransform={false}
          onError={(e) => console.log("error", e)}
          enableSort={false}
          navigationBar={false}
        />
      );
    }
  } catch (error) {
    return "Error: Invalid JSON format";
  }
})()}

To help you reproduce the issue, I've stripped the code down to the essentials. When I click on the action menu and then anywhere outside of it, the menu remains open.

Could you please provide any insights or suggestions on what might be causing this behavior? Is there any specific configuration or additional code required to ensure the menu closes as expected?

Thank you for your assistance.

**Comment by josdejong** [comment]
Can you create a minimal example for example on https://stackblitz.com/ ?

**Comment by Karanpal97** [comment]
![s5](https://github.com/josdejong/jsoneditor/assets/120642407/41c81643-ccd7-45e9-a751-b9888f3680ae)
see this i have used the lib and code already shared now here i open the action menu once opened ites not closing anyway that's the issue is.
![image](https://github.com/josdejong/jsoneditor/assets/120642407/629bb00f-6321-4903-97e4-86ef0c3b2db1)

**Comment by Karanpal97** [comment]
@josdejong plz reply

**Comment by josdejong** [comment]
Closing this issue now due to a lack of response. Please reopen if still relevant (and providing more information).
