### ISSUE TITLE
ES5 module import relies on nodeJs imports

### ISSUE THREAD

**Issue by Ketec** [josdejong/jsoneditor#1599]
```
Module build failed: UnhandledSchemeError: Reading from "node:url" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
```

The vanilla version (not svelte).

Why is it using nodeJs specific functionality that is not available in browser environments without custom polyfills?

**Comment by josdejong** [comment]
Thanks for your inputs. I think you are talking about the `svelte-jsoneditor` library, can you open an issue there? 

See: https://github.com/josdejong/svelte-jsoneditor/issues
