### ISSUE TITLE
not saving online

### ISSUE THREAD

**Issue by leandroruel** [josdejong/jsoneditor#160]
when i click "save online", nothing happens, and the message "saving document..." stay in a infinite loop.

**Comment by josdejong** [comment]
Thanks for your report. Does this happen consistently for you, or was this a one time error? What OS and browser are you using?

**Comment by leandroruel** [comment]
Ubuntu, this happened all the time. and was my first time using the site.

**Comment by josdejong** [comment]
Ok, and what browser are you using on Ubuntu?

**Comment by leandroruel** [comment]
chrome 40.

**Comment by mnstrr** [comment]
Same permanent issue on Windows 7(64):

Chrome 40.0.2214.94: Shows "saving document"-message, nothing happens, no reload.
Firefox 35.0.1: Site reloads, no message or url shown.
IE 10: Shows error-message "access denied".

**Comment by josdejong** [comment]
Thanks for the feedback. That's odd. I don't think this is related to a specific browser or OS (else we would have had *lots* of people having this issue). I'm not yet sure what can be causing this.

Any chance of checking out the JavaScript Console of your browser to see if that displays more detailed information about the problem? (typically you can press F12 to open this console).

**Comment by goricz** [comment]
Same problem with secured URL https://www.jsoneditoronline.org 

Console shows this error:
Mixed Content: The page at 'https://jsoneditoronline.org/#' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://api.jsoneditoronline.org/v1/docs/'. This request has been blocked; the content must be served over HTTPS.

Saving works fine on unsecured site (http://www.jsoneditoronline.org/)

**Comment by josdejong** [comment]
Thanks, good point.

**Comment by JosDet** [comment]
Fuck！！Big Fat liar! Hurry to repay $500000!!!!!

**Comment by josdejong** [comment]
I think this was fixed in #179
