### ISSUE TITLE
JSONEditor not rendering when value change

### ISSUE THREAD

**Issue by wilsontcm69** [josdejong/jsoneditor#1600]
This is a **React Typescript** project. I am using _JSONEditor_ to display data from `useState<Array<typeA>>` 

### Project Overview:
`useEffect()`
- Fetch and store data into data1 & data2 based on conditions. Then `map` & display through JSON Editor.

`addData1()`
- A predefined list(data3) is used for user to multiselect.
- Once confirmed, `push` the additional data into data1.

`deleteData(index: number)`
- Data is `splice` based on index then return newData

`copyToData2(index: number)`
- Add the data[index] to data2 then all `deleteData(index)`

### Problem
-  _JSONEditor_ doesn't reflect when `deleteData(index: number)` or `copyToData2(index: number)` is called.
- `console.log(data1)` and `console.log(data2)` is correct but _JSONEditor_ still showing old info.
- Scenario: data1 have 3 elements & data2 have 1. When `deleteData(index: number)` or `copyToData2(index: number)` on the 2nd element, data1 will remain 2 elements but  _JSONEditor_  is displaying the info for 2nd element.

File: [test.txt](https://github.com/user-attachments/files/15574840/test.txt)

**Comment by josdejong** [comment]
I think what is missing in your `JsonEditorComponent` is sending the updated version of `inputData` to `jsonEditorInstance` using `jsonEditorInstance.update(inputData)`. Currently, you only pass `inputData` once during construction.
