### ISSUE TITLE
Restrict auto-conversion of hexadecimal inputs

### ISSUE THREAD

**Issue by gauravgupta98** [josdejong/jsoneditor#1601]
Hello,

we are currently integrating JSON editor in appsmith and facing an issue where if we add any hex string in the json it gets autoconverted to integer. Is there a way we can prevent this behaviour and keep the hexadecimal as string.

Replication steps -
https://app.appsmith.com/app/json-editor-viewer/page1-659b8a776e6f515089938690?utm_source=portal
In the above link, edit any value and update it to `0x12` and tab out

**Comment by josdejong** [comment]
Thanks for reporting. I've fixed this bug via 3870ec1 (not yet published)

**Comment by gauravgupta98** [comment]
when is this expected to be published in prod?

**Comment by josdejong** [comment]
I expect tomorrow.

**Comment by josdejong** [comment]
Fixed now in `v10.1.0`
