### ISSUE TITLE
query?

### ISSUE THREAD

**Issue by stokebreakup** [josdejong/jsoneditor#1603]
> A web-based tool to view, edit, format, and validate JSON

JSONPath is a query language for JSON, similar to XPath for XML. It allows you to select and extract data from a JSON document. Would it be interesting to have JSONPath support in jsoneditoronline?

**Comment by josdejong** [comment]
Thanks, yes we could do that in the successor of this library, `svelte-jsoneditor`, which has an API to customize the query language and is used by https://jsoneditoronline.org. I've opened a discussion there (help implementing it would be welcome):

https://github.com/josdejong/svelte-jsoneditor/discussions/457

**Comment by josdejong** [comment]
Support for JSONPath is implemented via https://github.com/josdejong/svelte-jsoneditor/pull/470. It will take a couple of weeks before it will be plublished in the web application (is part of a big `v1` release of `svelte-jsoneditor`).
