### ISSUE TITLE
Error SELF IS NOT DEFINED when running as SSR.

### ISSUE THREAD

**Issue by ssoju** [josdejong/jsoneditor#1605]
hello.
I'm working with jsoneditor,
When I run it as SSR, I get an error as shown below.
I would like to know if there is any solution for this error.

Thanks for your time to read.

react: 18.2.0
webpack: 5.88.2
jsoneditor: 10.1.0
server: express

<img width="770" alt="image" src="https://github.com/user-attachments/assets/51385fb1-1d0b-4cdd-bb8a-366334ee8501">

**Comment by josdejong** [comment]
The solution is to not run the editor server side. You can achieve that by using a dynamic import.

**Comment by ssoju** [comment]
> The solution is to not run the editor server side. You can achieve that by using a dynamic import.

Thanks for the answer.

I tried, but it didn't work. Can you give me a hint?

**Comment by josdejong** [comment]
See #1433 or [search for similar questions about SSR](https://github.com/josdejong/jsoneditor/issues?q=is%3Aissue+ssr).

**Comment by gilbert-ya** [comment]
> See #1433 or [search for similar questions about SSR](https://github.com/josdejong/jsoneditor/issues?q=is%3Aissue+ssr).

We can't do this because we're not next.js.
And the other way is not beautiful either.

Any plans to upgrade this?

Thanks anyway.

**Comment by josdejong** [comment]
You can probably use something like `const JSONEditor = await import('jsoneditor')` in the constructor of your class.

There are no plans to make `jsoneditor` work with SSR, but if anyone wants to help make it work I'm open to a PR improving this.

**Comment by gilbert-ya** [comment]
<img width="450" alt="image" src="https://github.com/user-attachments/assets/473ec54e-8b94-4ac8-9f0c-3b5e4ed27c80">

We do this and get the same error.
I can't detect whether SSR is present or not.
Anyway, I get it. Thanks for your kind reply.

**Comment by ssoju** [comment]
> You can probably use something like `const JSONEditor = await import('jsoneditor')` in the constructor of your class.
> 
> There are no plans to make `jsoneditor` work with SSR, but if anyone wants to help make it work I'm open to a PR improving this (EDIT: the code base is not using any framework and is filled with `document.createElement(...)`, so I think it will be hard to make it SSR compatible).

<img width="416" alt="image" src="https://github.com/user-attachments/assets/cfe5a458-1075-4e9b-bfc4-b89583ce2185">

We do this and get the same error.
I can't detect whether SSR is present or not.
Anyway, I get it. Thanks for your kind reply.

**Comment by josdejong** [comment]
You're welcome. There is not a single answer to this unfortunately. How to enable/disable SSR depends on what framework and setup you use. I'll close this issue now, feel free to reopen if needed (and feel free to share your solution if you got it working).
