### ISSUE TITLE
reordering of fields

### ISSUE THREAD

**Issue by akshitasinghal1999** [josdejong/jsoneditor#1606]
HI,
in tree mode, after I import a JSON file, the order of the key value pairs get jumbled without any set pattern. I have tried to use sortObjectKeys={false} but it doesnt seem to be the root cause. Could you help me with the same please. 
Thanks.

**Comment by josdejong** [comment]
Can you give an example of a document that has the order of the keys changed when loading it into the editor?

**Comment by akshitasinghal1999** [comment]
![image (1)](https://github.com/user-attachments/assets/78388414-6c7c-4ab2-8831-e9701792cad2)
In this image, the first file's field are jumbled randomly.

**Comment by josdejong** [comment]
So, how can I reproduce your issue?

**Comment by akshitasinghal1999** [comment]
try to load a big json file to the editor, and verify the order of the fields.

**Comment by josdejong** [comment]
I have opened a big json file and I do not see changes in the order of the fields. I can only look into this when I can reproduce the issue. Please share a JSON document where the reordering of fields happens, tell me which fields are reordered in the document. Also: what browser are you using?
