### ISSUE TITLE
Can not select text in left frame use chrome

### ISSUE THREAD

**Issue by shaoming01** [josdejong/jsoneditor#161]
Good tool,
but there is a BUG:
Can not select text in left frame use chrome

**Comment by josdejong** [comment]
I'm not sure what you mean, you can just drag your mouse over the text to select it, like in any input field.

**Comment by shaoming01** [comment]
1,In Chrome
2,witch row has indentation
can't drag to select value part or double click to select value part.
please open this link to look

**Comment by shaoming01** [comment]
http://www.jsoneditoronline.org/?id=f42f5d9e5b8d4a897fdb0f8ee65027fa

**Comment by josdejong** [comment]
hm, that's odd. Works just fine here. 

I don't really have an idea why this wouldn't work on your Chrome specifically.

**Comment by FindNemo** [comment]
I find same bug,  chrome ver is 41.0.2272.76 m

**Comment by josdejong** [comment]
Thanks for letting me know. 

Could you maybe do a little test for me? Can you try whether selecting text works ok in Ace editor itself (the used code editor). There is an editor on the home page which you can try immediately: http://ace.c9.io/

**Comment by shaoming01** [comment]
Thank you so.
I test already,it's fine in the ace editor.

**Comment by FindNemo** [comment]
You are welcome.
I didn't see content of ace.c9.io/, China's GFW blocks the iframe in this page.

**Comment by shaoming01** [comment]
哥们，我也是翻过来的。。。。。

**Comment by FindNemo** [comment]
握爪

**Comment by josdejong** [comment]
@FindNemo maybe this link works: http://ace.c9.io/build/kitchen-sink.html

@shaoming01 thanks for testing, that means that the problem is not caused by Ace.

If you guys can do me another favor would be great: check whether the problem occurs in the JSON Editor (the component), or only on the website. Can you open this example: [03_switch_mode.html](http://htmlpreview.github.io/?https://github.com/josdejong/jsoneditor/blob/master/examples/03_switch_mode.html), switch to mode "Code" and see whether the select problem occurs there too?

**Comment by FindNemo** [comment]
"http://ace.c9.io/build/kitchen-sink.html" works

**Comment by shaoming01** [comment]
It is OK in 03_switch_mode.html(JSON Editor)

**Comment by josdejong** [comment]
Ok thanks a lot, that gives me quite some direction on where this bug can originate.

**Comment by shaoming01** [comment]
Hi josdejong
I know the cause of the BUG, if you use Chrome is English, it's no this BUG, what I use is simplified Chinese browsers, so there's a BUG.
so this BUG caused by chrome language.
hope can help you!

**Comment by josdejong** [comment]
ah, that could be an explanation! Thanks. I have set the language in Chrome to Simplified Chinese, and when I try to select the value "youcannotselectme" in [your example](http://www.jsoneditoronline.org/?id=f42f5d9e5b8d4a897fdb0f8ee65027fa), it sort of works but refuses to select the last two characters of the word.

Looking that the examples of Ace editor, the ace editor script is always loaded with a `charset` attribute, like: 
```html
<script src="src/ace.js" type="text/javascript" charset="utf-8"></script>
```
See also http://stackoverflow.com/a/22549282. 

Hopefully tonight I can give this a try, see if that resolves this issue.

**Comment by josdejong** [comment]
@shaoming01 I've updated the website to specify the utf-8 charset for the javascript code. Can you give this a try? 

http://jsoneditoronline.org/

You may need to refresh the web application before the source code is updated, if you see version 3.4.1 at the bottom of the application you have the latest version.

**Comment by shaoming01** [comment]
I just tested, this BUG is still there.
I remember in the last few versions, this BUG is not there.
There is no online store features that version

**Comment by josdejong** [comment]
Thanks for testing. So apparently we have to look further.

Do you mean that you can't load/save documents online anymore in the latest version?

**Comment by shaoming01** [comment]
I'm sorry, but that's not what I mean.load/save document online is always OK.

**Comment by josdejong** [comment]
Glad to hear that. You scared me ;)

**Comment by JosDet** [comment]
Fuck！！Big Fat liar! Hurry to repay $500000!!!!!

**Comment by yixiuxiaoxin** [comment]
version 3.1.2  is ok

**Comment by josdejong** [comment]
Thanks @yixiuxiaoxin , so this issue may have been introduced with the upgrade to jsoneditor v4 (switched from using ace to using brace there).

**Comment by bluesiriuswolf** [comment]
I may find a solution.
In Simplified Chinese ，the default monospace font is Nsimsun
but it is Consolas font in English 

I try to modify the css 

.ace-jsoneditor.ace_editor {
    font-family: Consolas, monospace, courier new, courier, sans-serif;
    line-height: 1.3;
}

then the bug is disappear

**Comment by josdejong** [comment]
wow, that would be great. I will fix this asap. Thanks for figuring this
out.

**Comment by shaoming01** [comment]
Haha,Wating for update.

**Comment by josdejong** [comment]
I've applied the fix to JSONEditor and to the website. 

You may need to refresh http://jsoneditoronline.org with F5 before you are up to date. There are a few cache layers in both the browser and the cloud which may not be up to date. To be really sure you run the latest version you can open http://jsoneditoronline.org/app.min.js and verify whether the word "consolas" occurs twice in the file.

Fingers crossed ;)
