### ISSUE TITLE
Use in vue project

### ISSUE THREAD

**Issue by gu0315** [josdejong/jsoneditor#1617]
你好，findUniqueName 这个方法会一直添加copy 是vue双向绑定的问题吗

**Comment by josdejong** [comment]
Can you please translate your question in English?

**Comment by gu0315** [comment]
Hello, the findUniqueName method will always add copies. Is this a problem with Vue's two-way binding?

**Comment by gu0315** [comment]
<img width="624" alt="Snipaste_2024-09-25_18-04-45" src="https://github.com/user-attachments/assets/d4b36f43-e180-4a47-a881-32dca5164dba">

**Comment by gu0315** [comment]
<img width="707" alt="Snipaste_2024-09-25_18-09-36" src="https://github.com/user-attachments/assets/6f2520f1-097d-413c-9942-31f9c4a126e0">
<img width="1239" alt="Snipaste_2024-09-25_18-09-13" src="https://github.com/user-attachments/assets/a95820a5-510f-4312-bbb6-a42bdc83a598">
The findUniqueName method will add (copy) existingPropNames each time to contain the latest input value

**Comment by josdejong** [comment]
> the findUniqueName method will always add copies. 

The internal function `findUniqueName` never adds a `(copy)` suffix, except when an edited key would result in a duplicate key.

Do you have a case where there actually is a problem in vue?

**Comment by gu0315** [comment]
I did add the (copy) suffix when I debugged the log. I don't know what the problem is. I haven't encountered a similar problem in Vue.

**Comment by josdejong** [comment]
I'm a bit confused, is there an actual problem? If so, how can I reproduce it?

**Comment by gu0315** [comment]
If you have time, you can try it. The following is my code. I don't know if my usage is correct. Thank you.   https://github.com/gu0315/n-vue/tree/jsoneditor

**Comment by josdejong** [comment]
The url is broken

**Comment by gu0315** [comment]
Hello, sorry, the private repository is now public.

**Comment by josdejong** [comment]
Ok I can clone and try out the project now. 

So, how to reproduce your issue related to `findUniqueName`?

**Comment by gu0315** [comment]
Hello, run the project and insert a non-existent key to see if the (copy) suffix will be added. I checked the source code and found that the (copy) suffix is ​​added by findUniqueName.

**Comment by josdejong** [comment]
That is interesting.

I added a line `console.log('init', this.json, this.jsonEditor);` at the end of the method `initJsonEditor`, and that shows that both `this.json` and `this.jsonEditor` are wrapped in a Proxy. I guess that these proxies are messing things up?

**Comment by gu0315** [comment]
<img width="670" alt="Snipaste_2024-09-25_20-58-21" src="https://github.com/user-attachments/assets/5df477dd-7231-4a6d-acdf-3e2fc6ce1885">
It may be wrapped in Proxy. I also debugged this method and it was not filtered out. It was magical. Things are complicated.

**Comment by gu0315** [comment]
<img width="670" alt="Snipaste_2024-09-25_20-58-21" src="https://github.com/user-attachments/assets/e1c3e6de-7a94-4789-b228-8a7af0e1ddba">
It may be wrapped in Proxy. I also debugged this method and it was not filtered out. It was magical. Things are complicated.

**Comment by gu0315** [comment]
/**
   * Get all field names of an object
   * @param {Node} [excludeNode] Optional node to be excluded from the returned field names
   * @return {string[]}
   */
  getFieldNames (excludeNode) {
    if (this.type === 'object') {
      return this.childs
        .filter(child => child !== excludeNode)
        .map(child => child.field)
    }

    return []
  }

It may be wrapped in Proxy. I also debugged this method and it was not filtered out. It was magical. Things are complicated.

**Comment by josdejong** [comment]
> Things are complicated.

😂 😅

**Comment by josdejong** [comment]
I have hardly any experience with Vue, but it looks like you need to figure out a way to keep this `jsonEditor` instance in the Vue component _without_ Vue wrapping it in a proxy and doing reactive stuff with it. I couldn't easily find how to do that though.

**Comment by gu0315** [comment]
I don't have much experience. Haven't other developers encountered similar problems? I'm sorry. I'll do some research.

**Comment by gu0315** [comment]
Just like you said, vue doesn't hold jsonEditor, thank you, the problem is solved

 const jsonEditor = new JSONEditor(document.getElementById('jsonEditor'), {
                mode: 'tree',
                onChange: this.onChange,
                onChangeJSON: this.onChangeJSON,
                navigationBar: false,
                statusBar: false,
                history: false,
                onCreateMenu: function (menuItems) {
                    // 过滤掉不想显示的操作
                    return menuItems.filter(function(item) {
                        // 隐藏 '排序', '变换', '提取' 等功能
                        return item.text !== '排序' && item.text !== '变换' && item.text !== '提取';
                    });
                },
                // eslint-disable-next-line no-unused-vars
                onEvent: function (node, event) {

                }
            });
            jsonEditor.set(this.json);

**Comment by josdejong** [comment]
👍
