### ISSUE TITLE
Switch mode destroy the menu

### ISSUE THREAD

**Issue by reactdeve123** [josdejong/jsoneditor#1624]
Hi Team,
I have used jsoneditor in my ExtJS code. 

in code mode I wrote, 
{
"cc: "test"
}

Problem is when I switch the context menu from code to tree, it throws error and destroys the menu.
error in ModeSwtcher.js in 
 this.dom.box.focus();
Uncaught TypeError: Cannot read properties of null (reading 'box')

Init code :

init: function (container, json) {
		try {
			container = document.getElementById(container);

			if (container.hasChildNodes()) {
				container.removeChild(container.childNodes[0]);
			}

			var options = {
				mode: 'tree',
				modes: ['code', 'form', 'text', 'tree', 'view'], // allowed modes
				
				//onChange: function () {},
				indentation: 4,
				escapeUnicode: true
			};
			var editor = new JSONEditor(container, options, json);
			viewmanager.setJsonEditorObj(editor);

		} catch (l_objException) {}
	},

**Comment by josdejong** [comment]
Since the JSON document is invalid, it cannot be rendered in `tree` mode. You'll need to handle this exception by for example swithing to `code` mode when the JSON document is invalid.
