### ISSUE TITLE
isValidationErrorChanged does not compare the error messsage

### ISSUE THREAD

**Issue by Tethys0** [josdejong/jsoneditor#1627]
isValidationErrorChanged does not compare the messsage , if we have the same count of error message in the error array, though message is different , it won't trigger "onValidationError" 

https://github.com/josdejong/jsoneditor/blob/develop/src/js/util.js#L1233https://github.com/josdejong/jsoneditor/blob/develop/src/js/util.js#L1233

We use custom validation and rely on onValidationError hook to reset the form control error.

**Comment by josdejong** [comment]
Thanks for reporting! We should improve this `isValidationErrorChanged` function. 

Anyone able to help fix this? Help would be welcome.

**Comment by josdejong** [comment]
Fixed now in `v10.1.1`
