### ISSUE TITLE
Warnings on install

### ISSUE THREAD

**Issue by cmdelatorre** [josdejong/jsoneditor#163]
On install, there are a couple of warnings:

```
$ npm install
npm WARN deprecated gulp-clean@0.3.1: use gulp-rimraf instead
npm WARN optional dep failed, continuing fsevents@0.3.5
...
```

Everything works great for me, just wanted to report in case a dependencies update is needed.

**Comment by josdejong** [comment]
Thanks, I've updated the dependencies in the `develop` branch.
