### ISSUE TITLE
when the error happens in Onchange,How can I get the error message

### ISSUE THREAD

**Issue by zhaowenqian666** [josdejong/jsoneditor#1631]
when the user enter a invalid JSON，the OnChange()  method will not be called，How I get the wrong JSON? I have tried the OnError method.It doesn't work

**Comment by josdejong** [comment]
I'm not sure what you mean, can you elaborate?

In general, you can put a `try/catch` block around code that can throw an error.

**Comment by zhaowenqian666** [comment]
this is my code:
` <json-editor
                            :json="form.responseType"
                            :on-change="handleResponse"
                            :options="{ mode: 'text', modes: ['form', 'text'], search: false, }"
                            :style="'height: 300px; margin: -22px 0px 0 18px; width: 980px'"
                        >`

when the  user enter the invalid JSON, the exception happen in the OnChange method,like this: 
![Uploading Snipaste_2024-11-22_16-31-23.png…]()


but my `handleResponse()`  will not be called, so  even i put the `try/catch` in my `handleResponse()` method，the `try/cacth` will not be called

**Comment by josdejong** [comment]
The `onChange` callback of `jsoneditor` itself doesn't throw an error. I think this is related to how the wrapper libary that you're using has implemented the `on-change` callback. Are you using a Vue wrapper? Please ask there.

**Comment by josdejong** [comment]
Ok clear. Please ask there.
