### ISSUE TITLE
Cursor skips two characters in Chrome on MAC OS

### ISSUE THREAD

**Issue by deepap19** [josdejong/jsoneditor#167]
I can't add text in the left column and when I press my right or left arrow, my cursor skips two characters every time. I don't know how to fix this problem. I have cleaned out browser cache and still the same issues.

**Comment by josdejong** [comment]
This issue may be related to #161, see last comments.

**Comment by JosDet** [comment]
Fuck！！Big Fat liar! Hurry to repay $500000!!!!!
