### ISSUE TITLE
is there a way to get a json via a url?

### ISSUE THREAD

**Issue by wentin** [josdejong/jsoneditor#169]
Hey,

I am doing a quick prototype, and used jsononlineeditor to put together a fake restful api response. Wondering if it is possible to directly have json url that i can just link my angular app to? My teammate is constantly making changes to this dummy json, so it would be great for prototype that i can just make it live directly fron the editor.

**Comment by josdejong** [comment]
Yes, you can directly GET/PUT/DELETE to the document store used by JSON Editor. 

Get the document with meta data:
GET http://api.jsoneditoronline.org/v1/docs/:id
GET http://api.jsoneditoronline.org/v1/docs/:id?callback=myCallback
GET http://api.jsoneditoronline.org/v1/docs/:id?jsonp=myCallback

Get the document contents without meta data:
GET http://api.jsoneditoronline.org/v1/docs/:id/data
GET http://api.jsoneditoronline.org/v1/docs/:id/data?callback=myCallback
GET http://api.jsoneditoronline.org/v1/docs/:id/data?jsonp=myCallback

Create/update a document:
PUT http://api.jsoneditoronline.org/v1/docs/:id
With the document (including meta data) as request body

Delete a document:
DELETE http://api.jsoneditoronline.org/v1/docs/:id/:rev

**Comment by wentin** [comment]
wow, thanks much! i love your project, make my life easier!

**Comment by josdejong** [comment]
You're welcome :)
