### ISSUE TITLE
modify JSONEditor.prototype.getText to accept JSON.stringify parameters

### ISSUE THREAD

**Issue by jbaranski** [josdejong/jsoneditor#171]
I would like to call JSONEditor.getText() and have it in pretty json (useful when writing editor contents to a file). JSON.stringify accepts 3 parameters ([releveant docs] (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify)).

Maybe something like this?

    /**
     * Get stringified JSON contents from the editor
     * @returns {String} jsonText
     */
    JSONEditor.prototype.getText = function (replacer, space) {
      replacer = replacer || null;
      space = space || 0;
      return JSON.stringify(this.json, replacer, space);
    };

Thanks for the great app.

**Comment by jbaranski** [comment]
Actually I can just do this or something similar, which isn't horrible actually...
    JSON.stringify(JSONEditor.get(), null, 4);

**Comment by josdejong** [comment]
Thanks, good point. I think the combination of `JSON.stringify` and `JSONEditor.get` is indeed fine, no real need to expand the API here. 

I have added an [explanation in the docs](https://github.com/josdejong/jsoneditor/blob/master/docs/api.md#jsoneditorgettext).
