### ISSUE TITLE
Feature request: Selection Path  event callback

### ISSUE THREAD

**Issue by github-duran** [josdejong/jsoneditor#175]
Hey, great editor :) 
I am using it for JSONPath selection of a Java JSON-Database in combination with a 2nd editor which displays the results.

Sadly I had to hack the editor to give me the Path array of a name/value that I click in the JSON tree. I then convert this array to a JSONPath string and put that in an editbox. Once i submit the edit box the JSONPath string (selection) is sent to the server (java), which does the JSONPath query and sends the result back to the 2nd edit window.

I'd like the editor to have an event callback function that gives the Path array of the name/value selection.

JSONPath:
https://github.com/jayway/JsonPath
There is also a JS version by goessner.
An online JsonPath Evaluator:
http://jsonpath.herokuapp.com

I think this feature request may have some overlap with the previous issue. Maybe it can be split; I'd like to have just the selection path, not a full JSONPath query & result, because I'm doing the query in java and that's slightly different to the JS version.

Thanks :)

**Comment by github-duran** [comment]
To be clear, I'd like to have just the selection path, not a full JSONPath query & result, because I'm doing the query in java and that's slightly different to the JS version.

**Comment by josdejong** [comment]
Not sure why I never replied to this issue, probably overlooked it somehow. Feel free to reopen if still an issue.
