### ISSUE TITLE
Problem saving file. Receiving "Aw, snap!" error 

### ISSUE THREAD

**Issue by miketrvn** [josdejong/jsoneditor#177]
Not sure what the problem is but I tried saving my json file but it keeps on giving me a -

The “Aw, Snap!" error occurs when a webpage doesn't display correctly. In most cases, you can simply reload the page to dismiss the error. If you keep getting the error, try the suggestions below.

It seems to happen as soon as I try to add more content to the current file. Did I hit the limit on file size? The file is 1.25MB, not sure if that matters, but I need help with this as soon as possible!

Thanks

**Comment by miketrvn** [comment]
Any ideas??

**Comment by josdejong** [comment]
Thanks for reporting this problem. I can reproduce this issue when loading a large file, it's indeed related to the file being too large. I will see how we can fix this. At least you should get a clear error message instead of a crash...

**Comment by miketrvn** [comment]
Appreciate it. Please let me know if you guys do end up extending the file size limit. I love working on your program - it's the best!
