### ISSUE TITLE
CTRL + L search line; breaks CTRL + L functionality in browser for edit url

### ISSUE THREAD

**Issue by DanielNoga** [josdejong/jsoneditor#178]

**Comment by josdejong** [comment]
Hm, that's a feature of Ace editor. I will see if I can disable it, I don't think line search is very relevant here.

**Comment by Esam-Bustaty** [comment]
CTRL + T is not working in firefox as well, it's working fine in chrome, though.

**Comment by josdejong** [comment]
What is `Ctrl+T` supposed to do?

**Comment by Esam-Bustaty** [comment]
opens a new tab, but in the jsononlineeditor.com's tab it transfers the character before the caret forward.

**Comment by josdejong** [comment]
Ah, thanks. I suppose that's some shortcut key of Ace editor. I will see whether I can disable it.

**Comment by josdejong** [comment]
I've fixed this in the `develop` branch
