### ISSUE TITLE
increase character limit

### ISSUE THREAD

**Issue by Joisar** [josdejong/jsoneditor#182]
it is not working when json string contains more than 10000 characters

**Comment by josdejong** [comment]
Thanks. What doesn't work exactly? 

I just tested with an object containing a string with a length of 20001 characters, which works fine.

**Comment by Joisar** [comment]
hi josdejong,
thanks for reply. I have just tested now and it is working now. Earlier it was giving error regarding format. I had tested multiple times before posting issue but anyways, may be I might be making some silly mistake.

**Comment by josdejong** [comment]
Ok thanks for the feedback, great it's solved :)
