### ISSUE TITLE
Option to choose <br> instead of \n

### ISSUE THREAD

**Issue by tmikaeld** [josdejong/jsoneditor#185]
Our system outputs the values as HTML, so an option to convert newline to <br> would be great.

EDIT: I see it's related to contentEditable, maybe an option to use textarea instead?

**Comment by josdejong** [comment]
See related discussions here: #5, #137, #4. 

From #137:

> The editor does indeed not unescape escape characters, it displays the "raw", escaped contents as is. For example a tab `\t`, return `\n`, or unicode characters like `\uXXXX` are just displayed as is, without turning it into some HTML character like (`<br>`) or the appropriate unicode character.

It's not so trivial to interpret the different sorts of enters (`<br>`) from a contentEditable, different browsers do this differently an you can get all sorts of ugly nesting of html elements. Textarea would be simple in this regard, but gives an other issue: it does not automatically size to fit its contents, solutions for that are not trivial either and performance.

What we could do is implement two callbacks where you could convert HTML to a JSON string and vice versa yourself the way you like.

**Comment by tmikaeld** [comment]
Two callbacks would be great.

I added a listener myself try and replace \n to <br> but the contentEditable only renders it, it does not print the <br> tag (of course). 

And you are right about enter being interpreted differently, but it can be overridden with event.preventDefault(); and then add custom tag on keypress, but this would still only work properly on textareas (because of <br> being rendered). 

I'll try and add a resizable textarea myself and see what the performance would be like, there are a few hacks out there that might do the trick... I'll report back.

**Comment by tmikaeld** [comment]
Did a few tests - changing the contenteditable to textarea have no performance issues, but resizing it does need calculation, so that ruins json files larger than 700kb and above. 

But.. leaving the textarea in a standard size and loading a wysiwyg on-focus and then destroy it on blur does not have performance issues.

Conclusion, please add an option to select the field type of contenteditable or textarea - then we can add the wysiwyg ourselves if we need it.

**Comment by josdejong** [comment]
Will close this issue due to inactivity. Feel free to reopen if needed.
