### ISSUE TITLE
TreeMode-Node.dom <-> Data Mapping ? 

### ISSUE THREAD

**Issue by mc007** [josdejong/jsoneditor#189]
Hi,
I know I could walk the root node down to build a map between Dom and data, or use the options.editable callback (won't give a full-map due to lazy rendering) but it doesn't really feel right. Is there a simpler/ more direct way? 

What I am trying:
- update/link ACE selection when Node is clicked/focused
- update tree from ACE changes without brutal editor.set() to preserve the TreeMode's state (selection, expanded nodes,...)
- select Node by path (similar as from within searchbox) 

any thoughts welcome.

**Comment by josdejong** [comment]
These sort of things are still on the wishlist. Related topics: #136, #44

**Comment by mc007** [comment]
hey mate, just saw you did some stuff on expressions, did you check out '(filtrex)[https://github.com/joewalnes/filtrex]' (bison based, still looking at custom & simple grammars...)? I use it for IDE user expressions which comes in a little heavy but looks fine for math.js,g

**Comment by josdejong** [comment]
ehhh, a bit off topic here... I hadn't seen filtrex before, thanks for the link.

**Comment by mc007** [comment]
ok,

to build a map between Node's dom and data, simplest was to extend Node.getDom for this.editor._emit('renderNode',this); 

whereby editor._emit is a variant of ace/lib/event_emitter (provides emit/on).

then you just need to write" editor.on('renderNode',function(node){
   var nodePath = node.path().join('.');
   this._visitedNodes[nodePath] = node;
});

I use this for applying [render-templates](https://github.com/mc007/xide-js/blob/master/json/JSONEditor.js#L400). So instead of rendering  "0 {10}" for elements in an array, 
you can change it to "0  - Inner Node's title field". That makes the editor a little more attractive for a custom context, or introduce something like 'schemas'  :-)

ok, thanks for the heads up!

**Comment by josdejong** [comment]
Thanks, interesting idea.

**Comment by mc007** [comment]
just to correct links, the final destination of my 'fork' is now [here](https://github.com/mc007/xamiro/tree/master/xapp/commander/plugins/JSONEditor/client/xfile). Its part of a file-manager. 

i think i will replace as next the renderer with my preferred [grid](dgrid.io), comes with all the neat stuff you would love to have in the workflow. if you need access to the 'utils' or my ace - version (rocks), let me know (its private for a while). biggest missing point is selection (multi) and custom rendering/actions, also auto-completion (ACE) for editing fields.
well, don't bother.

**Comment by josdejong** [comment]
Thanks for sharing. Can you please leave the license information of your assets intact?

**Comment by mc007** [comment]
sure, but really i doubt there will be anything left of your code :-)
