### ISSUE TITLE
minified jsoneditor.min.js seems to be adding unicode instead of spaces

### ISSUE THREAD

**Issue by gravitypersists** [josdejong/jsoneditor#190]
Fixed when using non-minified jsoneditor.js

![screen shot 2015-05-12 at 1 08 51 pm](https://cloud.githubusercontent.com/assets/231863/7597402/250bf318-f8a8-11e4-9410-5766d4ba931d.png)

4.1.3 installed via npm

**Comment by josdejong** [comment]
Thanks for the report. How can I repeat this issue? I replaced `jsoneditor.js` with `jsoneditor.min.js` in `examples/03_switch_mode.html`, but this problem does not pop up then.

**Comment by gravitypersists** [comment]
```
mkdir test && cd test
npm init
npm install jsoneditor
touch index.html
```

then in index.html:
```
<!DOCTYPE HTML>
<html>
<head>
    <link href="node_modules/jsoneditor/dist/jsoneditor.min.css" rel="stylesheet" type="text/css">
    <script src="node_modules/jsoneditor/dist/jsoneditor.min.js"></script> 
</head>
<body>
    <div id="jsoneditor" style="width: 400px; height: 400px;"></div>
 
    <script>
        // create the editor 
        var container = document.getElementById("jsoneditor");
        var editor = new JSONEditor(container);
 
        // set json 
        var json = {
            "Array": [1, 2, 3],
            "Boolean": true,
            "Null": null,
            "Number": 123,
            "Object": {"a": "b", "c": "d"},
            "String": "Hello World"
        };
        editor.setMode('code');
        editor.set(json);
 
        // get json 
        var json = editor.get();
    </script> 
</body>
</html>
```

Which is the sample code perhaps the `.setMode('code')` is what is needed for verification?

**Comment by josdejong** [comment]
I trapped in that pitfall a couple of times too. It's a pity that it's needed to add this header. It's not entirely clear why the Ace editor sometimes works ok without this header.

I've added the header in the examples in the docs now.
