### ISSUE TITLE
using editor.get() with invalid json breaks

### ISSUE THREAD

**Issue by gravitypersists** [josdejong/jsoneditor#191]
So if I have a change callback that looks like:

```
var options = {
	change: function() { editor.get(); },
}
var editor = new JSONEditor(document.querySelector("#jsoneditor"), options)
```

Seems to be that there's an error being thrown halting everything when JSON isn't valid, which you might expect it to sometimes be when you're inputing it via this tool.

Using `editor.getText()` works, until you try and do the same thing and JSON.parse it, but my main point behind this issue is that execution shouldn't be halted on errors. Perhaps return null when errors have occurred parsing the JSON?

**Comment by josdejong** [comment]
If you are in mode `code` or `text`, and you want to retrieve the contents of the editor, there are two ways: `editor.getText()` always works, as it just returns the text contents. `editor.get()` can fail if the editor contains invalid JSON. If that's the case, there is no way to represent that as a JSON Object and return it, the only option is to throw an error here.

So depending on your use case you can use `editor.getText()`, or use `editor.get()` surrounded by a try/catch block:
```js
var options = {
  change: function() { 
    try { 
      var obj = editor.get(); 
    } 
    catch (err) {
      // ... do something?
      console.log(err);
    }
  }
}
var editor = new JSONEditor(document.querySelector("#jsoneditor"), options)
```

**Comment by gravitypersists** [comment]
Tried the try/catch, it's resetting the cursor to the beginning of the text making typing impossible.

**Comment by josdejong** [comment]
I've fixed a bug causing this issue with `editor.get()`. Should be working fine in v4.2.0
