### ISSUE TITLE
Suggestion: boolean values in check button, instead of true-false

### ISSUE THREAD

**Issue by MarioMey** [josdejong/jsoneditor#193]
I know that by writting true/false we can change the type of the value on-the-fly... but, if it is a boolean, it would be great to change it by clicking only one time. So much faster.

Auto values would always have a check and the "edit value" next to check. So, if the value is a boolean, the check button will be activated (true or false). If I change the value to string or number, the check button will be deactivated. To activate again, I would need to write true/false. Like the attached image.

![suggest](https://cloud.githubusercontent.com/assets/4954109/7756950/0b0c4dd0-ffd5-11e4-908f-baa738075130.png)

**Comment by josdejong** [comment]
Thanks, interesting idea. This would be a nice option when we have support for JSON schema (see #56), so you can define the type of a value to be a boolean.

**Comment by josdejong** [comment]
Hi Mario, I've implemented your idea, it's now available in v5.1.0

**Comment by MarioMey** [comment]
:) :) :)
I'll check it later!
