### ISSUE TITLE
Load and Save Shortcuts

### ISSUE THREAD

**Issue by MarioMey** [josdejong/jsoneditor#194]
As I edit JSON every time, I wanted to have a shortcut to load and save files. I discovered accesskey="s" to use as [Alt]-[Shift]-S to save the file:

`<p>Load a JSON document: <input type="file" id="loadDocument" value="Load" accesskey="s"/></p>`

But, when I try accesskey="o" to open a JSON, instead of opening the open file window, the "Examinar" button is highlighted... but I need to press Space or Enter to open the window. I don't like that...

I know that this is not a jsoneditor issue, but a html one. Can somebody help me with this?

Maybe it could be included in example files...

**Comment by josdejong** [comment]
I've added a quick key `Ctrl+S` to save a document online. Browsers don't allow to override the `Ctrl+O` key. It's a good idea to enable other quickkeys for this then. DO you have any preferences here?

**Comment by MarioMey** [comment]
Maybe... "L"? As the word "load" (file).
I changed accesskey="o" to "l" and it works in Firefox. Alt-Shift-L open "Open File" dialog.

**Comment by josdejong** [comment]
We can try that. Ctrl+L is used to set focus to the browser addressbar but maybe we can override it.

**Comment by josdejong** [comment]
Ace editor (mode "code") was also using Ctrl+L for gotoline. I've just disabled this as some users reported an issue as this is getting in the way of normal browsing behavior. So it maybe better not to override Ctrl+L for loading either. I will close the issue for now until the missing quick key for loading is requested by some more users.
