### ISSUE TITLE
double and single quotes problem ...

### ISSUE THREAD

**Issue by themacboy** [josdejong/jsoneditor#195]
When I paste a text with ' inside the value or a key it is changed to " and then broke, Example:

```json
{"deck": "Dreamhaunter-6,Cruise Launcher-6,Octane's Bulwark-6,Cadmus the Dragon-6,High Constable-6 #2,Obsidian-6"}
```

Octane's Bulwark-6 -> ,Octane"s Bulwark-6

**Comment by josdejong** [comment]
When I paste your JSON example in http://jsoneditoronline.org/ it just works fine. 

Are you using the latest version of JSONEditor? There was a related issue in the past.
