### ISSUE TITLE
<cr><nl> problem ...

### ISSUE THREAD

**Issue by themacboy** [josdejong/jsoneditor#196]
Im not sure if that is a problem with your tool or if is a standards limitation in the Json object creation (im not an expert, sorry).

When I paste a object with <cr><nl> inside a value text (at the begining or ending) it brokes. Example:

```
{"result": {
"Tabitha": "
Optimized Deck: (100% win, 0% stall) 100: Tabitha, Dreamhaunter, Cruise Launcher, Octane's Bulwark, Cadmus the Dragon, High Constable #2, Obsidian = 7 units
"
}
}
```

**Comment by themacboy** [comment]
note:

key:value

"Tabhita":"<cr><nl>
Optimized Deck: (100% win, 0% stall) 100: Tabitha, Dreamhaunter, Cruise Launcher, Octane's Bulwark, Cadmus the Dragon, High Constable #2, Obsidian = 7 units <cr><nl>
"

**Comment by josdejong** [comment]
This is indeed a not allowed in JSON, return characters should be escaped. http://json.org/ describes in detail what's allowed.

**Comment by themacboy** [comment]
Great to know !!! A lot of thanks really thanks.

**Comment by josdejong** [comment]
you're welcome
