### ISSUE TITLE
Duplicate object keys in tree mode

### ISSUE THREAD

**Issue by mmacfadden** [josdejong/jsoneditor#197]
When editing field names, or dragging and dropping, it is possible to create an "invalid" tree where two nodes in the same object have the same field.  When getting the JSON from the editor, the duplicate field will be filtered out (which is somewhat correct).

Looking at the demo site:  https://www.jsoneditoronline.org/

If you add a duplicate key in text mode, and then try to load it into the tree view two things will happen.  1) The Ace editor will show a duplicate field error, and 2) the duplicate key is ignored and not loaded into the tree view.

So if you put a duplicate field in either the text mode or the tree mode the data will not be savable, loabable, or transferable to another mode.  I would like to be able to disallow duplicate keys.  I am not sure what the right way to do this would be.  There are three main questions:

1) Should it be always the case where duplicates are not allowed, or should be be configurable?
2) How to handle renaming an object field (it seems as though this would be hard since the field is changed as you type).  Would we revert back to the previous field?  Would we not let the field loose editing focus?  Would we replace the existing field?  Would you provide a callback or an option to let the user decided what to do?
3) How to handle the drag and drop.  We would either need to disallow the drop (show an x cursor or something)?  Would we revert the node back to where it came from?  Would we replace the existing field with the same name?  Should this be also configurable?

I am up for some discussion.  If we come up with a good design, I think I would be willing to implement it.

**Comment by josdejong** [comment]
Yes, indeed. This is still somewhere on the todo list. I was planning on highlighting duplicate keys with a read background or something like that, so you can resolve it the way you like.
