### ISSUE TITLE
Is a simple way to beautify the file, without entering in "code" mode?

### ISSUE THREAD

**Issue by MarioMey** [josdejong/jsoneditor#205]
I'm seeing that editor.getText() is used to export the file. But, if I save the file directly from Tree mode, the json is in one line.

Is there any way to beautify the output? Something like beautify(editor.getText())...?

I use jsoneditor to edit my json files... but, sometimes, I have to modify replace only a word, for example, and it is faster to do it with another app.

**Comment by josdejong** [comment]
Yes you can use `editor.get()` to get the JSON object, then you can use [`JSON.stringify`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify) to format it with or without indentation. 

See also the https://github.com/josdejong/jsoneditor/blob/master/docs/api.md#json-parsing-and-stringification

**Comment by MarioMey** [comment]
I checked JSON.stringify link and I wrote:

    // Save a JSON document
    document.getElementById('saveDocument').onclick = function () {
	
    var texto = editor.get();
    var beauty = JSON.stringify(texto, null, '\t');
    var blob = new Blob([beauty], {type: 'application/json;charset=utf-8'});
    saveAs(blob, 'custom.json');

Then, I checked the second link, and it says something similar.

Thanks!

**Comment by josdejong** [comment]
You're welcome
