### ISSUE TITLE
Floating point numbers that have only "0" in the decimal part reformat to integers

### ISSUE THREAD

**Issue by FerranMG** [josdejong/jsoneditor#206]
I have a json file with a field "weight": 1.0
I need the weight to be a float, because my parser distinguishes between int and float.
However, using the formatter, the value of this field is changed to simply 1, which renders my json useless.

**Comment by josdejong** [comment]
[JSON](http://json.org/) only knows `number`, it does not distinguish between floats and integers.

If you need to store this type information, you can do two things:
- Store the value as a string like 

  ```json
  {"weight": "1.0"}
  ```

- Store your numbers as an object with type information, like 

  ```json
  {"weight": {"type": "float", "value": 1}}
  ```
