### ISSUE TITLE
Changing Keyboard Language Bug

### ISSUE THREAD

**Issue by gxferreira** [josdejong/jsoneditor#207]
First of all, thank you very much for the tool. 
I have to edit JSON frequently and JSON Editor helps a lot with that, its an amazing tool.

I'm using Windows and I have a few keyboards input methods like Portuguese and English. 
When I'm editing a JSON file in the JSON Editor and I press the shortcut to switch the language (Windows key + Space bar key), I can't use the arrows and navigation keys (like Home and End).

It is just a little bug that I notice.

**Comment by josdejong** [comment]
Thanks for your report. I will see if I can reproduce this issue here.

**Comment by josdejong** [comment]
Is this still an issue?
