### ISSUE TITLE
npm error

### ISSUE THREAD

**Issue by kentvv** [josdejong/jsoneditor#209]
error is as follows
Error: No compatible version found: jsonlint@'josdejong/jsonlint#85a19d7'

Looking at package.json changes i see jsonlint went from dev dependancy to dependancy, and then to this lockfile.

Any reason not to remove the lock file linking back to jsonhint?

**Comment by josdejong** [comment]
The reason that we can't use the regular jsonlint package from npm is that there is a bug related to using it via browserify: https://github.com/zaach/jsonlint/issues/57. The official package seems not to be maintained at all :(. To solve this I forked the library, created a fix for it, and link to that fork from jsoneditor.

When does this error occur?

**Comment by balessan** [comment]
On my side this error occur when executing the npm installation

     npm install jsoneditor

Fails on retrieving the jsonlint package, so installation fails. Really strange as I did succeed to install it on another computer.

**Comment by balessan** [comment]
I fixed the issue on my side by forking your project, cloning it in my project instead of downloading using NPM and modifying the package.json to use the 1.0.0 version of jsonlint.

It is not ideal as it is part of the installation process of my current project.

Any ideas/clues how to fix that ?

**Comment by josdejong** [comment]
Maybe you have a different version of npm or something?

I've already removed the dependency on my forked version of `jsonlint` in the develop branch. I expect to have time to fix some more minor bugs and do a release the week after next week.

**Comment by josdejong** [comment]
The just released v5.0.0 has no longer a dependency on this raw git url of jsonlint, I suppose this issue is resolved now.
