### ISSUE TITLE
Accessing ace edit session removes all context menus

### ISSUE THREAD

**Issue by danlamanna** [josdejong/jsoneditor#210]
In trying to modify the contents of the 'Code' editor programatically using the Ace Editor API, all context menus break.

Running this code in the console of the [03_switch_mode.html example](https://github.com/josdejong/jsoneditor/blob/master/examples/03_switch_mode.html)
```var editor = ace.edit('jsoneditor')```

will reproduce the issue. Is this expected? Are we only able to use the ```.set``` method of ```JSONEditor``` to change the value?

**Comment by josdejong** [comment]
According to the docs of Ace (http://ace.c9.io/#nav=api&api=ace) the method `ace.edit('jsoneditor')` will create a new Ace editor in the DOM element `jsoneditor`. So you're simply replacing the JSON Editor with a plain new Ace editor...

Maybe what you mean to do is get a pointer to the Ace editor instantiated by JSON Editor? you can access it via `editor.editor` in that example (only when in mode `code`). See [this part of the code](https://github.com/josdejong/jsoneditor/blob/master/src/js/textmode.js#L131-L139).

**Comment by danlamanna** [comment]
You're correct - thanks!
