### ISSUE TITLE
Editor height in code mode compared to tree mode

### ISSUE THREAD

**Issue by machow** [josdejong/jsoneditor#211]
In tree mode, If height is not defined for the containing element of jsoneditor, then it will scale to fit the contents of the editor. However, in code mode, the contents won't be visible. Is it possible to set it so that code mode will scale to fit the contents of the editor, like tree mode does?

It looks like this was mentioned in issue #124.

**Comment by josdejong** [comment]
You can set the width and height of the container of the editor to 100%, does that solve the issue?

**Comment by machow** [comment]
Thanks for the quick response!

I checked on [03_switch_mode.html](http://htmlpreview.github.io/?https://github.com/josdejong/jsoneditor/blob/master/examples/03_switch_mode.html), and it looks like that works for the tree editor, but the code editor collapses so its contents aren't visible.

**Comment by josdejong** [comment]
I checked whether this is possible with ace editor, and you can do so using the option maxLines, you can access the ace editor (for code view) via `editor.editor` (only available when in mode `code`): 

```js
editor.editor.setOptions({maxLines: 100});
```

For the regular view where the JSON Editor has a limited height (in pixels or %) this looks less pretty as the left column with line numbers does not go to the bottom of the editor, so it's probably not a good idea to do this by default.

**Comment by machow** [comment]
Ah, okay--this is great! I saw that there should be an editor object available, but must have been in tree mode when I checked.

If you set
```editor.editor.setOptions({maxLines: Infinity});```

then it shows all of the contents, as in tree mode. A short blurb in the docs (maybe where code mode is explained?) might be helpful. I'm happy to add it if it seems useful.

**Comment by josdejong** [comment]
Yes, you can set Infinity though they warn against that:

http://stackoverflow.com/questions/11584061/automatically-adjust-height-to-contents-in-ace-cloud9-editor

A note about this in the docs will be useful, if you can provide something for that would be nice.

**Comment by machow** [comment]
Sorry, just getting back to this--and wanted to check one more thing before adding some documentation. It looks like the editor is recreated every time code mode is toggled, so editor options are reset when toggling back to tree mode. So if you were to do..

```editor.editor.setOptions({maxLines: 100});```

and then toggle to tree mode, then back to code, the options would need to be set again. What do you think of storing the previous editor rather than recreating it? I'm not too familiar with ace, so you probably have a much better sense for the issue. In any event, I'll plan to add some small notes to the docs.

[here is a jsfiddle for demonstrating the issue](http://jsfiddle.net/ps5tdhtv/)

**Comment by josdejong** [comment]
yes we could keep Ace in memory once loaded. 

An other solution could be to introduce an event like `modeChange` which is fired after the user switched mode. When the event occurs, you can check whether `mode=='code'` and if so, apply your custom settings for Ace.

**Comment by josdejong** [comment]
I've implemented a new option `onModeChange`, it's in the develop branch.

**Comment by josdejong** [comment]
This is now available in v5.0.0

**Comment by Amiryy** [comment]
Hey @josdejong , I am trying to fit my ace editor in "code" to the content but Can't access `JsonEditor.editor` or `JsonEditor.aceEditor` to `setOptions` as you suggested.
Is there a different way to achieve that nowadays?
Thank you.

**Comment by josdejong** [comment]
The internal `.editor` was renamed to `.aceEditor`. You can do something like:

```js
editor.aceEditor.setOptions({
  maxLines: 10000
})
```

Here a full demo: https://jsbin.com/gofabet/edit?html,output :rocket:
