### ISSUE TITLE
[Question] Validation JSON and showing error in a specific line

### ISSUE THREAD

**Issue by samuelalexanderg** [josdejong/jsoneditor#212]
I am new to ace editor and JSON editor.
Sorry if the question is not valid
 
How can I validate whether the user edited JSON content is a valid JSON Content?
How can I validate a JSON against a schema?

After validating how can we show the "error" or "x" for the specific line which has issues.

**Comment by josdejong** [comment]
The editor doesn't have support for JSON schema, so it can't. This feature is high on the wish list though (you can search the issues section of this project for related discussions).

**Comment by samuelalexanderg** [comment]
Hi Jos,
Thanks for reply. Is there chance that this feature will get added soon?

**Comment by josdejong** [comment]
I cannot really give an estimate but it will not be on very short term. It will require quite some work (not just a Friday afternoon), and it has to be done in spare time. I hope to free up some for this this summer or fall.

**Comment by samuelalexanderg** [comment]
Thanks a lot for effort and time

**Comment by samuelalexanderg** [comment]
Thanks a lot for effort and time

**Comment by josdejong** [comment]
You're welcome
