### ISSUE TITLE
Libre/Openoffice cell copied as table (bug, contenteditable)

### ISSUE THREAD

**Issue by bryc** [josdejong/jsoneditor#213]
When entering data from a spreadsheet, copying the cell and pasting is mishandled as entering HTML into the visual editor.
It shows the value as black (markup shows `<table>`), and displays a parse error when updating JSON:

```
Error: Parse error on line 1:
"\n \n  \n      5456456\n
^
Expecting 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '[', got 'undefined'
```

I am sure this has some security considerations too.

**Comment by josdejong** [comment]
Thanks for reporting this, I can repeat this issue.

**Comment by josdejong** [comment]
Will close this issue since it's outdated. Feel free to open a new issue for similar cases.
