### ISSUE TITLE
Usability features...

### ISSUE THREAD

**Issue by jshohel** [josdejong/jsoneditor#214]
I am wondering if below given things are possible -

1) When in "code" mode, is it possible to take off the text "powered by ace" from the title bar?
2) Is it possible to have the search option enabled when in "code" mode?
3) Is it possible to have "copy to clipboard" functionality?

Thanks

**Comment by josdejong** [comment]
1. Yes, this text has a className `poweredBy`, so you can hide it with some css `.poweredBy {display: none}`
2. When you press Ctrl+F a search window will open in the top right.
3. What would you like to copy and how? I mean, you can select text and copy/paste it using shortcut keys or the context menu like with any regular input field.
