### ISSUE TITLE
String values in Structured Editor should be quoted.

### ISSUE THREAD

**Issue by hansgru** [josdejong/jsoneditor#215]
Please render the String Values in the Structured Editor in quotes.
Colors are nice, but for this special type, quotes are what all users are used to.

Thank you.

**Comment by josdejong** [comment]
Thanks for your suggestion. The idea of the editor though is that you *don't* have to bother again about the quotes, the commas and the curly braces. If you do want to enter this yourself you can set the editor in mode "code" or "text".

**Comment by hansgru** [comment]
>  The idea of the editor though is that you don't have to bother again about the quotes, the commas and the curly braces. 

Not in the structured editor in edit mode, but in the renderer only - when the value is rendered.
It's a visible hint that makes it easier to distinct types, since all users are used to this convention.

**Comment by josdejong** [comment]
That depends of course on what sort of audience your user base consists of :) 

I'm sorry but I'm not planning on displaying quotes around strings. Note though that the editor is open source, so you could clone the project and adjust this behavior as desired if you want.
