### ISSUE TITLE
Support for EDN format?

### ISSUE THREAD

**Issue by hansgru** [josdejong/jsoneditor#216]
Hi,

Any chance supporting the EDN format (especially for the structured editor)?
https://github.com/edn-format/edn

There are also conversion libraries between JS and EDN:
https://github.com/shaunxcode/jsedn

Thank you.

**Comment by josdejong** [comment]
I understand your idea, for me this is out of the scope of the JSON editor.

**Comment by hansgru** [comment]
>  for me this is out of the scope of the JSON editor.

That's a pity since more than 90% of the code would be the same for such an editor.

Even more, this would basically true for any "structured" editor that acts upon a tree structure: right now there's no general configurable "web component" available for such a thing.

**Comment by josdejong** [comment]
Maybe some day we could rethink this decision and broaden the scope of the tool, but for now I want to keep the editor focused on JSON.

**Comment by aadrian** [comment]
+1 for EDN, or even better, a configurable Structured editor.

**Comment by aadrian** [comment]
@josdejong any chance considering EDN (or generic tree structure editor) support again? 
Even quite a few tools would need this (like most web based editors :) ), besides user applications.

**Comment by josdejong** [comment]
I haven't changed my mind, still want to focus purely on JSON. I'm working on a complete rewrite of the editor (including JSON Patch for example).
