### ISSUE TITLE
Inline display of array values for small arrays like FireFox?

### ISSUE THREAD

**Issue by hansgru** [josdejong/jsoneditor#217]
Firefox displays very nicely a compact view of data, but also allows to expand it completely like in the screenshot below:
![json_firefox](https://cloud.githubusercontent.com/assets/5159511/8935669/337d33de-354e-11e5-8912-df811307e65d.png)

It would be nice if JSON Editor would render this "inline/compact" mode too.

Thank you.

**Comment by josdejong** [comment]
Thanks for your suggestion. Actually, in a very very old version of JSON editor this was how the layout was done. However, for larger documents where you have quite some leafs expanded, you get the situation where the distance between the field name and the field value is very large so it becomes hard to see which value corresponds to which field.
