### ISSUE TITLE
Support C-style Comments

### ISSUE THREAD

**Issue by fporcaro** [josdejong/jsoneditor#219]
This isn't a bug, but a feature request.  This is an amazing tool for documenting JSON structures either as artifacts of projects or to communicate api expectations for collaboration.  I often need to add comments to explain possible values or other notes.  When I paste these values into the text side of the editor, they report as bad data.  For example: 
<img width="634" alt="outgoing_order_json_-_magento_development_-_confluence" src="https://cloud.githubusercontent.com/assets/2136862/9256819/82517c52-41b7-11e5-82ff-e3e4519d8547.png">
It would be helpful to keep these notes between iterations.

**Comment by josdejong** [comment]
Thanks for your suggestion. Unfortunately, JSON doesn't have support for comments. 

http://stackoverflow.com/questions/244777/can-i-comment-a-json-file

**Comment by fporcaro** [comment]
Totally appreciate the quick respone!  Thanks.

**Comment by josdejong** [comment]
You're welcome. Half the world wishes JSON has support for comments but unfortunately it doesn't...
