### ISSUE TITLE
Please add a typescript definition file.

### ISSUE THREAD

**Issue by niemyjski** [josdejong/jsoneditor#22]
http://www.typescriptlang.org/

**Comment by josdejong** [comment]
This is a very old issue, I will close it now. If anyone is interested in creating a typescript definition file for JSONEditor please let me know.

**Comment by josdejong** [comment]
Turns out someone actually made a TypeScript definition: 

https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/jsoneditoronline

Only, it's very outdated and not working with the latest version of JSONEditor. Anyone interested in getting it up to date?
