### ISSUE TITLE
.css min file minifying issue

### ISSUE THREAD

**Issue by boysmovie** [josdejong/jsoneditor#220]
Raw Source:

.jsoneditor .menu button {
  width: 26px;
  height: 26px;
  margin: 2px;
  padding: 0;
  border-radius: 2px;
  border: 1px solid #aec0f8;
  background: #e3eaf6 url("img/jsoneditor-icons.png");
  color: #4D4D4D;
  opacity: 0.8;
  font-family: arial, sans-serif;
  font-size: 10pt;
  float: left;
}

Min file converts the background property to 

background:url(img/jsoneditor-icons.png)#e3eaf6

This causes the images not to load. Please fix the min file provided in the distribution.

**Comment by josdejong** [comment]
The minified CSS is valid CSS and seems to work just fine. Maybe your issue has a different cause? Can you explain more about how your case?

**Comment by josdejong** [comment]
is this still an issue?
