### ISSUE TITLE
Size limit issue?

### ISSUE THREAD

**Issue by smoran** [josdejong/jsoneditor#221]
When i create a JSON, Everything works great until i reach a size of around 65-80K.
Then the ace code looks good but the tree view shows only part of the JSON.
When saving, The .get() function retrieves the partial JSON and not the full data :(
Please advise.
Regards,
Segev.
Great Piece of code BTW... Thank you :)

**Comment by josdejong** [comment]
Thanks for letting me know. 65-80K sounds like it shouldn't be a problem. Is it possible to share one of these files giving trouble so I can do some testing?

**Comment by smoran** [comment]
sure man.
i'll send you a file

**Comment by josdejong** [comment]
Thanks beforehand!

**Comment by josdejong** [comment]
I think I never received any file. Is this still an issue or shall I close it @smoran ?
