### ISSUE TITLE
Excessive change events on setMode('code')

### ISSUE THREAD

**Issue by jdmarshall** [josdejong/jsoneditor#222]
If you call `setMode()` or the user clicks on the mode switcher dropdown and changes to 'code', a cascade of calls to the change listener are fired.  Many tools have this sort of issue and the common workaround is to compare the new value to the old value and not report changes up the chain.

Except as it turns out that  `getText()` returns a different value on every intermediate event, obscuring whether a change has actually happened or not.  Since no other lifecycle events are reported it is difficult or possibly impossible to divine whether the user provided input or not.

**Comment by jdmarshall** [comment]
It looks like `_.debounce()` does a reasonable job of collapsing the repeated change events.

**Comment by josdejong** [comment]
Thanks for bringing this up. When changing mode there is no reason to emit `change` events, that should be fixed.

Indeed some throttle or debounce function will help.

**Comment by bmherold** [comment]
Seeing the same thing when switching to code editor - or even loading it by default. +1
