### ISSUE TITLE
options.error callback doesn't fire

### ISSUE THREAD

**Issue by bmherold** [josdejong/jsoneditor#223]
Not sure what what else needs to happen - here's my config anyway:

    $scope.editor = {
      options: {
        mode: 'code',
        error: function(error) {
          console.log('error in json', error);
        }
      }
    }

**Comment by josdejong** [comment]
That's it indeed. See also example [03_switch_mode.html](https://github.com/josdejong/jsoneditor/blob/master/examples/03_switch_mode.html).

Errors are fired for example when you try to switch mode from `code` to `tree` and your JSON is invalid, or when you try to format/compact JSON whilst it's invalid. When you're just in `tree` mode, no errors can occur.

**Comment by bmherold** [comment]
I was expecting that errors would be fired when you have invalid json in code mode. This is not the case.

**Comment by josdejong** [comment]
That's indeed not the case. That would fire a *lot* of errors whilst you're typing in `code` mode ;)

**Comment by bmherold** [comment]
That's fair - though in my case I do want to know this - since the json is technically invalid and erroneous. I've found a workaround. Thanks for the follow-up.

**Comment by josdejong** [comment]
Ok great. What sort of solution do you use now?
