### ISSUE TITLE
Collapsed in 'code' mode

### ISSUE THREAD

**Issue by epinapala** [josdejong/jsoneditor#226]
Is it possible to collapse by default in 'code' mode ? The only options I see when 'code' mode is selected are regarding indentation only.

**Comment by josdejong** [comment]
Hi, that's indeed not supported.

**Comment by epinapala** [comment]
Thanks for your reply. I know the code mode is using ace editor, which indeed supports the collapse

example : editor.getSession().foldAll(1, 28); 

I am open to hacking the code to add this functionality. Can you point me where can I look first to add this option?(if at all its feasible)

**Comment by josdejong** [comment]
That could be interesting. It's not yet clear to me how you could know at which lines you should fold, you have to know the structure of the JSON then. Do you have ideas for that?

Ace Editor is created here in the code: https://github.com/josdejong/jsoneditor/blob/master/src/js/textmode.js#L131-L139

**Comment by epinapala** [comment]
I tried something yesrerday in the exact same location u pointed. Will do some testing and will send a PR

**Comment by josdejong** [comment]
Any news on this issue? Is it still relevant?
