### ISSUE TITLE
Can't paste from other programs 

### ISSUE THREAD

**Issue by jhihn** [josdejong/jsoneditor#228]
I can't paste from outside programs (editor, chrome, etc) I get a red dot instead.
_sometimes_ I can though. It's really problematic. Sometimes if I use menus for Edit/Copy it'll work. But keyboard shortcuts don't ever work, except from your editor to your editor.

OSX, but I saw this on Linux Mint as well.

**Comment by josdejong** [comment]
Thanks for your report. How can I reproduce this exactly? (copying/pasting seems to work just fine here, running Linux Mint)

**Comment by jhihn** [comment]
I've played with it some more, and I can't reliably get it to fail, however I did experience both failures and successes in my attempts, they were't 100% repeatable.

For me, the best test so far is to enter {"a":1}  into the editor, copy it and hit paste, adding it to the document. That's when I get the white dot centered on red background in the character cell. 

Other programs have trouble to, but sometimes they work sometimes they don't. I wonder if it's something to do with the mime-type of the paste?

I'll try on Mint when I get home. For now the above scenario works on OSX.

**Comment by josdejong** [comment]
Thanks for the extra info.

A possible cause could be something that a zero width space character is inserted somehow, as explained here: 
- http://stackoverflow.com/questions/13463458/get-rid-of-character-from-jsfiddle
- Red dot inserted after URL https://github.com/adobe/brackets/issues/8688

**Comment by jhihn** [comment]
Very likely. Is there a way you can replace it with a normal space on the paste event?

**Comment by josdejong** [comment]
The pasting is happening in [Ace editor](http://ace.c9.io/#nav=about), JSON Editor doesn't have control over these paste actions. The issue seems to be known for a long time, and is still open :( see :

https://github.com/ajaxorg/ace/issues/175
https://github.com/ajaxorg/ace/issues/2124

**Comment by jhihn** [comment]
Ok. I accept that, but this is copy/paste issue is also on OSX, not middle paste on Linux. I
