### ISSUE TITLE
No events available

### ISSUE THREAD

**Issue by gheinemann** [josdejong/jsoneditor#229]
I'd like to be able to handle modifications (tree or form mode) knowing exactly what action has been performed in order to integrate the editor into a JS app.

Would it be possible to have custom events to catch with values as parameters (when it is the case) as a first step ? (e.g. change an index:value couple with ancestor path, add an entry of type x with ancestor path, etc etc)

**Comment by josdejong** [comment]
Yes, that will be great. The current `change` event doesn't provide any additional information. See also #39, of which this is a duplicate. I suggest we close this issue and continue discussion in #39.
