### ISSUE TITLE
JSON string POST instead of file download example

### ISSUE THREAD

**Issue by bryanandrews** [josdejong/jsoneditor#232]
First of all thank you very much! This is great work.

Would anyone be able to provide an example that uses *JSONEditor* to `POST` the json string instead of the example that prompts a browser to download a file? Is this possible?

**Comment by josdejong** [comment]
Sure that is possible, but it has nothing to do with JSONEditor itself. You can get the JSON contents from the editor using `editor.get()` or `editor.getText()`, then send the data to your server via an POST request (AJAX). Just google for how you send data to a server using a POST request.

**Comment by bryanandrews** [comment]
For those that might also want to do this, here is what worked for me.

The HTML submit/save button:
~~~
<p>
  <input type="button" value="Save" onclick="javascript:post('destination.php', {JSON: editor.getText()});"/>
</p>
~~~

The JAVASCRIPT function it calls:
~~~
  function post(path, params, method) {
    method = method || "post"; // Set method to post by default if not specified.

    // The rest of this code assumes you are not using a library.
    // It can be made less wordy if you use one.
    var form = document.createElement("form");
    form.setAttribute("method", method);
    form.setAttribute("action", path);

    for(var key in params) {
        if(params.hasOwnProperty(key)) {
            var hiddenField = document.createElement("input");
            hiddenField.setAttribute("type", "hidden");
            hiddenField.setAttribute("name", key);
            hiddenField.setAttribute("value", params[key]);

            form.appendChild(hiddenField);
         }
    }

    document.body.appendChild(form);
    form.submit();
  }
~~~

destination.php
~~~
echo $_REQUEST['JSON'];
~~~

Source: https://stackoverflow.com/questions/133925/javascript-post-request-like-a-form-submit

**Comment by josdejong** [comment]
Good to hear you solved it.
