### ISSUE TITLE
JSPM support

### ISSUE THREAD

**Issue by MadMub** [josdejong/jsoneditor#234]
Currently using JSPM/Systemjs for development and module loading. Should support jsoneditor right out of the box (personally I have used it for brace already), however it errors on install of jsonlint because unfortunately jspm does not support commit versions as dependencies.

Basically just wondering if I can use jsoneditor against the lastest release of jsonlint? Or could you make a semver release of your fork of jsonlint?

**Comment by josdejong** [comment]
There is a bug in the jsonlint library: https://github.com/zaach/jsonlint/issues/57

Unfortunately the `jsonlint` library isn't maintained at the moment (See  https://github.com/zaach/jsonlint/issues/56). Therefore I cloned the project, fixed the bug, and point to this fixed version on github.

**Comment by MadMub** [comment]
I understand. The only way to get jspm to install your version of the repo then would be to make a versioned release. 

Even if I specify jspm to install from your account, it will grab version 1.6. Obviously the underlying issue is  jspm not supporting specific commit versions. For the sake of testing out what I'm personally doing I can just fork your repo and create a versioned tag/branch.

**Comment by josdejong** [comment]
Maybe I should just copy the source code of jsonlint and put it in an assets folder in the jsoneditor project (its stale anyway). I don't like the current link to a git project either.

**Comment by MadMub** [comment]
Sounds good to me, i got a reply from the jspm dev and there are no plans to support commit versions. It's worth mentioned jsoneditor works 100% when importing the dist/ version from the repo. The only issue there is if developers like myself are also already using brace throughout the project then it is loaded twice in memory.

**Comment by josdejong** [comment]
I've fixed this: moved the jsonlint file into an assets folder in the develop branch of this project.
