### ISSUE TITLE
custom img path

### ISSUE THREAD

**Issue by MadMub** [josdejong/jsoneditor#235]
Currently bundling editor into single index.html file, only issue being the png file must be hosted on the correct relative path specified in the css. Workaround for it isn't too bad, just requires running a tiny script to update the references in the css file.

Just thought I'd through it out there for a custom path to the img asset. However that might be even more tricky as it might involve bringing less/sass into the picture or having some build process specifically for that one tiny issue.

**Comment by josdejong** [comment]
Thanks for your idea, but I'm not sure how you would like to customize the path of the image. This sounds to me like a task for a CSS bundler: move/copy images and update urls in the CSS accordingly. Or embed the image in CSS like for example Webpack can do very easily.

**Comment by MadMub** [comment]
After diving into the source code more I see it could easily be integrated in your gulpfile. Just thought I'd mention jsoneditor is fantastic!

**Comment by josdejong** [comment]
Thanks :)
