### ISSUE TITLE
Escaping backslash characters

### ISSUE THREAD

**Issue by HairyMike** [josdejong/jsoneditor#237]
Hey josdejong,

Really brilliant json editor you have here.

I see you have a feature where you escape backslash characters.  I am planning to use this to edit application configurations, but the backslash escaping is playing havoc with local paths: 

e.g. "c:\windows\system32" becomes "c:\\\\windows\\\\system32"

It would be great (for me) if this could be disabled through configuration.

**Comment by HairyMike** [comment]
The following change seems to stop the escaping:

```javascript
	/**
	 * escape a text to make it a valid JSON string. The method will:
	 *   - replace unescaped double quotes with '\"'
	 *   - replace unescaped backslash with '\\'
	 *   - replace returns with '\n'
	 * @param {String} text
	 * @return {String} escapedText
	 * @private
	 */
	Node.prototype._escapeJSON = function (text) {
	  // TODO: replace with some smart regex (only when a new solution is faster!)
	  var escaped = '';
	  var i = 0, iMax = text.length;
	  while (i < iMax) {
	    var c = text.charAt(i);
	    if (c == '\n') {
	      escaped += '\\n';
	    }
	    else if (c == '\\') {
	      escaped += c;
	      i++;

	      c = text.charAt(i);
	      //if ('"\\/bfnrtu'.indexOf(c) == -1) {
	      //  escaped += '\\';  // no valid escape character
	      //}
	      //escaped += c;
	    }
	    else if (c == '"') {
	      escaped += '\\"';
	    }
	    else {
	      escaped += c;
	    }
	    i++;
	  }

	  return escaped;
	};
```

**Comment by HairyMike** [comment]
I think I am being silly. Of course we need to escape the single backslash..  as any character may come afterwards.. eg \b \f \r \n.

I retract my issue :)

**Comment by josdejong** [comment]
You're welcome :) 

Indeed without escaping it's no valid JSON.

**Comment by HairyMike** [comment]
I will look into showing the value in its unescaped form while editing.  I see that user can enter carriage returns and have them rendered as \n when leaving the cell..  maybe this can be reversed when the user begins editing a cell.
