### ISSUE TITLE
Expecting 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '[', got 'EOF'

### ISSUE THREAD

**Issue by JPVenson** [josdejong/jsoneditor#238]
hey,

I tried to set the JSON to the Editor and got the error you can see in the header:

Error: Parse error on line 1:

^
Expecting 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '[', got 'EOF'

The string i tried to push is:

[{"test":"test"}]

Both methods set, setText produces this error
any help?

**Comment by josdejong** [comment]
I think there the code you try to load contains some weird error, the error you print there says that it sees an EOF (end of file) character.

**Comment by JPVenson** [comment]
Yea but why? I cannot find the Problem nor a Sollution for it. 

i am using 

 * @author  Jos de Jong, <wjosdejong@gmail.com>
 * @version 4.2.1
 * @date    2015-06-13

**Comment by josdejong** [comment]
I see I had a typo in my previous comment, ment to say I expect there is an invalid character in the string you try to load.

**Comment by JPVenson** [comment]
Well I tried to load a Constant string:

            var editor: JSONEditor;
            var JsonEditOptions = {
                "mode": "code",
                "modes": [
                    "tree",
                    "form",
                    "code",
                    "text"
                ],
                "history": false,            
            }
            editor = new JSONEditor(document.getElementById("json-editor"), JsonEditOptions);
            editor.set("[{\"test\":\"test\"}]");

and not even that is working. It throws the exception at the set function.

**Comment by josdejong** [comment]
ah, you pass a string instead of a JSON object. You can do either one of the following:

```js
editor.setText("[{\"test\":\"test\"}]");

var json = JSON.parse("[{\"test\":\"test\"}]");
editor.set(json);
```

here an example:

http://jsbin.com/gekohi/edit?html,output

**Comment by josdejong** [comment]
I still don't get it exactly, your code should still work and not throw an error: just load your text as a string containing this JSON.

**Comment by JPVenson** [comment]
I did so

editor.set(angular.fromJson("[{\"test\":\"test\"}]"));

still throws the error

![capture](https://cloud.githubusercontent.com/assets/6794763/11397559/c4e8752e-937a-11e5-9443-4f08fc7343a4.PNG)

**Comment by JPVenson** [comment]
I even tried to switch from my Local version to the CDN one. Same error

**Comment by JPVenson** [comment]
Ok i found, somehow the error. Its the Options object. After calling the Constructor without it, it shows property. This is no solution for me because i must be aware of the change event, but now it shows the Editor.

**Comment by josdejong** [comment]
Can you create a jsbin demonstrating the issue? I don't know how to reproduce it.

**Comment by JPVenson** [comment]
The exact code:

http://jsbin.com/yobeqagujo/1/edit?html,output

**Comment by josdejong** [comment]
I found the issue: in your `change` listener you do an `editor.get()`:

```js
change: function () {
  if (editor != null) {
    var contents = editor.get(); // ooops, editor.get() can throw an Exception
  }
}
```

This method `editor.get()` fails when the editor contains invalid JSON, which can be the case when you're in mode `code` or `text`. So to solve this, you could either use `editor.getText()` instead, or put a try/catch around `editor.get()` and handle this case somehow.

**Comment by JPVenson** [comment]
No thats not the problem, try comment it out and it still not working. After its works i found that problem and fixed it with:

this.SelectedItem.Content = angular.fromJson(editor.get());

this was right after my change to the working code:
https://jsbin.com/xedezofoko/2/edit?html,output

**Comment by josdejong** [comment]
> No thats not the problem, try comment it out and it still not working.

? 

your jsbin works indeed fine without the change listener (except for a ReferenceError as `angular.fromJson` is not defined).

I updated my jsbin, it throws exactly your original exception: http://jsbin.com/gekohi/edit?html,output. When you comment the change listener out, the problem is fixed.

**Comment by JPVenson** [comment]
Working fine for me, compared to my one:
http://jsbin.com/bipukoheke/1/edit?html,output

My:

![capture](https://cloud.githubusercontent.com/assets/6794763/11398403/a8814716-9380-11e5-82fb-e383749d63dc.PNG)

Yours:
![capture](https://cloud.githubusercontent.com/assets/6794763/11398391/89f22306-9380-11e5-943a-4a01b7a66939.PNG)

**Comment by josdejong** [comment]
In mode code and text, you will have to give the DIV container where you put the JSONEditor a height.

**Comment by JPVenson** [comment]
Ok forget it just another problem. I renamed the div and forgot the rename the stlye to ;-)
