### ISSUE TITLE
detect failure to load

### ISSUE THREAD

**Issue by bryanandrews** [josdejong/jsoneditor#239]
Is there a way to detect when jsoneditor does not load due to unsupported platforms like iPad+Safari?

Right now it simply doesn't load and leaves a blank space with no warning or error on load failure.

**Comment by josdejong** [comment]
The editor does not specifically support touch, but works fine on touch devices except that dragging rows up/down does not work. I just tried on an iPad 2 and the editor juts loads fine, maybe your issue has a different cause?
