### ISSUE TITLE
Add read only support.

### ISSUE THREAD

**Issue by niemyjski** [josdejong/jsoneditor#24]
I tried forking the code to make it possible to make the editor read only (no moving nodes or adding additional nodes, no menu etc.) but ran into issues.

In some cases, I'd just like to add a read-only viewer (yours is one of the best, but is editable). It would be awesome, if I could do this via an option.

**Comment by cope** [comment]
We are adding the 'jsoneditor-readonly' class to make the jsoneditor look like mode=code, but readOnly.

It would be nice if there was a _proper_ way to accomplish this, as well as to specify a readOnly theme. For example, I would love to use eclipse theme for regular code mode, and then dawn theme for code mode which would then be readOnly=true...

**Comment by josdejong** [comment]
Shall we continue this discussion in #360 ?

**Comment by cope** [comment]
The [#360 (comment)](https://github.com/josdejong/jsoneditor/issues/360#issuecomment-277521662) helped!
