### ISSUE TITLE
Drag off of handle, row stays highlighted

### ISSUE THREAD

**Issue by 1j01** [josdejong/jsoneditor#242]
If you end your drag outside of the handle, the row stays highlighted.

![jsoneditor-highlighting-stays](https://cloud.githubusercontent.com/assets/3630663/11700632/f8c9c374-9e98-11e5-8463-2945570410c5.gif)

Perhaps `unhighlight` in `_onDragEnd`?

**Comment by josdejong** [comment]
Thanks, will fix it within a few weeks.
