### ISSUE TITLE
XML support

### ISSUE THREAD

**Issue by Immortalin** [josdejong/jsoneditor#245]
It would be great if this can support XML.

**Comment by josdejong** [comment]
Thanks for your suggestion, but I have no plans to expand the editor to support for other data types, sorry. 

See also #216 .

**Comment by Immortalin** [comment]
Will you accept a pull request then?

**Comment by josdejong** [comment]
No, that would introduce quite some extra complexity and maintenance. I rather want to keep the library focused on JSON and extend it for example with support for JSON Schema.

Anyway, feel free to fork the project and implement XML support yourself :)

**Comment by saisurya-k** [comment]
@Immortalin did you create one with XML support,If yes can you please share.

**Comment by Immortalin** [comment]
@saisurya-k I am never got around to working on it :(
