### ISSUE TITLE
How to destroy JSONEditor

### ISSUE THREAD

**Issue by dimylik** [josdejong/jsoneditor#246]
I am using JSONEditor with Angular.
First time I open the page, everything is good and editor is working.

The problem what I got, if you change URL and press enter, Angular controller is getting called and new JSONEditor getting initialied, fine, but editor does not appear on the screen, 
empty div  id="editorPanelTree"

HTML : 
           div class="col-md-12" id="editorPanelTree"></div

Angular controller:

            var editorPanelTree = document.getElementById('editorPanelTree');
            // I was trying clearing previous div content like that, does not help
            editorPanelTree.innerHTML = "";

            var optionsTree = {
                "mode": 'code',
                "modes": ['tree', 'code'],
                "history": true,
                "search": true,
                "indentation": 2
            };

            $scope.someJson = {};
            $scope.state.JSONEditor = new JSONEditor(editorPanelTree, optionsTree, $scope.someJson);

            $scope.$on('$locationChangeStart', function (event, newLoc, oldLoc) {
                if ($scope.state.JSONEditor) {
                    // would be nice to call destroy() function here to remove previous JSONEditor editor
                    // $scope.state.JSONEditor.destroy(); ???
                }
            });

**Comment by josdejong** [comment]
There should be no need to "destroy" the JSONEditor, it should be enough to just remove it from the DOM and remove your reference in JS. There is one issue in this regard, #149, this isn't yet resolved.

It's hard to see from your code snippet what could go wrong. Can you create a jsbin or jsfiddle demonstrating the issue?
