### ISSUE TITLE
Docker support

### ISSUE THREAD

**Issue by mayankasthana** [josdejong/jsoneditor#248]
It would be great if this could be deployed directly through docker. 
I want to run this in our environment, but do not want to pollute the system installing npm, node, bower, gulp etc.

If there is support I will do a PR.

**Comment by mayankasthana** [comment]
Seems like I got this confused with the live version on http://jsoneditoronline.org/.
So, I am closing this.

**Comment by mottosso** [comment]
No confusion, you're right on the money.

If you click on the barely visible "Sourcecode" link at the bottom of that website, it'll take you here.

Docker support would be very convenient, so +1. I did find [this](https://github.com/djmattyg007/docker-jsoneditor) but haven't gotten it up and running yet (the usage instructions assume you are ready to deploy, whereas I'd like to try locally first).
