### ISSUE TITLE
Load / paste *.crt file returns an error

### ISSUE THREAD

**Issue by dandan6** [josdejong/jsoneditor#251]
I'm using JSON Editor Online 3.4.0 to format sites certificate strings.
It used to work until recently, and now when I upload  / paste *.crt file - I'm getting the following error:

===============================
Error: Parse error on line 1:
-----BEGIN CERTIFICA
^
Expecting 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '[', got 'undefined'
===============================

I'm using Chrome on Win7. (occuring both from JSON Editor online, and JSON Editor from Chrome Apps / Extensions)

[888.zip](https://github.com/josdejong/jsoneditor/files/75404/888.zip)

**Comment by josdejong** [comment]
You're file doesn't contain JSON. Hence, the JSON Editor throws an error. You can still view/edit the text of your file in the code editor, but this has nothing to do with JSON.

**Comment by dandan6** [comment]
Hello Jong,

Thank you for the quick reply .
I want to explain the flow we’re working on-
We are using JSON files to run REST commands, some of the parameters are using server authentication.

We’re using JSON Editor for a long time already in order to format the *.crt files to JSON file format, but for some reason – It stopped working recently.

I’m adding a JSON file example…



Dan Aviam
Software Quality Engineer
Office- 8717-2822

**Comment by josdejong** [comment]
Thanks for the extra explanation, but I still totally don't get it. The file in 888.zip that you linked to in your first message contains the following text (I removed the middle part):

```
-----BEGIN CERTIFICATE-----
MIID+zCCAuOgAwIBAgIDEAACMA0GCSqGSIb3DQEBCwUAMIGTMRUwEwYDVQQKDAxW
[...]
0s2dMl4xUKzWzsNOqFWrb1ZsBVIxTUpUsxZabQ5d0fgKFdUptrrX8Wvgih5TS9ww
32++BOXQOdRQp+b11P8H
-----END CERTIFICATE-----
```

This is in no way anything near valid JSON. I have no clue how you could turn this into valid JSON. JSONEditor never was and never will be able to make JSON out of this, it has simply nothing to do with JSON.

JSONEditor did not receive any update since June 2015 (except for two days ago, but that's *after* you noticed this problem). So I have no idea why your way of working would have stopped since recently.

**Comment by dandan6** [comment]
Hi .

In general – the *crt part would covert the text block into a single line string with “\n” separator.

But I guess we will have to find another alternatives for that.

Thank you .


Dan Aviam
Software Quality Engineer
Office- 8717-2822

**Comment by josdejong** [comment]
You mean like the contents of the crt file will become a string in a JSON object?

**Comment by dandan6** [comment]
Yes..


Dan Aviam
Software Quality Engineer
Office- 8717-2822

**Comment by josdejong** [comment]
Ah, ok now I get what you're doing :). I'm afraid this is a too specific case to make a generic solution for it in JSONEditor. We can't create a rule like *"if a file contains invalid JSON just enclose it in double quotes to make it a string"*, as that's not always a desired behavior. Sorry.

**Comment by dandan6** [comment]
Appreciate your time and effort.

As I wrote – we’ll have to find out another solution for that.
Thanks anyway. ☺


Dan Aviam
Software Quality Engineer
Office- 8717-2822

**Comment by josdejong** [comment]
Ok success!
