### ISSUE TITLE
When I use the Chinese input method in IE or Edge brower to enter text in the code mode ,have a problem.

### ISSUE THREAD

**Issue by gemron** [josdejong/jsoneditor#253]
Characters that will appear in disorder include both English and Chinese.
Chrome is no this problem.IE and Edge have this problem.
hope you can repair this problem,thanks!
![20160112211843](https://cloud.githubusercontent.com/assets/1953998/12264665/376f8f10-b973-11e5-9029-f671ee10d778.png)

**Comment by josdejong** [comment]
Thanks for reporting this MengYue, we will look into it.

**Comment by zyqhi** [comment]
I met the same problem in chrome  53.0.2785.143 under macOS Sierra.

**Comment by josdejong** [comment]
Thanks for reporting @zyqhi . We still haven't looked into this, sorry. Help is welcome.

**Comment by AloofJr** [comment]
I met the same problem in chrome 55.0.2883.87m under windows

**Comment by josdejong** [comment]
Thanks @AloofJr . Any idea how I could reproduce this issue on a non-Chinese computer? Set the language temporarily to Simlified Chinese or something? (I'm not familiar with non-European keyboards, a bit of guidance would be useful)

**Comment by AloofJr** [comment]
I found this video ,I guess  It may have some help

windows： [https://www.youtube.com/watch?v=HjeuiRBhrkE](https://www.youtube.com/watch?v=HjeuiRBhrkE) 

mac：[https://www.youtube.com/watch?v=f-7tC7tlw7E](https://www.youtube.com/watch?v=f-7tC7tlw7E)

When inputted Chinese  ,both English and Chinese will be appeared，it only appears in the code mode，you can also input Chinese in other mode use the same characters to diff and you’ll find the issue. 

there are some words  with the same meaning  in  Chinese  and English . you can input Chinese Pinyin to appear Chinese characters 

English  | Chinese Pinyin | Chinese characters 
---------|-----------------|---------------------
hello    |  nihao |  你好
name | mingzi | 名字
China | zhongguo | 中国

**Comment by josdejong** [comment]
Thanks for the pointers, I will give it a try soon.

**Comment by josdejong** [comment]
This should be fixed/improved in the latest v5.6.0 thanks to an upgrade to the latest version of Ace editor, see #381.
