### ISSUE TITLE
Abililty to suppress errors

### ISSUE THREAD

**Issue by mariahlynne** [josdejong/jsoneditor#254]
It would be very useful to have an option to suppress errors so that the console does not get cluttered up (example error message below). These errors are thrown while the user is typing and they add up quickly.

Error: Parse error on line 8:
...": true,  "test"  "Created": "2016-01-
---------------------^
Expecting 'EOF', '}', ':', ',', ']', got 'STRING'
    at Object.parse (jsoneditor.js:6586)
    at Object.validate (jsoneditor.js:1620)
    at Object.parse (jsoneditor.js:1476)
    at JSONEditor.textmode.get (jsoneditor.js:1408)
    at ng-jsoneditor.js:32
    at angular.js:17918
    at completeOutstandingRequest (angular.js:5552)
    at angular.js:5829

**Comment by josdejong** [comment]
You can catch errors with the config option `onError`, and just do nothing with them, would that help?

**Comment by josdejong** [comment]
Looking at your stacktrace, isn't this error caused because the angular directive tries to call `editor.get()` whilst the editor does not contain valid JSON? In that case https://github.com/angular-tools/ng-jsoneditor/issues may be the appropriate place to put this issue.

**Comment by mariahlynne** [comment]
Sounds good - I will create an issue over there. Thank you!

**Comment by baslr** [comment]
pr https://github.com/angular-tools/ng-jsoneditor/pull/7 fixes the error.

**Comment by josdejong** [comment]
Good to hear, thanks for ketting me know.

**Comment by pranav-js** [comment]
@josdejong when invalid JSON is present

```ts
 onChange: () => {
          this.showInitialHelpArrow = false;
          try {
            const newReq = this.editor.get();
            //some logic happening here
          } catch (error) {
            console.log(error); ----> this does
          }
        },
        onError: () => {
          alert('23232');   ----> this never invokes
        },
```

**Comment by josdejong** [comment]
Ah, clear. 

onError is indeed not invoked when the JSON contents are invalid (that is a "normal" situation which happens all the time whilst you're editing your JSON, not an exception). From the API docs on `onError`:

> The callback is only invoked for errors triggered by a users action, like switching from code mode to tree mode or clicking the Format button whilst the editor doesn't contain valid JSON.

**Comment by pranav-js** [comment]
@josdejong  so how can we suppress this error? Any other way?

Analytics tools like Sentry is catching all this :(

**Comment by pranav-js** [comment]
It can be catched I believe instead of leaving it unhandled>

something like wrappers are doing it, but it should be from original plugin only I think
https://github.com/angular-tools/ng-jsoneditor/pull/7/files

**Comment by pranav-js** [comment]
Hmm, I think this issue needs to be reopened since it is definitely the one

**Comment by josdejong** [comment]
So what _is_ the issue?

**Comment by josdejong** [comment]
You can decide yourself what you want to do when an error occurs. If you want to silently suppress errors you can do so, right?

```js
 onChange: () => {
          this.showInitialHelpArrow = false;
          try {
            const newReq = this.editor.get();
            //some logic happening here
          } catch (error) {
           // silently suppress error...
          }
        },
        onError: () => {
          // silently suppress error...
        },
```

However in general when an error occurs, it should not be suppressed but the user should be informed about it with some toaster message or something.

**Comment by pranav-js** [comment]
@josdejong  yeah my bad. try catch in onChange is suppressing it. 
It was my global error handler throwing console.error. 

Thanks for your quick responses though :)

**Comment by pranav-js** [comment]
ok my errors are not printing anymore because i removed console.error but angular's global error handler still catches it and the sentry is capturing it. 

I am trying to escape with regex check maybe like I am doing for HTTPErrrors
But is the below error custom error from plugin or standard JS error?

```js
sentry Error: Parse error on line 3:
... "Customer Name",  "email  ": "custome
----------------------^
Expecting 'STRING', got 'undefined'
```

```ts
catch (error) {
      //console.error(error);
      if (!(error instanceof HttpErrorResponse)) {
        console.log('sentry', error); ----> this will always print

        Sentry.captureException(error);
      }
```
