### ISSUE TITLE
Missing 'search' option in v5.1.0

### ISSUE THREAD

**Issue by MiroHibler** [josdejong/jsoneditor#255]
I'm getting console warning about 'search' option being unknown.

**Comment by josdejong** [comment]
Thanks for reporting this. The option still works but is wrongly displaying a warning in the console. The new options validator was missing the option `search`. Fixed now in the develop branch.

**Comment by MiroHibler** [comment]
Yeah, I was about to submit a PR, but got stuck with my GitHub SSH permissions for some yet unknown reasons... :)

**Comment by josdejong** [comment]
thanks anyway!
