### ISSUE TITLE
getFromSchema does not properly handle references

### ISSUE THREAD

**Issue by nivekmai** [josdejong/jsoneditor#257]
util/getFromSchema.js assumes a schema in which you can follow the path and curse through the schema object. However, if you have a schema that contains a reference, this will not be the case. This causes a exception when trying to run "improveSchemaError" on a schema that contains references.

Since references can be to anywhere in the internet, it might be best to simply abandon attempts to provide an improved error when a reference is made.

**Comment by josdejong** [comment]
Thanks, good point. I hadn't thought of that. 

I figured `ajv` has an option `verbose`, which passes a reference to the part of the schema where the error occurred, that's way easier than the `getFromSchema` function I had created before.

**Comment by josdejong** [comment]
This should be fixed now in v5.1.1, can you give it a try?

**Comment by nivekmai** [comment]
Seems to be working correctly.

**Comment by josdejong** [comment]
ok great, thanks for the feedback.
