### ISSUE TITLE
raw text

### ISSUE THREAD

**Issue by varazir** [josdejong/jsoneditor#258]
Hello, is there a way to get the left field as raw json text  ? I lik eto access it using AutoTool Tasker plugin on my android phone.

**Comment by josdejong** [comment]
Do you mean via JavaScript?

**Comment by varazir** [comment]
It's a android app. If there are a rested API I can use I could use that too

**Comment by josdejong** [comment]
If you can make calls via JavaScript, it's basically:

```js
var text1 = codeEditor.getText(); // left panel
var text2 = treeEditor.getText();  // right panel
```
you can try it out by opening a developer console in your browser when on the web page http://jsoneditoronline.org. 

Note that this is no offical API and may break some day in the future.

**Comment by varazir** [comment]
Thanks, now I just need to figure out how use it. 
It works in the dev console.
