### ISSUE TITLE
Context menu is causing form to submit if editor is inside of the form

### ISSUE THREAD

**Issue by desertkun** [josdejong/jsoneditor#259]
Hello!

If you put an editor div inside a `<form>` tag, open context menu, and expand menu item, the `<form>` will be submitted.

![1](https://cloud.githubusercontent.com/assets/1666014/12423656/2437a57e-bed5-11e5-9b84-fd5fda5cb028.png)

This happens since 5.0.0.

**Comment by josdejong** [comment]
Ah, that's funny. Well not really... ;) I will fix it, thanks for your report!

**Comment by josdejong** [comment]
Ok this is fixed now in the develop branch, next bug fix release will be this week.

**Comment by desertkun** [comment]
Thank you very much!
