### ISSUE TITLE
"Open url" doesn't work

### ISSUE THREAD

**Issue by jhaamit6666** [josdejong/jsoneditor#261]
![1](https://cloud.githubusercontent.com/assets/16834561/12507005/fd331026-c118-11e5-90ff-6748d234e759.png)

**Comment by josdejong** [comment]
What happens exactly? Clicking "Open url" should open a popup where you can enter a url. I've just tested on Chrome, FF, IE11, and it seems to work there. What browser and browser version are you using?

**Comment by jhaamit6666** [comment]
Yes, it's showing a popup, where we can enter a url. But, it doesn't parse. I am using latest Chrome on Windows 10.

**Comment by josdejong** [comment]
Ah ok. It can be the case that you try to open a non-public URL, that's not supported.

Can you check whether you can open the following URL via the "Open url" popup?

http://jsoneditoronline.org/test/example.json

**Comment by josdejong** [comment]
Yeah, it's not actually not exactly *non-public* urls in the sense of private intranet/public internet, you can open urls from your local machine or intranet, but the url must have CORS enabled for http://jsoneditoronline.org, and must not require credentials or special authentication tokens. I will make that more clear in the docs.

**Comment by jhaamit6666** [comment]
Yes, that was the issue. Thanks.
And can this be solved in http://jsoneditoronline.org ?
Means using other workaround, can you have it parsed?

**Comment by josdejong** [comment]
This is a browser security restriction, it can't be resolved in a website. It's only solvable by running it not as a web site but as a Chrome application or a desktop application (see #201).
