### ISSUE TITLE
"Expand all" and "Collapse all" if present will be helpful

### ISSUE THREAD

**Issue by jhaamit6666** [josdejong/jsoneditor#262]
![2](https://cloud.githubusercontent.com/assets/16834561/12507092/68776f9e-c119-11e5-97bb-142774bcf6cb.png)

**Comment by josdejong** [comment]
You can Ctrl+Click on the expand buttons ( &#9658; ) to expand/collapse all for that particular node.

**Comment by jhaamit6666** [comment]
OK. It would be good if options were present.
