### ISSUE TITLE
Same options should be present as inner objects

### ISSUE THREAD

**Issue by ranjan-ranjan** [josdejong/jsoneditor#263]
![3](https://cloud.githubusercontent.com/assets/16834561/12507213/5668b320-c11a-11e5-9cbb-4a7668e2272f.png)

**Comment by josdejong** [comment]
The root node simply has less options. You can't delete it else you have "nothing" left to work on. You can also only have a single root node else you don't have valid JSON, so you can't append/insert/duplicate on the root node level.

**Comment by jhaamit6666** [comment]
OK. Thanks.

**Comment by jhaamit6666** [comment]
"Insert" & "Duplicate" options on root node?

**Comment by josdejong** [comment]
Append, Insert, and Duplicate work on the child nodes, not on the parent node.

**Comment by jhaamit6666** [comment]
"Append" is not present. How to do it?

**Comment by josdejong** [comment]
Append is available for the last child of a node, insert for all childs.
