### ISSUE TITLE
Context menu not working on Firefox

### ISSUE THREAD

**Issue by FansubDB** [josdejong/jsoneditor#264]
On jsoneditoronline.org<br> 
When I try to add an object (append > object), it doesn't do anything, and in the web console it shows:

```
ReferenceError: event is not defined  app.min.js:2:9564
     i/</l.onclick() app.min.js:2
```

Thanks

**Comment by josdejong** [comment]
Thanks for reporting this. I did not manage to reproduce the issue though, can you describe more precisely when you get this error? And what version number do you see at the bottom of the website (3.6.0 is the latest)?

**Comment by FansubDB** [comment]
In fact, I have this with all!

![screenshot_2016-02-01_17-21-48](https://cloud.githubusercontent.com/assets/9019185/12723322/356a6eb0-c909-11e5-9ca6-714cd2e9dff1.png)

![screenshot_2016-02-01_17-26-24](https://cloud.githubusercontent.com/assets/9019185/12723301/24e41abe-c909-11e5-860a-e9f277bee249.png)

It can be a problem with my browser, so here my browser: Mozilla Firefox 45.0b1 (Beta channel)

**Comment by josdejong** [comment]
Ah, thanks a lot. I can reproduce it, it's an error occurring in Firefox. I have fixed the issue and will update the website within a few days.

**Comment by FansubDB** [comment]
Ok, I'm waiting for the fix. Thanks :)

**Comment by josdejong** [comment]
I've published a bug fix release for this, everything should now work fine on Firefox.
