### ISSUE TITLE
Allow creation of custom objects from schema

### ISSUE THREAD

**Issue by nomius** [josdejong/jsoneditor#267]
It would be really cool to be able to define some objects in a template/schema and to insert/append those directly instead of having to add an empty object plus all its all key:value/arrays items.

**Comment by josdejong** [comment]
Thanks for the suggestion, this is really a cool idea.

**Comment by Sayene** [comment]
+1 that would be really helpfull

**Comment by getvipin** [comment]
+1 That should be really awesome. I am trying to figure out how to insert a json data itself during an insert action.

**Comment by maaikez** [comment]
I implemented this, but it is not very portable. Would be great to have this option. My code, for people who want to use it (very basic):

I am using this function:
In this first function (getEmptyObject), nodes is a string with the nodes separated with a dot. So if you want to make an object from item name in person, you give 'person.name' to this function. With this function, you first navigate to the correct item in the schema and then retrieve the object from it.
`    Node.prototype.getEmptyObject = function(nodes)
    {
        var schema = this.editor.getSchema();
        var values = nodes.split(".");
        var jsonNode = schema;
        values.forEach(function(node)
        {
            if (jsonNode.type === "array")
            {
                jsonNode = jsonNode.items.properties[node]
            }
            else
            {
                jsonNode = jsonNode.properties[node];
            }            
        });
        
        if (jsonNode.type === "array")
        {
            jsonNode = jsonNode["items"];
        }
        
        var objectFromJson = {};
        
        var jsonNode = jsonNode.properties;
        return this._makeObjectFromJSON(jsonNode);
    }`

Once the correct json item is selected, the 'sub-object' is feeded into this function. It then makes a json object. It makes a new object and fills the object properties with default values. It makes only empty array's, but with objects this function goes one object deeper to retrieve the properties (recursive).
`   Node.prototype._makeObjectFromJSON = function(jsonNode)
    {
    	var newObject = {};
    	for (var key in jsonNode)
        {
            var value;
            switch (jsonNode[key].type)
            {
                default:
                case "string":
                {
                    value = "";
                    break;
                }
                case "number":
                {
                    value = 0;
                    break;
                }
                case "object":
                {
                	//make all object properties
                    value = this._makeObjectFromJSON(jsonNode[key].properties);
                    break;
                }
                case "array":
                {
                    value = [];
                    break;
                }
                case "boolean":
                {
                    value = false;
                    break;
                }
            }
            newObject[key] = value;
        }
        return newObject;
    }`

from showContextMenu, I call this function:
`    /**
     * Add an item to the context menu
     * @param node  the node of the context menu
     * @param menuItems  the menu items array
     * @param menuText  the text of the menu item
     * @param menuTitle  the title of the menu item
     * @param menuObject  the object / nodes to find the correct object to add (for example person.child.friend).
     */
    Node.prototype.addItemToMenu = function(node, menuItems, menuText, menuTitle, menuObject)
    {
        if (menuItems.length) 
        {
            // create a separator
            menuItems.push(
            {
              'type': 'separator'
            });
        }

        menuItems.push(
        {
            text: menuText,
            title: menuTitle,
            click: function()
            {
                node._onAppendToArray('', node.getEmptyObject(menuObject), 'object');
            }
        });
    }`

However, adding this to the menu is very custom. I have an 'if' for every array item, that checks the current type and parent. I only want to be able to add items to (some of the) arrays. 

I hope this code was at least a little bit helpful :).

**Comment by josdejong** [comment]
Thanks for sharing @maaikez !

**Comment by josdejong** [comment]
In v5.7.0 you can now define and use templates, implemented by @israelito3000 

Example usage: https://github.com/josdejong/jsoneditor/blob/master/examples/10_templates.html

**Comment by asimontsev** [comment]
The templates feature seems to work fine, however, it looks like it allows inserting a template everywhere. I wonder if it is possible to insert data based on a schema. For example, if we have a Person with the Addresses array, I want to make it possible to put Address object only to this array (and not to the root of the Person). 

Ideally, it should take the template from the schema (say, you may require a user to specify the "default" field; if it is not available, insert some generic value), rather than a part of the options. 

Is it possible to add it to in v6.1?

**Comment by israelito3000** [comment]
That was my first though actually, however after read some comments about schemaless json are more common to use, I preferred to do it like this, still it will be a nice to have feature. What do u think @josdejong?

**Comment by josdejong** [comment]
I think the current template functionality is a great and simple solution that everyone quickly understands. For more advanced solutions, Implementing a JSON Schema will be the most neat solution, allowing to automatically create templates from JSON Schema. So yes, that will be really cool. 

I suppose there are libraries to create a JSON instance from a JSON schema, in that case it should be quite easy to implement in JSONEditor.
