### ISSUE TITLE
Pasting text copied from Mac Terminal into the tree view prepends text with nine (9) newline characters ('\n')

### ISSUE THREAD

**Issue by MrSurly** [josdejong/jsoneditor#268]
Copying text from a Mac Terminal will result in several newline ('\n') characters being prepended to the field value _after the field has lost focus_.  This is in the tree view.

I'm using Chrome version 48.0.2564.97 64-bit, OS X El Capitan 10.11.1, Terminal version 2.6 (361)

**Comment by josdejong** [comment]
Thanks for reporting this. Apparently there are some (hidden?) control characters or something like that being copied and the editor treats them as new line characters. We only have to figure out what control characters these are exactly. I can see whether I can reproduce this on a mac of one of my colleagues tomorrow.

**Comment by josdejong** [comment]
I've done some testing. For some reason when you paste text copied from a terminal on a mac into a contenteditable div in Chrome, it prepends it with 9 newline characters. I guess it's some weirdity in Chrome, at least it's not done by JSONEditor itself. So basically I can't do anything about it, but I was thinking, it may not do harm to just trim values in the editor, and that solves this issue on Mac as a side effect.

**Comment by josdejong** [comment]
I've reverted the fix for this issue: trimming the values can be undesired behavior. 

I guess this simply will be a won't fix: there is no way for JSONEditor to determine when it should remove any prepended newline characters from pasted text.
