### ISSUE TITLE
ReadOnly nodes ... how to do?

### ISSUE THREAD

**Issue by shannoncruey** [josdejong/jsoneditor#27]
Hi, this may be a feature request, or I'd be happy if you could give me some guidance how to implement myself.

I'm using jsoneditor (very happily!) as a frontend in my app where users can edit mongo documents.  It's working well.

However, there are some fields in the document I need to restrict the user from changing.  (For example, the _id).  If a critical field is removed, our application doesn't work.

Where in the code could I add a hook to disable a node?  In my case it's a simple test - if the node name begins with an _, I want it to be disabled.

Thanks for this awesome tool!!!

**Comment by walkerrandolphsmith** [comment]
Hi @josdejong. I see that when the editor is in the `tree` mode I can decide which nodes are editable with the `onEditable` option. If I need all the nodes in the tree to not be editable I can use the `view` mode. I want to Use the `text` mode to display a read only view of the raw text. Textareas support a `readonly` attribute. Is there a setting I have overlooked or would this be a valid feature to implement. I can submit a PR if you like.

**Comment by walkerrandolphsmith** [comment]
I have moved this to a new issue [#382](https://github.com/josdejong/jsoneditor/issues/382)
