### ISSUE TITLE
Rename JSONEditor

### ISSUE THREAD

**Issue by zakirarrayiq** [josdejong/jsoneditor#270]
Thank you for creating excellent editor. In one of the project I was using schema based json editor from https://github.com/jdorn/json-editor. Both yours and theirs name the editor class JSONEditor so I could not use them on one page. Is it possible to rename your editor? or may be some build script that can create renamed script?

**Comment by josdejong** [comment]
Thanks. I will not change the name of JSONEditor, it's a good name. I would say a better name for the `json-editor` library would be "FormGenerator" or something like that, but that's a different story.

Anyway, there are a number of solutions to prevent these sort of name collisions. 

Best is to use a module system like common.js (my preference) or AMD, or go wild with the new module import/export functionality of ES6. When importing a module, you can assign it a name yourself:

```js
var JSONEditorA = require('jsoneditor');
var JSONEditorB = require('json-editor');
```

When you really have to load the scripts globally using `<script>`, you could do:

```html
<script src="assets/jsoneditor/dist/jsoneditor.min.js"></script>
<script>
  var JSONEditorA = JSONEditor;
</script>
<script src="assets/json-editor/dist/jsoneditor.min.js"></script>
<script>
  var JSONEditorB = JSONEditor;
</script>
```

**Comment by zakirarrayiq** [comment]
Thanks for your help and I can understand your perspective here. I wish there was some package definition like Java to resolve these type of conflicts. I am using ng-jsoneditor as using angularjs and need to maintain that

**Comment by josdejong** [comment]
>  wish there was some package definition like Java to resolve these type of conflicts

There are, as I explained. You have common.js, AMD, ES6 modules...

The problem here is that the `ng-jsoneditor` directive relies on a globally exposed `JSONEditor`, which is a problem in your case as you have two global `JSONEditor` objects. How about asking the maintainer of `ng-jsoneditor` to allow for passing the right `JSONEditor` via the options instead of using the globally exposed one? That way you could pass this `JSONEditorA` via the options.

**Comment by liuxihua** [comment]
@josdejong

**Comment by liuxihua** [comment]
could you pls give a example about how to use the JSONEditor with Reactjs,

**Comment by liuxihua** [comment]
import React from 'react'
var JSONEditor = require( '../lib/jsoneditor');

const jschema = {
    schema: {
        type: "object",
        title: "Car",
        properties: {
            make: {
                type: "string",
                enum: [
                    "Toyota",
                    "BMW",
                    "Honda",
                    "Ford",
                    "Chevy",
                    "VW"
                ]
            },
            model: {
                type: "string"
            },
            year: {
                type: "integer",
                enum: [
                    1995, 1996, 1997, 1998, 1999,
                    2000, 2001, 2002, 2003, 2004,
                    2005, 2006, 2007, 2008, 2009,
                    2010, 2011, 2012, 2013, 2014
                ],
                default: 2008
            }
        }
    }
}

export class JsonSchema extends React.Component {

    constructor(props) {
        super(props);
    }

    componentDidMount() {

        var element = document.getElementById('editor_holder');
        var editor = new JSONEditor(element, {
            schema: jschema,
            theme: 'bootstrap3'
        });
    }


    render() {
        return (
                <div id='editor_holder' ></div>
        )
    }
}
i put the jsoneditor.js in the lib folder, and the chrome report the "JsonSchema.js:60 Uncaught TypeError: JSONEditor is not a constructor" error. 

how to deal with this problem? thx

**Comment by josdejong** [comment]
@liuxihua can you please open a new issue for this? Your question looks unrelated.
