### ISSUE TITLE
Update values in tree view programatically

### ISSUE THREAD

**Issue by henkmollema** [josdejong/jsoneditor#271]
Perhaps this is a stupid question, but I can't figure it out: how do I reflect changes to node values I made programatically in the tree view. My use-case is a following:

When a node within a certain array is moved, I want to update a property which represents the sort order of that object programatically.

Roughly the flow:

1. Capture the global `onChange` event
2. Figure out if it's a `moveNodes` event and get the moved node
3. Set the value of a child node to an integer which represents the sort order: `childNode.childs[6].value = i + 1`

So far, so good. But the change is not reflected in the tree view. I could just call `editor.set(editor.get());` but that will cause the tree view to collapse.

This leaves me with two options:
Either use above function and expand the node again, however I could not get this working. I tried:
```
editor.content.removeChild(editor.table);
parentNode.expand();
editor.content.appendChild(editor.table);
```
Without success though..

Or update the DOM with `editor.node._updateDomValue()`. This would not work either.

Any advice will be greatly appreciated.

**Comment by josdejong** [comment]
Hi, this functionality is simply missing right now. You can only get/set the whole JSON object, and you can only get a notification that "something" changed but not what. 

@tomalec started implementing changesets a long time ago, see #102 and #136, but that was never finished. It's still on the wishlist though :).

**Comment by henkmollema** [comment]
I actually got it working using `node.updateValue()` :smile:

Thanks anyways!

**Comment by josdejong** [comment]
Ah, ok. Great if that works for you. It's no public API so it may break some day in the future, but fine for now I think.

**Comment by mnzaki** [comment]
For future googlers:
Here's a quick hack to maintain expanded nodes after changing the editors data: https://github.com/josdejong/jsoneditor/issues/312#issuecomment-373366336

**Comment by ohabash** [comment]
@henkmollema  how were you able to detect a change in the sort order? by reading here it looks like something like the following is possible... ?

```
onChange: function (changed) {
  if(changed === 'moveNodes'){
  	this.updateSortOrder()
  }
}
```

**Comment by josdejong** [comment]
@ohabash lets discuss in #583
