### ISSUE TITLE
Checkbox for boolean values in view mode

### ISSUE THREAD

**Issue by targos** [josdejong/jsoneditor#272]
Boolean values are editable in view mode. Example: https://www.lactame.com/visualizer/HEAD-min/index.html?viewURL=https://visualizer.epfl.ch/x/16alioEkk8OLrustuaHm/view.json

**Comment by targos** [comment]
^

**Comment by josdejong** [comment]
Thanks for reporting, will fix it asap.

**Comment by josdejong** [comment]
This has been fixed in the just released v5.1.5.

**Comment by targos** [comment]
Perfect. Thank you !
