### ISSUE TITLE
cdnjs hosting

### ISSUE THREAD

**Issue by henkmollema** [josdejong/jsoneditor#273]
I'm not sure if you can do something about it, but the CDN on [cdnjs](https://cdnjs.com/libraries/jsoneditor) does not host the SVG images: https://cdnjs.cloudflare.com/ajax/libs/jsoneditor/5.1.5/img/jsoneditor-icons.svg.

**Comment by josdejong** [comment]
Thanks, I see the cdn does not contain the svg image at all (this changed in v5 but I didn't change the cdn entry). 

I've opened a PR to fix this: https://github.com/cdnjs/cdnjs/pull/7008

**Comment by henkmollema** [comment]
It's fixed, thanks @josdejong!

**Comment by josdejong** [comment]
I still have to do a next release in order to add the svg image to the CDN, but the underlying issue is resolved.

**Comment by henkmollema** [comment]
@josdejong the URL I posted seems to work now.

**Comment by josdejong** [comment]
Ah, you're right, great. I did look at the website of cdnjs (https://cdnjs.com/libraries/jsoneditor) which isn't yet updated, but indeed the updated files are already being served.
