### ISSUE TITLE
Support for custom themes

### ISSUE THREAD

**Issue by fibo** [josdejong/jsoneditor#276]
Hi,

thank you very much for sharing jsoneditor, I will use it for my Dataflow programming project [dflow]() and it is really what I needed.

I would like to use a dark theme, and I found *jsoneditor/examples/css/darktheme.css* in the examples. It looks good, my question is: can you make it **official*, I mean, is there a chance to change theme by specifing it in the options?

Reading the documentation it looks like only default theme is supported, but, having a *default*, and *dark* that just points to the example above would be great. By now I am using jsoneditor as a bower dependency so I can reference the darktheme.css form the examples folder.

**Comment by josdejong** [comment]
You're right, currently only the default theme is supported, this dark theme is just an example. The dark theme isn't worked out 100%, for example not for the Ace editor used in mode "code". Ace editor has it's own way of themes, themes are written some special js+amd+stringified-css way ([see here](https://github.com/josdejong/jsoneditor/blob/master/src/js/ace/theme-jsoneditor.js)), which makes it complicated to integrate with custom theming of JSONEditor. Also, to support multiple themes for real I think we should switch from CSS to SASS or LESS to keep stuff maintainable. 

I will change the title of this issue to "Support for themes" and make it a feature request.

**Comment by fibo** [comment]
Maybe, if the inline css could be placed in its own file, and importing it using [webpack stylesheet feature](https://webpack.github.io/docs/stylesheets.html) (I could do a pr for this, it seems easy),
then maybe we could load (by now) two themes, *default* and *dark* and select it in some way with an option (I don't know where to modify the code to do that, right now).

**Comment by josdejong** [comment]
Would be great if you could do some experimenting and see where we end up.

**Comment by fibo** [comment]
Ok, I started putting the css that defines the theme in a separated file, using [webpack raw loader](https://github.com/webpack/raw-loader).
I tested it building and installing it via bower, it works.

Next step should be figure out where we can specify which theme we choose and create a dark theme.

I guess it could be a jsoneditor option parameter that than selects the proper ace theme. Do you have any hint?

Commit here: https://github.com/fibo/jsoneditor/commit/f8f6d038bab12d366d5ad08b6226bb0725a21ec5

**Comment by josdejong** [comment]
That's a nice start! To keep your commits readable it maybe a good idea not to commit the files in `./dist` (I only update them myself when doing a release, else the commits get big and cluttered).

**Comment by fibo** [comment]
Ok, I did it also to try the build and install it with bower, but I will follow this hint for future contributions to your project.

Question: how do you think it should be specified which ace theme you use?

**Comment by josdejong** [comment]
Since the theming of Ace is in a js file, we will have to create themes for JSON editor in js files too. The default theme will be bundled with the JSONEditor.js, and I think we can generate separate bundles for other themes, like `jsoneditor-theme-dark.js`. We can extend the existing configuration option `theme` such that it applies the theme to both JSONEditor and Ace editor.

**Comment by fibo** [comment]
Sorry, but I will use some other tool to edito json. It looks too complicated to customize the theme.
