### ISSUE TITLE
how to cleanly delete a json editor

### ISSUE THREAD

**Issue by jeromew** [josdejong/jsoneditor#278]
Hello,
first of all thanks for your editor !
I was looking into how I could cleanly delete an instance of the editor on a page.

I saw that there is a "_delete" method that is defined in plugins that is used to remove the editor from the DOM. Does it cleanly remove the event's that have been registered by the application ?

I was thinking that it could be interesting to have a special "delete" mode that could be invoked by setMode('delete') and that would do the right job. Do you think it would make sense ?

I thought about something like

    JSONEditor.registerMode({
     mode: 'delete',
     mixin: { create: function() {} },
     data: null
    });

**Comment by josdejong** [comment]
Good point. Thinking about it I'm wondering why I didn't already create such a method.

I think the best way will be to create a new public method `JSONEditor.destroy()`. This will just call the private method `_delete()` internally (`_delete()` indeed cleans up everything).

**Comment by josdejong** [comment]
v5.2.0 now has a method `editor.destroy()` to neatly cleanup stuff.

**Comment by oppoic** [comment]
> v5.2.0 now has a method `editor.destroy()` to neatly cleanup stuff.

and, before calling the `editor.destroy()` method, how to get the `editor ` ?

**Comment by josdejong** [comment]
@oppoic you have to keep a reference to the created editor yourself somewhere in JavaScript.
