### ISSUE TITLE
JSON.parse({"a":1.00})->Object {a: 1} it's a bug?

### ISSUE THREAD

**Issue by 104gogo** [josdejong/jsoneditor#279]
When I use the JSON formatting, it happens.

**Comment by josdejong** [comment]
In JSON, the number `1.00` is exactly the same as `1`, you can't distinguish between the two. If you want to keep trailing zeros, you have to store the number as a string like `{"a":"1.00"}`.

**Comment by 104gogo** [comment]
ok..Thanks for your reply.

**Comment by josdejong** [comment]
You're welcome
