### ISSUE TITLE
mode not working

### ISSUE THREAD

**Issue by shahjehanali1** [josdejong/jsoneditor#287]
```js
            var xotree;
            var editor = ace.edit("input");
            editor.setTheme("ace/theme/dreamweaver");
            editor.getSession().setMode("ace/mode/json");
            editor.getSession().setUseWorker(false);
            editor.getSession().setUseWrapMode(true);
            var editor2 = ace.edit("input2");
            editor2.setTheme("ace/theme/dreamweaver");
            editor2.getSession().setMode("ace/mode/json");
            editor2.getSession().setUseWorker(false);
            editor2.getSession().setUseWrapMode(true);
            
            var container = document.getElementById("output");

            var result = new JSONEditor(container);

            var options = {
                mode: 'view'
            };
```

mode not working

**Comment by josdejong** [comment]
It could help to pass the options to the `JSONEditor` constructor.

**Comment by shahjehanali1** [comment]
i try but is not working

**Comment by josdejong** [comment]
Can you show me your code again?

**Comment by shahjehanali1** [comment]
`var xotree;
            var editor = ace.edit("input");
            editor.setTheme("ace/theme/dreamweaver");
            editor.getSession().setMode("ace/mode/json");
            editor.getSession().setUseWorker(false);
            editor.getSession().setUseWrapMode(true);
            var editor2 = ace.edit("input2");
            editor2.setTheme("ace/theme/dreamweaver");
            editor2.getSession().setMode("ace/mode/json");
            editor2.getSession().setUseWorker(false);
            editor2.getSession().setUseWrapMode(true);
            
            var container = document.getElementById("output");
            var mode = $('#mode').val();
            var options = {
                mode: mode,
            };

            var result = new JSONEditor(container, options);`

i want change the mode by select and options

[check screenshot](http://prntscr.com/amc2yu)

**Comment by josdejong** [comment]
That looks ok at first sight. I guess you will have to do a bit more debugging, and check how things are done in the examples: https://github.com/josdejong/jsoneditor/tree/master/examples

**Comment by josdejong** [comment]
Is this still an issue?
