### ISSUE TITLE
CSS is not well encapsulated and breaks on some pages

### ISSUE THREAD

**Issue by dumconstantin** [josdejong/jsoneditor#289]
When using on the same page with some CSS libraries the ``` jsoneditor ``` layout breaks.

I've setup an example using ``` materialize.css ``` of this happening here:
https://jsbin.com/feqoso/edit?html,output

**Comment by josdejong** [comment]
Argh, these frameworks like bootstrap and materialize are so invasive. 

Thanks for setting up a jsbin for demonstration, will fix it.

**Comment by dumconstantin** [comment]
Thanks also, it's excellent work you've been doing. I've been using jsoneditor for https://github.com/dumconstantin/baobab-jsoneditor and works great!

**Comment by josdejong** [comment]
This should be fixed now in v5.4.0 (just released)

**Comment by dumconstantin** [comment]
Excellent! Looking great, thank you very much!
