### ISSUE TITLE
UI changes on clicking on 'New'

### ISSUE THREAD

**Issue by jhaamit6666** [josdejong/jsoneditor#293]
On clicking on 'New', the UI changes.
![1](https://cloud.githubusercontent.com/assets/16834561/14557012/b374c050-0318-11e6-9bd4-ad33fdb7fe88.png)

**Comment by josdejong** [comment]
Thanks for reporting, wil fix it asap.

**Comment by josdejong** [comment]
This has been fixed in v3.7.0 of the web application.
