### ISSUE TITLE
Problem when writing a string

### ISSUE THREAD

**Issue by FansubDB** [josdejong/jsoneditor#294]
When writing, the focus go at the beginning of the box.

**How to reproduces:**
* Append a string, write the label.

Here a small gif (of 3 frames).
I try to write `st`.

![gif](https://cloud.githubusercontent.com/assets/9019185/14604588/b4bbdbc0-0574-11e6-8145-db954bcf04fe.gif)

**My conf**
I test on http://jsoneditoronline.org/ (version 3.7.1; so it use `jsoneditor` v5.5.1) with:
* Firefox beta 46.0b11
* Firefox developer 47.0a2
I don't see any warning/error message in console.

Thanks

*Edit: reproduce with name of array too*

**Comment by josdejong** [comment]
Thanks for reporting this bug, I can repeat it. It also occurs in Firefox 45 and only in the `field` input (not `value`).

**Comment by josdejong** [comment]
This is fixed in JSONEditor v5.5.2 and http://jsoneditoronline.org v3.7.2. Thanks again for reporting so quickly! This regression was introduced in v5.5.0 released two days ago.

**Comment by FansubDB** [comment]
No problem, thanks for fixing it so quickly too!
