### ISSUE TITLE
Is it possible to add tooltips/hints over the nodes and also have combo box selectors

### ISSUE THREAD

**Issue by linkavich14** [josdejong/jsoneditor#295]
Hi:

First I would like to congratulate you for an amazing Json editor that looks really great, and is functional, right now I am using in a project and I would like to incorporate some extra features that would be quite useful for the end user.

I would like to know how to add tooltips or hints to some nodes when there is a mouse over and also if it is possible to have have combo box selectors for some nodes instead of text entry. I would like to know where should I start looking in the code to make this improvements.

Thanks

**Comment by josdejong** [comment]
The code currently doesn't provision customizations like this. It would be great to make the code more flexible of course.
