### ISSUE TITLE
why did it has the Maximum allowed file size of 1048576 bytes when save it?please cancel the limit.

### ISSUE THREAD

**Issue by ChenWenQian** [josdejong/jsoneditor#296]
Error: Maximum allowed file size exceeded (1048576) bytes
 when i did my job , i create a file ,but the size is exceed 1M because the data in the file is large and complicate,    it limit me a lot .   i can't save it to local file.  but i need to save it .
please tell me how to deal with it ?  i have to save the file that exceed 2M or larger .it is important.
thank you

**Comment by josdejong** [comment]
Storing documents online with the web application is a free service. It has to have some limit to prevent misuse and keep the bills I have to pay for it acceptable. If you really need to store large and really important JSON objects online you will have to store it in some (cloud) database yourself, I'm sorry.

**Comment by ChenWenQian** [comment]
thank you. I want to save it to the local position，not the cloud，is there any method to save the json that large than 2M？local place.

**Comment by josdejong** [comment]
Hm. What browser are you using? When using for example Chrome browser, there should be no limit (it can use HTML5 a.download (see [http://jsoneditoronline.org/datapolicy.txt](http://jsoneditoronline.org/datapolicy.txt) -> section 3).

You could always manually copy the contents from the left panel, paste it in a local text editor, and save it to disk.

**Comment by ChenWenQian** [comment]
thank you very much，i will try chrome.
