### ISSUE TITLE
Switch mode button disappears

### ISSUE THREAD

**Issue by woto** [josdejong/jsoneditor#298]
Hi, in this example
https://github.com/josdejong/jsoneditor/blob/master/examples/03_switch_mode.html

when switched in "Code" mode and made error in json editor, then after clicking on "Form" error alert shows up and "Switch mode button" disappears.

![image](https://cloud.githubusercontent.com/assets/146704/15235048/bac97aae-18c0-11e6-89f0-9413e25adc1d.png)

```this.dom``` is null

Thanks.

**Comment by josdejong** [comment]
Thanks for reporting this bug, will fix it!
