### ISSUE TITLE
String values are always trimmed in tree mode

### ISSUE THREAD

**Issue by chvelkov** [josdejong/jsoneditor#299]
Hi,
The editor is awesome! Thanks for the great work!
However I upgraded from 4.xx to 5.xx and noticed that string values now are always trimmed and I didn't find a way to disable it.
Regardless of how the empty space is encoded (html entity, unicode) it's always removed.
Am I missing something?
I need the original string that the user enters (including whitespace).

**Comment by josdejong** [comment]
Thanks for bringing this up. I wrongly assumed that it's normally ok to trim values in order to get #268 fixed. It may be best to just revert this and leave #268 unfixed.

**Comment by chvelkov** [comment]
After some testing with unicode spaces and noticed that only the U+0020 gets trimmed.
The other (e.g. U+2004, U+2005, U+2006 ... more here [https://www.cs.tut.fi/~jkorpela/chars/spaces.html](https://www.cs.tut.fi/~jkorpela/chars/spaces.html)) are left intact. 

So a workaround that is acceptable in my case was to have utf8 encoding enabled in the editor and then let the users know explicitly to add the corresponding code when whitespace is desired. For example U+2005 has the same 1/4 em width.

**Comment by josdejong** [comment]
I've reverted trimming fields, will be fixed in the first next release.

**Comment by josdejong** [comment]
I've done a release right away, this has been fixed in v5.5.3
