### ISSUE TITLE
number of occurrences in a string should be displayed in right side panel

### ISSUE THREAD

**Issue by jhaamit6666** [josdejong/jsoneditor#301]
Number of occurrences in a string should be displayed in left side panel as marked in the snapshot.

Also, if the "find string" control is placed in the border of the panel where red coloured rectangle is marked, it would be good. It would be in line with other panel (right side panel- where the json is parsed).
![1](https://cloud.githubusercontent.com/assets/16834561/15346854/9ab3ffc4-1cd9-11e6-9676-03d3aa234ecd.png)

**Comment by josdejong** [comment]
Thanks for the suggestion, would be nice indeed to have the same seach UI for both panels. Unfortunately this would not be easy to do: the search of the left panel is powered by Ace editor, and the search functionality is integrated inside this editor and cannot easily be extracted. I doubt whether this will be worth the effort.
