### ISSUE TITLE
Two editors with same mode on the same page.

### ISSUE THREAD

**Issue by igorescobar** [josdejong/jsoneditor#303]
Have you ever tried to setup two editores with the same `mode`? In my case `mode: code`. The first one works and the second one only appears the `top-navbar`. If I change the mode to `view` for example everything works fine. Any help?

**Comment by josdejong** [comment]
Thanks for reporting this, I will look into it. Sounds like a bug in JSONEditor.

**Comment by igorescobar** [comment]
@josdejong What happened is that if you don't define a height and width on your own CSS the editor doesn't assume a default so only the navbar showed. Sounds stupid but it cost me a few hours to discover the WHY the editor wasn't fully showing up.

**Comment by igorescobar** [comment]
So its not a bug... maybe would be good to assume a default editor size in order to decrease the "initial setup" to make it work. What happened is that after a few hours I refactored my HTML/CSS and I changed the class name of the element and forgot to change the CSS.

**Comment by josdejong** [comment]
Ah, ok you're right. Sorry for the trouble. 

I've fixed collapsing of the editor by giving the contents a min-height of 150px (see https://github.com/josdejong/jsoneditor/commit/c2c7dd5adfbc8fae1bec3bb33b2703a93ea86174)

**Comment by josdejong** [comment]
(will be fixed in the first next release)

**Comment by igorescobar** [comment]
Yeah! That will do the trick! Thanks for putting your time to make this plugin available for us. I really appreciate your work and what you accomplished here. Many Thanks!

Enviado do meu iPhone

**Comment by josdejong** [comment]
You're welcome!
