### ISSUE TITLE
Initialization jsoneditor and ace (separate instance)

### ISSUE THREAD

**Issue by gebv** [josdejong/jsoneditor#309]
I have on the page separate instance jsoneditor and aceeditor.
jsoneditor seems like it overrides ace mode
ace is only supported in json, it ignores the `setMode('ace/mode/toml')`

I need that would be ace was in the mode toml. What I'm doing wrong?

``` javascript
<script src="//cdnjs.cloudflare.com/ajax/libs/jsoneditor/5.5.6/jsoneditor.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/ace/1.2.3/ace.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/ace/1.2.3/mode-toml.js"></script>
<!-- <script src="//cdnjs.cloudflare.com/ajax/libs/ace/1.2.3/mode-json.js"></script> -->
<script>
var textEditor = ace.edit("editorid");
textEditor.setFontSize("11pt");
textEditor.getSession().setMode("ace/mode/toml");
// textEditor.getSession().setMode("ace/mode/json");

var jsonEditor;
var container = document.getElementById("json_viewer");
// https://github.com/josdejong/jsoneditor/blob/master/docs/api.md
var options = {
    mode: "tree", // Available values: 'tree' (default), 'view', 'form', 'code', 'text'. In 'view' mode, the data and datastructure is read-only. In 'form' mode, only the value can be changed, the datastructure is read-only. Mode 'code' requires the Ace editor to be loaded on the page. Mode 'text' shows the data as plain text.
    modes: ["tree"],
    indentation: 4,
    // ace: ace,

    search: false,
    onChange: function() {
        document.getElementById("rawdata").value = JSON.stringify(jsonEditor.get()); 
    }
};
jsonEditor = new JSONEditor(container, options);
</script>
```

**Comment by josdejong** [comment]
JSONEditor indeed initializes ace with for example JSON mode ([see code](https://github.com/josdejong/jsoneditor/blob/master/src/js/textmode.js#L147-L158)).

Did you try to apply `.setMode` *after* creating the jsonEditor? That should work I think.

**Comment by gebv** [comment]
@josdejong thanks for the answer
I've found following problem:
If init ace after jsoneditor - ok
```
<script src="//cdnjs.cloudflare.com/ajax/libs/jsoneditor/5.5.6/jsoneditor.min.js"></script> 
<script src="//cdnjs.cloudflare.com/ajax/libs/ace/1.2.3/ace.js"></script>
```
![ok](https://s3.amazonaws.com/idheap/ss/Edit_fiddle_-_JSFiddle_2016-06-19_13-24-05.png)


If init ace before jsoneditor - error (another mode ace editor not supported)
```
<script src="//cdnjs.cloudflare.com/ajax/libs/ace/1.2.3/ace.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jsoneditor/5.5.6/jsoneditor.min.js"></script>
```
![not working](https://s3.amazonaws.com/idheap/ss/Edit_fiddle_-_JSFiddle_2016-06-19_13-26-09.png)

https://jsfiddle.net/p43xm63p/2/

**Comment by josdejong** [comment]
ah I see. Maybe you can use jsoneditor-minimalist which has `ace` excluded, so you don't get conflicts there? 

https://github.com/josdejong/jsoneditor/tree/master/dist
https://github.com/josdejong/jsoneditor/blob/master/dist/which%20files%20do%20I%20need.md

**Comment by tomalec** [comment]
@gebv if you are fine with Ace delivered by JSONEditor, instead of loading entire ace once again, you can just import additional modes you need:


```html
<script src="bower_components/jsoneditor/dist/jsoneditor.min.js"></script>
<script src="bower_components/ace-builds/src-noconflict/mode-toml.js"></script>
```

https://jsfiddle.net/n3v0hpup/

I know, that it's not the cleanest solution, but at least a workaround that worked for me

**Comment by warpech** [comment]
This is still a problem. Maybe this was already solved by current version of `brace`?

**Comment by josdejong** [comment]
I've just released v5.5.11 containing an example on using a custom version of Ace: [08_custom_ace.html](https://github.com/josdejong/jsoneditor/blob/master/examples/08_custom_ace.html). Does that maybe help or is this a different issue?

See also #351 which is related.

**Comment by josdejong** [comment]
Ah, it's indeed a different issue (overriding an already instantiated version of ace). @warpech can you check whether this is still the case in the latest v5.5.11 (I can't reproduce it)?

**Comment by warpech** [comment]
I guess this might be *some* solution, but actually the ideal solution was if the Ace editor used by JSONEditor did not pollute the global namespace (`window.ace` should stay undefined).

**Comment by josdejong** [comment]
Yeah, totally agree but this is how Ace works I'm afraid (doing everything via the global `window.ace`. I'm not sure whether [brace](https://github.com/thlorenz/brace) can prevent this from happening, we could open an issue there.

The issue will not occur when using jsoneditor-minimalist.js, but I see it's still the case when using the full version jsoneditor.js.

**Comment by josdejong** [comment]
I experimented a bit with the [ace/index.js](https://github.com/josdejong/jsoneditor/blob/master/src/js/ace/index.js) file in JSONEditor, where JSONEditor loads brace+plugins, see this commit: https://github.com/josdejong/jsoneditor/commit/717ed484743e583036c29e051b048275f3ba9e24

I think that will generally work, and it makes the option `ace` that we have now redundant :). The tricky part is that we now silently assume that the already loaded version of Ace contains the required plugins, and still has the same API, but well that's up to you.

As for preventing `window.ace` being defined by brace: that's not going to work, see https://github.com/thlorenz/brace/issues/12 :(.
