### ISSUE TITLE
Expose getter for internal instance of Ace editor

### ISSUE THREAD

**Issue by nucleartide** [josdejong/jsoneditor#317]
I'd like to customize JSONEditor's instance of Ace editor instead of passing in a new instance of the Ace editor, since passing in a new instance would require me to bundle Ace's source code into my app a second time. Do you think it'd be a good idea to provide a getter method for JSONEditor's Ace instance?

On a related note, it seems like the better API for the `ajv` option would be to pass an Ajv options object, instead of an entirely new Ajv instance (which would also require that I bundle Ajv's source code into my app a second time). But it's not something I need at the moment.

**Comment by nucleartide** [comment]
Now that I think about it, it would be a lot easier in Ember/React to pass down a configuration function, like with `onEditable`.

**Comment by josdejong** [comment]
Though it's not part of the official, you can access the internal ace instance via `editor.aceEditor`

**Comment by nucleartide** [comment]
Oh, that's useful...thanks!
