### ISSUE TITLE
Use schema titles as field names and descriptions as tooltips

### ISSUE THREAD

**Issue by nevez** [josdejong/jsoneditor#321]
Hi!

I've used your editor as a configuration editor in my web application. I needed the field text to be more descriptive, so I thought about using the "title" and "description" field of json schemas as field names and tooltips.

I've changed very few lines of code (diff attached below). The field itself is not changed, only the way it appears on screen. Sorting and searching also work. I've added two configuration options "showTitles" and "showDescr" to activate the behaviour.

The only significant change is the move of the _updateSchema() call from the updateDom() function to the appendChild() function. In the end I think that's a better place to put it anyway (unless I'm missing something).

Will you accept it as a patch?

Thank you for your great work

EDIT: Updated patch, had whitespace issue.
EDIT2: Updated patch again...changed blur() function.

[node_diff.txt](https://github.com/josdejong/jsoneditor/files/445291/node_diff.txt)

**Comment by josdejong** [comment]
Thanks for sharing @nevez.

Using the JSON schema description as tooltip is nice, would be great to add that. Just thinking, this maybe doesn't even need an option. A PR would certainly be welcome and we could discuss the details there. 

Replacing the fields with titles from the JSON schema sounds a bit weird to me. I would rather generate the JSON structure beforehand based on the schema, and then load both into the JSONEditor (maybe in `form` mode).

**Comment by lucraeskin** [comment]
This would be a great feature! Is there a pull request?

**Comment by josdejong** [comment]
No, so far nobody jumped onto implementing this and I haven't had time for it myself either.

**Comment by thrkmmr** [comment]
I am currently using the following code to achieve this (I know it is grossly inefficient)

    // Show schema discriptions as tooltips.

    function setDescription(element, node) {
        if(node.dom.tdField === element) {
            if(node.schema) {
                jQuery(node.dom.tdField).attr('title', node.schema.description)
                return true
            }
        } else {
            for(var n in node.childs) {
                if(setDescription(element, node.childs[n])) {
                    return true
                }
            }
        }
        return false
    }

    jQuery(document).ready(function() {
        jQuery(document).on('mouseenter', '.jsoneditor-tree', function() {
            setDescription(this, editor.node)
        });
    })

**Comment by josdejong** [comment]
Thanks for sharing @thrkmmr !

**Comment by josdejong** [comment]
Document titles are now available in `v5.29.0` thanks to @AdamVig.
