### ISSUE TITLE
could you help me?

### ISSUE THREAD

**Issue by wentin** [josdejong/jsoneditor#324]
yesterday I was doing some learning with reactjs, didn't realize the sample code i used had a interval going on every 2 seconds, calling json data from jsoneditor, as a result I am blocked since yesterday. 
![image](https://cloud.githubusercontent.com/assets/2474904/18640953/73b92f3e-7e68-11e6-8ac2-82905ff73ed9.png)

**Comment by josdejong** [comment]
Well, basically you'll have to wait max one day until the daily limit is reset. For once I've reset the daily limits right now so you should be good to go again.

**Comment by wentin** [comment]
👍 thanks!
