### ISSUE TITLE
Unable to write Polish characters

### ISSUE THREAD

**Issue by kolorafa** [josdejong/jsoneditor#325]
Characters  "ęż" are writed using AltGr (Ctrl+Alt), and somehow when you click Ctrl+Alt+Z the editor wrongly executes undo (Ctrl+Z). The same with E.

**Comment by josdejong** [comment]
Thanks for reporting! Is this happening in the code editor on the website http://jsoneditoronline.org (left panel) or somewhere else?

**Comment by kolorafa** [comment]
The right panel and only on Windows, on Linux works normally only because on linux AltGr != Ctrl+Alt

But still if you click Ctrl+z or Ctrl+Alt+z - both shortcuts do "undo" (and only Ctrl+z should do undo)

On windows .... typing Ctrl+Alt is the same as AltGr that ends up with unable to type ż and ę on Windows in the right "Form" view.

**Comment by josdejong** [comment]
Ah, thanks for the extra info, that gives me a clue where to look.

**Comment by josdejong** [comment]
Not sure if this is still an issue. Will close now because of inactivity. Feel free to reopen if needed.
