### ISSUE TITLE
Can't load json from URL having parameters in query string

### ISSUE THREAD

**Issue by hriziya** [josdejong/jsoneditor#327]
I tried to get json from URL like http://domain.com/page.php?a=b&c=d 
It just load the last cached json on screen instead making call to URL.

Any solution?

**Comment by josdejong** [comment]
There is no magic in how JSONEditor loads a document from URL, it simply does an HTTP GET request. It doesn't do any caching itself, so this could be either something in your browser or on the server side or something.

**Comment by hriziya** [comment]
Lets try following URL to load it editor -> Open -> Open URL menu. 
http://ip.jsontest.com/?abc=xyz
https://jsonplaceholder.typicode.com/posts?test=test

then try to load it without parameters
http://ip.jsontest.com/
https://jsonplaceholder.typicode.com/posts

**Comment by josdejong** [comment]
Thanks, I see the problem now. Will fix this within a few days.

**Comment by josdejong** [comment]
This has been fixed now in the web application (version 3.7.5, displayed at the bottom)
