### ISSUE TITLE
in tree view Object prototype properties are always reported as duplicate keys

### ISSUE THREAD

**Issue by sonnyp** [josdejong/jsoneditor#329]
Load

`
{
   "watch": "foo"
}
`

In code view no error is reported.
In tree view the `watch` property is reported as a duplicate key.

**Comment by josdejong** [comment]
Thanks for reporting. I tried to reproduce your case but without success so far. 

What are the exact steps to reproduce this issue?

**Comment by sonnyp** [comment]
@josdejong http://jsoneditoronline.org/?id=eb800f9d2aff48a05c56baa5abe9e8b7

Check the tree view, "watch" property is considered a duplicated key.

Only happens in Firefox because of https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/Object/watch

A simple hasOwnProperty should fix the issue.

**Comment by josdejong** [comment]
ah, now I see, thanks! 

This is indeed easy to fix.

**Comment by josdejong** [comment]
This has been fixed in the latest version, jsoneditor 5.5.9. 

The website http://jsoneditoronline.org is also update (you will have to refresh your browser once, if you see v3.7.4 at the bottom you're up to date).

**Comment by sonnyp** [comment]
@josdejong thanks!
