### ISSUE TITLE
Space is taken too much in case of numbers

### ISSUE THREAD

**Issue by ranjan-ranjan** [josdejong/jsoneditor#332]
Isn't the portion marked in the snapshot taking too much space (yellow colour)?
![1](https://cloud.githubusercontent.com/assets/16834561/19618331/ee159590-9864-11e6-9aa3-1811ded8cb46.png)

**Comment by josdejong** [comment]
Do you mean in horizontal or vertical direction? The input field has a minimum width in horizontal direction to prevent the field from getting too small, which would make it hard to see and select the field.

**Comment by ranjan-ranjan** [comment]
horizontal direction. in other cases its not too small.

**Comment by josdejong** [comment]
OK. The horizontal direction has a minimum width of 32 pixels to prevent it from getting too small to be practically usable when it's contents is empty or just contains a few characters (like often is the case for numbers). This has done intentionally.
