### ISSUE TITLE
expandAll option

### ISSUE THREAD

**Issue by rossjha** [josdejong/jsoneditor#333]
Would it be possible to add expandAll as an option?  I don't think it's an option currently?  Would be useful on load and mode change, where applicable.

**Comment by josdejong** [comment]
Yeah we could think about that. It sounds a bit like duplicate functionality though. 

After a load you can immediately call `expandAll()` yourself, that just works fine right? 

The issue with mode change is that there is no mode change callback. If we would have that, you could call `expandAll()` after a mode change.

**Comment by rossjha** [comment]
Thanks, yeah I've tested that out and it works fine.  I'm using the [ember-jsoneditor](https://github.com/Glavin001/ember-jsoneditor) addon, so it feels like it would be easier as an option.  If the option is set, could this be called on mode change?

**Comment by josdejong** [comment]
I'm working on a new version of JSONEditor where I'm thinking about changing the API such that you always have to call `editor.set(json)` to set json and can pass additional options:

```js
const editor = jsoneditor(container, options)
editor.set(json, options)   // in the options you can pass a custom `expand` function

// for example:
editor.set(json, {
  expand: function (path) {
    return path.length == 0    // only expand the root node
  }
})

// or:
editor.set(json, {
  expand: function (path) {
    return true    // expand all
  }
})
```

The `expand` option is only applicable when setting json, so it makes sense to tie this option to the `set()` method, this gives the most flexibility on low level. The new version also has a `patch()` method which allows you to update the editor without losing it's current state.

A declarative framework like ember/react/angular would have to call `set` internally after construction of the editor. It should allow passing `expand` either via the general options or as a separate option somehow. It could also introduce an `onLoad` callback allowing you to call for example `expandAll()` right after the editor is loaded the first time. It's up to the wrapper library.

BTW I just had a look at the [demo page](http://blog.glavin.org/ember-jsoneditor/) of ember-jsoneditor. It seems like it doesn't really work: as soon as I type a character in the editor, the input loses focus. Is it just me?

**Comment by rossjha** [comment]
Sounds great, the editor is awesome, thanks for your hard work!  Re `ember-jsoneditor`, it does work.  It needs updated, but it's working okay for now.

**Comment by vineela-m** [comment]
When I tried to use expand function, I got the following warning "Unknown option "expand". This option will be ignored". I'm using latest version 5.10.1. Any help is appreciated

**Comment by josdejong** [comment]
@vineela-m the code example I posted above is a proposal, this expand function does not exist. There is a method `.expandAll()` though, is that what you mean? 

Checkout the docs: https://github.com/josdejong/jsoneditor/blob/master/docs/api.md

**Comment by vineela-m** [comment]
@josdejong I've mistaken your proposal as existing feature. expandAll will expand all nodes, But I want to expand only root node. Hope your proposal goes into development

**Comment by josdejong** [comment]
Yes, working on it but it will still take a long time.
