### ISSUE TITLE
Is it possible to send json via http get request ? 

### ISSUE THREAD

**Issue by azakordonets** [josdejong/jsoneditor#334]
Hi, 

I was wondering if it's possible to paste some GET URL to your editor to be able to paste the JSON data into the viewer. I have simple scenario that i would like to implement with python : 
1. Make API request and get json response
2. Take this JSON response and with ```python -m webbrowser -t "http://jsoneditoronline.org?{JSON}"``` open your editor in the browser automatickally

In that way i would avoid all the copy-pasting and just run one script that would do all the work for me. 

Thanks.

**Comment by josdejong** [comment]
Yes you can do that with a query parameter `json`, for example:

http://jsoneditoronline.org/?json={%22name%22:%22John%22,%22age%22:32}

See docs: http://jsoneditoronline.org/doc/index.html#query_parameters

**Comment by azakordonets** [comment]
Perfect, thank you so much :)

**Comment by josdejong** [comment]
:+1:

**Comment by davron112** [comment]
But in GET request, the length of a URL is limited (maximum URL length is 2048 characters)

**Comment by josdejong** [comment]
That's correct. The maximum url length varies per browser but is about 2000 bytes in worst case. For larger documents you could upload your JSON file at some public url yourself, and pass the url:

```
http://jsoneditoronline.org/?url=...
```

See docs: http://jsoneditoronline.org/doc/index.html#query_parameters

**Comment by BrunyC** [comment]
Guys. I need some help. Someone can tell me how can i make a request to api without params? Exemple: exmple/login.json works. 
How i make works without .json?

**Comment by josdejong** [comment]
@BrunyC I don't understand what you mean.
