### ISSUE TITLE
Set ace theme

### ISSUE THREAD

**Issue by rossjha** [josdejong/jsoneditor#335]
How do you set the ace theme?  `options.theme` seems to remove the path? So `/ace/theme/github` becomes `/theme-github`?

**Comment by josdejong** [comment]
The path is not changed, and you should indeed pass a path like `/ace/theme/github`. 

You have to load the theme first in your browser though, it's not bundled with JSONEditor.

Here an example: http://jsbin.com/fehafe/edit?html,output

**Comment by josdejong** [comment]
Is this still an issue? I will close it now, feel free to reopen if needed.

**Comment by anshulkatta** [comment]
I need to use mode tree and apply theme to it...its not working..there is no setTheme function seems there is a condition in code that for mode tree the object is initialized differently

**Comment by josdejong** [comment]
Gordon I guess you found a solution looking in #677
