### ISSUE TITLE
Customize object names

### ISSUE THREAD

**Issue by chromey** [josdejong/jsoneditor#339]
I'd like to have the possibility to customize what is rendered as the name of a collapsed object. For example, if I have an array with lots of objects with an identifying field such as 'id' or 'name', I'd rather display that instead of the default field count.

I have created a PR that accomplishes this with a callback "onObjectName" that can be passed as an additional option. The callback gets handed the object's path and child nodes. Returning null from the callback falls back to displaying the field count.

https://github.com/josdejong/jsoneditor/pull/338

Awesome project btw, keep going!

**Comment by josdejong** [comment]
Nice idea, I like it. this way you can give a more informative summary of what's in an object.

Your PR looks neat. A few remarks:
- Would it be interesting/consistent/useful to allow setting the name of Arrays too? 
- Can you describe the new feature in `docs/api.md` too?

**Comment by josdejong** [comment]
@chromey any news on this?

**Comment by chromey** [comment]
I realized that my implementation has an issue with the editor's lifecycle. That is, the object's name would not update when its properties change. Probably easy to fix, but it disappeared in my backlog.
Will look into it as soon as I find a minute.

**Comment by josdejong** [comment]
Thanks for your feedback. Would be nice if you could find a fix for that. If it becomes too complicated, it may be interesting to see whether this will be easier to implement in the upcoming v6 which is a complete rewrite (see #337).

**Comment by bnanchen** [comment]
Hi,
Any news about this issue? Has it been finalized? Will it be implemented in v6?
I've only found a PR (#338) with the last commit in November 2016.

**Comment by bnanchen** [comment]
I've opened PR #617 concerning this issue.
