### ISSUE TITLE
BIG INT issue

### ISSUE THREAD

**Issue by joarleymoraes** [josdejong/jsoneditor#341]
When the raw json contains BIG INT fields, the tree editor rounds the value. See screenshot for field `media_id`.

![captura de tela 2016-11-25 as 11 54 36](https://cloud.githubusercontent.com/assets/8397645/20628741/8dae4bea-b306-11e6-83cf-51990e1cf396.png)

**Comment by josdejong** [comment]
Thanks for reporting! This is a duplicate of #231, let's continue any discussion there.
