### ISSUE TITLE
Error compiling schema on .NET Web Application

### ISSUE THREAD

**Issue by francisconora** [josdejong/jsoneditor#343]
I am integrating JSON Editor in a C# Web Application. 

When publishing the application, JSON Editor does not load and I receive the following error on the console:

"Error compiling schema, function code: var refVal1 = refVal[1]; validate =  (function  (data, dataPath, parentData, parentDataProperty) { 'use strict'; var vErrors = null;  var errors = 0;         var errs_1 = errors;    var errs_2 = errors; if (typeof data === "number") {    if (  data < 0) { var err =  { keyword: 'minimum' , dataPath: (dataPath || '') + "" , schemaPath: "#/definitions/positiveInteger/minimum" , params: { comparison: '>=', limit: 0, exclusive: false }  , message: 'should be >= 0' , schema:  0         , parentSchema: refVal[1] , data: data  } ;  if (vErrors === null) vErrors = [err]; else vErrors.push(err); errors++;  }   }  if ((typeof data !== "number" || (data % 1))) {    var err =  { keyword: 'type' , dataPath: (dataPath || '') + "" , schemaPath: "#/definitions/positiveInteger/type" , params: { type: 'integer' }  , message: 'should be integer'  , schema: refVal[1].type , parentSchema: refVal[1] , data: data  } ;  if (vErrors === null) vErrors = [err]; else vErrors.push(err); errors++;  } var valid2 = errors === errs_2;   var valid1 = errors === errs_1;    validate.errors = vErrors;  return errors === 0;        });"

After further investigation, I notice that this happens when the flag "debug" is not set as true in the Web.config file in the following node from system.web section:
<compilation debug="false" targetFramework="4.5.2" />

**Comment by francisconora** [comment]
Aparently the error is not on the jsonEditor itself.

Problem solved

**Comment by francisconora** [comment]
Sorry to bother, but apparently the issue appeared again. 

I was defining the schema via the angular directive, but when using the setSchema method, the same error appears. The schema I'm trying to use is the following:

{
	"title" : "Schema Example",
	"type" : "object",
	"required" : [
		"Field1",
		"Field2",
		"Field3",
		"Field4",
	],
	"properties" : {
		"Field1" : {"type" : "string", "minLength" : 1},
		"Field2" : {"type" : "boolean"},
		"Field3" : {"type" : ["string", "null"], "minLength" : 1},
		"Field4" : {"type" : "string",	"minLength" : 1}		
	}
}

**Comment by josdejong** [comment]
First, try to isolate the error. See whether it's related to your .Net stuff, Angular stuff, JSONEditor, of the JSONSchema library used by JSONEditor: ajv.

The error "Error compiling schema" can be thrown by the ajv library, so that might give a clue. See whether you can reproduce this issue with just ajv (without JSONEditor) and whether it still happens without angular or .Net.

**Comment by francisconora** [comment]
Aparently the issue was caused by the Ajv, by creating a new Ajv (external to JsonEditor), everything is working correctly.

For me you can close this issue.

Thanks for the help

**Comment by josdejong** [comment]
Good to hear you've solve the issue!
