### ISSUE TITLE
Copy pasting a value for the JSON field from some source results in Error in the console

### ISSUE THREAD

**Issue by AshayTikekar** [josdejong/jsoneditor#344]
Hi,
On copy pasting certain value for a field in json (when editor is in the tree mode) results in the following error:
Error: Parse error on line 1:
"\n\n\n<!--\n /* Fon
^
**Expecting 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '[', got 'undefined'**

All I copied was following highlighted in yellow:

![issue](https://cloud.githubusercontent.com/assets/15188592/20918675/4514b02a-bbbe-11e6-8fdc-f698b210026c.PNG)

**Comment by josdejong** [comment]
hm, that's interesting. I expect that there where some special characters or something in de text that you pasted. Can you share the exact text that caused this error in a code block (enclosed by two pairs of triple backticks \`\`\` ... \`\`\`)?

**Comment by AshayTikekar** [comment]
The text was copied from skype . I checked in XVI32 hex editor as well but found no special characters 
added while copying.
The exact text copied is :

```yes```

**Comment by AshayTikekar** [comment]
The only way to reproduce the issue is to  copy the text from skype.
And yes it happens every time i try to copy from skype.
The issue gets solved if I try to copy from skype > paste it in some text editor > copy it from the text editor > paste it in the jsoneditor
But thats some unusual behaviour since no special characters are added

**Comment by josdejong** [comment]
I just tried to reproduce this issue by copying some text from Skype to JSONEditor, but no luck so far. I tried both selecting some text typed by somebody and pasting that as well as right click -> copy message.

I've tried with Skype 7.12.0.101 on Windows 10 and JSONEditor opened in Chrome. What are you using?

**Comment by AshayTikekar** [comment]
I am using skype 7.30.0.105 on windows 10 and JSONeditor in chrome

**Comment by josdejong** [comment]
I've updated my Skype to the latest version (same as you) and tried to reproduce but no luck. I'm afraid I can't do anything as long as I can't reproduce it :(
