### ISSUE TITLE
Search across multiple editors?

### ISSUE THREAD

**Issue by pchaganti** [josdejong/jsoneditor#345]
Any pointers or suggestions on searching across multiple editors with one search box? 

thanks!

**Comment by josdejong** [comment]
You could turn the search box of the individual editors off (option `{search: false}`). Then you create a separate search box yourself (a simple `<input>` or something) and when pressing search, call the function `editor.search('hello world')`.

Note that the function `search` is not part of the public API so it's not guaranteed to be available in future versions.

**Comment by pchaganti** [comment]
Got it. Thx for the tip!
