### ISSUE TITLE
Editor body gets smashed/shrinks after form submit

### ISSUE THREAD

**Issue by starmandeluxe** [josdejong/jsoneditor#346]
After the page refreshes from a form submit, the editor doesn't fully display again, instead it only shows 2-3 times at a time while scrolling even though there is plenty of space in the parent text area.

Before submit:

![image](https://cloud.githubusercontent.com/assets/1654255/21299260/220f16d2-c5dd-11e6-84e2-cf37a5e96460.png)

After submit:

![image](https://cloud.githubusercontent.com/assets/1654255/21299228/e0c02392-c5dc-11e6-9e81-c3addf527dfa.png)

**Comment by josdejong** [comment]
Thanks for reporting. How can I reproduce your issue? (can you create a jsbin/jsfiddle to demonstrate it?)

**Comment by starmandeluxe** [comment]
Unfortunately it wouldn't be possible in jsfiddle because it's a Razor page. But it looks like it simply sets the inner html of a message div on the page, then calls "window.scrollTo(0, 0);" on the submit() post success.

**Comment by starmandeluxe** [comment]
OK, the solution was to set the amount of lines in maxLines to the exact height of the json editor css height.  In my case, the height was 400px and 22 maxLines did the trick. Strange but at least I can close this issue.

**Comment by josdejong** [comment]
Ok thanks for the feedback. I guess it's something in the Ace editor but I don't have a clear idea on the cause either.
