### ISSUE TITLE
jsoneditor-menu does not respond to click

### ISSUE THREAD

**Issue by turigeza** [josdejong/jsoneditor#347]
I have found that I the json editor bar is not clickable. 

The buttons "Expand all fields", "Collapse all fields" and the search bar (So jsoneditor-menu div) is covered up by the div following it jsoneditor-outer. 

In my case this was because of the css code below which was in my css file.

`
div{
    position: relative;
}
`

Removing that or adding 
`
.jsoneditor-menu, .jsoneditor-outer{
    position: static;
}
`

solves this issue.

It really is not a major issue just posting because it might save some headache for others. 

Thank you for all the work 👍  :)

**Comment by josdejong** [comment]
Thanks, easy to make this CSS a bit more robust.
