### ISSUE TITLE
Event parse Text error

### ISSUE THREAD

**Issue by mvtcode** [josdejong/jsoneditor#348]
I setup 2 modes **text** and **tree**,
When i switch mode text, edit json error, and switch mode tree not notification and event.
I show **deverloper tools** see error, but the user will not know this action.
please add event _error_ when JSON.parse error!

**Comment by josdejong** [comment]
You can use the `onError` callback for catching these errors, see docs: https://github.com/josdejong/jsoneditor/blob/master/docs/api.md#configuration-options
