### ISSUE TITLE
home.json

### ISSUE THREAD

**Issue by PisethApk12** [josdejong/jsoneditor#349]
[{"title":"Taylor Swift - I Knew You Were Trouble (Exclusive)","number_of_views":319644991,"thumbnail_image_name":"https://s3-us-west-2.amazonaws.com/youtubeassets/taylor_swift_i_knew_you_were_trouble.jpg","channel":{"name":"Taylor Fan Forever","profile_image_name":"https://s3-us-west-2.amazonaws.com/youtubeassets/taylor_fan_forever_profile.jpg"},"duration":210},{"title":"Rihanna Work featuring Drake","number_of_views":92839921,"thumbnail_image_name":"https://s3-us-west-2.amazonaws.com/youtubeassets/rihanna_work.jpg","channel":{"name":"Rihanna's Channel","profile_image_name":"https://s3-us-west-2.amazonaws.com/youtubeassets/rihanna_profile.jpg"},"duration":189},{"title":"Beyonce - Put A Ring On It","number_of_views":52321223,"thumbnail_image_name":"https://s3-us-west-2.amazonaws.com/youtubeassets/beyonce_put_a_ring_on_it.jpg","channel":{"name":"Taylor Fan Forever","profile_image_name":"https://s3-us-west-2.amazonaws.com/youtubeassets/beyonce_profile.jpg"},"duration":410},{"title":"Kanye Interrupts Taylor Embarrassing Video","number_of_views":9999999999999,"thumbnail_image_name":"https://s3-us-west-2.amazonaws.com/youtubeassets/kanye-interupts-taylor-zoom.jpg","channel":{"name":"KanyeLover","profile_image_name":"https://s3-us-west-2.amazonaws.com/youtubeassets/kanye_profile2.jpeg"},"duration":80},{"title":"Rebecca Black - Friday","number_of_views":12312344,"thumbnail_image_name":"https://s3-us-west-2.amazonaws.com/youtubeassets/rebecca_black_friday.jpg","channel":{"name":"Rebecca Black's Awesome","profile_image_name":"https://s3-us-west-2.amazonaws.com/youtubeassets/rebecca_black_profile.jpeg"},"duration":232},{"title":"John Legend - All Of Me","number_of_views":334435123,"thumbnail_image_name":"https://s3-us-west-2.amazonaws.com/youtubeassets/john_legend_all_of_me.jpg","channel":{"name":"JohnTheLegend","profile_image_name":"https://s3-us-west-2.amazonaws.com/youtubeassets/john_legend_profile.jpeg"},"duration":301}]

**Comment by josdejong** [comment]
@PisethApk12 why are you pasting this JSON document here? Do you have a question or bug report or something?
