### ISSUE TITLE
how to resize the jsoneditor window when change mode to code

### ISSUE THREAD

**Issue by crazier** [josdejong/jsoneditor#350]
how to resize the jsoneditor window when change mode to code
when the json data contain many fiedls, the tree mode while resize the window to show all data,
but when change mode to code, it's too small and can't auto resize the window

**Comment by josdejong** [comment]
Does the DIV container of your editor have a height defined (like `400px` or `100%`)? 

Probably related to #211.

**Comment by SwapnilChidrawar** [comment]
Thanks for quick reply. yes DIV container of my editor have height defined 100% and this one is coming directly from ang-jsoneditor library . I tried giving height from my component but still did not get any success.

**Comment by josdejong** [comment]
That's a bummer that you can't get any height defined. I think 100% height only works when all parent DIV's have a height defined. In the worst case you'll have to define a fixed height instead, or plug in some JavaScript to adjust the height correctly or something like that.
