### ISSUE TITLE
npm ajv version conflict

### ISSUE THREAD

**Issue by asvae** [josdejong/jsoneditor#352]
Jsoneditor `"ajv": "3.8.8"` conflicts with webpack 2, which is `"ajv": "^4.7.0"`, and probably some other libraries.

[ajv 4.0](https://github.com/epoberezkin/ajv/releases?after=4.4.0) doesn't seem to have a ton of breaking changes. An neither does [webpack 2](http://javascriptplayground.com/blog/2016/10/moving-to-webpack-2/).

I'm also willing to contribute on the matter if that's wanted.

*BTW using exact versions in npm libraries is not the best approach IMO. If you need to test specific configuration — `npm shrinkwrap` exists for that purpose.*

**Comment by josdejong** [comment]
Thanks for bringing this up @asvae, I wasn't yet aware of any incompatibilities with webpack 2. Is this a matter of upgrading both ajv and webpack 2 to the latest versions?

It would be great if you could help out here. Using npm schrinkwrap sounds good too, npm isn't entirely deterministic if I understand it correctly.

**Comment by asvae** [comment]
Worth noting that gulp won't build on windows and gives `Error: spawn UNKNOWN`. On linux it's 'all green'.

**Comment by josdejong** [comment]
> Worth noting that gulp won't build on windows and gives Error: spawn UNKNOWN. On linux it's 'all green'.

Thanks, turns out `gulp-multi-process` does not work correctly on Windows. I've reported here: https://github.com/juanfran/gulp-multi-process/issues/3

**Comment by epoberezkin** [comment]
It makes sense to migrate to 5.0.1-beta or wait until 5.0.0 is out (when JSON-schema draft 6 is published). It's now more webpack-friendly...

**Comment by josdejong** [comment]
Thanks Evgeny, good to hear! As long as jsoneditor v6 itself is beta it's perfectly fine with me to use ajv v5 beta too.

**Comment by josdejong** [comment]
The windows problem with `gulp-multi-process` should have been fixed now.

**Comment by asvae** [comment]
@josdejong except for it's probably `0.0.4` as last commit informs me that
```
No compatible version found: gulp-multi-process@0.4.0
```
: 3

**Comment by josdejong** [comment]
oops my mistake, should be fixed now
