### ISSUE TITLE
Can't open the web site by Safari on macOS 10.12

### ISSUE THREAD

**Issue by FongRay** [josdejong/jsoneditor#357]
Am I the only one to meet this?
I got an error: `408 Request Timeout` whether using `http` or `https` by Safari, but Firefox or Chrome is OK.
![qq20170120-175655](https://cloud.githubusercontent.com/assets/5010519/22144769/da671d9a-df39-11e6-88d4-a4a71538764a.png)
And I tried to trust the certification in `Keychain Access`, but still not work.
![qq20170120-180059](https://cloud.githubusercontent.com/assets/5010519/22144955/6b6dd158-df3a-11e6-9111-5b3ec2cefbc5.png)

**Comment by josdejong** [comment]
hm, I haven't heard of this issue before, I'm not sure how I can help you with this.

**Comment by josdejong** [comment]
Is this still an issue?

**Comment by FongRay** [comment]
em..I use chrome instead of safari now.

**Comment by josdejong** [comment]
I've tried Safari 8, 9, and 10, all seems to work fine. Chrome works fine too :)
