### ISSUE TITLE
Add readOnly for mode=code

### ISSUE THREAD

**Issue by cope** [josdejong/jsoneditor#360]
We are adding the 'jsoneditor-readonly' class to make the jsoneditor look like mode=code, but readOnly.

It would be nice if there was a _proper_ way to accomplish this, as well as to specify a readOnly theme. For example, I would love to use eclipse theme for regular code mode, and then dawn theme for code mode which would then be readOnly=true...

One [can see here](https://ace.c9.io/build/kitchen-sink.html) that the Ace editor has readOnly as an option. It would be nice if this was also available in the jsoneditor.

**Comment by josdejong** [comment]
If you want to do custom configuration of the Ace editor that JSONEditor uses when in mode `code`, you can do so in two ways:

- Provide your own instance of Ace via the option `ace` ([see docs](https://github.com/josdejong/jsoneditor/blob/master/docs/api.md#configuration-options)).
- When the editor is in mode `code`, you can access the internal Ace editor via `editor.aceEditor`.

Does that help?

**Comment by cope** [comment]
Yes! Awesome, thanks!

Closing.

**Comment by CicherMK** [comment]
@cope **_how do you achieve it?_**... I was trying to pass an instance of Ace via the `ace` option, but to instantiate it seems to need a `div` element 🤔

**Comment by josdejong** [comment]
@CicherMK did you see the https://github.com/josdejong/jsoneditor/blob/develop/examples/08_custom_ace.html example?

**Comment by CicherMK** [comment]
Thanks @josdejong for your response !

I forgot to mention that I'm using [jsoneditor-react](https://github.com/vankop/jsoneditor-react), which in turn uses the [brace](https://github.com/thlorenz/brace) version of Ace Editor.

Anyways, checking [Ace Editor's documentation](https://ace.c9.io/#nav=embedding), it says that you need to pass the `id` of the DOM's containing element:

![Imgur](https://i.imgur.com/RO12hzr.png)

But:

![Imgur](https://i.imgur.com/LaVVpJj.png)

🤔

**Comment by josdejong** [comment]
JSONEditor creates it's own instance of Ace editor because it has to bind it to a DIV element that is created by JSONEditor itself. Looking at the [package.json of react-jsoneditor](https://github.com/vankop/jsoneditor-react/blob/master/package.json#L74) it looks like it uses `jsoneditor@7.1.0`, which switched from `brace` to `ace-builds`, so it should not rely on `brace` anymore.

What you can probably do is pass your own `edit` factory function to work around any difference between differing versions of ace, like: 

```jsx
render() {
  const myAceFactory = {
    edit: function (domElement) {
      // create your own Ace instance, bind it to the provided DOM element, return it
    }
  }

  return (
    <Editor
      ace={myAceFactory}
      // ...
    />
  )
}
```

**Comment by CicherMK** [comment]
Thanks @josdejong !!, it works! 🤓🤙

The only thing, I had to use an ugly `setTimeout`:
![Ugly setTimeout](https://i.imgur.com/Uj1YOBA.png)
otherwise, it just not works.... maybe is not the nicest approach, but I can live with that 😜
(at least for now)

**_Thanks!!_**

**Comment by josdejong** [comment]
👍 thanks for sharing your solution!
