### ISSUE TITLE
Add highlightActiveLine support

### ISSUE THREAD

**Issue by cope** [josdejong/jsoneditor#361]
One [can see here](https://ace.c9.io/build/kitchen-sink.html) that the Ace editor has highlightActiveLine as an option. It would be nice if this setting was also available in the jsoneditor.

Or maybe I missed something in the [API Reference](https://github.com/josdejong/jsoneditor/blob/master/docs/api.md)?

**Comment by josdejong** [comment]
See my reply here: https://github.com/josdejong/jsoneditor/issues/360#issuecomment-277521662

Please note thought that JSONEditor by defualt has `highlightActiveLine` configured true, the active line has a light yellow background color.

**Comment by cope** [comment]
The [#360 (comment)](https://github.com/josdejong/jsoneditor/issues/360#issuecomment-277521662) helped!

Closing.
