### ISSUE TITLE
Scroll wheel not working with 'jsoneditor-readonly' css class

### ISSUE THREAD

**Issue by cope** [josdejong/jsoneditor#362]
We are adding the 'jsoneditor-readonly' class to make the jsoneditor look like mode=code, but readOnly.

When we do this, the scroll-wheel is no longer working in that jsoneditor.

We can still scroll, but only by dragging the scrollbar up and down.

Maybe this should go along with #360 ?

**Comment by josdejong** [comment]
Thanks for reporting.

Giving the editor in example [02_viewer.html](https://github.com/josdejong/jsoneditor/blob/master/examples/02_viewer.html) a height of say 250px and expanding it's contents gives a vertical scrollbar and a normally functioning scroll wheel.

How can I reproduce this issue?

**Comment by cope** [comment]
My bad. I didn't realize that my colleague was adding the 'jsoneditor-readonly' class to the component that contains the jsoneditor, and not to jsoneditor directly.

Closing issue.

**Comment by josdejong** [comment]
:+1:
