### ISSUE TITLE
Window onResize bug with 'jsoneditor-readonly' css class

### ISSUE THREAD

**Issue by cope** [josdejong/jsoneditor#363]
We are adding the 'jsoneditor-readonly' class to make the jsoneditor look like mode=code, but readOnly.

I noticed a weird behavior in this case, on window resize. Namely, if the window is small and then maximized, the jsoneditor resizes externally, but not internally.

The best way to describe it is with a screenshot:
![fusion architect_2017-02-03_12-38-12](https://cloud.githubusercontent.com/assets/112515/22590131/0604435e-ea0e-11e6-8cba-7575344c5cce.png)

As you can see, only the lines that were visible prior to window resizing are the ones still visible. The lines below remain hidden, even though the scrollbar is properly resized.

If I resize it again, it fixes. But then once more and it is broken again.

It seems like on every first resize it breaks, and on the next one it gets fixed again.

**Comment by josdejong** [comment]
Does this behavior also occur in JSON Editor without the changes you did with the `jsoneditor-readonly` class, or has it to do with these changes? 

A few pointers: you could force ace to refresh when the window resizes by calling `editor.aceEditor.resize(force)`, and you could play around with `editor.aceEditor.$blockScrolling` which may have to do with this behavior.

**Comment by cope** [comment]
Firstly, this issue is actually our mistake, not the issue of jsoneditor. My bad.

And, I fixed it based on the [#360 (comment)](https://github.com/josdejong/jsoneditor/issues/360#issuecomment-277521662), by setting `editor.aceEditor.setReadOnly(true);`.

Closing.

**Comment by josdejong** [comment]
good to hear it's solved now, thanks for your feedback!
