### ISSUE TITLE
how to store json file on my server ?

### ISSUE THREAD

**Issue by Kavan72** [josdejong/jsoneditor#367]
how to store json file on my server ?

**Comment by Kavan72** [comment]
please sir answer me

**Comment by josdejong** [comment]
That's a bit of a generic question not related to JSONEditor. You can set up a database like MongoDB or CouchDB and store the documents there, and put a server with a REST API in front of it.

You can Google for tutorials like [this one](https://zellwk.com/blog/crud-express-mongodb/).

**Comment by Kavan72** [comment]
Ok server but i also uploaded source code on my server and edit mainfest.json and app-min.js but i get the error like this "Failed to load resource: the server responded with a status of 405 (Method Not Allowed)"

**Comment by josdejong** [comment]
I'm not sure what this has to do with JSON Editor. Please ask your question on stackoverflow or forums related to the server technology that you use (node.js? php? python? java?...)
