### ISSUE TITLE
Context-menu not fully visible.

### ISSUE THREAD

**Issue by SamMousa** [josdejong/jsoneditor#368]
The fix for #104 introduces a problem with showing the context menu for smaller editors.

Other libraries often specify a configurable target for context menus. That way you can choose between encapsulation and properly working (meaning overflowing) context menus.

The issue seems fixed if this css `div.jsoneditor { overflow: hidden; }` is removed, but I'm not sure what other things might break.

**Comment by josdejong** [comment]
You mean like in this picture?

![image](https://cloud.githubusercontent.com/assets/568626/23230217/6e89c84c-f943-11e6-9457-6cc6d9b30331.png)

The context menu has been rendered like this (inside the editor instead of overflowing it) for a long time. Before that, the menu was rendered absolutely but that gave issues in some specific cases where the editor was inside a bootstrap modal or things like that, therefore the menu is now rendered relatively to the context menu button.

I'm not sure how `div.jsoneditor { overflow: hidden; }` would fix this, that seems not the case.

**Comment by SamMousa** [comment]
removing the overflow hidden fixes it.

**Comment by josdejong** [comment]
To be sure I tried but it doesn't change anything. There is at least one other div inside `div.jsoneditor` with `overflow: auto` so I think it can't work like that. 

How to reproduce your fix exactly?

**Comment by SamMousa** [comment]
I'll add a screenshot tomorrow.

**Comment by josdejong** [comment]
:+1:

**Comment by SamMousa** [comment]
With the standard css:
![image](https://cloud.githubusercontent.com/assets/547021/23251687/8618132c-f9ae-11e6-8364-a2ce811d90fb.png)

After disabling the rule via chrome dev tools:
![image](https://cloud.githubusercontent.com/assets/547021/23251764/c53536c0-f9ae-11e6-99ec-e706bddff894.png)

![image](https://cloud.githubusercontent.com/assets/547021/23251731/a9d9918c-f9ae-11e6-88cc-b2671f59c95b.png)

**Comment by josdejong** [comment]
ahhh, now I see what you mean. I thought you where talking about the actions menu of JSON objects but you mean the "mode" drop down menu from the main menu. My bad.

I've applied your fix in the `develop` branch, it indeed works for this dropdown :). We still have to find a better solution for the actions menu itself (it sort of works, you can scroll down to see the whole menu, but it's not really nice). That fix must be done carefully, we have to check whether it also works in special cases like in modals.

**Comment by Karanpal97** [comment]
@josdejong  @SamMousa  when we open the context-menu it does not close when we click some where why??
![s5](https://github.com/josdejong/jsoneditor/assets/120642407/c56dbebe-838b-44cf-b291-021c92eaac13)

**Comment by josdejong** [comment]
@Karanpal97 please do not hyjack a separate topic, your issue is discussed in #1596.
