### ISSUE TITLE
Where are source codes of the website?

### ISSUE THREAD

**Issue by chinesedfan** [josdejong/jsoneditor#369]
The history log says the web application has been moved to another project since v3.0.0.

Could you tell me where it is? Is it not open source?

**Comment by josdejong** [comment]
The web application is indeed not open source any more, the JSON Editor component is.

**Comment by chinesedfan** [comment]
Please forgive my curiosity. The web application is a very good example. Why not keep it as open source? Due to security or commercial issues?

**Comment by josdejong** [comment]
I've had trouble in the past with multiple pirates/copycats grabbing the web application, removing attribution and putting it online - trying to make money from it without having to do anything at the expense of my own web application.

**Comment by chinesedfan** [comment]
What a shame! Do they violate Apache-2.0 license?

**Comment by josdejong** [comment]
Yes by removing attribution. 

Anyway, it's not worth spending any extra words on these guys. I rather like spend my time developing software :)

**Comment by chinesedfan** [comment]
Right. But for those people, they can still steal static files from your website. Just difficult to rewrite.

**Comment by josdejong** [comment]
Yeah, well, hopefully that is too much effort for them already.

I will close this topic now, hope your question is answered.

**Comment by chinesedfan** [comment]
Sure. Thank you very much!
