### ISSUE TITLE
Unable to load new ace theme into jsoneditor

### ISSUE THREAD

**Issue by gastonche** [josdejong/jsoneditor#372]
I have been trying to load a different theme into the editor and i keep receiving errors. 
I am having this error in the console:
```
Uncaught TypeError: Cannot read property 'cssClass' of undefined
    at afterLoad (file:///C:/Users/Gaston/opensource/testcon/jsoneditor.js:32580:25)
    at file:///C:/Users/Gaston/opensource/testcon/jsoneditor.js:20109:28
    at Array.forEach (native)
    at file:///C:/Users/Gaston/opensource/testcon/jsoneditor.js:20108:24
    at _acequire (file:///C:/Users/Gaston/opensource/testcon/jsoneditor.js:16486:38)
    at req (file:///C:/Users/Gaston/opensource/testcon/jsoneditor.js:16536:25)
    at afterLoad (file:///C:/Users/Gaston/opensource/testcon/jsoneditor.js:20104:10)
    at HTMLScriptElement.s.onload.s.onreadystatechange (file:///C:/Users/Gaston/opensource/testcon/jsoneditor.js:19750:18)
```
> This is my code:
```
<!DOCTYPE html>
<html>
<head>
	<title>Test</title>
	<link rel="stylesheet" type="text/css" href="jsoneditor.css">
	<script type="text/javascript" src="jsoneditor.js"></script>
	<script type="text/javascript" src="ace/ace.js"></script>
</head>
<body>
<div id="test"></div>
<script type="text/javascript">
	var body = document.getElementById('test');
	var options = {
		mode: 'code',
		modes: ['code','tree'],
		theme: 'ace/theme/tommorow-night-bright',
	}
	editor = new JSONEditor(body,options,body);
</script>
</body>
</html>
```
 and my file strucuture is 
![dir](https://cloud.githubusercontent.com/assets/11961056/23632011/a161ddc8-02c0-11e7-8726-e6a3cf554e72.PNG)

**Comment by josdejong** [comment]
I think you're forgetting to load this theme first, like: 

```html
<head>
	<title>Test</title>
	<link rel="stylesheet" type="text/css" href="jsoneditor.css">
	<script type="text/javascript" src="jsoneditor.js"></script>
	<script type="text/javascript" src="ace/theme/tommorow-night-bright.js"></script>
</head>
```

I also see that you're loading another instance of Ace in your application:
```html
<script type="text/javascript" src="ace/ace.js"></script>
```

that probably gives a conflict with the embedded version of Ace that comes with jsoneditor.js. Is that on purpose? (if you have other parts of your application using Ace you can use the minimalist version of JSONEditor instead and use your own version of Ace, see [08_custom_ace.html](https://github.com/josdejong/jsoneditor/blob/master/examples/08_custom_ace.html))

**Comment by gastonche** [comment]
When i include the theme without including ace i get the error, 

>  define is undefined.

The theme was gotten from the ace-builds repo.

**Comment by josdejong** [comment]
Here is an example: http://jsbin.com/ligazog/edit?html,output

it uses the theme from brace (which is also used internally by JSONEditor). I'm not sure where your problem originates from, could be a version mismatch or simply the Ace theme missing AMD (which uses `define`)

**Comment by gastonche** [comment]
The fiddle is exactly what i need, but i don't know what wrong
I must be getting something wrong with the script but when i try to set it up locally by downloading all the files required, it doesn't work, this is my new folder structure, and i am using the same code as in the fiddle but have changed the resources url.

![dir1](https://cloud.githubusercontent.com/assets/11961056/23726054/2d5a5bf0-0453-11e7-85d1-3e971af02062.PNG)

**Comment by josdejong** [comment]
I think you will have to do some debugging yourself, at least now you have a working fiddle to start from.
