### ISSUE TITLE
Unable to get the changed data

### ISSUE THREAD

**Issue by mac4manu** [josdejong/jsoneditor#373]
@josdejong -
I would like to capture the changes when user edits the JSON. I used angular2 wrapper.
I'm unable to get the changes. Please let me know if i'm doing wrong -
<json-editor [options]="{mode: 'code',onChange: checkData()}" [data]="_jsoncode">
</json-editor>

Thank you
Manu

**Comment by josdejong** [comment]
the `onChange` option only triggers you that something changed, to get the actual change you have to call the method `.get()` or `.getText()` on the editor. I don't know how this is dealt with in the angular2 wrapper you mention, I suppose the data automatically is updated (two way binding). Maybe you can better ask your question at the angular2 wrapper project that you use?

**Comment by mac4manu** [comment]
Thank you @josdejong

**Comment by josdejong** [comment]
Yes JSONEditor emits the following events/callbacks: `onChange`, `onEditable`, `onError`, `onModeChange`.

See docs for more details: https://github.com/josdejong/jsoneditor/blob/master/docs/api.md
