### ISSUE TITLE
How to load saved json in raw format instead of opening editor?

### ISSUE THREAD

**Issue by realtebo** [josdejong/jsoneditor#374]
I saved some json.

Is there a way to share the json via url without causing editor to open? Just to serve json to a remote app or to share json code without enabling editing

**Comment by josdejong** [comment]
You can fetch the data of a stored document like: 

```
http://api.jsoneditoronline.org/v1/docs/:id/data
```

where you replace `:id` with the id of your document. 

Be careful though, use this only for development, not for production. All documents are public and can theoretically be edited/deleted by anyone with the url.

**Comment by realtebo** [comment]
Thanks for replying, and for warnings.

**Comment by josdejong** [comment]
You're welcome :)
