### ISSUE TITLE
textbox

### ISSUE THREAD

**Issue by maheshwarigagan** [josdejong/jsoneditor#375]
where's the code written for textbox displayed against an attribute in ace editor

**Comment by josdejong** [comment]
I'm not sure what you mean, can you elaborate?

**Comment by maheshwarigagan** [comment]
I want have a use case where in I want the user to select value for an attribute through dropdown instead of them inserting it in the text box, how can I do it?

**Comment by josdejong** [comment]
sorry I still don't get it

**Comment by maheshwarigagan** [comment]
![screenshot 7](https://cloud.githubusercontent.com/assets/7816588/23793388/f203c9ce-05b0-11e7-9a1a-6061be78f8a5.png)
As you can see in the attached screenshot,I want the user to select value for field staticValue from drop-down instead of textbox. How can i do so?

**Comment by maheshwarigagan** [comment]
Basically i want a drop-down instead of textbox, am I clear?

**Comment by josdejong** [comment]
You can do that using enums in a JSON Schema, see this example: https://github.com/josdejong/jsoneditor/blob/master/examples/07_json_schema_validation.html

It's not available in view mode though like in your screenshot, only in modes form/code (view mode is read only).

**Comment by maheshwarigagan** [comment]
Surely, I will use the form mode for this purpose.
More details:
Can i have a drop-down and a text-box side by side displayed on the UI?

**Comment by maheshwarigagan** [comment]
https://github.com/josdejong/jsoneditor/blob/master/examples/07_json_schema_validation.html
I didn't get much from this example, do you have a lime demo or a fiddle running for this?

**Comment by josdejong** [comment]
If you've installed JSONEditor with npm or downloaded it on your computer, simply find the examples folder inside and open the example from there.

It's not possible to display a dropdown and text input side by side.

**Comment by maheshwarigagan** [comment]
I just included the required JS files in my project to get JSONEditor running.
I don't have examples folder.

**Comment by maheshwarigagan** [comment]
> It's not possible to display a dropdown and text input side by side.
Why is that?

**Comment by maheshwarigagan** [comment]
> It's not possible to display a dropdown and text input side by side.

Why is that?

**Comment by josdejong** [comment]
> Why is that?

Very simple: I didn't implement that and neither did anybody else :). Making this more customizable is on the roadmap for v6.x though.

**Comment by maheshwarigagan** [comment]
Is it possible to have it?
If yes, can you direct me in right direction please

**Comment by josdejong** [comment]
v6 is under construction but not yet ready, that will still take some serious time before it's finished.

**Comment by maheshwarigagan** [comment]
What if i want to develop it by my side, can you just direct me to the code base where i can make the code changes so as to get my required functionality?

**Comment by josdejong** [comment]
It's this part of the code (v5)

https://github.com/josdejong/jsoneditor/blob/master/src/js/Node.js#L1277-L1332

**Comment by maheshwarigagan** [comment]
okay, lemme check it +1:
