### ISSUE TITLE
How to customize the submenu of Insert? (tree editor)

### ISSUE THREAD

**Issue by ShaiTeller** [josdejong/jsoneditor#377]
![jsoneditor - class](https://cloud.githubusercontent.com/assets/15266505/24324323/65696e6a-1195-11e7-8f7d-c03b0ee3fb69.png)

I would like to add "class" in the submenu of Insert. I managed to do that by changing the code in jsoneditor.min.js (adding it to the submenu of Insert)

```
, { // THIS HAS BEEN CHANGED
                        text: "Class",
                        className: "jsoneditor-type-object",
                        title: r.class,
                        click: function() {
                            i._onInsertBefore("", {})
                        } //
```

now some of the things I dont understand how to do (from most important to least):

1. Change the function that happens when i click on it (as in inserting a class), inserting a class in my example would be to insert an object that has 2 objects in it already (2 empty strings) of module and path. example:
![jsoneditor - class2](https://cloud.githubusercontent.com/assets/15266505/24324370/62b5fe30-1196-11e7-90bb-0ccf7bdf1b0f.png)

It would create a new instance of a class object (the values of the fields would be empty at first).

From what i saw it calls the function `_onInsertBefore` so i tried to find the implementation of the function and found this: (line 5927 when unminified)

`n.prototype._onInsertBefore = function(e, t, i) {
            var r = this.editor.getSelection(),
                o = new n(this.editor, {
                    field: void 0 != e ? e : "",
                    value: void 0 != t ? t : "",
                    type: i
                });
            o.expand(!0), this.parent.insertBefore(o, this), this.editor.highlighter.unhighlight(), o.focus("field");
            var s = this.editor.getSelection();
            this.editor._onAction("insertBeforeNodes", {
                nodes: [o],
                beforeNode: this,
                parent: this.parent,
                oldSelection: r,
                newSelection: s
            })
}`

but not really sure what exactly needs to be changed in order to do what I want to do.

2. How do I change the icon? I dont understand how each element gets a different icon in the code.

Any chance for some guidance? (I hope I made it clear enough)

**Comment by ShaiTeller** [comment]
OK I just changed the object that gets passed:

```
, { // THIS HAS BEEN CHANGED
                        text: "Class",
                        className: "jsoneditor-type-object",
                        title: r.class,
                        click: function() {
                            i._onInsertBefore("", {**module: "", class: ""**})
                        } //
```

that solved question 1.

**Comment by josdejong** [comment]
Customizing the context menu isn't supported, though you may be able to hack something in the code of the editor. 

Related issues: #267, #337
