### ISSUE TITLE
Partially updating tree

### ISSUE THREAD

**Issue by yasserf** [josdejong/jsoneditor#378]
Hello!

I'm trying to update parts of the json tree, without it collapsing / rerendering everything.

I'm a bit at a loss if there is a problem with my implementation, or if the library doesn't actually support the feature. 

What I'm doing here is doing a  `set` with the same keys but different values.

![jsoneditor](https://cloud.githubusercontent.com/assets/2734923/24327088/5f537bfe-11bf-11e7-9532-9a459b2b46ee.gif)

Thanks!

**Comment by josdejong** [comment]
This isn't yet supported, but you will be able to that in the next major version, v6, which still has a long way to go. See #337 for more details.

**Comment by yasserf** [comment]
Sounds great, will try it out given I don't need that many of the features currently available.

Thanks for the quick reply!
