### ISSUE TITLE
Porting to vuejs 2?

### ISSUE THREAD

**Issue by safaorhan** [josdejong/jsoneditor#379]
Is there any attempts to port this awesome library to vue?

**Comment by josdejong** [comment]
Not that I know of. Would be cool. If anyone is interested in picking this up please let me know.

There is an important limitation in the current jsoneditor API in this regard: you can only replace the JSON in the editor as a whole, you can't do a partial update. This will be addressed in the next major version v6, see #337.

**Comment by safaorhan** [comment]
I'm learning Vue in these days. I'm now using JSONEditor with get/set methods. (not with reactive data and not as a separate vue component). It's still handy.

I can work on porting JSONEditor to vue someday. More specifically, after I totally understand how Vue works :)

Thanks

**Comment by josdejong** [comment]
Ok cool. Just let us know when you're about to start, to prevent someone else accidentally building a wrapper too at the same time.

**Comment by Adam-Jimenez** [comment]
Something like this? https://github.com/Adam-Jimenez/vue2-jsoneditor/blob/master/src/components/JsonEditor.vue

I'm having a little trouble configuring webpack to build an individual vue component though. When I figure it out I'll publish it on npm.

**Comment by josdejong** [comment]
I guess this solves the issue? Will close it now.
