### ISSUE TITLE
Readonly text mode.

### ISSUE THREAD

**Issue by walkerrandolphsmith** [josdejong/jsoneditor#382]
Hi @josdejong. I see that when the editor is in the tree mode I can decide which nodes are editable with the onEditable option. If I need all the nodes in the tree to not be editable I can use the view mode. I want to Use the text mode to display a read only view of the raw text. Textareas support a readonly attribute. Is there a setting I have overlooked or would this be a valid feature to implement. I can submit a PR if you like.

**Comment by josdejong** [comment]
Fixed in v5.6.0 with your PR #383. Thanks again :)
