### ISSUE TITLE
messy code when content length is very long

### ISSUE THREAD

**Issue by jsy625** [josdejong/jsoneditor#387]
when the value length is longer than init width, the editor will show messy code.
![Uploading image.png…]()

**Comment by jsy625** [comment]
![image](https://cloud.githubusercontent.com/assets/2771259/25129500/f1d05858-2470-11e7-8782-9ad7a5fe1469.png)

**Comment by josdejong** [comment]
Thanks for reporting. Do you mean the Chinese characters I see on the left? Or the way the text is wrapped? I suppose this is something that only occurs on Chinese systems, I'm not sure if I could reproduce issue this on my system.

Just to be sure: are you using the latest version of JSONEditor, `v5.6.0`?

**Comment by jsy625** [comment]
Imean the Chinese characters on the left.  I change to the last version and problem solved. Thank you!

**Comment by josdejong** [comment]
Great to hear that!
