### ISSUE TITLE
[v6] Implement checkboxes for booleans

### ISSUE THREAD

**Issue by josdejong** [josdejong/jsoneditor#390]
For values which are boolean, Implement checkboxes left from the value to easily toggle true/false like in the following image:

![image](https://cloud.githubusercontent.com/assets/568626/25146523/78041e20-2474-11e7-8e76-c968be41e292.png)

Rendering a checkbox is not the only special rendering of a value. For example an enum of a JSONSchema will be rendered as a drop down (which replaced the free input field). In the end it should become completely customizable how a value is rendered. This should be kept in mind when implementing this feature.

Related: #391

**Comment by dougn7** [comment]
Hello. Theres a way to disable this? I'd like to implement a verification myself.

**Comment by josdejong** [comment]
@dougn7 it shouldn't be to hard to hide the checkboxes with some CSS if you don't want them.

**Comment by dougn7** [comment]
It works! Thanks. Thank guys for the hard work. I could help implement some stuff, but im not experienced enough with Javascript best practices and Git..

**Comment by josdejong** [comment]
Thanks for your kind words :+1:
