### ISSUE TITLE
Implement select box for JSONSchema enums

### ISSUE THREAD

**Issue by josdejong** [josdejong/jsoneditor#391]
For enum values of JSONSchema, the value of a node should be rendered as a select box like in the following image:

![image](https://cloud.githubusercontent.com/assets/568626/25146785/781d2626-2475-11e7-8741-ceefa6a1872b.png)

Rendering a select box is not the only special rendering of a value. For example booleans will be rendered  with a checkbox in front of it. In the end it should become completely customizable how a value is rendered. This should be kept in mind when implementing this feature.

Related: #390

**Comment by Koushikphy** [comment]
really need this

**Comment by josdejong** [comment]
It's already available in v5, have you tried it?

**Comment by Koushikphy** [comment]
using v5.32
and my json and scheema 
`        var schema = {
            "properties": {
                "job": {
                    "type": "array",
                    "items": {
                        "properties": {
                            "company": {
                                "enum": ['test1', 'test2']
                            },
                            "salary": {
                                "type": "number",
                                "minimum": 120,
                                "examples": [100, 110, 120]
                            }
                        }
                    }
                }
            }
        };
        var json = {
            job: [{
                company: 'test1',
                salary: 100
            }]
        };`

It does not shows the dropdown box for company

**Comment by josdejong** [comment]
That looks like a bug, seems like enums are not turned into dropdowns when inside an array or something. I've created a separate issue for it: https://github.com/josdejong/jsoneditor/issues/697

**Comment by Koushikphy** [comment]
Happy to know that. I'm trying this for hours and thought that my schema is not valid. I'll be keeping an eye for this to fixed

**Comment by josdejong** [comment]
:( sorry to hear that. Hope we can fix it soon.

**Comment by josdejong** [comment]
#697 has been fixed. I think we can close this issue.
