### ISSUE TITLE
[v6] Get the library working in external React projects

### ISSUE THREAD

**Issue by josdejong** [josdejong/jsoneditor#393]
Get the library working in external React projects. Expose an API for React. 

Since JSONEditor v6 is written in React, it should be easy to consume in an other React project, and not via a bundled version which has React embedded (which gives conflicts).

This probably means correctly generating ES5 code under `./lib`, and some configuration in package.json and babelrc.

- [x] Create a build script to generate ES5 JavaScript code under `./lib` (for usage in React)
- [x] Compile and bundle CSS for source code under the `./lib` folder (right now you get an error because a plain WebPack setup doesn't do LESS).
- [x] Create a usage example for React. See `./examples/react_demo`.
- [x] Get `import JSONEditor from 'jsoneditor/react'` working
- [x] Get dependencies right (peer dependencies for react)?
- [x] Using the React version should not give console errors `Uncaught Error: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded`
- [x] Using the React version should not give console warnings `Warning: A component is `contentEditable` and contains `children` managed by React. It is now your responsibility to guarantee that none of those nodes are unexpectedly modified or duplicated. This is probably not intentional.`
- [ ] Document API and usage of the React version

**Comment by veeramarni** [comment]
I think you need to move the react dependencies into `peerDependencies` section. I have experience with `typescript` and `webpack` to built packages, may be something like [this](https://github.com/krasimir/webpack-library-starter) would help. 

```
    "react": "15.4.1",
    "react-dom": "15.4.1"
```

**Comment by josdejong** [comment]
Thanks, that's indeed the root cause of the issue, thanks for the tip! 

Instead of putting the react dependencies in `deepDependencies`, I think we have to move them to `devDependencies`, since the library can be used without React too (and in that case users should not get errors regarding unmet peer dependencies). But this probably introduces an other issue (not sure if multiple copies of React is the cause). When running the `react_demo` example, we get a console warning: 

> Uncaught Error: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded

There are a few more issues that need to be tackled, I've created a small checklist.

**Comment by veeramarni** [comment]
You can probably use `npm ls` to find whether there is any duplicate react libraries. I have noticed this issue if we use any third party components which pull its own version of `react`. I still suggest you to add `react` libraries (that generally supported with your package) in `peerDependencies` section and you may also include a specific version in `devDependencies` for test purpose. 

Something like this. 
```
  "peerDependencies": {
    "react": ">=15.0.0",
   "react-dom": ">=15.0.0"
 }
  "devDependencies": {
    "react": "15.4.1",
    "react-dom": "15.4.1"
 }
```

**Comment by josdejong** [comment]
Yes exactly.

But still, when defining `peerDependencies`, users using the "vanilla" version instead of the React version will get npm warnings because they don't have react installed right?

One solution could be to create two separate npm libraries: `jsoneditor` and `jsoneditor-react` but that would probably only complicate things more (at least qua maintenance).

**Comment by josdejong** [comment]
Will close this issue now, it's old and inactive.
