### ISSUE TITLE
JSON view feature - user disabled mode

### ISSUE THREAD

**Issue by govardhan-s92** [josdejong/jsoneditor#394]
Hi,

This module is really great to work with, But need a **view mode**[User shouldn't be able to edit the json structure] of the json structure with the existing feature. Can you please help me in developing this.

Regards,
Govardhan

**Comment by josdejong** [comment]
There is actually a `view` mode, see configuration option `mode` in the [API docs](https://github.com/josdejong/jsoneditor/blob/master/docs/api.md#configuration-options). Is that what you're looking for?

**Comment by govardhan-s92** [comment]
yeah.  Thanks for the help.
