### ISSUE TITLE
Missing dependencies in "code" mode

### ISSUE THREAD

**Issue by mariail** [josdejong/jsoneditor#395]
I am unable to install the plugin through npm or bower so I just downloaded the three files I (thought I) needed and popped them into my project (jsoneditor.min.js, jsoneditor.min.css and the svg file).

Since **code mode** simply wasn't working, I also included the ace.js and mode-json.js files downloaded separately, along with theme-jsoneditor.js from the project files. And now it works. Sorta.

It's still looking for the worker-json.js file. I added that too and included it in my view, except it's looking for it in my vendor files for some reason. I don't know how to point it in the right direction and I'm at a loss. I'd like to have validation too. And get rid of that ugly "failed to load worker script" console error.

Any thoughts? Thanks.

**Comment by josdejong** [comment]
Thanks for reporting Maria. This file `worker-json.js` is (or should be?) embedded in the JSONEditor bundles. 

When you load a custom version of Ace I can imagine it tries to load it's own version of this `worker-json.js` file.

I'm not sure how to reproduce your issue, when I try any of the examples and load the minified version of the library (from `dist`) there, the examples with Ace work just fine. Can you provide a minimal example?

**Comment by josdejong** [comment]
Closing this issue now due to lack of response, feel free to reopen if needed,
