### ISSUE TITLE
Autocompletion

### ISSUE THREAD

**Issue by josdejong** [josdejong/jsoneditor#398]
In https://github.com/josdejong/jsoneditor/pull/396#issuecomment-299991903, @israelito3000 suggests implementing autocompletion. 

Not sure how that may best work, maybe something like collect all words in the JSON document and create a dropdown with autocompletion options whilst typing.

**Comment by israelito3000** [comment]
Check this out: https://israelito3000.github.io/jsoneditor/11_autocomplete.html

Tested in Chrome.

The autocomplete engine are external, so is not need to be embedded into the component, just need to have autocomplete option with the following interface:

```
autocomplete : {
    ActivationChar : '',   // This is a character that makes the autocomplete activate if the line startswith it.
    ApplyTo:['values']    // it can be 'values' or 'name' depending where you want autocomplete feature.
    Show: function (node, element){
        // Show the autocomplete 
     }
    Hide: function() {
       // hide the autocomplete
    }
}
```

In the example I create autocomplete options for create jsonpaths based on json structure, you can see more details in the branch: https://github.com/israelito3000/jsoneditor/tree/feature/autocomplete

What do you think? does this feature can apply for a pull request?

Regards.
Israel.

**Comment by josdejong** [comment]
That's cool, your example works like a charm!

It may be a good idea to keep the implementation of the autocomplete engine externally, though I'm not sure whether such an API (where people have to hook up their own solution) works nicely with existing autocompletion libraries. Do you know whether that's the case? If not, it may be better to implement the rendering of this dropdown ourselves, and only expose an `onAutocomplete(text)` function which allows you to return an autocompleted version of the input text.

**Comment by israelito3000** [comment]
Hello Jos.

Thank you for your feedback, actually I was researching before work on autocomplete and the main issue is that most of the autocomplete libraries rely on input text fields, which is not ahow jsoneditor works, I found one "horsey autocomplete" and I integrated without too many issues, I actually set the example here:

https://israelito3000.github.io/jsoneditor/12_autocomplete_horsey.html

It need to be refined a little bit to accept "." as autocompletion trigger, to work similar to the one I did .. but this is also specific for my scenario of jsonpath options. 

If you dont mind, I am going to create a more easy example to only display a set of options base on the node content, not using the jsonpath validation which is very specific for a project that I am working on. and I am going to create a pull request. 

There is not too many changes in the core of jsonpath to achieve this feature actually.

**Comment by josdejong** [comment]
Thanks, so if I understand it correctly there are hardly any auto complete libraries that could be hooked up with JSONEditor, sounds logic that most of them work with input and not with editable divs. 

In that case I think we serve people best with embedding our own autocomplete dropdown in JSONEditor (neatly styled matching the other components) rather than forcing people to implement or find their own. What do you think?
