### ISSUE TITLE
Unable to Copy/Paste to JSON Editor Tree view in MAC

### ISSUE THREAD

**Issue by champ51** [josdejong/jsoneditor#399]
I am trying to copy the json text from my local file to editor in MAC and it is not copying inside json editor. i am using COMMND+C Command+V controls to do the same .  but i am not any facing such issue with windows copy paste ctrl c, or ctrl v but observed the issue with MAC OS . is this issue existed or any work around for this

**Comment by josdejong** [comment]
Thanks for reporting. 

How about copying text from other places than your local file editor? Like from a website or something? Doesn't that work either?

**Comment by champ51** [comment]
It is not copying from both local file as well as other places like website

**Comment by josdejong** [comment]
Thanks for the update, I have an idea on where this issue could originate

**Comment by champ51** [comment]
can you please share your thoughts. so that i can try in my code

**Comment by josdejong** [comment]
What I was thinking is that the editor somewhere only catches the `event.ctrlKey` and not the `event.metaKey` when dealing with copy/paste (a case I recently encountered in another project). Looking at the code there is no such event handling though, it's just the default browsers.

I don't have a Mac to try, can probably ask a colleague after the weekend, or maybe you can do some debugging yourself. 

What's odd though is that JSONEditor exists for years already having may users and I've never heard from any Mac user that copy/paste doesn't work. Could it be that it's something weird on your Mac or the browser you're using?

**Comment by josdejong** [comment]
I've tried in Chrome on a Mac, but copy and paste works just fine there. Can it be that there is something weird with your Mac? Or maybe you have some chrome extensions that don't play nice or something?

As long as I can't reproduce the issue I'm afraid I can't solve it.

**Comment by josdejong** [comment]
Will close the issue now due to inactivity and missing input, feel free to reopen if needed.
