### ISSUE TITLE
duplicate multiple

### ISSUE THREAD

**Issue by TimSlade** [josdejong/jsoneditor#400]
I know that customising the menu is a topic that is raised elsewhere, and is being looked at.
I think it would be valuable to add a dropdown to 'Duplicate' that would allow multiple duplicates to be created simultaneously, whilst retaining the behaviour of creating a single duplicate for a simple click on the Duplicate item.

**Comment by josdejong** [comment]
Do you mean like duplicating a node say 10 times? Or do you mean duplicating multiple selected nodes at once?

**Comment by TimSlade** [comment]
The first- Duplicating a single node many times.
Thanks

**Comment by josdejong** [comment]
Ok thanks. That can be useful though I'm not sure whether this is indeed a common use case and should be built-in by default. It's at least interesting to make it possible via a custom action menu item. 

(or you can just press `ctrl+d` in the node you want to duplicate and keep the keys down until you've enough copies ;) )

**Comment by josdejong** [comment]
Will close due to lack of activity

**Comment by Mamtha-Naidu** [comment]
Even I need a option to duplicate multiple.
How can we access the selected node code and manually write code to duplicate multiple times?

**Comment by josdejong** [comment]
You could add a custom button yourself to the context menu for example (using `onCreateMenu`), and write the functionality you want yourself: get the json and current selection using `editor.get()` and `editor.getSelection()`, adjust the document, and then update via `editor.update(...)`.
