### ISSUE TITLE
Example of functional validation

### ISSUE THREAD

**Issue by riccibitti** [josdejong/jsoneditor#401]
Silly me, I'm missing how to validate using a javascript function (examining nodes values) **in addition** to json-schema validation.

**Comment by josdejong** [comment]
Can you elaborate? Do you mean you would like to get the errors from the json schema validation or something?

**Comment by riccibitti** [comment]
Disclaimer: I'm new to json-schema and may just overlooking a more proper way of doing it with schema alone.
What I meant was doing part of the validation using the schema, and then running a customized function performing more checks and possibly adding more errors. I'm trying to configure a machine with accessories and setpoints that have cross dependencies I can describe comfortably with an algorithm but I'm unable to figure out how to express it equivalently using json-schema alone - if even possible.  Also, starting with a function and gradually transforming it to a schema could make json-schema learning curve easier for me ;-)

**Comment by josdejong** [comment]
I think what you're looking for is "custom keywords" of ajv, the library that does the actual json-schema validation (JSON Editor only displays the errors that come from ajv).

Have a look at the docs of ajv to see if that's what you need:

 https://github.com/epoberezkin/ajv#defining-custom-keywords

**Comment by riccibitti** [comment]
Definitely! Got a ton of new stuff to learn, thank you for pointing me in the right direction!

**Comment by josdejong** [comment]
:+1:
