### ISSUE TITLE
Can not modify with Polymer 1.x?

### ISSUE THREAD

**Issue by lomori** [josdejong/jsoneditor#403]
We are using Polymer CLI (Starter Kit) 1.0.1 , with elements from Polymer 1.x. we can load and display a JSON just fine but the element seems to be readonly, i.e., can not add or change any node. 

Regards,
Luiz

**Comment by josdejong** [comment]
Can you create a jsbin or jsfiddle to demonstrate the issue? 

The JSONEditor uses editable divs. The only thing that pops up in my mind is that there are css conflicts in combination with polymer or something like that.

**Comment by lomori** [comment]
Thanks. I will try. Just noticed that editing an item seems to work, delete/append/remove/duplicate do not. The demo works fine, but that is loading webcomponents 0.6.

**Comment by lomori** [comment]
I've tracked that down to the "shady" versus "shadow" global Polymer configuration. Add the Polymer.dom configuration right after the webcomponents import in your sample and you will see the problem. Also, I found out that Ctrl+D/M are working and that the problem is affecting the onClick event for the context buttons.
..
    <script src="//cdn.jsdelivr.net/webcomponentsjs/0.6.0/webcomponents.min.js"></script>
    <script>
      // Setup Polymer options
      window.Polymer = {
        dom: 'shadow',
        lazyRegister: true,
      };
    </script>
...

**Comment by josdejong** [comment]
Thanks, that gives some clue I suppose. I haven't used Polymer so I don't really know. @lomori would it be possible for you to setup a jsbin/jsfiddle to demonstrate the issue?
