### ISSUE TITLE
How  can i call JsonEditor Text on Key up event

### ISSUE THREAD

**Issue by champ51** [josdejong/jsoneditor#406]
I wanted to fire my custom validation method on key up event

```js
this.options.onChange: function(){
validate()
}
```
My Validation Method is:
```js
Validate() {
    this.validatorOutput = Validator(this.jsonEditor.get());
    if (this.validatorOutput.Success) {
       saveWorkingFolder(this.fileLocation, JSON.stringify(this.content));
       this.content = this.jsonEditor.get();
      this.readEditor.set(this.jsonEditor.get());
    }
  }
```
I am getting error Validate is not a function of undefined

**Comment by josdejong** [comment]
maybe because function and variable names are case sensitive? You call `validate()` whilst the method is defined as `Validate`?

**Comment by champ51** [comment]
thats my bad .. calling onchange before initialization

**Comment by josdejong** [comment]
So did you solve your issue?
