### ISSUE TITLE
How do i know that JSON is valid or not

### ISSUE THREAD

**Issue by champ51** [josdejong/jsoneditor#408]
I want to check the json in jsoneditor is valid or not. i am getting errors in console.log if any error

**Comment by josdejong** [comment]
If you try to get the JSON via `jsoneditor.get()`, and error will be thrown when invalid, and JSON will be returned when valid.

**Comment by champ51** [comment]
what it will return if error occurred, if no errors all good. but if any error raises i wanted to catch the error . how can i achieve this. help is appriciated. thank you

**Comment by josdejong** [comment]
```js
try {
  var json = jsoneditor.get();
  console.log('JSON is valid', json);
}
catch (err) {
  console.error('JSON is invalid', err);
}
```

**Comment by champ51** [comment]
That works for me Thanks a lot

**Comment by josdejong** [comment]
ok

**Comment by lgl1993** [comment]
it's great!
