### ISSUE TITLE
error on a numeric value

### ISSUE THREAD

**Issue by rodriformiga** [josdejong/jsoneditor#409]
I have a erro on put this Json
`{
  "grid": [
    {
      "NU": 100000000098201,
      "NO": "Antonio Vuata Kukembiko"
    },
    {
      "NU": 00271029,
      "NO": "Daniel Joaquim Correia Fiquissa"
    }
  ]
}`

because **00271029** have two left zeros. If I put the value 271029 it works perfectly.

**Comment by josdejong** [comment]
Extra zeros left and right of a number will indeed be removed, that doesn't change the numeric representation of the value. If these zeros do have meaning (maybe it represents an id or something), it's safer to change it into a string.

**Comment by josdejong** [comment]
o wait, and indeed, zeros on the left are no valid JSON at all. See http://json.org

**Comment by rodriformiga** [comment]
@josdejong
Ok... its correct.. thanks. I changed into a string.
My XML to Json converter generated the number that way, so I made a correction.

**Comment by josdejong** [comment]
:+1:
