### ISSUE TITLE
how to setup jsoneditor like jsoneditoronline.org

### ISSUE THREAD

**Issue by visik7** [josdejong/jsoneditor#410]
Anyone knows how to setup it in the same way of jsoneditoronline.org ?

**Comment by josdejong** [comment]
You will have to build it yourself. 

Unlike the JSONEditor component used in the web application, the web application itself is not open source.

**Comment by visik7** [comment]
Any detail on how to do it ?

**Comment by josdejong** [comment]
Ehhh, yes, like:

- Set up a web application
- Implement two panels each with a JSONEditor instance and different mode (code and tree)
- Implement copying JSON between the two panels via two buttons.
- Implement a server + database to store JSON documents
- Implement loading/saving of documents in the web application
- Implement loading/saving a JSON document from disk and url
- Implement all sorts of small details

**Comment by djmattyg007** [comment]
I have something I've cobbled together here: https://github.com/djmattyg007/docker-jsoneditor

It's a little out of date, but still perfectly usable. It also wouldn't take much effort to run it outside of a container.

If you want to submit contributions to improve the functionality so it matches jsoneditoronline.org, they'll be most welcome. Currently it doesn't support things like loading files from disk or anything like that.

**Comment by josdejong** [comment]
Thanks for sharing Matthew!

Shall we close this issue?
