### ISSUE TITLE
How Do I update a value on a Addition,Duplicate or Insert?

### ISSUE THREAD

**Issue by jasoncarrorig** [josdejong/jsoneditor#411]
I would like to auto-populate (auto number) a field whenever there is a Addition,Duplicate or Insert event,  I have the function to generate to next number , I just dont know how to fire that function on Addition,Duplicate or Insert and how to edit a specific node.

Is this possible currently?

**Comment by josdejong** [comment]
Thanks for your input. This is currently not possible. What comes close is the `template` option which allows you to insert a predefined data structure on insert.

See example: https://github.com/josdejong/jsoneditor/blob/master/examples/10_templates.html
