### ISSUE TITLE
cannot capture editor.get() error

### ISSUE THREAD

**Issue by 4garfield** [josdejong/jsoneditor#413]
## How to reproduce:
1. setup JSONEditor as code mode, listening onChange event:
```javascript
var options = {
  mode: 'code',
  onError: function (err) {
    alert(err.toString());
  },
  onChange: function() {
    console.log(JSON.stringify(editor.get()));
  }
};
```
2. change the json to invalid structure, like:
![capture](https://user-images.githubusercontent.com/11541408/27208595-24c0724e-5279-11e7-9094-9cf7d33440f9.PNG)
3. in the console, it shows the error:
![error](https://user-images.githubusercontent.com/11541408/27208633-5ea0e9d0-5279-11e7-9bca-a2293cc7f4f3.PNG)

## What Expected

If JSONEditor can capture the `editor.get()` error; then we can provide right information if user try to save the incorrect json. But now, nothing would happen.

So, How about capture that error by `onError` event or in the get method?

**Comment by josdejong** [comment]
Errors triggered by a user action (like switching from code mode to tree mode whilst the JSON document contains errors) will trigger the `onError` callback.

Errors triggered programatically, like `editor.get()`, can be caught by putting a try/catch around it:

```js
var options = {
  mode: 'code',
  onError: function (err) {
    alert(err.toString());
  },
  onChange: function() {
    try {
      console.log(JSON.stringify(editor.get()));
    }
    catch (err) {
      console.error(err);
    }
  }
};
```

**Comment by 4garfield** [comment]
Thanks @josdejong
