### ISSUE TITLE
Schema description as title for field name

### ISSUE THREAD

**Issue by thrkmmr** [josdejong/jsoneditor#415]
I'm not sure if this is the right venue for a newbe question. If not, then please point me in the right direction.

It would be very useful for my user to be able to see the schema description as title for the property names as suggested in issue: https://github.com/josdejong/jsoneditor/issues/321. I've poked a bit around in the code, but was unable to find a way to access the property info from the HTML node around the name. I imagine the a solution, using jQuery, could look something like this that (called after the editor is constructed):

    $('jsoneditor-field').attr('title', $(this).propinfo.schema.description)

Any hints would be appreciated.

And thanks for this great tool!

**Comment by josdejong** [comment]
Thanks!

I don't think there is a workaround to get this working via some smart jquery or something, since the HTML lacks information about the JSON path of the field and value. So we'll really have to implement this in the JSONEditor itself.

Let's continue any discussion on this topic in #321 ok?
