### ISSUE TITLE
FATAL ERROR:JavaScript heap out of memory

### ISSUE THREAD

**Issue by njueyupeng** [josdejong/jsoneditor#417]
Every time I refresh the page multiple times(about 30 times or more), the following error occurs--
"**FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory**"

**Comment by josdejong** [comment]
Thanks for reporting. 

Can you explain how this happens and how I can reproduce the issue? Did you load a very large file or something like that?

**Comment by josdejong** [comment]
Related: #418

**Comment by josdejong** [comment]
@njueyupeng can you explain what this exactly solves and how to reproduce? If not I will close this issue and your PR.
