### ISSUE TITLE
Dist files contain only 'undefined'

### ISSUE THREAD

**Issue by turettn** [josdejong/jsoneditor#419]
It looks like the minifier didn't cooperate on the last build (v.5.7.1 \ 9e5dd53e8ddaa20f26e0f254f60170a9ddbd5443).

The following files contain only the 9 bytes `undefined`:
* disr/jsoneditor.min.js
* dist/jsoneditor.map
* dist/jsoneditor-minimalist.min.js
* dist/jsoneditor-minimalist.map

**Comment by josdejong** [comment]
Whoops! that's not good. I upgraded to uglify-js 3 and thought everything was fine (no errors), I should have seen this. Should be fixed now in `v5.7.2`. This Sorry for the inconvenience.

**Comment by turettn** [comment]
Thanks for the quick fix!

**Comment by josdejong** [comment]
:+1:
