### ISSUE TITLE
JS minification bug in 5.8 release. Files damaged.

### ISSUE THREAD

**Issue by FractalizeR** [josdejong/jsoneditor#421]
There is no JS content here:

https://github.com/josdejong/jsoneditor/commit/a6bd4646ca179019f4a26da250d9599a7e46565e#diff-b21180a0cd769a6ef30460364ec95caf

**Comment by josdejong** [comment]
Thanks for reporting. The exact same just happened a week ago too (see [version 5.7.2](https://github.com/josdejong/jsoneditor/blob/master/HISTORY.md#2017-06-27-version-572)). Will fix it asap.

**Comment by rjmacarthy** [comment]
Yep, undefined in the js file.

**Comment by FractalizeR** [comment]
It would be great to add some... validation or something because that problem has just broken my production (not a public side, but nevertheless...). Component author didn't expect a non-minor version change to be so critical.

**Comment by josdejong** [comment]
Should be fixed again in v5.8.1. It's a sloppy mistake. I'm struggling with npm v5. changing a version number of dependencies in package.json and running `npm i` doesn't always install the configured version for some reason, I still confused about it's behavior.

> Component author didn't expect a non-minor version change to be so critical.

LOL. this is indeed quite a drastic "change". Really sorry for the inconvenience. 

It's of course always safer not to change versions of your dependencies straight in production, and instead test that beforehand. The new package-lock.json of npm v5 should help (though so far it gives me quite a headache).
