### ISSUE TITLE
Issue with Buttons Display

### ISSUE THREAD

**Issue by ScottDWagner** [josdejong/jsoneditor#425]
using all the same includes a single page has 0 issue with display. when showing the boxes in a jquery dialog i get the issue in the image below.
![image](https://user-images.githubusercontent.com/9826792/27871452-4ccb3c14-616b-11e7-8db2-1b26f5160be2.png)

**Comment by josdejong** [comment]
Looks like there is some CSS of your application conflicting with the CSS of JSONEditor?

**Comment by ScottDWagner** [comment]
I think I will try changing the css on JSONEditor.  I will let you know.

**Comment by josdejong** [comment]
:+1:

**Comment by ScottDWagner** [comment]
Ok i tried that still did not work. I am able to run the exact same code on a single page outside of a jquery dialog and i have no issues. Any Ideas. Also the page in question is running on a Sharepoint Server using a custom application page.

**Comment by josdejong** [comment]
Try to isolate and pinpoint the issue. Strip your application until the issue doesn't occur anymore. Does it have to do with jquery? Some specific jquery plugin? etc.
