### ISSUE TITLE
Mode undefined

### ISSUE THREAD

**Issue by trystan2k** [josdejong/jsoneditor#429]
Hi,

Due to a change done in latest version (5.8.2) - in this [PR](https://github.com/josdejong/jsoneditor/pull/424)  - when creating the editor, it looks for the first element of the modes array, in case modes array is informed but it does not check if the array is empty ( no elements ), which can cause the error:

`Uncaught Error: Unknown mode "undefined"
    at n.setMode (jsoneditor.min.js:30)
    at n._create (jsoneditor.min.js:30)
    at new n (jsoneditor.min.js:30)`

I believe a complementary check should be added to keep this change backward compatible since there could be people (like me :) ) that was declaring and passing the modes array empty.

I have done  PR(https://github.com/josdejong/jsoneditor/pull/428) for this 

Please let me know if you see any issue on this or have any comment !

Thanks

**Comment by josdejong** [comment]
Fixed via #428
