### ISSUE TITLE
[enhancement] the tool should remove all white space in the json data which user paste it.

### ISSUE THREAD

**Issue by hoangthach252** [josdejong/jsoneditor#430]
[enhancement] the tool should remove all white space in the json data which user paste it.

I paste the json string below and the tool does not understand it. I have to remove all white space and then it works.

**Comment by josdejong** [comment]
Can you share the JSON object that gives issues? There is probably some special white space characters in it or something.

**Comment by hoangthach252** [comment]
[{"atr1": {"provenance": [{"info": "10.10.10.10", "domain": "dc=hcm,dc=com", "type": "Directory"}], "editable": false, "value
": "Thach"}, "imaddresses": [],"alias": {"provenance": [{"info": "10.10.10.10", "subType": "ActiveDirectory_2012", "domain": "dc=hcm,dc=com", "type": "Directory"}], "editable": false, "value": "Thach Hoa
ng 4441925"}}]

**Comment by hoangthach252** [comment]
here it is. This json data works fine on http://jsonviewer.stack.hu/. THanks.

**Comment by josdejong** [comment]
Thanks, that is an interesting case. There is an unescaped return character somewhere in your JSON, which makes the JSON invalid. 

I've added some more logic to the sanitizer which tries to fix broken JSON, and now it will neatly escape unescaped control characters like the `\n` in your example. You can try in the updated web application (ensure to refresh the web page once, should display v3.7.8 at the bottom).
