### ISSUE TITLE
the set method is loosing the reference.

### ISSUE THREAD

**Issue by m2omou** [josdejong/jsoneditor#431]
Hi,

Is there a way for JSONEditor.set method, to not loose the reference of my object ?

So basically when I change something in the editor, it should automatically reflect on my object, right now the only solution is to use JSONEditor.get and reset my object.

Thanks for the help!

**Comment by josdejong** [comment]
This is indeed the intended behavior, load an object via `JSONEditor.set`, listen for changes using `onChange`, get the changed object via `JSONEditor.get`. 

Can you explain why you need to apply the changes to your existing object instance and why replacing the object is not an option?

**Comment by m2omou** [comment]
I was just curious, since I was passing an object, I was expecting JSONEditor to update that same object so I don't have to call every time JSONEditor.get to refresh my object.

Btw thank you for that awesome json editor. 🏅

**Comment by josdejong** [comment]
Thanks, you're welcome.

Having JSONEditor mutate the JSON object that you pass it via `set` would lead to hard to debug code if say the same object is also managed by Angular or something. How can JSONEditor know that something was changed inside the object externally? How can external components know that JSONEditor changed anything in the object?

In general, the JavaScript community is moving away from shared objects which can are manipulated by different parts of an application at the same time, towards functional and immutable techniques. This leads to much easier to understand code, easier to understand flow of data through an application, and easier to test and debug code. I think that's great! 

The [new JSONEditor v6 version](https://github.com/josdejong/jsoneditor/issues/337) that I'm working on will have a new function which gives you JSONPatch changes via `onPatch` (replacing `onChange`), which allows patching an existing instance of a JSONObject or keep multiple editors in different browsers in sync and that sort of stuff. Still a long way to go for v6 though but we'll get there.

**Comment by m2omou** [comment]
True what you are saying makes total sense. It's more safe.

Excited to try the v6! ;)

**Comment by josdejong** [comment]
:+1:
