### ISSUE TITLE
Can't select multiple items

### ISSUE THREAD

**Issue by Buyachaka** [josdejong/jsoneditor#433]
Hello, I use this tool a lot. There was a feature where I would select multiple items by dragging the mouse. It does not work anymore.

**Comment by josdejong** [comment]
Thanks for reporting, that used to work indeed and now it indeed doens't work anymore.

**Comment by josdejong** [comment]
I see this issue wasn't closed, the bug was already fixed in `v5.9.3` (2017-07-24)
