### ISSUE TITLE
ContextMenu display issues

### ISSUE THREAD

**Issue by dhughes-xumak** [josdejong/jsoneditor#440]
Noticed while working on https://github.com/josdejong/jsoneditor/pull/438/commits/fbd082de1313ab01b05c89851050bd7a1993a3f1

Sometimes ContextMenu items with submenus do not display correctly (the arrow is not a separate element from the rest of the button).  When this happens, the submenuTitle is not displayable; the parent menu item's title displays instead.  This may also trigger the parent's click handler when trying to open the submenu.  The overflow behaviour for the menu items could also be improved, so the last button in this example looks better.
![image](https://user-images.githubusercontent.com/28631401/28340136-86fdef46-6bc3-11e7-94a0-65a79d2f6ff1.png)

These are probably trivial CSS changes, but I'm not even going to try fixing them.  Hopefully somebody else could help fix these display issues.

**Comment by josdejong** [comment]
Thanks, let's address this whilst working out #438. I will have a look into it too (probably this weekend).

**Comment by dhughes-xumak** [comment]
I revisited this and realized that the difference was intentional.  

`Type` has no click handler, so the entire button can be used to expand the submenu.
`Sort` has a click handler on the top-level button, so a second button is added for expanding the submenu.

Consequently, I am going to close this issue as invalid.  The text overflow wasn't an issue until #438 introduced custom context menu items, so it can be dealt with in that PR.

**Comment by josdejong** [comment]
:+1:
