### ISSUE TITLE
Custom fields editable in arrays

### ISSUE THREAD

**Issue by lambertdeblois** [josdejong/jsoneditor#450]
How can i allow the elements of an array to be removed but not the array itself?
![2017-08-21_13-44-55](https://user-images.githubusercontent.com/8781906/29531787-09ae5e20-8678-11e7-99c8-942ed922b64b.png)
i want to be able to add/remove items in the array (need, install, add) but i don't want to let the array itself editable (must be there)
i looked in the example 5, and i couldn't figure it out.

**Comment by josdejong** [comment]
You can use `onEditable(node)`, and check the property `path` in the argument `node`. If that for example is an array ending with `[..., 'keywords']`,you can return `false` to make the array itself readonly.
