### ISSUE TITLE
feature request of onEditable API

### ISSUE THREAD

**Issue by 4garfield** [josdejong/jsoneditor#452]
currently, under the `tree` mode, the json value is not editable.
```js
var options = {
    mode: 'text',
    modes: ['text', 'code', 'tree'],
    onEditable: function (node) {
      return {field: false, value: true};
    }
  };
```

some question:
1. As the `onEditable` API says, the `tree` mode returned object should indicate the json key/value editable or not, but the value is not editable.
2. currently, the `text` and `code` mode just make the whole json as read-only, but in our use-case, we want provide flexible configuration so user cannot edit the json key. Do you have any suggestion ?

**Comment by 4garfield** [comment]
Seems while the #392 finished, the `onEditable` API can retrieve the the json in current "node" ?

**Comment by josdejong** [comment]
1. I'm not sure what you mean here. Is something not working as it should?
2. You could validate when the user wants to save the configuration, return an error when for example the id is edited. What also can help is specify a JSON Schema which gives the user feedback on whether the document is valid or not. An other option is to disable the `text` and `code` mode if you need control. 
3. The JSON contents of the node is not passed to `onEditable`, but you can easily retrieve it by getting the whole JSON with `editor.get()`, and then finding the current part of the JSON given the node's path, using a `lodash.get(object, path)` or something like that.

**Comment by 4garfield** [comment]
1. under `tree` mode, while `onEditable` return `{field: false, value: true}` the JSON value is not editable, but it should.
2. use the JSON Schema validation could solve it.

**Comment by josdejong** [comment]
1. Maybe I'm missing something but it seems to work like expected (field readonly, value editable) http://jsbin.com/bawukey/edit?html,output
2. yes. Mind you though that JSON schema will not _prevent_ making disallowed changes, it will only warn you about it.
