### ISSUE TITLE
context menu

### ISSUE THREAD

**Issue by shinyamade** [josdejong/jsoneditor#454]
Is there any way to show the context menu for the action of objects in the middle of the editor?
There are some discussions here that the menu is clipped.  The option would useful for mobile as well.

**Comment by josdejong** [comment]
Yes, the context menu positioning could be improved. I guess you refer to #416?

Let's continue any discussion on this in #416 to keep it focused ok?

**Comment by shinyamade** [comment]
Thank you for your reply.  I agree...

**Comment by josdejong** [comment]
:+1:

**Comment by igiton** [comment]
Hi, is it possible to completely hide context menu and leave only templates?

**Comment by josdejong** [comment]
@igiton yes, you could use mode `form` I think.
