### ISSUE TITLE
Not able to pass flag '/i' or '/g' to schema pattern

### ISSUE THREAD

**Issue by rameshwar-jadhav** [josdejong/jsoneditor#455]
I'm using regex for schema validation, which is working perfect. But I want to pass ignore case flag with regex. 
As I see regex initialization code there is no option to set flag
```
function patternCode(i, patterns) {
	  return 'var pattern' + i + ' = new RegExp(' + util.toQuotedString(patterns[i]) + ');';
}
```
So Is there any other option to use regex with flag.
Thanks.

**Comment by josdejong** [comment]
I'm not sure how this is related to JSONEditor, can you elaborate?
