### ISSUE TITLE
Click a url string in view mode, but the web page is opened in two new tabs instead of one on Firefox and Safari

### ISSUE THREAD

**Issue by magiclen** [josdejong/jsoneditor#461]
npm install jsoneditor

**index.html**

	<!DOCTYPE HTML>
	<html>
	<head>
		
		<meta http-equiv="Content-Type" content="text/html;charset=utf-8">

		<link href="node_modules/jsoneditor/dist/jsoneditor.min.css" rel="stylesheet" type="text/css">
		<script src="node_modules/jsoneditor/dist/jsoneditor.min.js"></script>
	</head>
	<body>
		<div id="jsoneditor" style="width: 400px; height: 400px;"></div>

		<script>
			// create the editor
			var container = document.getElementById("jsoneditor");
			var options = {
				mode: 'view',
				modes: ['code', 'form', 'text', 'tree', 'view'] // allowed modes
	   		};
			var editor = new JSONEditor(container, options);

			// set json
			var json = {
			    "url": "https://magiclen.org"
			};
			editor.set(json);

			// get json
			var json = editor.get();
		</script>
	</body>
	</html>

- Firefox version: 55.0.2
- Mode: view

In Firefox, click the url which is in the json object. Then, two new tabs are created and open the same web page. But it expects to create only one tab to open the web page, doesn't it?

**Comment by josdejong** [comment]
Thanks for reporting this bug @magiclen ! I can reproduce this issue on Firefox. The issue doesn't occur on Chrome.

**Comment by josdejong** [comment]
Same issue on Safari

**Comment by josdejong** [comment]
This should be fixed now in `v5.9.6`
