### ISSUE TITLE
feature

### ISSUE THREAD

**Issue by kumarvijay95** [josdejong/jsoneditor#464]
There should be a facility to change the value of a field (suppose we have an array and in that array we want to change the value of a specific field for all record)

**Comment by josdejong** [comment]
I suppose you mean changing the field programmatically? 

The editor currently does only support replacing the whole JSON object. You could use that to replace one nested property value though it's not ideal. For the upcoming `v6` we're working on support for JSON Patch which makes it easy to programmatically change the JSON without losing the state of the editor, see #337.

**Comment by josdejong** [comment]
I will close this issue now - without any more feedback I guess it will be covered in `v6`
