### ISSUE TITLE
Editor corrupts large numbers, exposing limitation of underlying jscript

### ISSUE THREAD

**Issue by CamyDee** [josdejong/jsoneditor#466]
Repro:

Create a simple JSON structure like so:
```json
{
   "name" : "Numeric Corruption Repro",
   "value" : 9223372036854775807,
   "detail" : "Int64.MaxValue by the way..."
}
```

As soon as you enter the value, it is oddly changed to:

```json
{
   "name" : "Numeric Corruption Repro",
   "value" : 9223372036854776000,
   "detail" : "Int64.MaxValue by the way..."
}
```

This makes sense only when you know about the way numbers are stored in JavaScript, but should not corrupt the data the user is trying to save. Numeric values should probably be stored internally as strings rather than the limited storage type internally used by JavaScript, to avoid this kind of thing.

**Comment by josdejong** [comment]
Yes that's indeed a good point. I made a start with it long time ago but so far didn't implement it in JSONEditor, see #231. Let's continue any discussion in #231.
