### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by gmeissner** [josdejong/jsoneditor#468]
Hello,

we started using jsoneditor. Our company is located in Germany and therefore it would be very nice, if we could localize button-labels and messages. As we stated so far, the labels and messages are placed right in the source-code and there is actually no chance to edit them in a separate file.

It would be very nice, if there might be a seperate file to edit labels and messages. That would help us to keep up to date with the latest version of jsoneditor and to have our localized messages and labels.

Thanks very much!

**Comment by josdejong** [comment]
Thanks for your suggestion! 

Let's continue any discussion in #275 (I will mark this as a duplicate)
