### ISSUE TITLE
Uncaught TypeError: Cannot read property '$ref' of undefined

### ISSUE THREAD

**Issue by yinhongbo** [josdejong/jsoneditor#469]
Uncaught TypeError: Cannot read property '$ref' of undefined
f._getExternalRefs	@	jsoneditor.js:556
f._loadExternalRefs	@	jsoneditor.js:578
f.init	@	jsoneditor.js:251
f	@	jsoneditor.js:221
(anonymous function)	@	test.html:17

test.html 内容为：
<!DOCTYPE HTML>
<html>
<head>
    
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8">

    <link href="jsoneditor/dist/jsoneditor.min.css" rel="stylesheet" type="text/css">
    <script src="jsoneditor/dist/jsoneditor.min.js"></script>
</head>
<body>
    <div id="jsoneditor" style="width: 400px; height: 400px;"></div>

    <script>
        // create the editor
        var container = document.getElementById("jsoneditor");
        var options = {};
        var editor = new JSONEditor(container, options);

        // set json
        var json = {
            "Array": [1, 2, 3],
            "Boolean": true,
            "Null": null,
            "Number": 123,
            "Object": {"a": "b", "c": "d"},
            "String": "Hello World"
        };
        editor.set(json);

        // get json
        var json = editor.get();
    </script>
</body>
</html>

环境：Window+Chrome 50.0.2661.87 m

**Comment by josdejong** [comment]
Are you using the latest version of JSONEditor? This sounds like an issue introduced in `v5.9.5` and fixed in `5.9.6`

**Comment by GrimJacky** [comment]
@josdejong I'm seeing this problem on version 5.11.0 provided that the page is loaded DataTables

**Comment by josdejong** [comment]
@GrimJacky I'm not sure what you mean, can you elaborate?

**Comment by voops** [comment]
Dear  @josdejong 

This example reproduces the issue 

Please paste this json into http://brutusin.org/json-forms/

```
{
  "$schema": "http://json-schema.org/draft-03/schema#",
  "oneOf": [
    {
      "type": "array",
      "items": {"type": "string"},
      "required": true,
      "title": "A multiple of 3"
    },
    {
      "title": "An object",
      "type": "object",
      "properties": {
        "p1": {
          "type": "string",
          "required": true,
          "title": "A required string"
        },
        "p2": {
          "type": "boolean",
          "title": "A boolean"
        }
      }
    }
  ]
}
```
