### ISSUE TITLE
Caret position in status bar for mode `text`

### ISSUE THREAD

**Issue by josdejong** [josdejong/jsoneditor#471]
It would be nice to extend the status bar created by @meirotstein in #443 with support for `text` mode: currently the `text` mode doesn't display a caret col/row location in the status bar like mode `code` has.

**Comment by meirotstein** [comment]
@josdejong - I'll do some research

**Comment by josdejong** [comment]
:+1: thanks.

I think what you will have to do is get the text, get the caret position character number from the start of the whole text), then count the occurrences of `\n` before this location to calculate the current line number, and calculate the number of characters from the last `\n` till current position to get the current column number. Not sure if there is some special logic needed to handle Windows which uses `\r\n` for next line.

**Comment by meirotstein** [comment]
Yes - this is also what I had in mind, however my concern is mainly in regard to performance -specially when it comes to a large text - I'm afraid that running this on every keydown such as arrow  left/right/up/down may had some performance impact.

I would like to think of a way to optimize it - some ideas: delta calculations, asynchronous execution (to avoid screen lock).

**Comment by josdejong** [comment]
> I would like to think of a way to optimize it

Let's _first_ implement the simplest solution possible. Then see whether there actually _is_ a performance problem. And only _if_ so, start thinking about more fancy solutions... (the first next solution would be simple debouncing of keydown events I think.)

**Comment by meirotstein** [comment]
ok - sounds reasonable.

**Comment by leolems** [comment]
i can recommend a throttle solution..|
there is a good one made by underscore js that you can easily isolate and use: 
http://underscorejs.org/#throttle

**Comment by meirotstein** [comment]
#492

**Comment by josdejong** [comment]
This new feature is now available in `v5.13.0`, thanks again Meir :)
