### ISSUE TITLE
Descending option is being overlapped in the menu

### ISSUE THREAD

**Issue by daynedavis** [josdejong/jsoneditor#474]
You can better see from the screenshots below, but the descending option is not fully visible. I am using the default settings and imported jsoneditor.min.css. I would expect the sort options to look similarly to the insert options which I also attached below.
![jsoneditor style issue](https://user-images.githubusercontent.com/7105109/31553096-533bc70e-b007-11e7-824d-745544467955.PNG)
![jsoneditor style issue 2](https://user-images.githubusercontent.com/7105109/31553103-560b9130-b007-11e7-8f32-f08209412515.PNG)
![jsoneditor style issue 3](https://user-images.githubusercontent.com/7105109/31553109-586893ec-b007-11e7-80c6-d9a22a4214ec.PNG)

**Comment by josdejong** [comment]
Thanks for reporting. 

I tried to reproduce on Firefox 56 with both minified and non-minified files, but everything looks fine there.

Can it be that there is some CSS on your page that collides with the CSS of the JSONEditor or something? Does the issue also occur on this jsbin for example? http://jsbin.com/dubocax/1/edit?html,output
