### ISSUE TITLE
Support JSON5

### ISSUE THREAD

**Issue by daledude** [josdejong/jsoneditor#477]
I understand this is niche but I'm attempting a request anyways. I use a few projects that use JSON5 and the ability to add comments alone is awesome.  2 public projects that I use with it are babel and containerpilot, 

[https://github.com/json5/json5](https://github.com/json5/json5)

**Comment by josdejong** [comment]
It could indeed be interesting. And yeah, there are plenty of JSON dialects :). 

I would like to keep JSONEditor focused though and (at least for now) do not want to implement JSON5.

**Comment by daledude** [comment]
Understood. Thanks for the useful editor.
