### ISSUE TITLE
Schema validation

### ISSUE THREAD

**Issue by Cyberhan** [josdejong/jsoneditor#478]
Hi, I'm using a schema to validate a JSON file. I have a property named 'transportLengthMM' which has a minimum value of 400. (just an example). 

I don't get a JSON error in case I fill in a wrong value (see picture below):

![image](https://user-images.githubusercontent.com/31624546/31819043-165e3fbc-b59b-11e7-8cde-6b8310209641.png)

I get only an error in case I changed a list box (see picture below):

![image](https://user-images.githubusercontent.com/31624546/31819098-5e133c2c-b59b-11e7-8afa-78ac0d5ba62b.png)

I think it is related to my schema (there are a lot of refs) although I think it satisfies the meta schema.

Do you know what is wrong? The schema validator seems to work correctly but only in case it detects an error on a different place.

I have attached a part of my JSON file inclusive a part of the schema (enough to see the problem (I hope ;-) )).

Kind regards,
Han

[schema.json.txt](https://github.com/josdejong/jsoneditor/files/1401785/schema.json.txt)
[model.json.txt](https://github.com/josdejong/jsoneditor/files/1401789/model.json.txt)

**Comment by josdejong** [comment]
Thanks for your detailed report @Cyberhan . That's weird.

From a first quick look I'm not sure whether this is an issue in your Schema or in the processing of it in JSONEditor. Maybe you can strip your schema and model to figure out a minimal example demonstrating what goes wrong exactly?

If it' indeed s an issue in JSONEditor, its most probably originates in [`ajv`](https://github.com/epoberezkin/ajv), which JSONEditor uses to generate JSON schema errors. JSONEditor itself has no logic for that, so it will be good to verify whether it's indeed occurring in `ajv` too and not just in JSONEditor.
