### ISSUE TITLE
expand All field option

### ISSUE THREAD

**Issue by AlexDuc** [josdejong/jsoneditor#479]
do we have an option to expand all fields when the json loaded without clicking expandall button?
Thanks

**Comment by josdejong** [comment]
The JSONEditor has a method `expandAll()` which you can use to expand everything programmatically, is that what you mean?

**Comment by AlexDuc** [comment]
Got it, thanks

**Comment by josdejong** [comment]
oki!

**Comment by ra-esmith** [comment]
expand all works GREAT!
How would I, through the api, just expand the first level of my json tree?  I can see it seems to happen when I toggle between modes (say to text and then back to tree).  But how can I do it by default when I load my json ...
