### ISSUE TITLE
Office 365 and DocumentType object

### ISSUE THREAD

**Issue by dvd73** [josdejong/jsoneditor#481]
Hi

I can't use your library in Office 365 env because DocumentType object is different than expected 

![image](https://user-images.githubusercontent.com/8290112/32728030-d9ed5f9c-c88f-11e7-8366-8c47a95d2b52.png)

As result the DocumentType.prototype is undefined

**Comment by josdejong** [comment]
I'm not familiar with Ofice 365 env, and DocumentType is not JSON but a JavaScript object. I'm not sure what you mean, can you elaborate?

**Comment by dvd73** [comment]
DocumentType.prototype is undefined 
![image](https://user-images.githubusercontent.com/8290112/32749119-65be0528-c8cf-11e7-933d-7fdcb8767e14.png)

**Comment by josdejong** [comment]
Ah, now I get it. That's code of a polyfill which indeed depends on the existence of DocumentType. Will fix it!

**Comment by josdejong** [comment]
Should be fixed now in `v5.10.0`
