### ISSUE TITLE
Case sensitiveness in autocomplete

### ISSUE THREAD

**Issue by ruchira27** [josdejong/jsoneditor#482]
Hi,

Currently the autocomplete feature is case sensitive. Is there any option to enable case insensitive search?

**Comment by josdejong** [comment]
That makes sense. Maybe it's better to always do case insensitive matching for the autocompletion. @israelito3000 what do you think?

**Comment by israelito3000** [comment]
I think should be configurable. Let me add it.

**Comment by josdejong** [comment]
Ok :+1:

**Comment by israelito3000** [comment]
Added [pull request](https://github.com/josdejong/jsoneditor/pull/490)
