### ISSUE TITLE
Template JSON from schema

### ISSUE THREAD

**Issue by Selvaguru** [josdejong/jsoneditor#483]
Hello,

I want to pre-populate the editor with sample json generated using the properties defined in the schema. For example, if the schema is,
```json
{
            "$schema": "http://json-schema.org/draft-04/schema#",
            "type": "object",
            "properties": {
                "name": {
                    "description": "Full name of the employee",
                    "type": "string"
                },
                "salary": {
                    "description": "Salry of the employee in rupees (in letters)",
                    "type": "string"
                }
            }
        }
```

I want the editor to show,
```json
{
"name" : "Full name of the employee",
"salary":  "Salry of the employee in rupees (in letters)"
}
```

is there anyway to do that?

**Comment by josdejong** [comment]
That's not something JSONEditor does, but I guess you can find libraries that do that for you?

The only thing that JSONEditor has that comes close is templates, [see example](https://github.com/josdejong/jsoneditor/blob/master/examples/10_templates.html).
