### ISSUE TITLE
Custom Context Menu Items

### ISSUE THREAD

**Issue by Lucaszw** [josdejong/jsoneditor#484]
It would be nice to be able to have custom context menu items. 

Perhaps something like an "extraContextMenuItems" option.

```javascript
var options = { 
  ...
  extraContextMenuItems: [
    {
     text: "Custom Item",
     title: "Custom Title",
     click: (e)=>console.log("clicked", e),
     ...
    }
  ]
}
```

**Comment by Lucaszw** [comment]
Noticed this is already being worked on for #438 . Closing this issue.

**Comment by josdejong** [comment]
:+1: 

The PR is #428 has not been active for quite a while though...
