### ISSUE TITLE
dist/jsoneditor.min.js of v5.7.1 is undefined

### ISSUE THREAD

**Issue by hadalin** [josdejong/jsoneditor#485]
https://github.com/josdejong/jsoneditor/blob/v5.7.1/dist/jsoneditor.min.js

```
undefined
```

**Comment by josdejong** [comment]
Try the latest version of jsoneditor instead :)

**Comment by hadalin** [comment]
Maybe someone doesn't want the latest version :)

Not related to this issue, but e.g. `5.7.1` introduced ajv version `5.2.0`, which might [break things](https://github.com/epoberezkin/ajv/releases/tag/5.0.0):

>This release is fully backward compatible, but it may require either migrating your schemas
(recommended, e.g. using "migrate" command of ajv-cli) or changing your code that uses Ajv.

`5.7.0` -> `5.7.1` is should maybe be a major step, not a patch.

**Comment by hadalin** [comment]
Thanks for jsoneditor btw. Really appreciate your effort.

**Comment by josdejong** [comment]
You're welcome :)

You're right, 5.7.1 should have been a major change.
