### ISSUE TITLE
Question: Open file on rpi

### ISSUE THREAD

**Issue by rikki78** [josdejong/jsoneditor#488]
Hello
I would like to use this nice tool to edit a json file on the same raspberry PI as this editor is installed. Is that possible somehow?
thanks

**Comment by josdejong** [comment]
Yes, you can use HTML5 api's to load/save files from disk, or look into Electon to create a desktop application. This functionality is not contained in the JSONEditor library itself though.

**Comment by rikki78** [comment]
Thanks for your reply. I have seen an example about that I believe. I
thought that was to load files from the PC that is connected to the page. I
would like to use a file that is on the same server as where the page is
running. Is that possible as well?
Op wo 29 nov. 2017 om 08:27 schreef Jos de Jong <notifications@github.com>

**Comment by josdejong** [comment]
Yes, a server can access files on disk and you can pass them to a web application via HTTP Fetch for example.
