### ISSUE TITLE
"Error in onChange callback:  Error: Parse error on line 1" in code mode

### ISSUE THREAD

**Issue by AlejandroME** [josdejong/jsoneditor#491]
Hi there!

I have a problem. When using the editor in code mode with a valid JSON loaded, let's say that the user decides to delete all the content and left the editor in blank. With that action, the console starts to print this error, until the JSON starts to take a valid form:

**When the user deletes the content:**

![captura de pantalla 2017-12-13 a la s 4 30 48 p m](https://user-images.githubusercontent.com/2565308/33963468-07bbcac6-e023-11e7-9b7f-94ecfb2fe2e1.png)

![captura de pantalla 2017-12-13 a la s 4 31 25 p m](https://user-images.githubusercontent.com/2565308/33963484-1567bcd4-e023-11e7-889b-c36fcee1b5c9.png)

**When the user starts to write content (until it becomes valid):**

![captura de pantalla 2017-12-13 a la s 4 32 28 p m](https://user-images.githubusercontent.com/2565308/33963537-394d0230-e023-11e7-8482-0a47349beebb.png)

![captura de pantalla 2017-12-13 a la s 4 33 49 p m](https://user-images.githubusercontent.com/2565308/33963579-6e93b006-e023-11e7-89e5-8d4b8589d622.png)

I know that you're not the direct maintainer, but I'm using Angular 5 with [this jsoneditor wrapper plugin](https://github.com/devmark/ngx-jsoneditor) and I'm providing the `onChange` and `onError` handlers.
Unfortunately, they don't work. What it seems strange to me is the error message saying `Error in onChange callback`.

These are my handlers:

```
onChange(value: any) {
         try {
             console.log('Change');
         } catch (err) { }
     }

     onError(err: any) {
         try {
            console.log('Error');
         } catch (err) { }
     }
```

I followed your advice with the `try` mentioned in [this issue](https://github.com/josdejong/jsoneditor/issues/413#issuecomment-309124848), but it doesn't work.
Is there any additional configuration to suppress this console output without losing the capability of showing the errors in the editor?

The configuration of my editor is as follows:

```
this.jsonEditorConfig = {
            sortObjectKeys: false,
            mode: 'tree',
            modes: ['tree', 'code']
        };
```

Thank you

**Comment by josdejong** [comment]
It looks like the `onChange(value)` handler of the Angular 5 wrapper plugin you mention already parses the JSON document before firing `onChange`, and passes it as an argument to `onChange`. Which means it will fail when the JSON in the code mode isn't valid. 

To solve this, the angular 5 wrapper should catch possible parse errors like you encounter right now. Maybe it could introduce an `onTextChange(jsonText)` event or something so you can get callbacks without errors when in text/code mode too.

**Comment by lroman2025** [comment]
I have the same problem: when user removed value in input, I saw error in console. Is there some fix or workaround?

**Comment by josdejong** [comment]
@lroman2025 have you asked in the project of the concerning angular wrapper plugin?

**Comment by josdejong** [comment]
Will close due to lack of activity.
