### ISSUE TITLE
Giant dropdown list on modes

### ISSUE THREAD

**Issue by khaivngo** [josdejong/jsoneditor#493]
Hi
Has this giant dropdown list on modes been addressed? 
v.5.12.0
Simplest solution so far has been to set the height:
  .jsoneditor-menu li {
            height: 25px;
 }

![](http://puu.sh/yL42k/7a666eabcb.png)

**Comment by josdejong** [comment]
Thanks for reporting. How can I reproduce this issue? It doesn't occur when running any of the examples like examples/03_switch_mode.html

**Comment by khaivngo** [comment]
I'm closing this, turned out to be my own fault :)

**Comment by josdejong** [comment]
👍 glad to hear you found the cause
