### ISSUE TITLE
when the key includes the '\n' like 'a\nb', the navigationbar is incorrect

### ISSUE THREAD

**Issue by reyhappen** [josdejong/jsoneditor#494]
when the key includes the '\n' like 'a\nb', the navigationbar is incorrect.
![image](https://user-images.githubusercontent.com/3281751/34297563-b8c37c74-e753-11e7-9b5c-fa7cb427b9b6.png)

**Comment by josdejong** [comment]
Thanks for reporting this issue!

**Comment by josdejong** [comment]
This should be fixed now in `v5.13.0`, thanks Meir.

**Comment by josdejong** [comment]
@Meir I came across one more issue in this regard: when a field which already contains an escape character like `a\nb`, initially the navigation bar text is not escaped when you click the field. Second time you click on the field it will be updated correctly. 

I've fixed this via https://github.com/josdejong/jsoneditor/commit/43832dd53204e6159dfa09c360aa320475948810 (fix not yet released)

**Comment by josdejong** [comment]
Ok should now be fixed in `v5.13.1`
