### ISSUE TITLE
comment section 

### ISSUE THREAD

**Issue by veeramarni** [josdejong/jsoneditor#496]
Is it possible to add comment section which is just read-only text component? I would like to modify it to similar in vscode's settings page. 

![image](https://user-images.githubusercontent.com/3382355/34349625-3000cab0-e9e0-11e7-9728-cf35b068c367.png)

**Comment by josdejong** [comment]
Do you mean the green colored comments on the left side? Or the sentence on top of it "Place your settings..."? 

JSON itself doesn't support comments, so there is not much we can do there (though there are some JSON-like data formats that have added support for comments)
