### ISSUE TITLE
Pressing Ctrl + S multiple time makes problem

### ISSUE THREAD

**Issue by tutysathish** [josdejong/jsoneditor#498]
Hi,
First, Thanks very much for providing this kind of great application to the world...

When I was press Ctrl+S It's showing one popup window, and then I was pressing again it's showing two popup window on the top of old one. I think it it's doesn't look good.

**Comment by josdejong** [comment]
Thanks for your suggestion, you have quite an eye for details ;)

Should be better now in http://jsoneditoronline.org  v4.2.2
