### ISSUE TITLE
Update "Code editor" after insert JSON with custom button

### ISSUE THREAD

**Issue by YuriyChaban** [josdejong/jsoneditor#501]
Hello jodejong, can you help me with understanding in editor, how can i update all editor when i paste a json with a button? I mast update frameor smth else, becouse when i click button, json pasted but not showing and when i keydown some button from keyboard, pasted json is showed becouse editor updated after keydown event. But when i try to understand for what element i must update view i can't do this, because i can't find element what i need for updating editor.

**Comment by josdejong** [comment]
I'm not sure what you mean. You can programmatically replace the contents of the editor with the methods `set(json)` and `setText(jsonText)` when pressing this "Custom button", is that what you mean?

**Comment by YuriyChaban** [comment]
I mean, when i pasted json with button click i pasted it in cursor position, and json is pasted but all editor not updated. I pasted json with `$(".ace_text-input").val(`"some json": {}`);` and i must to update editor because json hold in cursor position but width of cursor is only `16px;`.

**Comment by josdejong** [comment]
Instead of making changes in the DOM, you should use the API of the Ace editor (google for "Ace editor replace selected text" or something like that). Something like:

```js
const aceEditor = jsonEditor.aceEditor
aceEditor.session.replace(aceEditor.selection.getRange(), "Hello world") 
```

**Comment by YuriyChaban** [comment]
thanks for you answer, but i want to say that i don't need to replace existing JSON with new, I want to add new JSON to existing in cursor position. OK I try something else.

**Comment by josdejong** [comment]
Just google for the right API's of Ace editor to achieve what you need

**Comment by YuriyChaban** [comment]
[This is an example. ](https://codepen.io/YuriyChaban/pen/GyxgGG)

**Comment by YuriyChaban** [comment]
Josdejong, your answer was helpful for me, I used this code: 
```
const aceEditor = jsonEditor.aceEditor
aceEditor.session.replace(aceEditor.selection.getRange(), "Hello world")
```

and this worked fine for me. You can close this issue, thanks for your help.

**Comment by josdejong** [comment]
Good to hear :+1:
