### ISSUE TITLE
Error loading AWS CloudFormation JSON Schema 

### ISSUE THREAD

**Issue by mauroj** [josdejong/jsoneditor#505]
I tried to load the AWS CloudFormation JSON schema located at:
https://d1uauaxba7bl26.cloudfront.net/latest/gzip/CloudFormationResourceSpecification.json

I received the following error message: ERROR: Failed to load JSON schema.

These were the steps taken: 

I clicked on Setting->Add Schema

Then in the Add JSON Schema window I select:
"Specify a public url. Urls which need authentication or do not have CORS enabled cannot be loaded"

and enter the URL: https://d1uauaxba7bl26.cloudfront.net/latest/gzip/CloudFormationResourceSpecification.json
after Clicking OK, I received the error message.

Please advise,
Thank you
Mauro

**Comment by josdejong** [comment]
The document doesn't allow CORS, therefore the website jsoneditoronline.org cannot access it. 

Easiest would be to copy and save the document online via jsoneditoronline.org, but this free service has a limit of 1MB, whilst the schema you want to load is 1.2 MB. So, you will have to save a copy of the schema somewhere online yourself, in such a way that it can be loaded by jsoneditor.

**Comment by meirotstein** [comment]
@mauroj you can put your schema file in Github pages which allows CORS.
