### ISSUE TITLE
Validation for Code mode

### ISSUE THREAD

**Issue by YuriyChaban** [josdejong/jsoneditor#506]
Hi, can anyone help me with understanding how to create custom validation error in Code mode like in Tree mode
![image](https://user-images.githubusercontent.com/15606604/35733738-327dc5e4-0827-11e8-8b9a-42885e1e850f.png)

For now in Code mode i only have default validation like this: 
![image](https://user-images.githubusercontent.com/15606604/35733691-fe65cb6c-0826-11e8-841b-5ae902690bac.png)

**Comment by josdejong** [comment]
In `code` mode, JSON Schema errors are not displayed in the left gutter bar but at the bottom. I see though that there is a css issue, will fix that soon.

**Comment by YuriyChaban** [comment]
Thanks i will be waiting for update

**Comment by josdejong** [comment]
Oops! I fixed that immediately but forgot to report back, sorry. Should be fixed in v5.13.3:

https://github.com/josdejong/jsoneditor/blob/master/HISTORY.md#2018-02-07-version-5133
