### ISSUE TITLE
How to control the Editable?

### ISSUE THREAD

**Issue by aRealCat** [josdejong/jsoneditor#508]
Hi, 
I want to change the readOnly value , true or false.
or update the options.  for example:
///////////////////////////////////////////////////////////////////////////////////////
                 var options = { };
                 var editor = new JSONEditor(container, options, json);
                  editor.options.onEditable = { field:false,value:false };
                  //editor.node.editable = { field:false,value:false }; //or like this
////////////////////////////////////////////////////////////////////////////////////////
but all  no use.
how can i do it ?
Thanks.

**Comment by josdejong** [comment]
Here is an example: https://github.com/josdejong/jsoneditor/blob/master/examples/05_custom_fields_editable.html

**Comment by aRealCat** [comment]
Thanks @josdejong 
after initialize the options, i  want to change the options

**Comment by josdejong** [comment]
JSONEditor does not support changing the options after creation (except for some which have their own setter method), but you have full control over what onEditable returns, so I guess you can figure something out?
