### ISSUE TITLE
Color Picker

### ISSUE THREAD

**Issue by rabbishuki** [josdejong/jsoneditor#511]
It would be nice if we had a visual of the color if the value is a color.

I think it could work if the field is called color, and then just take the value and apply a div next to it with the color.

Big Bonus if a color picker can be integrated on  #click.

For reference here is what it looks like in Webstorm when the css value is a color.
![image](https://user-images.githubusercontent.com/24904197/36073384-677d7a42-0f38-11e8-8069-994574c07521.png)

**Comment by josdejong** [comment]
Thanks, nice suggestion!

**Comment by jackparmer** [comment]
Would love to see a hook for an integrated color picker! Plotly uses this project extensively for chart JSON editing and it's a tad cumbersome to change hex or RBG color values manually:

http://plotly-json-editor.getforge.io/
![image](https://user-images.githubusercontent.com/1865834/42970178-971ed308-8b76-11e8-858f-1f4938c7ceb0.png)

**Comment by josdejong** [comment]
Since `v5.24.0` there is a color picker built in in the JSONEditor. 

The build-in color picker is [vanilla-picker](https://github.com/Sphinxxxx/vanilla-picker). It can easily be replaced with your own favorite color picker using the option `onColorPicker` (check out the docs for more info).
