### ISSUE TITLE
Parse newline

### ISSUE THREAD

**Issue by YuriyChaban** [josdejong/jsoneditor#513]
Hi, i have a problem with parse json in editor in mode Code. When i add JSON and in some text field add a lot of new lines and save that and validator pass that and this is saved. When i got a saved json from beckend i try to parse saved json but got an error. I can't parse json becouse a lot of new lines broke JSON.parse()

On backend json encoded for special charsets and when i got json i decoded json for show normal text.

After i send json on backend i saw in request that \r or \n replaced to long free space.
For decode i use ('html-entities').AllHtmlEntities. 
If i don't use decode i see a specials charset and i see a big space on place where i must see new row or new line.

![image](http://i.prntscr.com/e35qyS69Sg2gDUZOhMw5Ug.png)

Maybe something from Ace editor will help me with fixing this?

**Comment by josdejong** [comment]
Thanks for reporting @YuriyChaban . Can you post an example of the JSON document that gives issues, so I can try to reproduce? Does it also happen on https://jsoneditoronline.org? 

For Ace to work correctly with special characters, you indeed have to specify UTF-8 encoding on your website and script, this issue also occurs with Chinese character sets (See for example #502).

**Comment by YuriyChaban** [comment]
Hi @josdejong, sorry that  I did not answer for so long, you can close this issue as I solved this problem. The problem was that when I decoded the encoding on the backend symbols `\r` and `\n` I received an error when parsing in the editor becouse i've got `&#13;` as `\r` and `&#10;` as `\n` and can;t decode this charsets until i replaced  `&#13;` to `\r` and `&#10;` to `\n`

**Comment by josdejong** [comment]
:+1: 

you can close the issue yourself too :)
