### ISSUE TITLE
Cursor position and value after inserted content

### ISSUE THREAD

**Issue by YuriyChaban** [josdejong/jsoneditor#516]
Hi @josdejong, could you help me with understanding with behavior of cursor position after inserted content in editor.
Some time ago I created issue for insert content by press button in cursor position [issues-501](https://github.com/josdejong/jsoneditor/issues/501).
The problem was in position of cursor after insert content using this code:
`const aceEditor = jsonEditor.aceEditor
aceEditor.session.replace(aceEditor.selection.getRange(), "Hello world") `

Using `aceEditor.selection.getRange()` I can insert content in cursor position but after that position of cursor stayed not after inserted content.

The problem was in position of cursor after insert content using this code, cursor position set below one or two lines and in not correct column position.

I tried use to [https://jsoneditoronline.org](https://jsoneditoronline.org/) and insert content with Ctrl + V or Comand + V and position of cursor stay correct after insert.

Maybe I could be use something else for add content in cursor position but save cursor position after add content?

**Comment by josdejong** [comment]
Maybe you can use `setRange` in the Ace editor to adjust the cursor location after replacing contents?

**Comment by YuriyChaban** [comment]
Thanks for quick reply @josdejong  . I used `setRange() `for set position of cursor but this not working in all my case. For example, if I write a coma after `}` and insert content by click on button I have correct cursor position becouse I calculate this position and set it. And if I write a coma after `}` and pressed  Enter a couple time  and inserted content by click on button I have incorrect cursor position becouse I can't calculate how many empty row I have that for set correct cursor position.

**Comment by josdejong** [comment]
Maybe the Ace editor has functions to do text replacement? Have you searched in the docs?

For example on the page "Working with Ace / Common Operations" I see:

> Insert at cursor, emulating user input:
>
>     editor.insert("Something cool");
>
> Replace text in range:
>
>     editor.session.replace(new ace.Range(0, 0, 1, 1), "new text");
>

https://ace.c9.io/#nav=howto&api=editor

Anyway, I don't think I can help you any further than pointing to the docs of Ace editor.
