### ISSUE TITLE
Feature Request: VSCode extension

### ISSUE THREAD

**Issue by ricardogaspar2** [josdejong/jsoneditor#518]
This web app is a great tool! 
Could you create an extension for Visual Studio Code? It would be awesome!

**Comment by josdejong** [comment]
Thanks for your suggestion Ricardo. That could be interesting. 

I have no time to work on such an extension myself but if anyone is interested just let us know in this topic.

**Comment by DanStevens** [comment]
This exists already. In fact this, is how I came across this project.

https://marketplace.visualstudio.com/items?itemName=nickdemayo.vscode-json-editor

**Comment by josdejong** [comment]
wow, cool :sunglasses: . Thanks for sharing @DanStevens
