### ISSUE TITLE
Cannot clean build version 5.14.1

### ISSUE THREAD

**Issue by jaxgibbmq** [josdejong/jsoneditor#519]
Given that I download the project
And I delete the "dist" directory
When I "npm run build"
Then the resultant jsoneditor.js does not contain Node.js
And no errors are shown on the console
And errors are shown within jsoneditor.js: 

8057: var Node = __webpack_require__(!(function webpackMissingModule(){var e=new Error("Cannot find module\"./Node\""); e.code='MODULE_NOT_FOUND'; throw e;}()));

**Comment by josdejong** [comment]
I just did a fresh install:

```
git clone https://github.com/josdejong/jsoneditor.git
npm install
npm run build
```

and that works just fine on my computer. I also deleted `dist` before running `npm run build`, works fine too. Are you using a recent version of node.js and npm?
