### ISSUE TITLE
Support ISODate editing

### ISSUE THREAD

**Issue by mizzao** [josdejong/jsoneditor#520]
When editing JSON documents with `Date` objects, e.g. from Mongo, dates are turned into empty objects:

![image](https://user-images.githubusercontent.com/2080084/38430243-b9e415fe-398e-11e8-8274-9180e0813e5e.png)

other JSON editors convert the date into an ISODate string which can be edited:

![image](https://user-images.githubusercontent.com/2080084/38430338-fa7b7904-398e-11e8-88ed-b78c8c7d3311.png)

Is there any way to do this for `Date` editing, or to specify a transform function for dates to and from a string so they can be edited directly? I know this is not part of standard JSON, but it is a use case that emerges quite often.

**Comment by josdejong** [comment]
Date objects are indeed no JSON. I guess you could use `JSON.stringify` and pass a replacer to replace dates with their ISOString?
