### ISSUE TITLE
Update README maintained badge

### ISSUE THREAD

**Issue by NorthDecoder** [josdejong/jsoneditor#521]
The badge is displaying as not maintained, however it seems clear that updates are actively being made, and issues resolved.

I (humbly) suggest changing the badge
__FROM:__ https://img.shields.io/maintenance/yes/2017.svg ![Maintenance](https://img.shields.io/maintenance/yes/2017.svg)
__TO:__ https://img.shields.io/maintenance/yes/2018.svg ![Maintenance](https://img.shields.io/maintenance/yes/2018.svg)

**Comment by josdejong** [comment]
Whoops! thanks for bringing this up Joe. Should be fixed now.
