### ISSUE TITLE
Any way to display a tooltip of each property?

### ISSUE THREAD

**Issue by wbern** [josdejong/jsoneditor#523]
I tried adding a description to a title to my schema, but I don't see any visual indications of any of these. I have tested form and tree as visual settings.

Is there any way to make them show? Am I missing something?

**Comment by josdejong** [comment]
Titles and descriptions from a JSON schema aren't used in the interface, it's only used to display schema errors and create enum fields so far. 

Could be an interesting addition. Anyone interested in implementing this?

**Comment by josdejong** [comment]
This has been implemented some time ago, when you have a JSON schema with titles and/or descriptions, they will show up when you hover a field.
