### ISSUE TITLE
Errors when ran through Babel

### ISSUE THREAD

**Issue by stevenvachon** [josdejong/jsoneditor#525]
Compiling my code, which depends on v5.14.1 of this library, results in:
```
jsoneditor.js:38 Uncaught TypeError: Cannot set property 'JSONEditor' of undefined
    at webpackUniversalModuleDefinition (jsoneditor.js:38)
    at jsoneditor.js:30
```
and/or:
```
jsoneditor-minimalist.js:38 Uncaught TypeError: Cannot set property 'JSONEditor' of undefined
    at webpackUniversalModuleDefinition (jsoneditor-minimalist.js:38)
    at jsoneditor-minimalist.js:30
```

This is my .babelrc:
```json
{
  "plugins": [
    ["transform-builtin-extend", {
      "globals": ["Error"]
    }],
    "transform-object-rest-spread"
  ],
  "presets": [
    ["env", {
      "targets": {
        "browsers": "last 2 versions"
      },
        "test": {
            "plugins": [
                ["istanbul",
                    {
                        "exclude": "*.+(test|stub|spec).*",
                        "useInlineSourceMaps": false
                    }
                ]
            ]
        },
      "useBuiltIns": true
    }]
  ]
}

```

**Comment by josdejong** [comment]
Looks like you're trying to bundle the bundled version of JSONEditor. I guess there is an issue because the bundled versions try to attach the JSONEditor object to `window` which is not available when bundling or something.

Maybe it works when bundling the source code instead, which is in the folder `src`?

**Comment by stevenvachon** [comment]
My project does not currently use ES modules, unfortunately.

**Comment by josdejong** [comment]
> My project does not currently use commonJS or ES modules, unfortunately.

So what is your project using then?...

**Comment by stevenvachon** [comment]
Concatenation and AngularJS modules

**Comment by josdejong** [comment]
I'm not sure how I can help you. I guess you will have to make sure `window` is defined at the start of your concatenated files or something like that.
