### ISSUE TITLE
css style missed

### ISSUE THREAD

**Issue by YuFengDing** [josdejong/jsoneditor#526]
![image](https://user-images.githubusercontent.com/23763023/39612195-c9f9aa96-4f8f-11e8-8c55-882e2302cbc0.png)
i have copyed the same demo  but it seems like some styles have missed

**Comment by josdejong** [comment]
Looks like the images are missing, that's the file `jsoneditor-icons.svg`. Maybe you've not copied it or it's not added to your bundle or something

**Comment by YuFengDing** [comment]
thanks for resolving, i have handled it.
