### ISSUE TITLE
JSON editor options look grayed out (i.e. disabled)

### ISSUE THREAD

**Issue by jeffsmith99** [josdejong/jsoneditor#532]
My company uses ArangoDB. The ArangoDB User Interface appears to have many menu selections in a gray color. It looks to my eye like they are **"grayed-out"**.

The ArangoDB support team tells me that 

> "this seems to be the default design of the 3rd party widget we use in the Web UI"

 and they suggested that I notify your jsoneditor team of the question.

![image](https://user-images.githubusercontent.com/35961304/40133010-5eb91772-590c-11e8-9751-def4d28c9b4f.png)

However, when I hover over them with my mouse, they suddenly light up and display their color, and I find that they are active and available menu choices.

![image](https://user-images.githubusercontent.com/35961304/40133027-6f5693d4-590c-11e8-828d-01e875261fbe.png)

This is confusing to me as I always assumed that when something is grayed-out, it is in-active and is unable to be selected, as in this example, where the forward and back buttons are grayed out, indicating that they are not viable selections at this time.

![image](https://user-images.githubusercontent.com/35961304/40133040-7c9e0d06-590c-11e8-9688-a1a445e4aa3a.png)

Does this choice reflect new thinking in GUI design? Admittedly this is not the first place I have noticed the "active" grayed-out behavior in newer applications, but I fail to understand why it is being used and what it means.

Thanks, Jeff

**Comment by josdejong** [comment]
Thanks for your input Jeff. The menu font normally doesn't look that light-gray, I suppose a different styling is applied in ArangoDB.

You can see the default styling in the web applicationin the screenshots in the README of the project:

![image](https://user-images.githubusercontent.com/568626/40139947-caa28bae-5951-11e8-95fe-9603ad0ea94b.png)

**Comment by jeffsmith99** [comment]
Thank you so much for the information.  I guess that begs a follow-up question just for curiosity: 
If the choice of gray is just a styling decision, why did JSON editor decide use gray for its menus? Does that color have any modern significance?
Because like I mentioned, as a user, I always thought gray indicated that I should not bother to click on a menu choice because it is "grayed out" https://en.wikipedia.org/wiki/Grayed_out
Jeff

**Comment by jeffsmith99** [comment]
Thank you for  asking for clarification. The issue is not ArangoDB. I think they are just following your coloring decision without modification. Lets look at another example: jsoneditoronline.org (sorry for the lengthy response)

Here is one I understand: As you said, the text font is gray or black which corresponds if I can click it or not.
![font](https://user-images.githubusercontent.com/35961304/40209391-e0a8b9a8-5a0c-11e8-8aa6-40a29a905b27.PNG)

To further illustrate, I can click on the black color text and modify it as you can see in this image. But when I try to click the gray color text I cannot modify it. The gray color informs me that the text is disabled, so I don't waste time trying to click on it or edit it.
![black text](https://user-images.githubusercontent.com/35961304/40209546-d9354dc0-5a0d-11e8-94b1-53ccae4e99aa.PNG)

However here is the part I don't quite get: When I first view the screen I also get these gray icons (that I have circled in red.)
![1](https://user-images.githubusercontent.com/35961304/40209204-f6bda9a2-5a0b-11e8-96ac-22ae1a576b28.PNG)

I would assume that the icons are disabled because they are gray. But when I hover over one of them it suddenly turns black, and the tool-tip appears so now I discover it is actually available for me to use. 
![black icon](https://user-images.githubusercontent.com/35961304/40209482-6d2860ae-5a0d-11e8-95b9-710c00c325d2.PNG)

What that tells me is that I should hover over everything I see - to find out if it is enabled or disabled regardless of its color - even if it is gray.

Does that explain my question? As a computer user, and helper of other users, I just want to understand why the gray color icons.

**Comment by josdejong** [comment]
Thanks for your clear explanation, I understand your concern. 

The thought behind making the action menu button and drag area dots light gray is to prevent an overload of information to the user. In the interface I tried to introduce two "layers" of information: (1) the actual contents (2) secondary information and actions to work on the data. I want to have the core UI elements to be most prominent and the secondary UI elements to be a bit in the background. 

I'm afraid that when I give all UI elements the same prominence, that it becomes harder to focus on what really matters in the editor: the actual JSON data. I'm open to discuss improvements though, so if you have ideas/mockups on an improved UI I'm really interested.

Just as a side note: it may be interesting to look at the UI of Gmail, which also has a lot of gray and light gray UI elements. I suppose there are a lot of smart people behind designing the UI of Gmail, so such an approach may make sense. Will be interesting to think about when light gray UI element do work and when it doesn't.

![image](https://user-images.githubusercontent.com/568626/40267430-60612d56-5b5c-11e8-8692-a0f0cc29b42b.png)

**Comment by jeffsmith99** [comment]
Thank you for your explanation. It makes sense the way you tell it. I like the reference to 2 layers of information. 
Now I have a better understanding, and can help share it with others when I am helping them.
Have a great day,
Jeff

**Comment by josdejong** [comment]
Sound good. Thanks for the constructive discussion.

I'm always open to ideas to improve the UI/UX, so feel free to bring up any suggestions.

**Comment by josdejong** [comment]
@jeffsmith99 you got me thinking. 

I'm now changing the context menu icons to not being grayed out, there it doesn't make that much sense. The icons in the editor itself are still light gray so they don't pick too much attention.

![image](https://user-images.githubusercontent.com/568626/42566921-75c82570-8508-11e8-915b-dc0d60326694.png)

what do you think?

**Comment by jeffsmith99** [comment]
Jos, In my opinion it looks good in your screen-dump, and it will help the users in general. Thank you for thinking about it and for seeking my input!
Have a great day, Jeff

**Comment by josdejong** [comment]
:+1:
