### ISSUE TITLE
Issue in Json content Expand

### ISSUE THREAD

**Issue by Vigneshwaran-RR** [josdejong/jsoneditor#534]
<img width="1327" alt="screen shot 2018-05-19 at 6 57 23 pm" src="https://user-images.githubusercontent.com/7962684/40269080-8e7d2b24-5b96-11e8-8d0f-e70b89992b79.png">

When expanding contents of JSON, the listid  values are incorrect. It shows identical listid, although my actual json holds different listid.

**Comment by josdejong** [comment]
Thanks for reporting. This has to do with your document containing 64 bit long values which can't be represented in JavaScript numbers. Which means we would need a special parser.

Let's continue any discussion in #231 which is about the same topic to keep it focused.
