### ISSUE TITLE
in Safari on iOS, tapping into editor body slides the page all the way to the top

### ISSUE THREAD

**Issue by prushynskyy** [josdejong/jsoneditor#535]
Have anyone seen this behavior?

makes the editor practically unusable on mobile :/ 

Steps to reproduce:
from mobile view on iOS 11 click into jsoneditor that is in the middle of the web page beyond the fold

Results:
clicking into an editor scrolls the page to the top and does not persist the key in.

**Comment by stefyc** [comment]
No, in fact, when clicking on a line, https://jsoneditoronline.org zooms into the line which is quite nice!

We continue to experience this bug.  Any clues?

**Comment by Aeon** [comment]
@josdejong Hi Jos! Thanks for the great library

Here's a jsbin example that exhibits the behaviour described: 

http://jsbin.com/mavebeb

Scroll down to the editor and focus on it. You will see the browser immediately scroll all the way to the top of the page. 

This may be an ACE editor issue, we're not quite sure at the moment. Any advice on how to work around it would be fantastic.

**Comment by josdejong** [comment]
@Aeon thanks for creating this jsbin. Though I don't have an iOS device, I can reproduce the issue when running it on BrowserStack. It does not occur on Android devices as far as I can see.

It could indeed be related to ACE editor. To test that, we would have to create a similar jsbin just creating an Ace editor at the bottom of a large page.

**Comment by josdejong** [comment]
Will close this issue due to inactivity. Feel free to reopen if still relevant.
