### ISSUE TITLE
Update schema dynamically?

### ISSUE THREAD

**Issue by vladyslav2** [josdejong/jsoneditor#537]
Hello!

First of all - thank you for a great product.

I wonder if there any option to actually add/remove fields from schema dynamically?
Let's say I have a long list of variables and I want to have the ability to update schema based on user input

**Comment by josdejong** [comment]
You will have to replace the whole schema when you want to change it.

**Comment by vladyslav2** [comment]
@josdejong I tried it but then I need to update UI somehow too (without losing user data)

**Comment by josdejong** [comment]
Sorry for the late reply.

You can replace the current schema without loosing the current state of the JSON document using `editor.setSchema(schema)`, is that what you mean?

**Comment by vladyslav2** [comment]
@josdejong thank you for reply. I build my own workaround already but its good to know about setSchema. Thank you!
