### ISSUE TITLE
How to open editor at specific node

### ISSUE THREAD

**Issue by audas** [josdejong/jsoneditor#538]
Sorry i know it must be trivial - however I am unable to open an editor at a specific node. I presume this is possible however setSelection does not appear to work for this. Is there some method I am missing to dynamically open the editor on a specific node ?

**Comment by meirotstein** [comment]
@audas can you provide the json you use and the node you try to select?

**Comment by audas** [comment]
So below - how would I open the first or second item of the "manifests".
`[
  {
    "manifest": [
      {
        "delay": "0",
        "duration": "16",
        "animate_in": "bounceInLeft",
        "animate_out": "fadeOut",
        "position": [
          "1.25276247660319%",
          "11.883645276826837%"
        ],
        "id": 0,
        "src": "<div style=\"text-align: center;\"><span style=\"font-weight: bold; font-size: 40px;\">Scheduled maintenance.</span></div>",
        "size": [
          "97.49053125000002%",
          "7.05950237717908%"
        ],
        "mediatype": "text",
        "filetype": [
          "text",
          "txt"
        ],
        "text_in": {
          "staggerTimeRnd": "normal",
          "orderType": "outwards",
          "colorRnd": "normal",
          "alphaRnd": "normal",
          "xposRnd": "randomBoth",
          "yposRnd": "normal",
          "zposRnd": "normal",
          "scaleRnd": "normal",
          "rotationRnd": "normal",
          "rotationXRnd": "normal",
          "rotationYRnd": "normal",
          "zRotationRnd": "normal",
          "originPercOrPx": "px",
          "xOriginRnd": "normal",
          "yOriginRnd": "normal",
          "zOriginRnd": "normal",
          "hShadowRnd": "normal",
          "vShadowRnd": "normal",
          "blurRnd": "normal",
          "shadowColorRnd": "normal",
          "title": null,
          "duration": 2,
          "staggerTime": 0.02,
          "ease": "Back",
          "functionType": "simultaneousTween",
          "targetType": "chars",
          "color": "#000000",
          "alpha": 0,
          "xpos": 809,
          "ypos": 0,
          "zpos": 0,
          "scale": 1,
          "rotation": 0,
          "perspective": 1000,
          "rotationX": 0,
          "rotationY": 0,
          "zRotation": 0,
          "xOrigin": 0,
          "yOrigin": 0,
          "zOrigin": 0,
          "hShadow": 0,
          "vShadow": 0,
          "blur": 0,
          "shadowColor": "#000000",
          "direc": "in",
          "alternate": -1
        },
        "scale": [
          "none",
          "top"
        ]
      },
      {
        "id": 3,
        "delay": "0",
        "duration": "16",
        "mediatype": "text",
        "src": "<div style=\"text-align: center;\"><span style=\"font-weight: bold; font-size: 30px;\"><font color=\"#f7f7f7\">THANKS.</font></span></div>",
        "animate_in": "tada",
        "position": [
          "38.406525717841255%",
          "78.714793306523%"
        ],
        "size": [
          "23.184975694444443%",
          "4.682323296354992%"
        ],
        "animate_out": "fadeOut",
        "scale": [
          "none",
          "top"
        ]
      }
    ]
  }
]`

**Comment by meirotstein** [comment]
This command worked for me:
```js
var start = {path: [0, "manifest", 0]};
var end = {path: [0, "manifest", 1]}
editor.setSelection(start, end);
```

**Comment by audas** [comment]
Ok I will try that - thanks. The docs are not very clear on that. Appreciate it.

**Comment by meirotstein** [comment]
This command selects a specific range of nodes, if it is collapsed it also expand to the selected nodes.
According to what I have checked it working as expected (see pics below).

Please elaborate what your'e trying to achieve - what are you doing and the actual vs expected results.

![image](https://user-images.githubusercontent.com/2209844/41216977-1e990744-6d5f-11e8-94c5-9e996dd42342.png)
![image](https://user-images.githubusercontent.com/2209844/41216995-30411126-6d5f-11e8-9664-94930ee9dd70.png)

**Comment by audas** [comment]
I want to achieve what you have done. Unfortunately it just keeps setting it at the selected manifest and does not expand it as you have in your example.

I have given up after much frustration and am now rebuilding the item and populating it with the specific node and setting it as expanded.

Not sure why it is failing.

**Comment by josdejong** [comment]
I guess I will close this issue then, sorry to hear you couldn't solve it.
