### ISSUE TITLE
Code mode read only option

### ISSUE THREAD

**Issue by venkateshr8849** [josdejong/jsoneditor#539]
in a code mode i wanna make some keys and values should be read only . but  i can't... :)

**Comment by josdejong** [comment]
I understand, that would indeed be nice, but it's not possible: the code mode (and text mode) simply contain a single large text area which is completely free to type/cut/copy/past/move text there, it's not possible to restrict changing a specific field in there.

What you can do is when saving the changed document, validate it: check whether the readonly keys are unchanged and else throw an error.
