### ISSUE TITLE
How to have multipe autocomplete?

### ISSUE THREAD

**Issue by robbanp** [josdejong/jsoneditor#540]
How can I add multiple autocomplete in a value field?
I want to select tags into a field separated by comma.
Can it be done?

**Comment by josdejong** [comment]
The autocomplete solution is quite flexible, you have full control over what to replace and when to show what autocomplete options. I guess it's possible to implement autocompletion for multiple texts, though I haven't tried it. There are a couple of examples in the `examples` folder that show how you can use autocomplete, these may give you some ideas on how to approach this.

**Comment by robbanp** [comment]
Ok, thanks!
