### ISSUE TITLE
navigator is not defined : Error in node.js 

### ISSUE THREAD

**Issue by harsh4044** [josdejong/jsoneditor#543]
![error](https://user-images.githubusercontent.com/35723107/41714031-52c1c504-754f-11e8-9f1e-74d568fe2520.PNG)

**Comment by josdejong** [comment]
JSONEditor requires a browser environment with a DOM, having objects like `document` and also `navigator` to run, you can't use JSONEditor in a node.js environment.

What is exactly the reason you try to load JSONEditor inside node.js?

**Comment by harsh4044** [comment]
Thanks again for this great tool. I found the json-editor tool in node package manager and thought i could use it directly in node.js environment. But anyways i can include it in my browser environment now. Thanks for the info.

**Comment by josdejong** [comment]
:+1:
