### ISSUE TITLE
How to Drag from outside the editor and Drop into some node? 

### ISSUE THREAD

**Issue by rodrigosalinas** [josdejong/jsoneditor#545]
Hi and thanks a lot @josdejong for such an outstanding component. I'm trying to make a Drag and Drop operation from outside the Editor into a node inside the Editor. I want to create a json element inside the array node where I'm trying to drop.

Can someone please guide me how can I do that? Or some idea at least? When I do the drop I can obtain the target element (DOM element) inside the editor. No problem with that. But how can I get the correspondent Node instance to call perhaps the _onInsertBefore or _onAppend on it?

This way I do the drop:

    $(container).on('drop', 'div.jsoneditor-field', function(event) {
        event.preventDefault()
        // **this** gives me here the DOM element, but don't know where to call 
        // the _onAppend or something like that.
    }

Thank you very very much in advance.

**Comment by josdejong** [comment]
I think you're looking for the static function `Node.getNodeFromTarget(event.target)`, which is just a few lines of code:

```js
Node.getNodeFromTarget = function (target) {
  while (target) {
    if (target.node) {
      return target.node;
    }
    target = target.parentNode;
  }

  return undefined;
};
```
You can find usages of it in the codebase.


Disclaimer: This is an unofficial, internal API, which could break in future versions when internal changes are made.

**Comment by rodrigosalinas** [comment]
Thank you very much again @josdejong. I added a reference to Node inside JSONEditor, exported a new function in JSONEditor called getNodeFromTarget which just delegated the call to the Node.getNodeFromTarget function. It worked like a charm.

**Comment by PunKHS** [comment]
@rodrigosalinas could you please attach some piece of code that can demonstrate the drag&drop function in jsoneditor?
