### ISSUE TITLE
Incorrect data parsing of long type

### ISSUE THREAD

**Issue by summertian4** [josdejong/jsoneditor#546]
My input is 5000000000000000123, but each parsing is 5000000000000000123

<img width="1300" alt="qq20180626-155140 2x" src="https://user-images.githubusercontent.com/7870394/41897181-2e18557a-7959-11e8-97fc-35642f7fe7ef.png">

**Comment by summertian4** [comment]
I see this issue #231 .
So, Is this a problem that cannot be solved temporarily?

**Comment by josdejong** [comment]
It's indeed the same issue as #231, and unfortunately there is no workaround for it.

**Comment by josdejong** [comment]
Will close this issue now in favor of #231.
