### ISSUE TITLE
 jsoneditor_1.default is not a constructor

### ISSUE THREAD

**Issue by BennieMeng** [josdejong/jsoneditor#548]
when i run product in the development mode. i find this issue. code follow:
import JSONEditor, {JSONEditorMode, JSONEditorNode, JSONEditorOptions} from 'jsoneditor';

this.jsonEditor = new JSONEditor(nativeElement, options, json);

ERROR TypeError: jsoneditor_1.default is not a constructor
    at AdvancedDeploymentTplComponent.initJsonEditor (advanced-tpl.component.ts:63)
    at AdvancedDeploymentTplComponent.tplDetail (advanced-tpl.component.ts:40)
    at ListDeploymentComponent.deploymentTplDetail (list-deployment.component.ts:117)
    at Object.eval [as handleEvent] (ListDeploymentComponent.html:98)
    at handleEvent (core.es5.js:11998)
    at callWithDebugContext (core.es5.js:13467)
    at Object.debugHandleEvent [as handleEvent] (core.es5.js:13055)
    at dispatchEvent (core.es5.js:8614)
    at eval (core.es5.js:9228)
    at HTMLAnchorElement.eval (platform-browser.es5.js:2648)

**Comment by josdejong** [comment]
How can I reproduce your issue?

I've just tried in a plain `create-react-app`, there you can load the JSONEditor like:

```js
import JSONEditor from 'jsoneditor'
import 'jsoneditor/dist/jsoneditor.css'
```

**Comment by josdejong** [comment]
Are you using TypeScript? I'e stumbled across similar issues with mutliple modules in TypeScript recently. There is an issue when these modules use commonjs exports and have no `default` export. A workaround that I used is to use `require` instead of `import`:

```js
// tslint:disable-next-line
const myCommonjsModule = require('myCommonjsModule')
```

**Comment by josdejong** [comment]
I've tried to reproduce this issue in a new TypeScript project, but without success.

If anyone finds a way to reproduce it we can open this issue again.

**Comment by Marshall-George** [comment]
@josdejong - I'm seeing this as well currently.  I'm implementing jsoneditor in a large Visual Studio application with webpack and Aurelia.  I'm not getting any compilation errors, nor any Typescript issues, but as soon as I try to instantiate a new editor, I'm getting the error.

**Comment by josdejong** [comment]
Thanks for reporting. I tried again in a TypeScript project and now I managed to reproduce it.

Can you try if a fix I did in `v5.24.6` for this fixes the issue for you?

**Comment by Marshall-George** [comment]
I'll install that version this morning and see if it fixes the problem.
Thanks for the quick response!

**Comment by Marshall-George** [comment]
Just tested it - success!  Thank you again for the fix and response!

**Comment by josdejong** [comment]
:+1:

**Comment by mercmobily** [comment]
@josdejong Hi there. I maintain another project, and users are complaining about the same problem. I think it has to do with typescript + webpack -- and I don't use neither of them.

I saw your fix here: https://github.com/josdejong/jsoneditor/commit/655990c2a7a812233f9f6d6a10b06d4589bbbf85#diff-19ff55e70a45ef317b8e93cb043c9b4c

I did the same for my project, but... would you happen to know why adding a "default" static property to the constructor would make a difference?

**Comment by josdejong** [comment]
@mercmobily it has something to do with how TypeScript compiles ES6 imports/exports to CommonJS and the other way around, see https://github.com/Microsoft/TypeScript/issues/2719. 

If I'm not mistaken, if you importing a default using ES6 like:

```js
import JSONEditor from 'jsoneditor'
```
And the library you're importing is CommonJS, it expects a `.default` property to resolve the default export. That's not how CommonJS default exports are exposed though so.

**Comment by mercmobily** [comment]
Thanks! Well my patch is effective by the looks of it!
