### ISSUE TITLE
why node just clear tdError if get multiple errors at same time

### ISSUE THREAD

**Issue by jincui** [josdejong/jsoneditor#549]
code in Node.js，I saw

```javascript
Node.prototype.updateError = function() {
  var error = this.error;
  var tdError = this.dom.tdError;
  if (if (error && this.dom && this.dom.tr && !tdError)) {
    ... // update tdError
 }
 else {
    if (tdError) { // clear current tdError
      this.dom.tdError.parentNode.removeChild(this.dom.tdError);
      delete this.dom.tdError;
    }
  }
```
*I know node will clear error status first when validate,  but when same node(same dom) get mulitple errors(even number) at same time,  here just clear old last error, but not update new error status!*

and in `treemode.js` - validate() function:
```javascript
this.errorNodes = parentPairs
      .map(function (pair) {
          return {
            node: pair[0],
            child: pair[1],
            error: {
              message: pair[0].type === 'object'
                  ? 'Contains invalid properties' // object
                  : 'Contains invalid items'      // array
            }
          };
      })
      .concat(errorNodes)
      .map(function setError (entry) {
        entry.node.setError(entry.error, entry.child);  // will invoke Node.udpateError
        return entry.node;
      });
```
example:  errorNodes: `([{ node: node1, error: error1 },  { node: node1, error: error2 }])`
error1 will set successfully, but when excute  error2, error1 will be removed, and error2 also not update

I use `propertyNames` valiate in my schema, and then got this problem. ::>.<::

**Comment by josdejong** [comment]
This was a bug which was fixed just a few days ago, see #544.
