### ISSUE TITLE
Feature: extend event behaviour

### ISSUE THREAD

**Issue by cristinabarrantes** [josdejong/jsoneditor#550]
Hi Jos,

   I would like to extend the functionality with a new API option to extend behaviour when an event is triggered. The reason to do it is because I would like to use internal structures and code when some type of events are triggered. I have done the changes locally so if you agree, I open a PR.

Best regards,
Cristina

**Comment by josdejong** [comment]
That could be interesting Cristina. Can you explain a bit more about the actual events that you needed and implemented?

**Comment by cristinabarrantes** [comment]
Hi Jos,

I think that the clearest way to show you this, is with a PR so I have just opened [one](https://github.com/josdejong/jsoneditor/pull/551).

Tell me if you want more information about it.

Thank you,
Cristina

**Comment by josdejong** [comment]
This issue should have been closed already long time ago...

**Comment by cristinabarrantes** [comment]
Ok, thank you!
