### ISSUE TITLE
save to disk > setting > default path ?

### ISSUE THREAD

**Issue by djmisterjon** [josdejong/jsoneditor#552]
hi, it possible to add a feature ? a **`default path folder`** for save disk a specific .json?
Also maybe a global case for check: **`overwrite`** files if file already exist, For keep fast productivity.
it by default save in the chrome download folder, i need alway move file to the correct folder :)
thank, your app save me a lot time and are awesome.

**Comment by josdejong** [comment]
As far as I know a browser application cannot pass a default path when saving a file.

In most browsers, when saving a document for the second time, the browser will still remember the path that you used the previous time and will start there, so I think it's quite doable?

**Comment by djmisterjon** [comment]
@josdejong 
i use it like thats on my map editor when i need save a json to disk.
But i don't have a json editor like you.
```javascript
    function create_jsonData(options) {
        const data = [];
        TilesMap._objSprites.forEach(e => {
            const d = spriteToJson(e);
            data.push(d);
        });
        const path = `data/Map${$gameMap._mapId.padZero(3)}_sprites.json`; // Map001_sprites.json
        const fs = require('fs');
        const content = JSON.stringify(data, null, '\t'); //human read format
        fs.writeFile(path, content, 'utf8', function (err) { 
            if(err){return console.log(err) }
            console.log('complette: ', err);
        });
   };
```
Maybe you can look to add nwjs and node module.

**Comment by josdejong** [comment]
I'm not sure whether I understand you, the example you give is about a server side node js application, not about a client side web application like JSON Editor Online. This would only work if I create an Electron or nwjs desktop application but right now I don't have such intentions.
