### ISSUE TITLE
Please simply 301 redirect instead of this message

### ISSUE THREAD

**Issue by RobThree** [josdejong/jsoneditor#553]
http://www.jsoneditoronline.org/

![image](https://user-images.githubusercontent.com/607888/42380537-8d8a9126-812e-11e8-9451-00f2e062177b.png)

Could you please do a [301 redirect](https://en.wikipedia.org/wiki/HTTP_301) instead of this annoying message? My browser somehow always tries to visit www.... even if I explicitly enter without the www. I know the problem is in my browser (and should be looked at / fixed) but on your end there's no need for the message when a redirect could be done immediately. I'm having high hopes of this issue being fixed about a thousand times quicker than trying to move a major browser vendor to look into this issue...

**Comment by josdejong** [comment]
I've never heard of browsers automatically prefixing a url with `www.`, that must be annoying. I guess there are quite some websites out there that don't have a www version so do all of these websites break on your browser?

This 301 solution is not a trivial change, see https://github.com/josdejong/jsoneditor/issues/529

**Comment by RobThree** [comment]
> I've never heard of browsers automatically prefixing a url with www., that must be annoying

It's not "just some obscure browser"; it's (the latest and greatest) Chrome (67.0.3396.99 (Official Build) 64-bit). Only 2 plugins: LastPass and AdBlock Plus (and both have been ruled out by disabling).

> I guess there are quite some websites out there that don't have a www version so do all of these websites break on your browser?

Nope. None. Just jsoneditoronline.com

![problem](https://user-images.githubusercontent.com/607888/42437004-ff5fc666-835b-11e8-934c-56929e68d684.gif)
(Sorry, didn't have screen recorder software installed)

I'm pretty sure it has cached a naked domain to www redirect or something. But clearing caches etc. didn't help either. And, again, this is the only site that does it, I have no problem with naked domains elsewhere.

**Comment by djmisterjon** [comment]
https://jsoneditoronline.org/

**Comment by josdejong** [comment]
That's really odd. Does it only happen only with Chrome, or also on other browsers? In the latter case it maybe something DNS related? Clearing DNS cache on your computer should help then.

**Comment by RobThree** [comment]
This happens on my main PC but also on my Macbook Air and on another PC. All three use the same Chrome account (synchronized) so I'm pretty sure it's somewhere in the account. It also happens in "private mode". And to be clear; one of the Chrome PC's is at work and the MacBook air's Chrome and the other PC Chrome are at home. That almost entirely rules out DNS issues (different ISP's, different DNS servers, different operating systems and different caches).

Again; I'm quite sure it's somewhere deep within my account / settings somewhere but I can't find it and I have too much stuff in it to reset it. So that was why I was hoping a 301 redirect would be possible. If it's not, no problem, it's just me experiencing this, I understand you not wanting or being able to fix this.

**Comment by RobThree** [comment]
Uh, okaaaay... well this is interesting. I just fired up Safari on my MacBook pro which I rarely, very rarely ever, if at all, use and it redirected to www too?

**Comment by josdejong** [comment]
argh :roll_eyes: that sounds even crazier.

I agree that having full support for auto redirect from www to the url without (keeping any query parameters intact) but I simply lack the time on short term to migrate the website, I'm sorry :(

**Comment by RobThree** [comment]
No worries; again, the problem is very likely on my side. I'll live with it 😉 

Thanks for answering and considering! 👍

**Comment by josdejong** [comment]
:+1: 

Just stick with IE then ;)

**Comment by RobThree** [comment]
😂
