### ISSUE TITLE
Final build files size

### ISSUE THREAD

**Issue by netojose** [josdejong/jsoneditor#554]
Hi, looking in your online example http://jsoneditoronline.org/ , I looked at the files size, and I found:
* app.min.js 203kb
* app.min.css 7.4kb
* all site 223kb

But, when I look at [project dist folder](https://github.com/josdejong/jsoneditor/tree/master/dist),  I found files larger:

- app.min.js 736kb
- app.min.css 31kb

And my final build is very big. So, how I can use the jsoneditor like you, how your final build is smaller than github project source?

Thanks

**Comment by josdejong** [comment]
I think you're comparing the minified+gzipped version of app.min.js (203 kb) with the minified but _not_ gzipped version jsoneditor.min.js (736 kb)

If you compare minified+gzipped versions in both cases you get something like:
jsoneditor.min.js 196 kb
app.min.js 206 kb

If you need a smaller version of the jsoneditor, you can see if the minimalist version is suitable for you, this excludes the code editor and JSON Schema validation and is about 67 kb (minified+gzipped).
