### ISSUE TITLE
Scrolling scrolls data outside of right panel.

### ISSUE THREAD

**Issue by CarmeNima** [josdejong/jsoneditor#557]
When you open and close children, if you scroll, the data is getting scrolled outside of the right panel.
Video: http://recordit.co/X2InvnGmXm

**Comment by josdejong** [comment]
ouch, that's ugly! I think this is a regression introduced in the latest version. Will fix it asap, thanks for reporting.

**Comment by josdejong** [comment]
@CarmeNima this should be fixed in the latest version, can you give that a try? Refresh your browser and check whether version 4.6.1 is mentioned at the bottom of the web application.
