### ISSUE TITLE
Allow invalid json with set or setText

### ISSUE THREAD

**Issue by taditdash** [josdejong/jsoneditor#559]
The purpose of the work I am doing is to allow users to be able to correct the json blocks. If the block is invalid, I cannot use `set` method as I don't have a valid json.

However, if I use `setText` (which allows me to populate the invalid text), it ends up showing the json with newline and carriage returns, which totally ignores the spacing and indentations something like below.

![image](https://user-images.githubusercontent.com/11786875/43647894-94def2a8-9756-11e8-8ea1-def54bc124bf.png)

What I want is the following with validation error so that user knows it is invalid and can work on it to make it valid:
![image](https://user-images.githubusercontent.com/11786875/43647997-d1c7200a-9756-11e8-8dbc-18546e7e61f5.png)

Hope it is clear. Please help!

**Comment by josdejong** [comment]
I think you have an issue with escaping your code. See what you get back when you call `getText()` when having the contents of your second screenshot and compare it with what you have in your first screenshot.

**Comment by taditdash** [comment]
The first case when I do `setText()`, then `getText()` shows me the following:
![image](https://user-images.githubusercontent.com/11786875/43657667-1cc24cde-9774-11e8-8bce-c02e236e60c5.png)
Whereas if I do `set()` (with valid JSON and then make it invalid inside the editor), then `getText()` displays the following:
![image](https://user-images.githubusercontent.com/11786875/43657839-8f41a02a-9774-11e8-9cc8-2cf4dc8413ef.png)

**Comment by taditdash** [comment]
Okay, I guess I got it!

I was doing like this:

`var jsonEditor = new JSONEditor(container, options, jsonText);`

Now I removed the third parameter and used setText like below:

`var jsonEditor = new JSONEditor(container, options);
jsonEditor.setText(jsonText)`

Interesting!

**Comment by josdejong** [comment]
Ahh, that explains it. The third argument of `new JSONEditor(container, options, json)` expects a JSON object. You did pass a string, and a string is a valid JSON value. In the code editor, JSON contents will be stringified, hence the string input is enclosed in double quotes `"`, and all returns and double quote characters are escaped (simply `JSON.stringify(jsonText)`).
