### ISSUE TITLE
Feature request : JSON-schema (bidirectional)

### ISSUE THREAD

**Issue by Asc2011** [josdejong/jsoneditor#56]
Hello Jos,
and many thanks for the tree-editor. I recently integrated ACE into futon and believed that i had to hack my own JSON-Treeview-component. I'd like to make futon smth. like a JSON-Schema-Workplace in the browser. I'm currenty working on validation of JSON-docs from the DB. This is pretty simple, but i'd love to make the editing of a JSON-Doc depending on a JSON-Schema.  E.g. a schema determines that certain properties at the node that i'm working on are legal and others may be not. I'd regard it a huge support for the author if the editing-environment would be able to suggest properties found in a schema. Kind of context-sensite snippets. Same way, if a new node is not allowed by the schema, give feedback and e.g. mark it red. 
I'd reckon, that this kind of user-support/app-feedback has not been done before. Since i lost hope, that any native editor-app (Textmate/BBEdit/SublimeText, etc.) will ever be able to offer such features, i guess a browser-based editor, closely coupled with a JSON-capable DB (couch/pouch whatever) really makes sense.
Another nice feature would be to be able to set the focus of the tree-view to a certain node.The result/error-report from a JSON-doc validation comes with a (schema-)path that specifies the offending JSON-element '/properties/size/type'(schemaPath) or just '/size'(docPath). A function to collapse all nodes is already there. Another function to expand all nodes along a given path would help. The path/schemaPath-result came from the tv4-validator.   

I'm looking forward to your next release,, greets Andreas

**Comment by John-Sheppard** [comment]
Hi Jos,
   First off, thank you for a very good editor.  Nice work, nice code.  Thank you for this contribution.
I wanted to see if the schema integration has gained any more traction.  We have lots of different Json objects that we need to provide editors for.  If this tool was extended so that we could set the schema for an instance of the editor then I think that would address most, if not all, of our needs.  Do you have a timeline for this feature or need help implementing it?

Thanks,

John

**Comment by josdejong** [comment]
Hi John, thanks. Yes, JSON schema support would be great. Unfortunately I haven't found time for this yet, and I don't expect to have time for it on short term. Help would be very welcome!

**Comment by josdejong** [comment]
I will close this issue in favor of #13
