### ISSUE TITLE
Does it support the full screen?

### ISSUE THREAD

**Issue by sobird** [josdejong/jsoneditor#561]

**Comment by josdejong** [comment]
? can you elaborate

**Comment by crossyou** [comment]
Sometimes I want to edit json data in full screen, so does jsoneditor support this feature?

**Comment by josdejong** [comment]
If you mean the web application https://jsoneditoronline.org, what you can do is make your browser full screen (F11), and you can drag the middle bar between the two panels horizontally to make one of the two panels full screen.

**Comment by wuxinyao** [comment]
if I want to set the panel full-screen when I use it as a Component in my project. Does it support?

**Comment by josdejong** [comment]
Full screen is not part of the component, but you can render the editor fullscreen yourself by making the `div` that you've used as container for the editor fullscreen (with CSS like `position: fixed, left: 0, top: 0, right: 0, bottom: 0, z-index: 1`)
