### ISSUE TITLE
How to add expandAll and collapseAll in node mode

### ISSUE THREAD

**Issue by hanweifish** [josdejong/jsoneditor#564]
We use mode 'code' in order to do some josn validation. 
However, if we want to have expandAll/collapseAll button for the editor, have any idea to handle it? Thanks.

**Comment by josdejong** [comment]
In the code mode there is no support for expanding/collapsing all nodes at once. There is only the compact/format buttons. I'm not sure if this is something that is supported at all by the Ace editor that's behind it.

**Comment by hanweifish** [comment]
Thanks. In this case, since it collapse/expand the code when click the side bar on the code mode,  is that possible to add the expandAll/collapseAll automatically based on the click event. How this click event happen to works with ace editor? 

You mentioned the  compact/format buttons, but I cannot find them in the api reference, do you have more info about them? Thanks.

**Comment by josdejong** [comment]
I'm not exactly sure what you mean. What do you mean with "the click event"? 

As for the format/compact buttons: that's simply the buttons top left of the code/text mode. There is also corresponding metods `compact()` and `format()` when in code/text mode (see docs).
![image](https://user-images.githubusercontent.com/568626/44052483-017baa08-9f3d-11e8-9563-eaf559978306.png)

**Comment by hanweifish** [comment]
Thanks. The 'click' means the manually trigger the 'expand/collapse' for specific node, 
![image](https://user-images.githubusercontent.com/7715770/44057126-17c1cefc-9eff-11e8-9efe-d72a17af9528.png), via clicking the Inverted triangle icon. 

If we want to implement them, not sure it is the right solution, like using: 
https://github.com/ajaxorg/ace/blob/master/lib/ace/edit_session/folding.js#L648

**Comment by josdejong** [comment]
Ah, ok, I understand you. 

I guess you will first have to find out if Ace editor supports programmatically expanding or collapsing these nodes. You can access the ace Editor in the JSONEditor via `myJSONEditor.aceEditor` to try out.

**Comment by hanweifish** [comment]
Yes. It works for me with foldAll and unfold method in Ace editor. Thanks.

**Comment by heshangamage** [comment]
Hi @hanweifish and @josdejong  can u guys explain how this worked. I am facing the same issue. i want to introduce button for expand and collapse programmatic in in editor code mode. I tried to with
let event: keyBoardEvent = new keyBoardEvent("keydown",{key='0',  altKey=true});
element.dispatchEvent(event);
event the event trigger correctly as same as manual key press. editor not collapsing
