### ISSUE TITLE
When switching modes, and clicking on current mode, mode button dissapears

### ISSUE THREAD

**Issue by VeraZab** [josdejong/jsoneditor#568]
You can see it in this example.
https://github.com/josdejong/jsoneditor/blob/master/examples/03_switch_mode.html

When in mode 'tree', and clicking on mode 'tree' again, the mode button disappears.
Same happens for modes Form and View.

**Comment by josdejong** [comment]
ouch! thanks for reporting Vera. I can indeed reproduce this issue. 

Shouldn't be difficult to fix, I hope to look into it coming weekend.

**Comment by josdejong** [comment]
This should be fixed now in `v5.24.1`
