### ISSUE TITLE
feature request: turn off draggable mode and context menu

### ISSUE THREAD

**Issue by VeraZab** [josdejong/jsoneditor#570]
Would it be possible to add a boolean flag to turn off draggable mode and context menu mode.
To just have a foldable json tree like so
![screen shot 2018-08-23 at 10 28 37 am](https://user-images.githubusercontent.com/4257572/44531901-da865080-a6bf-11e8-915e-8a70a9099a24.png)

I'm currently doing this with very ugly css, that also makes the custom validation popup not always appear very elegantly..

Thank you!

**Comment by josdejong** [comment]
What you ask looks very much like the `form` mode, which removes draggable and context menu, and also makes all field names readonly. Is `form` mode suitable for you?

**Comment by VeraZab** [comment]
Oh, I'll check that out, thanks!
