### ISSUE TITLE
Error when trying to user getBoundingClientRect

### ISSUE THREAD

**Issue by victoramsantos** [josdejong/jsoneditor#573]
This feature was working well yesterday.
When I trying to click in the bounding icon, nothing happens.
This exception is thrown:
app.min.js:18 Uncaught TypeError: Cannot read property 'getBoundingClientRect' of undefined
    at n.show (app.min.js:18)
    at HTMLSpanElement.o.children.length.a.onclick (app.min.js:19)

**Comment by josdejong** [comment]
Thanks for reporting @victoramsantos . How can I reproduce this issue exactly? Where to click? Can you also force a refresh in your browser (Ctrl+F5) to make sure it's not an outdated or half updated version running)?

**Comment by josdejong** [comment]
Will close this now, without more information I can't do anything about it.
