### ISSUE TITLE
Hide the Sort and Transform buttons

### ISSUE THREAD

**Issue by MarkHerhold** [josdejong/jsoneditor#580]
In [version 5.19.0](https://github.com/josdejong/jsoneditor/blob/master/HISTORY.md#2018-07-11-version-5190), sort and transform options were added. While these are really cool options, I would like to hide them from users to keep the interface simple.

Are there plans to allow hiding the sort/transform buttons via the options object?

Thanks for your time and the awesome module!

**Comment by josdejong** [comment]
I had no plans to disable this but we can add two options for that.  

For the time being: it should be possible to hide the buttons from the main menu and context menu using CSS (`display: none`)

**Comment by tanmayrajani** [comment]
This can probably be closed since it was implemented in the PR above

**Comment by MarkHerhold** [comment]
Thank you @tanmayrajani
