### ISSUE TITLE
changeAnnotation event problem

### ISSUE THREAD

**Issue by Stenudd** [josdejong/jsoneditor#582]
It is possibly and fairly easy to replicate this bug

open 03_switch_mode.html
switch to code mode
replace everything with "{},"
now remove the comma (with backspace for example) and close after restore the comma (by pressing comma or ctrl+z)
now if you timed that correctly you will have a mismatch between annotations and the status bar (parseErrorIndication)

I think this is a bug, I haven't been deep diving into the code to see whats happening but I suspect the debouncer to be part of the problem? Or is there any asynchronous race condition?

If you vary the timing between removing the comma and restoring it you will notice you get different results, listening on changeAnnotation event I can see the following scenarios happening

1: as above, I get two events which seems out of order, the first event containing the error and the second one with an empty list, the time between the events are less than 50ms, ~20-30ms

2: if you restore the comma extremely fast you will also get two events, the same as above, but in the right order, same timing between them as scenario 1, ~20-30ms

3: if you remove it and wait for about 150-200ms before putting it back you get 3 events, first empty, second containing error and third empty as well, first event coming at time 0, second ~50ms after and third >~150ms after the first one

4: if you wait any longer you get 4 events, starting with 2 empty ones for removing the comma and same as in scenario 3 second one comes ~50ms after the first one, when restoring the comma you get 2 more events, 50ms timing between them, first empty, second with errors as expected

I can also confirm that the mismatch does not seems to happen for brace in itself, https://thlorenz.com/brace/
you can test the exact same thing in the upper right box, never got it to misbehave

**Comment by meirotstein** [comment]
@Stenudd @josdejong I will have a look

**Comment by josdejong** [comment]
@meirotstein I may have found a solution for this issue, see #582

**Comment by meirotstein** [comment]
@josdejong cool!

**Comment by Stenudd** [comment]
I could have gave more details on how it is replicated if I knew you were stuck with that :) good to see there are progress being made with this and that disabling the validating debouncer makes the problem go away, is it possible to do with options?

**Comment by josdejong** [comment]
@Stenudd you could override debouncing by:
```js
editor._debouncedValidate = editor.validate
```
but this could lead to performance degradation (the debounce is there for a reason).

**Comment by josdejong** [comment]
@Stenudd this issue should now be fixed in `jsoneditor@5.24.7`, thanks to the fixo from @meirotstein.
