### ISSUE TITLE
onChange detects if node order changed

### ISSUE THREAD

**Issue by ohabash** [josdejong/jsoneditor#583]
I am trying to change a sort value on a node object if my user changes the node order. is something like the following possible?

```
onChange: function (changed) {
  if(changed === 'moveNodes'){
  	this.updateSortValues()
  }
}
```

**Comment by josdejong** [comment]
You could detect changes in the order of array items by comparing the current and previous version of the JSON document. Object properties on the other hand are officially unordered in JSON, that would be tricky.

**Comment by ohabash** [comment]
@josdejong thank you. Im wondering if there are any example use cases of the drag to order functionality — it doesnt seem like there is any programatic purpose.

**Comment by ohabash** [comment]
@josdejong I see now. Like you said; changing the order of an obj cannot be saved, only arr. onChange I would like to detect the visible order of the objects so that i can use the values in `obj['sort'] `. Any tips on where to start with this?

**Comment by josdejong** [comment]
I'm not sure what you mean with "values in `obj['sort']`" but if you need to know the order of the properties of an object inside the editor you will have to hack into the editor. The editor has an internal property `node`, and each node which is an object or array has a property `childs` (an array). That way you could iterate over your nodes/childs to figure out the order.

```
editor.node.childs[7].childs[2]
```

Disclaimer: accessing `node` and `childs` and everything is internal API which could change in future versions of the editor without notice, so if you depend on that your code can break some day.

**Comment by ohabash** [comment]
Thank you. This is what im doing. Every time the editor detects a change the `setOrder` function will add a key called "order" on all the top level nodes. Now if i were to save what is in the editor to my db the order will be set so my users can drag and drop to re-order their data

```
initEditor() {
	const self = this;
	const container = document.getElementById("jsoneditor");
    const options = {
        mode: 'tree',
        modes: ['code', 'tree'], // allowed modes
        sortObjectKeys: false,
        onChange: function () {
    		self.setOrder();
        },
    };
    this.editor = new JSONEditor(container, options, this.data);
}

setOrder() {
	let json = this.editor.get();
    this.editor.node.childs.map( (it, i) => {
    	json[it.field]['order'] = i;
    });
    this.editor.set(json); // I have a save button on the editor
}
```

**Comment by josdejong** [comment]
:+1: thanks for sharing your solution. Will close this issue now.
