### ISSUE TITLE
textmode.js validation problem - console errors

### ISSUE THREAD

**Issue by millerlight** [josdejong/jsoneditor#590]
textmode.js validation crashes in line 732 when there is no parseErrorIndication available.

so i added
    if (this.getText() && this.parseErrorIndication) { ...

to get rid of the console errors.

btw. there must another way then to put all the stuff in try/catch blocks...

**Comment by josdejong** [comment]
Thanks for reporting, fixed it in https://github.com/josdejong/jsoneditor/commit/7d2d669191d0d196e60bd08274cf8bbdf55a242d.

It's indeed good to be careful where to use try/catch. I think it makes sense here though, the `this.get()` can fail when the editor does not contain a valid JSON object. But if you have an idea for improvement I would be glad to hear :)

**Comment by josdejong** [comment]
Should be fixed now in `v5.25.0`.
