### ISSUE TITLE
Template schema validation

### ISSUE THREAD

**Issue by nehru** [josdejong/jsoneditor#592]
{
  "outerValue1": 1,
  "outerValue2": 2,
  "objA": {
    "value1": 10,
    "value2": 20,
    "value3": 30,
    "objB": {
      "value4": 40,
      "value5": 50
    }
  }
}

If the append template in jsonEditor contains an object objB as "{} addObj". How to implement a schema validation if objB is attached anywhere in the json then it must show invalid message. objB must be inside object objA. If it is outside objA or any other place, then jsonEditior must show invalid message.

**Comment by josdejong** [comment]
Hm, I'm not sure if you can do that with JSON Schema. 

You could implement your own custom validation though, see this example: https://github.com/josdejong/jsoneditor/blob/master/examples/18_custom_validation.html
