### ISSUE TITLE
JSON syntax validation

### ISSUE THREAD

**Issue by kranack** [josdejong/jsoneditor#593]
In the Code view, I can't write attributes like in Javascript (without the double quotes) which is great and normal.
But if I write really fast 2 letters in the editor, I can have something like this with no errors : 

![capture d ecran 2018-10-19 a 17 19 09](https://user-images.githubusercontent.com/2787828/47227741-d9be2200-d3c3-11e8-8a02-adf0f5a81e2b.png)

Of course when I'm doing another change (delete or add a new character), the editor detects this as a syntax error.

I was on `5.23.1` but it's still happening on `5.24.6`

**Comment by josdejong** [comment]
Thanks for reporting @kranack. This sounds very similar to #582, which was fixed almost two weeks ago in v5.24.7. Can you check whether this issue is fixed in the latest version?

**Comment by kranack** [comment]
Thanks for your response @josdejong. It seems to be same issue indeed, I've downloaded the last version on npm `5.24.7` and it worked as expected !

Thanks again for the reply !

**Comment by josdejong** [comment]
Good to hear, thanks for the update
