### ISSUE TITLE
Advertisement video flickering.

### ISSUE THREAD

**Issue by songoo** [josdejong/jsoneditor#594]
Advertisement video on the top right corner (one with a bird flying into water) keeps refreshing endlessly after 3s. Bird does not have even time to hit water :) . But moreover its pretty disturbing to have this flickering event next to jsons :)

**Comment by songoo** [comment]
Nn, its not complaining about ad, its bugged ad see video - https://drive.google.com/open?id=1op_e3z8zgQK6I05rTKpFwCcYM7oHD2iP

**Comment by josdejong** [comment]
@songoo I got feedback from FreeStar, the ad you saw is "a video ad running out of a normal ad slot. It looks like this was just an isolated incident with a broken creative". 

I guess it should not happen again.
