### ISSUE TITLE
Tool tip windows not closing from editor mode selector

### ISSUE THREAD

**Issue by dvstans** [josdejong/jsoneditor#597]
When using the mode select widget, mode-specific tool tip windows will open when you mouse over each of the options shown in the drop-down list. When an option is selected while a tool tip is visible, this tool tip will remain visible forever. Repeating this adds additional tool tip windows that remain visible.

Using latest master branch of jsoneditor. The instance of the json editor is contained in a column-oriented flexbox div inside of a jQuery-ui dialog. This has been seen on Google Chrome ver 70.0.3538.67 and Firefox ver 63.0 both under Ubuntu 16.01.

**Comment by josdejong** [comment]
Thanks for reporting @dvstans . I tried to reproduce your issue in one of the examples that comes with JSONEditor (examples/03_switch_mode.html), but I don't know how to reproduce this. Can you create a minimal example which demonstrates the issue?

**Comment by dvstans** [comment]
> Thanks for reporting @dvstans . I tried to reproduce your issue in one of the examples that comes with JSONEditor (examples/03_switch_mode.html), but I don't know how to reproduce this. Can you create a minimal example which demonstrates the issue?

I just tried the same example and it works as expected; however, what I notice is that the tool tip windows resemble the styling of the editor. In my test case (with jquery-ui), the tool tip windows are styled as jQuery-ui widgets. This makes me wonder if jQuery-ui is somehow intercepting or overriding the tool tip code in jsoneditor. I will create a jQuery-ui based example and see if I get the same results.

**Comment by josdejong** [comment]
Just to be sure we're on the same page: with "tool tip windows" you mean the title that you see when hovering a menu item? Like the text "Switch to plain text editor" in the screenshot below?

![image](https://user-images.githubusercontent.com/568626/47675874-608caf00-dbbb-11e8-8695-abfab8d3ded1.png)

This yellow tooltip is just a plain and simple "title" attribute on the menu items, it is rendered by the browser.

**Comment by dvstans** [comment]
Yes - that's what I'm referring to.

**Comment by josdejong** [comment]
Well, there is no HTML or CSS involved in this title, so I guess your jQuery is replacing plain "title" attributes with styled ones or something like that (maybe https://jqueryui.com/tooltip/?). So you will need to figure out how to clean them up again or prevent having jquery manipulate the title attributes inside the editor.

**Comment by dvstans** [comment]
I've verified that it is definitely the jQuery-ui tooltip function causing the problem. I don't know what their function does besides adding styling to the tooltip window, but it's certainly causing the problem. (My guess is they are intercepting events and/or creating timers that are not working in this case.)
