### ISSUE TITLE
Search field can't be focused in object view

### ISSUE THREAD

**Issue by maiscourt** [josdejong/jsoneditor#598]
When clicking on the search field, cursor doesn't set into it.
However, clicking on the magnifier button works as expected.

**Comment by josdejong** [comment]
@maiscourt do you mean that you can't get the focus to the search field, or that you can't move the focus to say the first search result to start typing there?

**Comment by maiscourt** [comment]
@josdejong first one

**Comment by josdejong** [comment]
Ah, now I understand what you mean! that's an odd bug! Thanks for reporting

**Comment by josdejong** [comment]
Should be fixed now in `v5.26.1`

**Comment by sobolevskyfuncorp** [comment]
works now fine for me, thanks a lot!
