### ISSUE TITLE
Dynamically attach an object or array in the json

### ISSUE THREAD

**Issue by nehru** [josdejong/jsoneditor#599]
Is there any api to attach an object or array or key value dynamically in the json object using a mouse click. Is there any samples code. Looking for a function to attach an object at particular node using click event.

Thanks

Nehru

**Comment by josdejong** [comment]
There is no API for this, though you can listen for mouse click events using `onEvent`, and you can dynamically change (part of) your JSON without losing the state of the editor using `.update(json)`.
