### ISSUE TITLE
Get / GetText - Returning DOM Text In Some Cases

### ISSUE THREAD

**Issue by Marshall-George** [josdejong/jsoneditor#601]
This one is a bit weird.  I've modified the Node.js a little to include an 'Add' button on the header row of an array.  I'm using the 'Form' mode to keep users from making a mess of the JSON that we're going to save as the data is relational.  I'm also using schemas from our backend code as the objects displayed in the control can vary, and it also allows us to pass customized title values for the fields.

This is the JSON definition for the object I'm having problems with.

{
modelName: string,
modelYear: int
groupName: string,
trimCodes: [ { trimCode: string } ]
}

Displayed:
{
Model Name:  'model name',
Model Year: 12345,
Group Name: 'group name',
Trim Codes: [] <Add Button>
}

I setup the 'add' button on 'TrimCodes' for adding a new value to the array.  The click event is bound and triggers as expected.

When I click the 'Add' button, the get() method is called to retrieve the current JSON.  When I check the JSON, the object changes to:

{
modelName:  string,
modelYear: int,
groupName: string,
Trim Codes: [ { trimCode: string } ]
}

I've found what is happening is there is a call to the treemode.get method, where a call to node.blur() occurs.  After that blur event fires is when the JSON gets changed.

I'm not sure if the call to treemode.get is even supposed to happen here - I have the editor setup for 'form'.

**Comment by Marshall-George** [comment]
Sure - I know that my message was a bit convoluted.  I'll walk through the
code from the blur event and see if I can detail it out some more.  I can
get a workaround for now but wanted to let you know about the issue.

**Comment by Marshall-George** [comment]
Ok - I found where it gets changed.  When
calling Node.prototype._getDomField, there is an evaluation of:

if (this.dom.field && this.fieldEditable) {
   this.fieldInnerText = util.getInnerText(this.dom.field);
}

It's passing on the if statement, so it's returning the inner text instead
of the field value.  So in my example I posted, it returns 'Trim Codes',
and then the inner array.  It should return 'trimCodes' for the key there.

I hope that makes sense!

**Comment by Marshall-George** [comment]
I just tested changing this in the Node.js file.

Node.prototype._getDomField = function(silent) {
//  if (this.dom.field && this.fieldEditable) {
  if (this.dom.field && this.contentEditable) {
    this.fieldInnerText = util.getInnerText(this.dom.field);
  }

When I changed it to 'contentEditable' it worked (it was undefined but got
around it).

I think the issue is that while the array itself is 'editable', it should
be returning that and not the parent.

**Comment by josdejong** [comment]
I know the code and why it's there. I'm not sure what I can do though - this code is there for a reason.

**Comment by Marshall-George** [comment]
It's probably for when the editor is set in tree mode.  I'll work with it a
little more and see what I can figure out.

**Comment by josdejong** [comment]
:+1:
