### ISSUE TITLE
Remove Blank Strings

### ISSUE THREAD

**Issue by DanielJDufour** [josdejong/jsoneditor#602]
Hi, @josdejong .  Love your project!  We are now using it at code.gov for our schema validator https://code.gov/about/compliance/inventory-code/validate-schema 

I was wondering what you would think about adding a configuration option to add a button in Text Mode that would "remove optional fields with blank strings"?  Or instead of a button, it could include this removal in the sanitize function as a part of repairing?

It could be configured like the following:
```
const options = {
  mode: 'text',
  removeOptionalBlanks: true
}
const editor = new JSONEditor(container, options)
```

Open to your thoughts and happy to submit a PR if you think it is a good idea! :-)

**Comment by josdejong** [comment]
Thanks for your kind words @DanielJDufour .

I understand your use case. I'm not sure though whether it is common enough to build a solution for, it sounds quite application specific. 

You could quite easily override the `editor.repair` function to extend it your desired behavior (removing empty optional properties): 
https://github.com/josdejong/jsoneditor/blob/9ac82e24d2eb4d7ef99290bbb61b71e8d3bcdf9e/src/js/textmode.js#L597-L604
Or hack an extra button into the main menu to cleanup these properties or something like that.

**Comment by DanielJDufour** [comment]
@josdejong , thanks for the quick reply.  You bring up a good point.  Because your code is so well documented and organized, it won't be hard for me to modified the repair function or add an extra button for only our use case!  I'll close this issue now. Thanks and have a good day :-)
