### ISSUE TITLE
Set different font colors for certain JSON fields and values

### ISSUE THREAD

**Issue by maestr0** [josdejong/jsoneditor#603]
I want to build a JSON diff tool and I want it to look like the Github diff tool. In order to do that I need to conditionally set colors for certain JSON props and values (red and green).
There's a hacky way to do it using **this.jsoneditor.node.childs[0].dom.field.style.background = 'red';**
but the dom elements are only created for visible/expanded fields. So I have to expand all the nodes first to update the colors. It's not optimal. I wonder if there's any other way.

**Comment by maestr0** [comment]
I've added an ability to set a custom css class on each node. It solves my problem. Made a PR with my change. 
https://github.com/josdejong/jsoneditor/pull/604

**Comment by josdejong** [comment]
This feature has been implemented long time ago already, forgot to close this issue.
