### ISSUE TITLE
Addition of a "non-string" type

### ISSUE THREAD

**Issue by wernerstucky** [josdejong/jsoneditor#605]
Hi Jos

I'm using JSONEditor to work on some JSON files that have values that are later string interpolated.
So I might have a value like `"settings":<!--{$settings}-->`
The `<!--{$settings}-->` will get parsed out at run-time and replaced with a JSON object string.
Currently on the "Auto" type it converts this to : `"settings":"<!--{$settings}-->"`
So I end up with `"settings":"{"object_val1":"test"}"`

Could you maybe add an additional value type called "non-String" to force the editor to leave out the string denotation?
It might also be useful for people wanting to force a value to be a Number.

Regards

**Comment by josdejong** [comment]
@wernerstucky I'm not sure what you mean exactly, `"settings":<!--{$settings}-->` is no valid JSON. Something like `{ "settings": "<!--{$settings}-->" }` is valid JSON and leaves the text contents as is.

**Comment by wernerstucky** [comment]
Hi Jos

Sorry for the confusion.

Let me explain what I want to do in steps.

1. I have an invalid JSON document that has :
`"settings":<!--{$settings}-->`

This is invalid JSON I know.  But the resulting document will get passed through a template engine to replace all the `<!--{ $VAR }-->` markers and input either JSON or other variables.

2. The replacement variable for $settings would be something like this.
`{"object_var":"test"}`

3. After template interpolation I would get this (which would be valid JSON)
`"settings":{"object_var":"test"}`

It occurs to me that I could implement this within the templating engine which would probably be a better place to include this.
I think I'll try that first.

Thanks
