### ISSUE TITLE
Allow adjust MAX_VISIBLE_CHILDS or add an option to turn off showMoreNodeFactory

### ISSUE THREAD

**Issue by kutu** [josdejong/jsoneditor#614]
Hello,

I have around 200 items in my json, when I scroll down to letter Z, and `update` my json (I do this often) with new data, list cuts down with "Show more" option.

I tried to hack it with
```
jsonViewer = new JSONEditor... 
jsonViewer.node.MAX_VISIBLE_CHILDS 
```
but that didn't help

If you don't wanna add this as an option, please tell me how to adjust this value, without changing source code.

Thanks.

**Comment by josdejong** [comment]
I'm indeed not sure if I would want this as an option, though it may be worth considering.

As a hack, you could do:

```js
jsonViewer.node.constructor.prototype.MAX_VISIBLE_CHILDS = 1000
```
Not guaranteed that this will keep working in the future though...

**Comment by kutu** [comment]
unfortunately, it didnt help aslo

even so this code shows 1000
```js
console.log(jsonViewer.node.MAX_VISIBLE_CHILDS)
```
after your's hack

**Comment by josdejong** [comment]
hm sorry. Can you try this?

```js
var editor = new JSONEditor(container, options);
editor.node.constructor.prototype.MAX_VISIBLE_CHILDS = 1000
editor.node.constructor.prototype.visibleChilds = 1000
```

**Comment by kutu** [comment]
its working, thanks

**Comment by josdejong** [comment]
:+1:
