### ISSUE TITLE
Deeply nested path of properties not fitting in navigation bar

### ISSUE THREAD

**Issue by joshkmartinez** [josdejong/jsoneditor#619]
When using *BIG* json files (mine is 2385 lines long) it is hard to see the list of nodes (under the search bar) when you select a node very deep into the json tree.  
like [**this**](https://i.imgur.com/1wWsZhC.png)
I think it would be helpful to make the list of nodes kind of like a carousel scroll thing so it is easier to see the list of nodes

**Comment by josdejong** [comment]
Thanks @joshkmartinez , you're right, when your deeply nested in a document, the path may not fit in the navigation bar.

@meirotstein do you have some ideas to improve this? Wrap to the next line or show ellipsis halfway the path or something?

**Comment by meirotstein** [comment]
@josdejong @joshkmartinez 
This is a bug. the navigation bar should always show the selected node - see [here](https://github.com/josdejong/jsoneditor/issues/443#issuecomment-332020010) the discussion we had about it in the past.
Let me look into it a bit, also if you think about a better approach - let me know.

**Comment by meirotstein** [comment]
@josdejong I had a bit of miss understood here - I thought that the selected node is not visible - which is a bug. however, this is not the case here.

The current approach trims the beginning of the path if it is not fit the navigation bar space and currently there's no way to move along it.

What I have in mind is when the path is trimmed to add arrows that allow to 'scroll' along the path. I think that two arrows in each direction are required - one for scroll and one for 'jump to start/end', something like that:
![image](https://user-images.githubusercontent.com/2209844/50729139-58159f00-113d-11e9-92ea-738dd93df088.png)

What do you think?

**Comment by josdejong** [comment]
@meirotstein sounds good, I'm ok with either solution you think is best. Curious what you come up with.

**Comment by josdejong** [comment]
I forgot to close this issue: improved navigation path is available since some days now in the latest version thanks to the PR of Meir (#628).
