### ISSUE TITLE
[Bug] Height exceeds container

### ISSUE THREAD

**Issue by blowsie** [josdejong/jsoneditor#621]
When using `style=height:800px` on my container, jsoneditor adjusts accordingly, but when in `code` mode, the height exceeds the container. Is this the expected behaviour?

![image](https://user-images.githubusercontent.com/308572/50601699-e0c9dc00-0eac-11e9-942b-d2022e5fd88a.png)

Related: https://github.com/josdejong/jsoneditor/issues/211

**Comment by blowsie** [comment]
Looking at the css, `jsoneditor-outer` has a height of 100% but, height is also being taken up by `jsoneditor-menu` and `jsoneditor-statusbar`.

Does it not make sense to use something like `calc` here?
```
height: calc(100% - 35px - 26px) 
```

**Comment by blowsie** [comment]
At the time of writing the version was at 5.10.1.
The bug is easily reproducible;
https://jsbin.com/vikasegumu/edit?html,output

But it appears to be fixed in latest versions.

In newer versions is there a way to show the status bar by default instead of it being hidden?

**Comment by josdejong** [comment]
Ah, that's good to hear. Thanks for your feedback.

The status bar is indeed always visible. The warnings are collapsed by default when in `code` mode (since it also shows the warnings inline), and expanded by default when in `text` mode.
