### ISSUE TITLE
Two instances of the JSON editor appearing on one page when only one should show?

### ISSUE THREAD

**Issue by Rytiggy** [josdejong/jsoneditor#622]
I was wondering if there was a way to only have one editor on the page at once. this is what it looks like now. 
![screen shot 2019-01-02 at 4 24 00 pm](https://user-images.githubusercontent.com/17414914/50613989-6f3e5d80-0ead-11e9-82a6-8939facadb80.png)

here is the code to generate it.
``` Javascript
   let JSONEditor = require('jsoneditor')

        // create the editor
    var container = document.getElementById("jsoneditor");
    var options = {  
      modes: ['code', 'form', 'text', 'tree', 'view'], // allowed modes
      onError: function (err) {
        alert(err.toString());
      },
      onModeChange: function (newMode, oldMode) {
        console.log('Mode switched from', oldMode, 'to', newMode);
      } 
    };

    var editor = new JSONEditor(container, options);
    editor.set(this.schema);

    // get json
    var json = editor.get();
```

**Comment by blowsie** [comment]
Hey, im also new to jsoneditor but you must have something else going on here.
You would need to post some HTML or something

**Comment by josdejong** [comment]
@Rytiggy can you post a full jsbin/jsfiddle/codesandbox demonstrating your issue? 

I think there is something else going on, can it be that your code is run twice or something? Have a look at the examples that come with JSONEditor, they all load just one editor.

**Comment by farwish** [comment]
Actually i also meat the problem on vue-router link in vue-ssr render. 
When come back from other router link (without whole page fresh).

See problem:
<img width="400" alt="2" src="https://user-images.githubusercontent.com/6552412/136661252-42697b53-c73d-4eca-b427-6cafa50d8ded.png">

I resolved it by check is there any child nodes in container.
<img width="400" alt="3" src="https://user-images.githubusercontent.com/6552412/136661550-40def885-26d7-453a-bcba-79e3321c62b1.png">

Now it become normal when come back from other router link. The site is https://tool.offso.com/json

Hope useful to you.
@Rytiggy @blowsie @josdejong

**Comment by farwish** [comment]
> @farwish is the JsonEditor destroyed when you unmount your component?

<img width="400" alt="5" src="https://user-images.githubusercontent.com/6552412/136665794-8543fe0d-67b2-4739-94f0-389d44348225.png">
The container is a little div template into .vue file. 

And no other vue lifecycle method beside `mounted` i write in this .vue file.

So, you mean maybe JsonEditor is not destroyed?   I thought it may be true.
That problem will appear again without above checking code.
