### ISSUE TITLE
Cannot parse draft-07 spec of JSON-schema (jsoneditoronline.org)

### ISSUE THREAD

**Issue by wongjn** [josdejong/jsoneditor#625]
Specifying the `$schema` key with value of `http://json-schema.org/draft-07/schema#` in a JSON schema throws the following error in jsoneditoronline.org:

> Failed to parse JSON schema: Error: no schema with key or ref "http://json-schema.org/draft-07/schema#"

Throws error:
```json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "properties": {
    "example": {
      "type": "string"
    }
  }
}
```

Fine here:
```json
{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "properties": {
    "example": {
      "type": "string"
    }
  }
}
```

**Comment by josdejong** [comment]
Thanks for reporting @wongjn . It could be that we should upgrade to the latest version of `ajv`, we should verify that first. Will be a breaking change (currently still working with `ajv@5`).

**Comment by josdejong** [comment]
@wongjn I've fixed this now in the web application (using the latest version of ajv there). Can you give it a try?

Still needs to be addressed for JSONEdtior itself, I've created a separate issue here: #635

**Comment by wongjn** [comment]
Seems like it works; nice.

**Comment by lnaie** [comment]
Now you could mention the version of supported schema draft as well in the front page or a link to that information. Thanks! :)

**Comment by Flydroid** [comment]
@josdejong This issue still seems to be occurring on the current  "10.1.0" version. 
Did ajv maybe break it again?

**Comment by josdejong** [comment]
@Flydroid `jsoneditor` is still using Ajv 6 and only supports `draft-04` and `draft-06`, see #1371. The successor of this library, [`svelte-jsoneditor`](https://github.com/josdejong/svelte-jsoneditor/) uses Ajv 8 and supports newer versions of JSON Schema.

**Comment by Flydroid** [comment]
Right, then i miss understood the other issues I had read. 
Will try svelte-jsoneditor.
