### ISSUE TITLE
min js file in /dist does not work

### ISSUE THREAD

**Issue by spnkr** [josdejong/jsoneditor#626]
i had to copy the source code from http://jsoneditoronline.org to get it to work. did not try to build from source.

![image](https://user-images.githubusercontent.com/11250/50808503-dce2f300-12cc-11e9-9201-448f829e846d.png)

**Comment by josdejong** [comment]
Did you download via npm? Please read the install instructions in the readme: https://github.com/josdejong/jsoneditor#install
