### ISSUE TITLE
Error when using draft-04 schemas for validation (jsoneditoronline.org)

### ISSUE THREAD

**Issue by andreasulmer** [josdejong/jsoneditor#629]
When using a draft-04 schema for validation, https://jsoneditoronline.org shows error
![image](https://user-images.githubusercontent.com/25357523/51176949-912cdc80-18be-11e9-925a-f04f6c68a76f.png)

#### reproduction:
1. Save new online document with content
```json
{
  "$schema": "http://json-schema.org/draft-04/schema",
  "properties": {
    "test": {}
  }
}
```

2. Add this file as schema in settings-> Add schema

3. When this file is checked for schema validation
-> 
* jsoneditor shows above error message `Failed to parse JSON schema: Error: no schema with key or ref "http://json-schema.org/draft-04/schema"`
* no validation happens

**Comment by andreasulmer** [comment]
In my setup (which loads jsoneditor.js from cdnjs) I can fix it by providing a custom Ajv instance that has the draft-04 metaschema added, as suggested [in the Ajv docs](https://github.com/epoberezkin/ajv#using-version-6).

```js
var ajv = new Ajv({});
ajv.addMetaSchema(draft04MetaSchema);
            
new JSONEditor(domNode, {
  ajv: ajv
  ...});
```

After this, `ajv._schema` holds both draft-06 and draft-04 metaschemas, and JSONEditor accepts schemas referencing both. 
(using jsoneditor@`5.27.0`, ajv @`5.5.2`)

---

So I guess the fix for jsoneditoronline.org could be to to initialize it with both 04 and 06 metaschemas (or more) by default.
Unfortunately at the momentI can not verify this, or provide a PR: so far I'm unable to get JSONEditor to run properly from the cloned src.

**Comment by josdejong** [comment]
Thanks @andreasulmer . I've updated the web application to use the latest ajv@6.7.0, and configured it to allow both draft-04 and draft-06. Can you give it a try?

Besides, we should update the version of ajv bundled with JSONEditor, that's still on ajv@5.5.2. Will be a breaking change.

**Comment by andreasulmer** [comment]
👍 the good: `draft-04` schemas now work for me.
❌ not-so-good: change seems to have broken support for `draft-06`.

I tested with 
```
{
  "$schema": "http://json-schema.org/draft-06/schema",
  "properties": {
    "test": {}
  }
}
```

which shows error `Failed to parse JSON schema: Error: no schema with key or ref "http://json-schema.org/draft-06/schema"`.

----

And out of curiosity: jsoneditoronline.org changes/commits are not tracked in this repo, right? Is there another repo for it? I was looking for your commit but couldn't find it.

**Comment by josdejong** [comment]
whoops! I thought I had tested draft-06 but apparently only tested draft-04 and draft-07. It should be fixed now, I added the draft-06 too when loading Ajv.

> And out of curiosity: jsoneditoronline.org changes/commits are not tracked in this repo, right? Is there another repo for it? I was looking for your commit but couldn't find it.

That's correct, the web application is located in a private repo. Only the JSONEditor library is open source.

**Comment by andreasulmer** [comment]
Can confirm both 04 and 06 now work as expected for me.
Thanks! 
Closing this as fixed.

---

...with a follow-up question:
Plans to add similar change-metaschema / multi-metaschema functionality to JSONEditor as well?
If not, maybe a note in the docs how to use JSONEditor with other schema(s) than the included default would be helpful?
