### ISSUE TITLE
Have you considered table editing use case?

### ISSUE THREAD

**Issue by anaran** [josdejong/jsoneditor#63]
Hi!

Perhaps I just missed this feature trying to find it in your docs/examples.

Editing of spreadsheet-like JSON data could be a great use of jsoneditor!

Is this already possible today?

Would you consider it for the future?

Some (read-only display) ideas may be had at following resources.

(I also opened https://github.com/marianoguerra/json.human.js/issues/15, then I found your issue entry there, so I came here because I like your integration with jsonlint very much)

See
https://developers.google.com/chrome-developer-tools/docs/tips-and-tricks#console-table

and the original
http://getfirebug.com/wiki/index.php/Console_API#console.table.28data.5B.2C_columns.5D.29
(see also http://www.softwareishard.com/blog/firebug/tabular-logs-in-firebug/)

**Comment by josdejong** [comment]
Rethinking this, I think it's a bit out of scope. I will close this issue now.

**Comment by josdejong** [comment]
This feature request is opened again and continued in #402.
