### ISSUE TITLE
[Question] Is advance search available with current version?

### ISSUE THREAD

**Issue by vikasgurjar** [josdejong/jsoneditor#634]
Is advance search available with current version?

I want to search for a path in the JSON. examle - Person.Name.Firstname

How can I do that?

_Originally posted by @vikasgurjar in https://github.com/_render_node/MDEyOklzc3VlQ29tbWVudDQ1NDcxNzk1NQ==/timeline/issue_comment#issuecomment-454717955_

**Comment by josdejong** [comment]
Let's continue discussion in #43
