### ISSUE TITLE
Upgrade to ajv@6

### ISSUE THREAD

**Issue by josdejong** [josdejong/jsoneditor#635]
Reminder for myself.

Will be a breaking change (there are API changes in Ajv)

**Comment by no1seman** [comment]
@josdejong, 
is it time to upgrade to ajv 6.10.0? I changed ajv version in package.json on 5.33.0 release, rebuild jsoneditor and looks like everything works fine including readonly/writeonly, regex checks and other stuff...
Also seems to me that it will be usefull to make Node._findSchema function from Node.js public or to pass to onEditable event handler node's schema data. Now I'm using the following code to prevent readonly items to be editable:
                                    onEditable: function({ path, field, value }) {
                                        if (path != null) {
                                            if (field != null) {
                                                var nodeschema = findSchema(config_schema, {}, path);
                                                if (nodeschema !== null) {
                                                    if (nodeschema.readOnly != null) {
                                                        if (nodeschema.readOnly == false) {
                                                            return { path, field: false, value: true };
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                        return { path, field: false, value: false };
                                    },
works also fine fully according to draft-07 json-schema spec.

**Comment by josdejong** [comment]
Yes definitely time to upgrade. I hope to find time for it the coming weeks.

**Comment by no1seman** [comment]
@josdejong,
good news, will wait for.

Here is modified **Node.prototype.updateDom** that uses schema node title if exist instead of node's name:
Node.prototype.updateDom = function(options) {
    // update level indentation
    var domTree = this.dom.tree;
    if (domTree) {
        domTree.style.marginLeft = this.getLevel() * 24 + 'px';
    }

    // apply field to DOM
    var domField = this.dom.field;
    if (domField) {
        if (this.fieldEditable) {
            // parent is an object
            domField.contentEditable = this.editable.field;
            domField.spellcheck = false;
            domField.className = 'jsoneditor-field';
        } else {
            // parent is an array this is the root node
            domField.contentEditable = false;
            domField.className = 'jsoneditor-readonly';
        }

        var fieldText;
        if (this.index != undefined) {
            fieldText = this.index;
        } else if (this.field != undefined) {
            **var fieldScheme = Node._findSchema(this.editor.options.schema, this.editor.options.schemaRefs || {}, this.getPath());
            if (fieldScheme) {
                if (fieldScheme.title) {
                    fieldText = fieldScheme.title;
                } else {
                    fieldText = this.field;
                }
            } else {
                fieldText = this.field;
            }**
        } else if (this._hasChilds()) {
            fieldText = this.type;
        } else {
            fieldText = '';
        }
        domField.innerHTML = this._escapeHTML(fieldText);

        this._updateSchema();
    }

    // apply value to DOM
    var domValue = this.dom.value;
    if (domValue) {
        if (this.type == 'array') {
            this.updateNodeName();
            util.addClassName(this.dom.tr, 'jsoneditor-expandable');
        } else if (this.type == 'object') {
            this.updateNodeName();
            util.addClassName(this.dom.tr, 'jsoneditor-expandable');
        } else {
            domValue.innerHTML = this._escapeHTML(this.value);
            util.removeClassName(this.dom.tr, 'jsoneditor-expandable');
        }
    }

    // update field and value
    this._updateDomField();
    this._updateDomValue();

    this._updateCssClassName();

    // update childs indexes
    if (options && options.updateIndexes === true) {
        // updateIndexes is true or undefined
        this._updateDomIndexes();
    }

    // update childs recursively
    if (options && options.recurse === true) {
        if (this.childs) {
            this.childs.forEach(function(child) {
                child.updateDom(options);
            });
        }
    }

    // update rendering of error
    if (this.error) {
        this.updateError()
    }

    // update row with append button
    if (this.append) {
        this.append.updateDom();
    }

    // update "show more" text at the bottom of large arrays
    if (this.showMore) {
        this.showMore.updateDom();
    }
};
In tree mode works fine.

**Comment by josdejong** [comment]
Thanks @no1seman for sharing your code!

**Comment by josdejong** [comment]
I've just published `v6.0.0` containing the latest version of `ajv@6.10.0`, and also use the JSON schema title as object name if available.

**Comment by no1seman** [comment]
@josdejong,

great, thank you for good jib, new major version is cool, but you added JSON schema title ONLY for root. Is it possible to add node naming logic not only for root, but for all nodes acoording to suggested logic? It wiil be useful if there's an option to choose JSON node name or SCHEMA node title.

Also, it wiil be good if you add suggested writeonly/readonly logic from the box....

**Comment by josdejong** [comment]
@no1seman every (nested) title is shown when you hover a node. All nodes but the root node have their property name or array index as name. The root node has no parent, so there the JSON schema title is displayed. Where would you like to display the titles of nested items?

**Comment by no1seman** [comment]
@josdejong,

let's just look at at example from here: https://jsonschema.net/

JSON with name:
....
  "**name**": "A green door",
....
SCHEMA:
...
"**name**": {
"$id": "#/properties/name", 
"type": "string", 
"**title**": "The Name Schema", 
"default": "", 
"examples": [
"A green door"
], 
"pattern": "^(.*)$"
},
...
JSON with title:
...
  "**The Name Schema**": "A green door",
...

I'm talking about ability to choose what to show  in JSON editor: name or title. This will be very useful when we have a JSON from API with non-human readable nodes name like: "Name1", "Name2"... "NameN", and using schema with such a functinality we can substite it by for example: "Fuul product name", "Short product name", ...., "Internal product name" instead of "Name1", "Name2"... "NameN".

Look at my code above, it's work fine for me, and also seems that it will be useful for other users of you lib.

**Comment by josdejong** [comment]
I understand you. I'm cautious with this idea because it replaces actual data from the JSON object (ie. `name`) with a human readable label (ie. `The Name Schema`). At the core the editor is meant as an editor to edit JSON data, not as a form generator. So I prefer having information from the JSON schema _alongside_ the data, to enrich it and make your life easier, rather than replacing data.

We could think about a hook though allowing you to customize how fields and values are rendered, that would allow you to these kind of thinks like replacing a property with a schema title.

**Comment by no1seman** [comment]
Hook? Not good seems to me. May be boolean option and simple logic on render event - in method Node.prototype.updateDom, as I've already suggested?

**Comment by josdejong** [comment]
Here I explain what I mean: #738. 

I'm not sure the behavior you want is a use case generic enough to built it into the editor itself. Allowing you to achieve what with a custom hook yourself is a great solution then. And if it turns out to be a much requested feature we can again consider to built it into the editor itself.

**Comment by no1seman** [comment]
You are right, in editor mode logic that I suggested will be quite strange.
Ok, let it be so
Thanks in advance
