### ISSUE TITLE
Use brace instead of ace to integrate with commonjs

### ISSUE THREAD

**Issue by thlorenz** [josdejong/jsoneditor#64]
I created [brace](https://github.com/thlorenz/brace) by auto-refactoring the ace editor so it is common-js compat.

This would allow you to just `require` it when the code-editor is used instead of the user having to include extra script tags.
Additionally warning/error annotations will just work without the server having to provide the worker script (from the same domain) since the worker code gets inlined via  webworker `blob`.

So [this is what you'd get out of the box](http://thlorenz.github.io/brace/). -- `json` on the upper right.
You'll find more info on the brace repo.

It is not crucial, but a nice improvement IMHO.
If you are ok with this change, but too busy, I'm willing to submit a PR.

**Comment by josdejong** [comment]
@thlorenz I've finally given up on AMD and have just refactored JSONEditor to CommonJS, using brace. Works like a charm, thanks!

Let's see if this maybe resolves the Polymer issues too.

**Comment by thlorenz** [comment]
Awesome nice to see it happen :)
