### ISSUE TITLE
JSONEditor is not a constructor

### ISSUE THREAD

**Issue by MalikGitHub** [josdejong/jsoneditor#641]
I am using OpenUI5 framework.
I installed the files via npm install.

any idea why this is happening ? 

![jsoneditor](https://user-images.githubusercontent.com/34463240/52049045-b3705c80-2544-11e9-9aac-0aa5b50fe022.PNG)

**Comment by meirotstein** [comment]
@MalikGitHub did you put the jsoneditor path in the sap.ui.define of your module?

**Comment by MalikGitHub** [comment]
@meirotstein Yes I did

**Comment by meirotstein** [comment]
can you put your code here?
Try to put `node_modules/jsoneditor` in the path

**Comment by MalikGitHub** [comment]
/* global JSONEditor:true */
sap.ui.define([
	"com/inova8/lens/controller/BaseController", 
	"com/inova8/lens/jsonEditor/node_modules/jsoneditor/dist/jsoneditor"
],
function(Controller, JSONEditor) {
	"use strict";

	return Controller.extend("com.inova8.lens.controller.ConfigurationEditor", {

		/**
		 * Called when a controller is instantiated and its View controls (if available) are already created.
		 * Can be used to modify the View before it is displayed, to bind event handlers and do other one-time initialization.
		 * @memberOf com.inova8.lens.view.Settings
		 */
		onInit: function() {

		},

		/**
		 * Similar to onAfterRendering, but this hook is invoked before the controller's View is re-rendered
		 * (NOT before the first rendering! onInit() is used for that one!).
		 * @memberOf com.inova8.lens.view.Settings
		 */
		//	onBeforeRendering: function() {
		//
		//	},

		/**
		 * Called when the View has been rendered (so its HTML is part of the document). Post-rendering manipulations of the HTML could be done here.
		 * This hook is the same one that SAPUI5 controls get after being rendered.
		 * @memberOf com.inova8.lens.view.Settings
		 */
		onAfterRendering: function() {
			var container = this.byId("configurationEditor"); 
			var options = {};
			var editor = new JSONEditor(container, options);
			// set json
			var json = {
				"Array": [1, 2, 3],
				"Boolean": true,
				"Null": null,
				"Number": 123,
				"Object": {
					"a": "b",
					"c": "d"
				},
				"String": "Hello World"
			};
			editor.set(json);

			// get json
			json = editor.get();
		}

		/**
		 * Called when the Controller is destroyed. Use this one to free resources and finalize activities.
		 * @memberOf com.inova8.lens.view.Settings
		 */
		//	onExit: function() {
		//
		//	}
	});
});

**Comment by MalikGitHub** [comment]
/* global JSONEditor:true */
sap.ui.define([
	"com/inova8/lens/controller/BaseController", 
	"com/inova8/lens/jsonEditor/node_modules/jsoneditor/dist/jsoneditor"

],

function(Controller, JSONEditor) {
	"use strict";

	return Controller.extend("com.inova8.lens.controller.ConfigurationEditor", {

		/**
		 * Called when a controller is instantiated and its View controls (if available) are already created.
		 * Can be used to modify the View before it is displayed, to bind event handlers and do other one-time initialization.
		 * @memberOf com.inova8.lens.view.Settings
		 */
		onInit: function() {

		},

		/**
		 * Similar to onAfterRendering, but this hook is invoked before the controller's View is re-rendered
		 * (NOT before the first rendering! onInit() is used for that one!).
		 * @memberOf com.inova8.lens.view.Settings
		 */
		//	onBeforeRendering: function() {
		//
		//	},

		/**
		 * Called when the View has been rendered (so its HTML is part of the document). Post-rendering manipulations of the HTML could be done here.
		 * This hook is the same one that SAPUI5 controls get after being rendered.
		 * @memberOf com.inova8.lens.view.Settings
		 */
		 
		onAfterRendering: function() {
			var container = this.byId("configurationEditor"); //document.getElementById("configurationEditor");
			var options = {};
			var editor = new JSONEditor(container, options);
			// set json
			var json = {
				"Array": [1, 2, 3],
				"Boolean": true,
				"Null": null,
				"Number": 123,
				"Object": {
					"a": "b",
					"c": "d"
				},
				"String": "Hello World"
			};
			editor.set(json);

			// get json
			json = editor.get();
		}

		/**
		 * Called when the Controller is destroyed. Use this one to free resources and finalize activities.
		 * @memberOf com.inova8.lens.view.Settings
		 */
		//	onExit: function() {
		//
		//	}

	});

});

**Comment by MalikGitHub** [comment]
`/* global JSONEditor:true */
sap.ui.define([
	"com/inova8/lens/controller/BaseController", 
	"com/inova8/lens/jsonEditor/node_modules/jsoneditor/dist/jsoneditor"

],

function(Controller, JSONEditor) {
	"use strict";

	return Controller.extend("com.inova8.lens.controller.ConfigurationEditor", {

		/**
		 * Called when a controller is instantiated and its View controls (if available) are already created.
		 * Can be used to modify the View before it is displayed, to bind event handlers and do other one-time initialization.
		 * @memberOf com.inova8.lens.view.Settings
		 */
		onInit: function() {

		},

		/**
		 * Similar to onAfterRendering, but this hook is invoked before the controller's View is re-rendered
		 * (NOT before the first rendering! onInit() is used for that one!).
		 * @memberOf com.inova8.lens.view.Settings
		 */
		//	onBeforeRendering: function() {
		//
		//	},

		/**
		 * Called when the View has been rendered (so its HTML is part of the document). Post-rendering manipulations of the HTML could be done here.
		 * This hook is the same one that SAPUI5 controls get after being rendered.
		 * @memberOf com.inova8.lens.view.Settings
		 */
		 
		onAfterRendering: function() {
			var container = this.byId("configurationEditor"); //document.getElementById("configurationEditor");
			var options = {};
			var editor = new JSONEditor(container, options);
			// set json
			var json = {
				"Array": [1, 2, 3],
				"Boolean": true,
				"Null": null,
				"Number": 123,
				"Object": {
					"a": "b",
					"c": "d"
				},
				"String": "Hello World"
			};
			editor.set(json);

			// get json
			json = editor.get();
		}

		/**
		 * Called when the Controller is destroyed. Use this one to free resources and finalize activities.
		 * @memberOf com.inova8.lens.view.Settings
		 */
		//	onExit: function() {
		//
		//	}

	});

});`

**Comment by josdejong** [comment]
@MalikGitHub I have no idea what `sap.ui.define` is, is it some sort of AMD like module loader?

**Comment by meirotstein** [comment]
UI5 uses their own implementation of module loader which is not AMD.

@MalikGitHub see the following:
https://blogs.sap.com/2017/04/30/how-to-include-third-party-libraries-modules-in-sapui5/

**Comment by josdejong** [comment]
I'm not sure how we can help here. Will close due to lack of response.
