### ISSUE TITLE
templates getting "[object Object]"

### ISSUE THREAD

**Issue by lucasdSan** [josdejong/jsoneditor#642]
Hi, I tried  jsoneditor and, in order to using templates whose template[].value" is a object , I witness a behaviour where the value is took as a string and resulting in `"[object Object]"` value. I tried the examples in git, but the error continues. I have not read the whole code, so my solution may not be perfect but in `Node.prototype.setValue` (Ctrl+F) I have find out that `_getType()` returns `'auto'` for objects. My solution:

 ```
this.type = this._getType(value);// this line is already there
		
    if(value && typeof value ==  'object'){
			this.type = 'object'
			if(Array.isArray(value))
				this.type = 'array'
    } 

```
Now it is working and no conflicts (apparently).

**Comment by josdejong** [comment]
Thanks for reporting, will look into it.

**Comment by lucasdSan** [comment]
@josdejong. in my scenario I am coding in node-webkit and the jsoneditor is opened in a separate window  when a function is called. the function is:

```
editJson: function(json,title,templates=[]){
        return new Promise(res=>{
            templates= [
               // for testing purposes I'm forcing templates to "Person Adress example" here.
            ]
            nw.Window.open(process.cwd()+'/src/jsoneditor/editJSON.html',{}, function(win){
                win.on('loaded',()=>{
                
                    win.window.document.title = (title?title:'Edição');
                    var container = win.window.document.querySelector('#editor')
                    var save = win.window.document.querySelector('#save')
                    var editor = new win.window.JSONEditor(container, {modes:['tree','text','code'],mode:'text',templates:templates},json)
                    editor.set(json)
                    save.addEventListener('click',()=>{
                        var json2 = editor.get()
                        
                        res(json2)
                        win.window.close
                        
                    }) 


                })
            
            })
        })
    }
```
![sem titulo](https://user-images.githubusercontent.com/46091190/52234291-71c71500-28a8-11e9-87fb-3c68d3f2cfd9.png)

In short the function gets a json, edits and resolves a promise with the changed json. possibly the error comes by sending a json to a new window enviroment (I'm not sure). I will run a test without create a window and post again with the results.

**Comment by josdejong** [comment]
Thanks for explaining the context. Curious to know how to reproduce the issue. It looks like `.toString()` is called somewhere on the template object.

**Comment by lucasdSan** [comment]
Well...
I've run a test adding a line in the child window 'loaded' event,
`win.window.templateArgsTest = templates`. Now the child window has a global for templates to compare. Running I get this:
![sem titulo](https://user-images.githubusercontent.com/46091190/52423203-c2c04e80-2ade-11e9-845f-21cdf8f6da6b.png)
templates is a instance of Object in Parent, and is not  in Child, but their typeof is same.
jsoneditor's Node._getType() uses instanceof for define the type and works fine in example. It's a specific problem in transport vars for new windows, not in jsoneditor (it works fine if all the stuff run inside the same window).

**Comment by josdejong** [comment]
So if I understand it correctly it has to do with iframes or something? In that case you can maybe do a trick stringinfying the objects as JSON and then parsing it again?

**Comment by lucasdSan** [comment]
Yes, it worked here. Thanks.

**Comment by josdejong** [comment]
:+1:
