### ISSUE TITLE
CSS: Text bubble not near mouse cursor in Code mode

### ISSUE THREAD

**Issue by Serveurperso** [josdejong/jsoneditor#644]
There is a tiny CS bug,
The Code error bubble is not near mouse cursor when the jsoneditor window is positioned.

![css](https://user-images.githubusercontent.com/4873680/52162009-e72abe00-26cd-11e9-8612-0de40996db38.png)

**Comment by josdejong** [comment]
Thanks for reporting @Serveurperso. This is part of the Ace editor, but maybe we can find a solution for it. How can I reproduce your issue? Do you have a minimal code example demonstrating the problem?

**Comment by Serveurperso** [comment]
I'm curious to see a reversed version of http://jsoneditoronline.org  !!!

I use your jsoneditor inside an Ajax loaded Lity (https://sorgalla.com/lity)
I think I do a CSS thing the Ace don't like:D I must minimize this code :

main CSS
```
div.popup {
 padding: 10px;
 background-color: #<?php echo $fond; ?>;
 max-height: 600px;
 overflow: hidden;
 text-align: center;
 white-space: nowrap;
}
```

code + CSS override
```
<link rel="stylesheet" href="node_modules/jsoneditor/dist/jsoneditor.css" type="text/css" />

<script src="node_modules/jsoneditor/dist/jsoneditor.js" type="text/javascript"></script>
<script src="node_modules/json-override/json-override.js" type="text/javascript"></script>

<style type="text/css">
 #jsoneditor {
  width: 400px;
  height: 400px;
  background-color: #ffffff;
  white-space: normal;
 }
</style>

<div class="popup">
 <h2><?php echo $titre; ?></h2>
 <br />

 <form id="postjson.php" class="formpopup" method="post" action="">
  <fieldset>
   <label class="gauche">Nom du robot</label><input readonly="readonly" type="text" name="robotname" class="droite" id="robotname" value="<?php echo $robotname; ?>" /><br />
   <br />

   <a id="minimal">Configuration usine</a> |
   <a id="diff">Modifications apportées</a> |
   <a id="effective">Effective</a><br />
   <br />

   <div id="jsoneditor"></div>
   <br />

   <input type="hidden" name="type" id="type" value="<?php echo $type; ?>" />
   <input type="hidden" name="json" id="json" value="" />

   <input type="submit" value="Vérifier et enregistrer la configuration" />
  </fieldset>
 </form>
</div>

<script>
 <!--
  $(function() {
   let jsoneditor;
   let schema = '<?php echo getjson($schema); ?>';
   let minimal = '<?php echo getjson($minimal); ?>';
   let json = '<?php echo $json; ?>';
   let conf;

   jsoneditor = new JSONEditor($("#jsoneditor")[0], {
    mode: "tree",
    modes: ["code", "form", "text", "tree", "view"],
    enableSort: false,
    enableTransform: false,
    search: false,
    navigationBar: false,
    schema: JSON.parse(schema),
    onChangeText: majForm
   });

   minimal = JSON.parse(minimal);
   json = JSON.parse(json);
   conf = overwriteKeys(minimal, json, true);

   $("#minimal").on("mousedown", function() {
    jsoneditor.set(minimal);
    $("#json").val(jsoneditor.getText());
   });

   $("#diff").on("mousedown", function() {
    jsoneditor.set(json);
    $("#json").val(jsoneditor.getText());
   });

   $("#effective").on("mousedown", function() {
    jsoneditor.set(conf);
    $("#json").val(jsoneditor.getText());
   });

   function majForm(json) {
    $("#json").val(json);
   }

   jsoneditor.set(json);
   $("#json").val(jsoneditor.getText());

  });
 //-->
</script>

```

**Comment by josdejong** [comment]
Thanks. What is "json-override.js"? Would it be easy for you to put your code in a jsfiddle/jsbin/codesandbox?

> I'm curious to see a reversed version of http://jsoneditoronline.org !!! Swap tree and code editor

I guess this is a feature request? :D I would like to give not too much configuration options to the user and keep the UI simple and predictable. If there are many people though that would like to see the panels swapped we can consider it.

**Comment by Serveurperso** [comment]
json-override it's for override a json on another json. line a json "sum".
I use it to override a user configuration to an factory configuration.

I use also a json diff function I made, like a json "subtraction". it's usefull to store only the differential from factory inside a database for each robots. All user can customize configuration without a lot of copy from the factory configuration ! It's the easy way to maintain and I can add global robotics feature without re-parsing entire database of robots to update all users.

I think swapped mode is an useless feature for jsoneditoronline.org (But you can enable all mode user choice on two side)

But you can add the capability to override two json and diff two json, it's an awesome feature to work with json. I give you my diff function but it's php because I use it only before database write (jsoneditoronline need full javascript).


```
 function isAssoc($array) {
  if(!is_array($array))
   return false;

  return array_keys($array) !== range(0, count($array) - 1);
 }

 function arrayRecursiveDiff($array1, $array2) {
  $diff = [];

  foreach($array1 as $key => $value) {
   if(array_key_exists($key, $array2)) {
    if(isAssoc($value)) {
     $recursiveDiff = arrayRecursiveDiff($value, $array2[$key]);
     if(count($recursiveDiff))
      $diff[$key] = $recursiveDiff;
    } else if($value !== $array2[$key])
     $diff[$key] = $value;
   } else
    $diff[$key] = $value;
  }

  return $diff;
 }

 $json1 = file_get_contents($full);
 $json2 = file_get_contents($factory);

 $array1 = json_decode($json1, true);
 $array2 = json_decode($json2, true);

 $diff = arrayRecursiveDiff($array1, $array2);
 $json = json_encode($diff, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);

 //$json contain only the diff from factory configuration (user customization).
```

**Comment by Serveurperso** [comment]
Ah ! I can't reproduce the bug with a minimal code.
I must do another minimal code with a Lity popup.

**Comment by Serveurperso** [comment]
I think this is the same as https://github.com/ajaxorg/ace/issues/3262

**Comment by Serveurperso** [comment]
I think this is the same as ajaxorg/ace#3262
What is the ace version embedded inside jsoneditor ?
I need the non minimized version ace inside jsoneditor to mate more test

**Comment by Serveurperso** [comment]
Here is the minimal code inside a virtual dir on my server : https://www.serveurperso.com/temp/

jsoneditor.html - a basic instance to test, it work perfectly alone.
```
<link rel="stylesheet" href="../node_modules/jsoneditor/dist/jsoneditor.css" type="text/css" />

<script src="../node_modules/jsoneditor/dist/jsoneditor.js" type="text/javascript"></script>
<script src="../node_modules/json-override/json-override.js" type="text/javascript"></script>

<style type="text/css">
 #jsoneditor {
  width: 400px;
  height: 400px;
  background-color: #ffffff;
 }
</style>

<div id="jsoneditor"></div>

<script>
 <!--
  function test() {
   let schema = '{}';
   let minimal = '{}';
   let elem = document.getElementById("jsoneditor");

   let jsoneditor = new JSONEditor(elem, {
    mode: "code",
    schema: JSON.parse(schema)
   });

   minimal = JSON.parse(minimal);

   jsoneditor.set(minimal);

  }
  test();

 //-->
</script>

```

lity.html - my AJAX loader with Lity. This make the bug (add an invalid char to see it)
```
<script src="../js/jquery.min.js" type="text/javascript"></script>

<link rel="stylesheet" href="../js/lity.css" type="text/css" />
<script src="../js/lity.min.js" type="text/javascript"></script>

<script type="text/javascript">
 <!--
  $(function() {
   "use strict";

   function chargeLity(php, element) {
    $.ajax({
     type: "GET",
     url: php,

     success: function(data) {
      element.html(data);
     }
    });
   }

   function nouveauLity(php) {
    let instance = lity('<div id="ajax"></div>');
    let element = instance.element().find("#ajax");

    chargeLity(php, element);
   }

   nouveauLity("jsoneditor.html");

  });
 //-->
</script>

```

**Comment by josdejong** [comment]
I see the issue happening. I've had a short look at the css for positioning the popup on the center of the page. I guess there is some tricks going on there (like `::before` with a `vertical-align: middle`) which the Ace editor doesn't reckon with. I'm not sure if it would be easy to get this fixed in Ace editor (at least you would need a minimal example demonstrating the issue with pure CSS+Ace editor and without Lity.
