### ISSUE TITLE
Every time i open the editor, instances increases ?

### ISSUE THREAD

**Issue by 70i5h** [josdejong/jsoneditor#647]
When Opened once:
![click1](https://user-images.githubusercontent.com/45033595/52211053-ba81cc80-28ae-11e9-8171-9769fe8ae6c6.png)
When Opened Twice:
![click2](https://user-images.githubusercontent.com/45033595/52211063-c1104400-28ae-11e9-9920-ca838f4f3c7b.png)

**Comment by josdejong** [comment]
@70i5h I guess that your application creates a new JSONEditor when you open your modal, but does not cleanup the previous one or something like that.

**Comment by 70i5h** [comment]
Yes, Exactly....that's the problem....Usually this does not happen....

**Comment by josdejong** [comment]
This is something that you have to handle in your application. If you want to remove the editor every time you close the popup you can use `editor.destroy()`. If you reuse the popup every time and only hide it you only have to create the editor once instead of every time the popup opens.
