### ISSUE TITLE
How to get json file to change data and then save changes 

### ISSUE THREAD

**Issue by debashefi** [josdejong/jsoneditor#654]
How we can add automatically a json file (no upload) by giving a path or so. After loading we also need to save changes on that particular json file from where it was loaded.

Thanks,
Deba

**Comment by josdejong** [comment]
@debashefi do you mean with the web application https://jsoneditoronline.org?

**Comment by debashefi** [comment]
@josdejong  yes, using jsoneditor Is it possible to open to load/open alreay existing json file and save changes?

**Comment by josdejong** [comment]
If you use JSONEditor as a component in your own web application it's best to create your own backend with database to store your documents, there are many ways to do this. In your web application you can use HTTP fetch to load/save data to some backend REST API.
