### ISSUE TITLE
Using multiple schemas with $ref

### ISSUE THREAD

**Issue by KristiLofton** [josdejong/jsoneditor#656]
I'm having a problem with my refs working when they point to a separate json file. I'm implementing the json editor in an angular component, and for the most part it's working great! I'm basically working with three separate schemas (one main one, and two definition files -- may seem unnecessary to split it up but it's part of a larger project). It's possible I've typed something out wrong, or I've seen some people complain there's issues when the ref points to other objects in remote files with individual properties. But I can't figure it out! When I use the browser version at jsoneditoronline.org, I tried saving the three schemas locally and using sample data to validate with the main one, but it gives me this error:  Failed to parse JSON schema: Error: can't resolve reference  in reference to both definition schemas.

[warehouseTariffSchema.txt](https://github.com/josdejong/jsoneditor/files/2862717/warehouseTariffSchema.txt)
[entitySchema.txt](https://github.com/josdejong/jsoneditor/files/2862718/entitySchema.txt)
[generalSchema.txt](https://github.com/josdejong/jsoneditor/files/2862719/generalSchema.txt)

Also I realize that this will still be a more involved fix with my angular component, as I'm thinking I'm going to have to do some digging in ajv to get the multiple schema loading right. But mainly right now I just want to understand why my references aren't working in the browser ):  

Sorry this is so long and if this is a basic question, please let me know if anyone has any ideas/answers! I've attached my three schemas for reference, but as a quick(er) example: 

Snippet of my main file (ref to an object)
```
"type": "object",
	"properties": {
		"warehouseIdentity": {
			"title": "Warehouse Identity",
                        "description": "Describes the warehouse involved.",
                        "type": "object",
                         "allOf": [{"$ref": "entitySchema.json#/definitions/entity"}]
		 }
```
entity in entitySchema: 
```
          "definitions": {
	          "entity": {
	                  "type": "object",
	                   "properties" : {
	                             "entityID": {
			                  "title": "Entity ID",
			                  "description": "The ID number of the specific entity",
			                  "type": "number"
		                      },
    		                    "entityName": {
    			                 "title": "Entity Name",
                                         "description": "The name of the entity.",
    			                 "$ref": "generalSchema.json#/definitions/name"
    		                      },
    		                    "entityAddress": {
    			                 "title": "Entity Address",
    			                 "description": "The address(es) of the entity.",
    			                 "type": "array",
    			                  "items": {
                                                     "type": "object",
                                                     "$ref": "generalSchema.json#/definitions/addressFullText"
                                           }
    		                      }
                               "required": [
                                          "entityID",
                                          "entityName"
                                ]
```
name in generalSchema (as string example)
```
         "definitions": {
		"name": {
			"title": "Name",
			"description": "The name of a person or organization.",
			"type": "string"
		   }
```

**Comment by josdejong** [comment]
You should be able to pass references separately from the schema, like demonstrated in

**Comment by josdejong** [comment]
You should be able to pass references separately from the schema, like demonstrated in [07_json_schema_validation.html](https://github.com/josdejong/jsoneditor/blob/master/examples/07_json_schema_validation.html). You cannot use schemas with references in the web application jsoneditoronline.org since there is no way there to pass `schemaRefs`. 

It could be that you hit a bug in resolving schema references. @AdamVig fixed a couple of bugs in this regard some days ago. These fixes are available now in `v5.29.0`.

**Comment by KristiLofton** [comment]
That makes sense, I totally misunderstood the online file storage for the web app. Thanks so much for responding! I tried resetting up the schema refs again like this and it worked:

schemaRefs: {
        '#/definitions/rateAmount': this.schema.definitions.rateAmount,
        'entitySchema.json#/definitions/entity': this.entitySchema.definitions.entity,
        'generalSchema.json#/definitions/name': this.generalSchema.definitions.name,
        'generalSchema.json#/definitions/addressFullText': this.generalSchema.definitions.addressFullText,
        'entitySchema.json#/definitions/entityType': this.entitySchema.definitions.entity.properties.entityType,
        '#/definitions/entityWarehouse': this.entitySchema.definitions.entityWarehouse,
        'generalSchema.json#/definitions/currencyCodeType': this.generalSchema.definitions.currencyCodeType,
        'generalSchema.json#/definitions/unitStandard': this.generalSchema.definitions.unitStandard,
        'generalSchema.json#/definitions/date': this.generalSchema.definitions.date,
        'generalSchema.json#/definitions/telephoneNumber': this.generalSchema.definitions.telephoneNumber,
        'generalSchema.json#/definitions/email': this.generalSchema.definitions.email
      }

 Not sure if I was just setting that up wrong originally, or if the bugs affecting me got fixed. Thanks again for your help, this json editor has been fantastic!

**Comment by josdejong** [comment]
:+1:
