### ISSUE TITLE
Support for hjson (principally to allow comments)

### ISSUE THREAD

**Issue by dgwsoft** [josdejong/jsoneditor#658]
Hi Jos,

Is it possible to enable support for hjson (or otherwise to enable comments)? I note that this is possible at https://ace.c9.io/build/kitchen-sink.html (select Mode=Hjson) and I see you have hjson.js in your source tree, but it is not obvious (to me at any rate) how to turn it on in your editor.

If it is possible, then some pointers how to do it would be much appreciated.

cheers

Gareth

**Comment by josdejong** [comment]
There is no support for hjson or other json dialects right now, and it's not on the roadmap to add support for it any time soon.
