### ISSUE TITLE
Serialize history

### ISSUE THREAD

**Issue by RobAley** [josdejong/jsoneditor#660]
Hi,

Is there any way to serialize (or similar) the editor history to save & restore it? What I would like to do is save the current history alongside the json document when the user closes the editor, so that when they open it again I can load both the json and the history, effectively restoring the "state" the editor was in in the previous session.

I have tried JSON.stringify on editor.history.history, which works on simple history items (like value changes), but when the history item involves nodes (e.g. adding new nodes) it fails due to circular references (to the editor, node etc.). I tried removing the circular references before stringifying it, but when reinstating the history in the new session there was too much missing info in the nodes to work.

Is there any other strategies anyone has used (e.g. any way to easily serialize nodes such that they can be restored later) to do anything like this? Or any obvious way I am missing to save/restore the history (or indeed save/restore the whole state of the editor)?

Thanks

**Comment by josdejong** [comment]
Interesting idea. The history indeed relies on (non-serializable) Nodes, that makes it sort of impossible to restore.

Just thinking aloud: what _may_ work (not sure) is create a listener `onChangeJSON`, and after a change, get the latest version of the JSON document and append it to an array, that way building your history. This list can be serialized. To restore you could "replay" history by calling `JSONEdtior.update(json)` for every document from the persisted array. If storage size becomes an issue you could do smart things with only storing diffs or something.

**Comment by RobAley** [comment]
Thanks, I thought as much. I may have a go at creating something based on diffs/patches if I can do that quick enough on large docs. I'll close this for now though.
