### ISSUE TITLE
TR locale has duplicate entries

### ISSUE THREAD

**Issue by andreasseidler** [josdejong/jsoneditor#661]
TR locale in src/js/i18n.js has duplicate entries:

tr: {
    ...
    drag: 'Drag to move this field (Alt+Shift+Arrows)',
    drag: 'Bu alanı taşımak için sürükleyin (Alt+Shift+Arrows)',
    ...
    showMoreStatus: 'displaying ${visibleChilds} of ${totalChilds} items.',
    showMoreStatus: '${totalChilds} alanın ${visibleChilds} alt alanları gösteriliyor',
    ...
    sortTitle: 'Sort the childs of this ${type}',
    sortTitle: '${type}\'ın alt alanlarını sırala',
    ...
    transformTitle: 'Filter, sort, or transform the childs of this ${type}',
    transformTitle: '${type}\'ın alt alanlarını filtrele, sırala veya dönüştür',
    ...
    validationCannotMove: 'Cannot move a field into a child of itself',
    validationCannotMove: 'Alt alan olarak taşınamıyor',
    ...
  }

This breaks jsoneditor in IE.

**Comment by josdejong** [comment]
ouch! Thanks for reporting. This is fixed now in `v5.29.1`.
