### ISSUE TITLE
SearchBox.next() => undefined

### ISSUE THREAD

**Issue by silasjoisten** [josdejong/jsoneditor#662]
Hello,
i am using your great lib! 🥇  I figured out when you're using `mode: "form"` and try to jump to next/previous result.
`SearchBox.next()` is `undefined`. Any Idea?
This is my code:

```js
let orderJson = document.querySelector('input[name*="orderJson"]')
let options = {
        mode: 'form',
        onChangeJSON: (json) => {
            orderJson.value = JSON.stringify(json)
        }
};
let json = JSON.parse(orderJson.value);
let editor = new JSONEditor(element, options, json);
```
![bildschirmfoto 2019-02-25 um 14 51 32](https://user-images.githubusercontent.com/10114981/53341820-dce69300-390c-11e9-811a-679b29f1aa30.png)

**Comment by josdejong** [comment]
@silasjoisten I'm not sure what you mean. Do you mean you're using the editor inside a `form`? How can I reproduce your issue?

**Comment by silasjoisten** [comment]
@josdejong you need to do:
* search after `first` forexample
* and try to use the arrows in the search field
 You see in the screenshot that ther're 4 results. But when you use the arrows its not jumping to the next/previous results. 

So i went in to the code and made a `console.log()`then `SearchBox.next()` was `undefined`

**Comment by josdejong** [comment]
`SearchBox.next()` always returns `undefined`, it doesn't return anything.

I've tried to reproduce your issue but the next/prev arrows work fine as far as I can see. Are you using the latest version of JSONEditor (I remember there was an issue in `v5.19.1` with this, see [history](https://github.com/josdejong/jsoneditor/blob/master/HISTORY.md#2018-08-02-version-5192)) ? Can you create a codesandbox/jsfiddle/jsbin that demonstrates the issue?

**Comment by silasjoisten** [comment]
Okay good to know 👍 
I am using the latest version (5.29.1) of your lib and i created a [fiddle](https://jsfiddle.net/8ezxq753/21/) for you: 
* it is highlighting the next/previous results but its not jumping to it.

**Comment by josdejong** [comment]
Ah, I get what you mean. This is the same question as #611, where I explained:

> Jumping to a search result only works when the editor has a limited height and scrolling contents. The editor cannot control the website that it is part of, it can only control its own contents. Does that make sense?

**Comment by silasjoisten** [comment]
Thanks a lot! i am closing this.
