### ISSUE TITLE
Is there an option to change the display text of the code modes?

### ISSUE THREAD

**Issue by josh-saunders-vroi** [josdejong/jsoneditor#669]
Is there an option change the display text of the code modes? I would rather the modes be something like "Read-only (instead of view), Beginner (instead of form), Intermediate (instead of tree) and Advanced (instead of code)"

**Comment by josdejong** [comment]
There is no API for that. Maybe you can use a custom translation for that?

https://github.com/josdejong/jsoneditor/blob/master/src/js/i18n.js#L76-L85

**Comment by josh-saunders-vroi** [comment]
I'll give that a shot. Thanks for the quick reply.

**Comment by josdejong** [comment]
:+1:
