### ISSUE TITLE
Ace options

### ISSUE THREAD

**Issue by mathiastm** [josdejong/jsoneditor#672]
Is that possible to set ace options ? 
I would like to set a custom autoCompletion on code mode but i need to set enableBasicAutocompletion: true to ace options.

**Comment by josdejong** [comment]
Yes, you can access the ace editor via `editor.aceEditor`, and even better is to provide your own instance of ace via the options (see https://github.com/josdejong/jsoneditor/blob/master/docs/api.md#configuration-options -> `ace`)

**Comment by GeorgeBekh** [comment]
@josdejong how can you provide your own Ace instance if jsoneditor always tries to create a new one?

https://github.com/josdejong/jsoneditor/blob/master/src/js/textmode.js#L267

**Comment by josdejong** [comment]
@GeorgeBekh you can provide your own Ace constructor via the options, `options.ace`. You could provide your own `ace.edit` factory function returning some instance of your own making.
