### ISSUE TITLE
Not working with jquery prototype target

### ISSUE THREAD

**Issue by Jack184** [josdejong/jsoneditor#673]
`
![Captura de Tela 2019-03-13 às 10 40 32](https://user-images.githubusercontent.com/38541696/54283463-da2aa580-457c-11e9-9ab2-86dd22fde3d5.png)
class CodeInput {
    
    constructor(config) {

        let self = this;

        this.config = {
            value: {}
        }

        if (config !== undefined) {
            this.config = $.extend(true, this.config, config);
        }

        this.container = new Div(); // $('<div>');

        this.editor = new JSONEditor(this.container[0], {mode: 'code'});
        this.editor.set(this.config.value);

    }

    /**
     * @returns {Object}  
     */
    getView() {
        return this.container;
    }

}

// Creating instance
var input = new CodeInput(inputConfig);
column.append(input.getView());
`

**Comment by Jack184** [comment]
It was my mistake, sorry

**Comment by josdejong** [comment]
:+1:
