### ISSUE TITLE
Is there any way to change colors?

### ISSUE THREAD

**Issue by fykcz** [josdejong/jsoneditor#677]
![image](https://user-images.githubusercontent.com/6848471/54826950-37c39e00-4cb1-11e9-952a-4ff7a6740fe9.png)
I am using a dark theme and in the json editor the nodes are badly seen. Is there any way to change colors?

**Comment by josdejong** [comment]
Does the following example help? 

https://github.com/josdejong/jsoneditor/blob/master/examples/06_custom_styling.html

**Comment by fykcz** [comment]
I'm sorry, I finally found the setting. Issue can be closed (or completely deleted and forgotten).

**Comment by anshulkatta** [comment]
> I'm sorry, I finally found the setting. Issue can be closed (or completely deleted and forgotten).

how do you it ? need to use dark mode in tree mode

**Comment by anshulkatta** [comment]
ok got it..use this css - `https://raw.githubusercontent.com/josdejong/jsoneditor/master/examples/css/darktheme.css` 

thanks josdejong

**Comment by abhi0805** [comment]
css not working in angular 13
@josdejong

**Comment by josdejong** [comment]
@abhi0805 if you have a specific issue in combination with angular, please open a new issue and provide a minimal example demonstrating your issue,
