### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by surajkj** [josdejong/jsoneditor#678]
Anyone working on darkmode support?

**Comment by josdejong** [comment]
@surajkj have you seen #677 and the following example? 

https://github.com/josdejong/jsoneditor/blob/master/examples/06_custom_styling.html

**Comment by rhl20kmr** [comment]
Can Aynone help me to do it using angular 9?

**Comment by josdejong** [comment]
This is pure CSS styling, it's not specific to Angular or an other framework.
