### ISSUE TITLE
Allow expanding when in view mode.

### ISSUE THREAD

**Issue by VictorioBerra** [josdejong/jsoneditor#680]
Why cant I expand nodes in view mode?

**Comment by josdejong** [comment]
What do you mean exactly? Expanding by clicking the expand button should just work, see https://unpkg.com/jsoneditor@5.32.0/examples/02_viewer.html

**Comment by VictorioBerra** [comment]
@josdejong I broke everything when I fighting with trying to append it to the proper container. I had to append it a different way.

**Comment by josdejong** [comment]
:+1:
