### ISSUE TITLE
Is there any previous work that integrates jsoneditor with swagger-ui?

### ISSUE THREAD

**Issue by harsh-tamr** [josdejong/jsoneditor#681]
Having a JSONEditor inside the Swagger-UI would be super helpful

http://petstore.swagger.io/#/pet/updatePet
http://recordit.co/t3k6Kb4YPi/gif/notify

**Comment by josdejong** [comment]
You mean like having JSONEditor inside the Swagger-UI to help fill in the right JSON models?

**Comment by harsh-tamr** [comment]
yup

**Comment by josdejong** [comment]
I'm not aware of any such integration. Does it make sense to share this idea with the swagger UI development team instead of here?

**Comment by harsh-tamr** [comment]
Sure

**Comment by josdejong** [comment]
:+1:
