### ISSUE TITLE
UglifyJs Unexpected token: keyword «const»

### ISSUE THREAD

**Issue by Nice-PLQ** [josdejong/jsoneditor#684]
`const` declaration was used on line 1970, so it will fail in UglifyJs
[https://github.com/josdejong/jsoneditor/blob/master/src/js/Node.js#L1970](https://github.com/josdejong/jsoneditor/blob/master/src/js/Node.js#L1970)

**Comment by josdejong** [comment]
oops! should be fixed now in `v5.32.3`. Thanks for reporting @Nice-PLQ
