### ISSUE TITLE
How to get an existing JSONEditor object?

### ISSUE THREAD

**Issue by Arslan-Ali-Butt** [josdejong/jsoneditor#686]
I'm using an app that already has a JSONEditor embedded into, but I would like to refer to that, and I'm unable to figure out that.

There is an HTML element: `<div class="jsoneditor-wrap">`, and it contains the JSONEditor.

I want to accomplish that each time, the page loads it would expand all the nodes through `explandAll()`.

P.S: https://stackoverflow.com/questions/55539712/how-to-get-an-existing-jsoneditor-object

**Comment by josdejong** [comment]
The piece of code that creates the JSONEditor needs to keep a reference somewhere, and you have to pass that to the code that needs access to the editor.

**Comment by Arslan-Ali-Butt** [comment]
Ah man, that's bundled up in a gem, which means I have to fork that project, modify it, and build a new version of it to use in my project where I can put the reference in a global version.

Anyway, thanks.

**Comment by josdejong** [comment]
I don't think there is need to fork the project, you can simply write a wrapper around the constructor which stores the reference to the created editor "somewhere": could be in a JavaScript global or even attached to the HTML element that you use as container.
