### ISSUE TITLE
When add a new variable in very long list, the added variable should get auto focused.

### ISSUE THREAD

**Issue by zaidmir5** [josdejong/jsoneditor#691]
![image](https://user-images.githubusercontent.com/48056293/56024817-6d96f800-5d2e-11e9-8980-cc43972f9da8.png)

ISSUE:   When add a new variable,it comes down and i have to scroll the scrollbar to see that new variable.
Expected:    It should be dynamically comes down.

**Comment by josdejong** [comment]
Are you sure you are using JSONEditor and not an other editor?

**Comment by zaidmir5** [comment]
Yes 
<div id="JsonSchemaEditorDia" class="modal-body"
                 style="height: 450px; overflow: auto;">

**Comment by zaidmir5** [comment]
Yes 
<div id="JsonSchemaEditorDia" class="modal-body"
                 style="height: 450px; overflow: auto;">

**Comment by zaidmir5** [comment]
<div id="JsonSchemaEditorDia" class="modal-body"
                 style="height: 450px; overflow: auto;">

**Comment by zaidmir5** [comment]
<div id="JsonSchemaEditorDia" class="modal-body"
                 style="height: 450px; overflow: auto;">

**Comment by zaidmir5** [comment]
![image](https://user-images.githubusercontent.com/48056293/56079813-102aa600-5e17-11e9-8078-448eade55f4a.png)

**Comment by josdejong** [comment]
?

the screenshot you post looks nowhere near JSONEditor, which looks like:

![image](https://user-images.githubusercontent.com/568626/56079935-5114c180-5dfb-11e9-926c-02fc0f1ef688.png)

is it a strongly customized version, or a very old version of it or so?

**Comment by zaidmir5** [comment]
$('#JsonSchemaEditorDia .operand_tree').contextMenu({
        selector: 'IMG.addproperty', 
        trigger: 'left',
        callback: function(key, options) {
            LocalObj.addProperty(this[0].alt, key);
            #JsonSchemaEditorDia {
            $("#modal-body").focus();
        }
        },
        items: {
            "string": {name: "Add String"},
            "number": {name: "Add Number"},
            "boolean": {name: "Add Boolean"},
            "object": {name: "Add Object"},
            "array": {name: "Add Multiple",
            		"items" : {
            			"arrStr" : {name : "Strings"},
            			"arrNum" : {name : "Numbers"},
            			"arrBol" : {name : "Booleans"},
            			"arrObj" : {name : "Objects"}
            		} 
            }
            
        }
    });

I added these properties there...

**Comment by josdejong** [comment]
Doesn't ring a bell. I think you are using an editor other than this JSONEditor.

**Comment by zaidmir5** [comment]
I added these properties there,but the problem is when i add new property there (Ref screenshot1) it is not focused,means i have to scroll to see this new property

**Comment by josdejong** [comment]
How can I reproduce this issue in an unaltered version of JSONEditor?

**Comment by josdejong** [comment]
Can't do anything without being able to reproduce. Will close this issue now due to lack of response.
