### ISSUE TITLE
Getting error message: "TypeError: Cannot set property 'onclick' of null"

### ISSUE THREAD

**Issue by UTSAV-DEEP** [josdejong/jsoneditor#693]
When the `https://jsoneditoronline.org/` page is left open and unattended for very long time (a few days) then after coming back to the page sometimes it shows this error:

`TypeError: Cannot set property 'onclick' of null`

Here is the screenshot:

<img width="1680" alt="Screen Shot 2019-04-29 at 3 27 32 PM" src="https://user-images.githubusercontent.com/5794948/56883325-e7521400-6a98-11e9-817f-bb81fa1b033d.png">

**Comment by josdejong** [comment]
Thanks for reporting @UTSAV-DEEP. 

Two days ago I updated the web application with some fixes and improvements. It can be that your browser still used a cached version of the HTML and an updated version of the JavaScript causing this error. It should be solved by refreshing your browser.
