### ISSUE TITLE
Add example or recommendation how to test JSONEditor with cypress.

### ISSUE THREAD

**Issue by marekdano** [josdejong/jsoneditor#695]
It would be really great if someone can create a new example or provide a sample snippet for testing JSONEditor with cypress. 
I'm struggling to enter JSON to editor in the cypress test and expect JSON in the editor too.

**Comment by josdejong** [comment]
The rendered contents in the JSONEditor has clear CSS classes which you could match against to do some checks on whether the contents of the JSON document are there, classes like `jsoneditor-value`. Does that help?

**Comment by marekdano** [comment]
Thanks for your suggestion. I'm playing with cypress in my react app where I use JSONEditor.
I think to add some test cases to example of react_demo when I figure out how cypress works. Is it Ok for you if I do it?

**Comment by josdejong** [comment]
I hope you get it working soon. 

The react demos are meant as lightweight examples, just so you get the idea. I think it would go a bit far to include cypress testing for it, everything we add needs to be maintained too.

**Comment by marekdano** [comment]
Ok, thanks for your reply! ;)

**Comment by josdejong** [comment]
:+1:
