### ISSUE TITLE
Display nothing or placeholder in the jsoneditor after loading a page.

### ISSUE THREAD

**Issue by marekdano** [josdejong/jsoneditor#696]
Is there an option to initialize JSONEditor and having nothing displayed in the area of JSONEditor? I tried to set editor with **null** or  **undefined** but they were displayed as a string in the editor. If I do not set anything after initializing JSONEditor, **{}** is displayed. In all cases I have to delete everything before entering JSON into the editor. I'd like to have JSONEditor with nothing or with a placeholder which will automatically remove when I start adding or typing something in the editor. Is there a way to do it? Thanks!

**Comment by josdejong** [comment]
In tree mode, you have to provide a valid JSON object, that can be an empty object or Array, `null`, or a String or number. Without contents, there would be no root item where you could start adding elements too.

In code/text mode, you can set empty contents using `editor.setText('')`.

**Comment by wangchong19940101** [comment]
I want it to have no content instead of {}
@josdejong

**Comment by josdejong** [comment]
Please read my explanation. It's not supported.

**Comment by revitalf3** [comment]
@josdejong 
Hey is there anything new about this? Is it possible to put an empty value instead of {}?

**Comment by josdejong** [comment]
It's still the same situation as explained in [my comment above](https://github.com/josdejong/jsoneditor/issues/696#issuecomment-491597152).

Can you explain why you want to display an "empty value" and how you see that exactly?
