### ISSUE TITLE
onCreateMenu option is not working

### ISSUE THREAD

**Issue by wsjwa** [josdejong/jsoneditor#699]
The option for onCreateMenu is not working. The Event is never called.

I'm using the editor with no options except the event.

onEvent gets triggert for all events except onCreateMenu

**Comment by josdejong** [comment]
Have you tried the following example?

https://github.com/josdejong/jsoneditor/blob/master/examples/21_customize_context_menu.html

**Comment by wsjwa** [comment]
Tried it just now. Nothing is shown in the log if i click the context menu button

**Comment by wsjwa** [comment]
I'm using the chrome btw

**Comment by wsjwa** [comment]
Does not work in firefox either. I looked in the code and onCreateMenu is not listed as an valid option

**Comment by josdejong** [comment]
If I open the following example in Chrome I see this:

https://unpkg.com/jsoneditor@5.32.5/examples/21_customize_context_menu.html

![image](https://user-images.githubusercontent.com/568626/57921037-b34e5f80-789c-11e9-981d-1e543e87ffed.png)

The data in the console is coming from the console.log statement inside `onCreateMenu`

**Comment by wsjwa** [comment]
It does not work in the version: 5.24.7(package.json in the jsoneditor dir). 
Just need to update then

**Comment by wsjwa** [comment]
My Bad. I'll close the issue. Thanks for your help

**Comment by josdejong** [comment]
:+1: this feature was implemented in [v5.30.0](https://github.com/josdejong/jsoneditor/blob/master/HISTORY.md#2019-03-02-version-5300)
