### ISSUE TITLE
Creating a json tree inside a box with collapse/expand of attributes.

### ISSUE THREAD

**Issue by ajith-om** [josdejong/jsoneditor#701]
Dear Team,
I would like to have json in a box, where I can expand and collapse each attribute. The size of the box increases as there are more key value pairs.  I have attached a sample of how I expect the UI to look like. Please help me on the building the same.

![Captusdare](https://user-images.githubusercontent.com/50866383/58083924-891bdb00-7bd7-11e9-8653-9ed22ec02cad.PNG)

**Comment by josdejong** [comment]
You mean the `view` mode?

https://github.com/josdejong/jsoneditor/blob/master/examples/02_viewer.html
https://unpkg.com/jsoneditor@5.32.5/examples/02_viewer.html

**Comment by josdejong** [comment]
or do you mean hiding the menu? There are some options for that, and you can be creative with hiding borders using CSS
