### ISSUE TITLE
What seems to be the problem？

### ISSUE THREAD

**Issue by wangchong19940101** [josdejong/jsoneditor#703]
![image](https://user-images.githubusercontent.com/30942709/58143898-f46cb800-7c7e-11e9-8787-f4092a0da0d2.png)

**Comment by wangchong19940101** [comment]
When editing jsoneditor, such error will appear, I have already raised issues, please ask the big brother to help to see what is the problem

**Comment by wangchong19940101** [comment]
@josdejong

**Comment by josdejong** [comment]
Looks like you call `editor.setText(text)` or `editor.updateText(text)` with text being `undefined` instead of a string.

**Comment by wangchong19940101** [comment]
yes,it is my error.sorry!

**Comment by josdejong** [comment]
:+1:
