### ISSUE TITLE
onNodeName usage naming array components

### ISSUE THREAD

**Issue by berry4u** [josdejong/jsoneditor#704]
Can someone suggest me a way to customize the name of objects in arrays using the value of one of their attributes ?

**Comment by josdejong** [comment]
I'm not sure what you mean, can you elaborate?

**Comment by ayoungprogrammer** [comment]
with this PR: https://github.com/josdejong/jsoneditor/commit/ca2a2054e293f88bc4feeb0ad840e3ddefdf8eaa

it should be easy to customize the name of objects in array:

e.g


```
var editor = new JSONEditor(
        container, {
        mode: "view",
        onNodeName: function ({ path, type, size, value }) {
          if (path.slice(0, -1).join('.') == 'your.path.here') {
            return value.your_array_field_name_here
          }
          return null
        },
      }
      )
```
