### ISSUE TITLE
Please add a feature to hide string text value

### ISSUE THREAD

**Issue by rodrigoduterte** [josdejong/jsoneditor#706]
Please for the contributors of this project. I am asking you to add a feature to hide the value of string keys especially for passwords. The string would appear once a user double clicks the hidden value of the string .

**Comment by josdejong** [comment]
Thanks for your suggestion Gabriel. This idea was already on the wishlist but hasn't been addressed so far, see #460 

I will close this issue as a duplicate, lets continue any discussion in #460
