### ISSUE TITLE
Access raw json with content-type: application/json (cross site)

### ISSUE THREAD

**Issue by jgroenen** [josdejong/jsoneditor#709]
I came across this question: https://github.com/josdejong/jsoneditor/issues/258 Think it is still open:

Would love to be able to do something like: https://jsoneditoronline.org/?id=67c78d2851c04ed18ce2cb8e328fa37c&type=raw and get only the json back (without the interface), with content-type application/json and access control allow origin *

**Comment by josdejong** [comment]
It's not an official public API, but you can do https://jsoneditoronline.herokuapp.com/v1/docs/67c78d2851c04ed18ce2cb8e328fa37c/data

**Comment by jgroenen** [comment]
Very nice. Would be cool to make it official public API, very useful! Thank you!

**Comment by josdejong** [comment]
Yeah agree. Before I can do that I have to think about consequences of people misusing such a public API for just dumping large amounts of JSON files, causing a huge bill for me for the cloud storage. I was thinking about implementing a login so you have better control and can prevent such misuse.

**Comment by jgroenen** [comment]
Yes, might be a paid feature above a certain amount of storage

**Comment by josdejong** [comment]
Yes indeed, something like that. And a paid, ad-free version maybe. Ok will close this issue now.
