### ISSUE TITLE
Add a new line seperated json file to it?

### ISSUE THREAD

**Issue by aryabharat** [josdejong/jsoneditor#714]

**Comment by josdejong** [comment]
Can you explain what you mean?

**Comment by aryabharat** [comment]
I have NDjson file. how can I load this file to the editor, the file is huge it is taking a lot of time to convert it to proper JSON formate.

**Comment by josdejong** [comment]
JSONEditor works fine with JSON objects up to 50 or 100 MB or so. It does not support NDjson, so if you have such a file I suppose you first have to convert it to JSON and then load it into the editor.
