### ISSUE TITLE
on Editable 

### ISSUE THREAD

**Issue by ericvanderlinden** [josdejong/jsoneditor#716]
Question.
(Very useful and well-made tool by the way!)
I'm working on a site using iiiF json (Manifest, canvas) and I want to make the meta data editable for researchers. The names if keys are mandatory. 
`{   `
`...  `
`  "label": "Title of the object.", `
`  "metadata": [`
`    {`
`    "label": "object-general-type", `
`   "value": "physical"`
` },  `
`...  `
`}  `

I want to make label editable and metadata.label readonly. 
I can't change the labels. I can't find a way to do this with the onEditable function.
Maybe I misunderstand the use of path.

**Comment by josdejong** [comment]
Thanks Eric.

Have you tried adding a console.log inside your `onEditable`, so you can see what `field`, `value`, and `path` are passed for every node in your JSON? I expect that you will see paths like `['label']` and `['metadata', 'label']` which allows you to distinguish between the two.

**Comment by ericvanderlinden** [comment]
Yes I did... I tried:
`case 'label':`
`            return {`
`              field: false,`
`             value: true,`
`            path:['label']`
`           };`
`        default:`
`         return false;`

But all fields with name label become editable.

**Comment by josdejong** [comment]
You should not compare `node.field` but `node.path`.

**Comment by ericvanderlinden** [comment]
Thanks it took some trial and error but I solved it like this:
`switch (true) {`
`  case node.path=='metadata,0,value':`
`    return {`
`      field: false,`
`      value: true`
`};`
`  case node.path=='label':`
`    return {`
`      field: false,`
`      value: true`
`};`
`  default:`
`  return false;`
`}`
There is probably a better solution but at least I have a start now.

**Comment by josdejong** [comment]
That's indeed the right way 👍, though I would use a simple `if(...)` instead of a `switch(true)`. You _need_ `path` to distinguish nodes with the same field but a different path. I would expect though that you have to do a `node.path.join(',')` since `node.path` is an array though.
