### ISSUE TITLE
Is it necessary to disable `key` modification in `tree` mode?

### ISSUE THREAD

**Issue by zslucky** [josdejong/jsoneditor#717]
Is it necessary to disable `key` modification in `tree` mode? 

May be this can be configured in options?

**Comment by josdejong** [comment]
I'm not sure what you mean. What do your to achieve? Making all keys readonly? Have you seen the mode `form`?

**Comment by zslucky** [comment]
@josdejong thank you so much. `form` is correct, and I can switch to `tree` by using `setMode`

**Comment by josdejong** [comment]
👍
