### ISSUE TITLE
Could you please help

### ISSUE THREAD

**Issue by Puneetsharma891** [josdejong/jsoneditor#719]
Hi,

I need your help on implementing below changes with JSON editor
1. Add new icon to main menu bar to save JSON data.
2. Any way to implement autocomplete node wise.?
3. Any way to customize the side menu bar to insert only specific object template and not default.?

Appreciate your valuable feedback. Thanks in advance.

**Comment by josdejong** [comment]
That's a lot of questions :)

1. Using a `querySelector` you can find the div containing the menu, then you can add your own button if you want.
2. The autocomplete is very flexible with options like `getOptions` and `trigger`, you can fully customize it per node. There are some nice examples in the examples folder that show what you can do with autocomplete.
3. Do you mean the context menu on the left of every node? You can customize that with `onCreateMenu`.
