### ISSUE TITLE
[Tree Editor] Schema error pop-up is not fully visible

### ISSUE THREAD

**Issue by EimantasZubavicius** [josdejong/jsoneditor#723]
When loading a JSON schema from [https://json-schema.org/learn/examples/address.schema.json](https://json-schema.org/learn/examples/address.schema.json) the error display pop-up that is shown when you hover over the yellow triangle with exclamation point gets cut off.
You can see this bug on [https://jsoneditoronline.org/?id=1ff9890ef4ac4aef91a8fb9496865647](https://jsoneditoronline.org/?id=1ff9890ef4ac4aef91a8fb9496865647). 
Screenshot displaying issue [http://prntscr.com/o9zsge](http://prntscr.com/o9zsge).

**Comment by josdejong** [comment]
Thanks for bringing this up @EimantasZubavicius. Would be great if we can fix this, it's annoying. 

Anyone interested in fixing the popups not overflowing?

**Comment by Koushikphy** [comment]
Same thing happen sometimes with the color picker box too

**Comment by josdejong** [comment]
Unlike the popups, the color picker has correct overflow. It is always aligned to the bottom though, so when close to the bottom of the page you can't see all of it. I guess we could improve that by rendering it on top in that case.
