### ISSUE TITLE
Hoe to show onlt text.plain in the editor

### ISSUE THREAD

**Issue by aryabharat** [josdejong/jsoneditor#724]
Some of my files are plain/text, it's giving invalid JSON error, I read the API aslo, is there any option for it

**Comment by josdejong** [comment]
I'm not sure what you mean. Can you elaborate?

**Comment by aryabharat** [comment]
I want to show some plain text in the editor, is that possible?

**Comment by josdejong** [comment]
Well, there is the `text` and `code` mode, but these will give warnings if the contents is no valid text. The editor is meant for JSON only.

**Comment by aryabharat** [comment]
so, if have a text file which is not JSON I cannot load it in the editor.

**Comment by josdejong** [comment]
You can load any text file using `editor.setText(text)` when the editor is in mode `text` or `code`. But if the contents is not valid JSON, the editor will show warnings.

**Comment by aryabharat** [comment]
ok got it thanks!
