### ISSUE TITLE
Emit the focus and blur event?

### ISSUE THREAD

**Issue by TheoXiong** [josdejong/jsoneditor#727]
Hi,
     Can you support emitting the focus and blur event?

**Comment by josdejong** [comment]
Thanks for your suggestion. That could make sense. 

Can you explain your use case, why do you need this?

**Comment by TheoXiong** [comment]
Because I need to change some UI when the jsoneditor is focused, such as border color. And restore to default UI when blurred.

In my case, i put the jsoneditor in a form which consists some input element，like the demo below.
In general，the input element will changed some UI when hovered or focused.
So i hope the jsoneditor could keep the same style with input element.

![image](https://user-images.githubusercontent.com/42533484/60754558-5f970180-a015-11e9-92df-2fe44359ee22.png)

**Comment by josdejong** [comment]
Ah, now I fully understand what you mean, thanks for the explanation. I was initially assuming that you meant focus/blur of a node, but you mean focus/blur of the editor as a whole. So this should work for all of the modes of the editor.

**Comment by TheoXiong** [comment]
Yes, I  mean focus/blur of the editor as a whole.
Can this be added?

**Comment by josdejong** [comment]
Yes, makes sense to me. I will not have time to implement it my self it any time soon though. 

Anyone interested in implementing this feature?

**Comment by 123survesh** [comment]
@josdejong, can I give it a try?

**Comment by josdejong** [comment]
Thanks for your offer Survesh, that would be great!

**Comment by 123survesh** [comment]
@josdejong I have created a PR exposing the onFocus and onBlur events. Can you check if the approach I have taken is ok and tell me if anything has to be changed?

**Comment by josdejong** [comment]
The new `onFocus` and `onBlur` implemented by @123survesh are now published in `v7.3.0`.
