### ISSUE TITLE
CTRL + Z empty my content...

### ISSUE THREAD

**Issue by bbr-yp** [josdejong/jsoneditor#730]
Hi,

I'm using jsonEditor (6.1.0) with Brace and when you open an editor with content.
```
const editor = new JSONEditor(container, options);
editor.set(json);
```

If you press CTRL + Z. All the content is emptied...
In the same way, if you're editing a code... And cancel once too often... Everything gone..

Not a big deal because I can `redo` my `undo`.

I already asked to on [Brace](https://github.com/thlorenz/brace) project issue how to deal with that. 

They answer me: [here](https://github.com/thlorenz/brace/issues/167#issuecomment-508928560)

So after my initialization, I had this:
```
  const editor = new JSONEditor(container, options);
  // set json  
  editor.set(jsonContent);

  editor.aceEditor.session.getUndoManager().reset();
```

But CTRL - Z always emptied my content...

Do you have any solution?!

**Comment by josdejong** [comment]
That's an interesting case. Thanks for figuring out the solution with Brace.

Your solution works except that you have to reset the undo manager on the next tick, like:

```js
  const editor = new JSONEditor(container, options);
  // set json  
  editor.set(jsonContent);

  setTimeout(function () {
    editor.aceEditor.session.getUndoManager().reset();
  }, 0)
```

I worked out a fix: https://github.com/josdejong/jsoneditor/commit/bc0e99ab4a79e562f2aacb8e300841e4620d116e (not yet published)

**Comment by bbr-yp** [comment]
It's working fine!!

Thanks a lot
