### ISSUE TITLE
Choosing HTML5 datalist instead of select 

### ISSUE THREAD

**Issue by Koushikphy** [josdejong/jsoneditor#740]
I'm working with a project where a `datalist` tag will be perfect choice instead of select of just a text input. I want to give to the user choice from some pre listed values but also want to give the freedom to input a value they desire. Like the input box you get when choosing the font size in Office software.  Is it possible to do something like that?

**Comment by josdejong** [comment]
Would #738 be a solution for you (not yet implemented)?

**Comment by Koushikphy** [comment]
Yeah! that would be really good implementation.

**Comment by josdejong** [comment]
Ok cool! Let's close this issue and continue any discussion there.
