### ISSUE TITLE
how to disable cache

### ISSUE THREAD

**Issue by MohandesaliRahnema** [josdejong/jsoneditor#741]
why component value(data) cache?
i had to reload page to clear that?

**Comment by josdejong** [comment]
?

**Comment by MohandesaliRahnema** [comment]
i write a react app with https://www.npmjs.com/package/jsoneditor and i
have a list of json filess that when i click them the user must edit them
when i print json every json files are uniqe and ok but
when i use this component it show the last file and i had to refresh to
show the correct data
i guess it will cache my prev data

**Comment by josdejong** [comment]
Can you share a small code example demonstrating your issue?

**Comment by MohandesaliRahnema** [comment]
<Editor
  {...JsonEditorOptions}
  value={JSON.parse(file.jsonContent)}
  onChange={(e) => this._handleJSONChange(file, e)}
  ajv={ajv}
  ace={ace}
  theme="ace/theme/github"
/>

**Comment by josdejong** [comment]
How can I execute that and how does this demonstrate the issue? Can you create a demo on https://codesandbox.io/ or something like that?
