### ISSUE TITLE
website not load in Iran (ip)

### ISSUE THREAD

**Issue by FarhadHP** [josdejong/jsoneditor#748]
website not load in Iran (ip)

**Comment by josdejong** [comment]
Any idea why?

**Comment by FarhadHP** [comment]
As are able to open it via VPN, it might be you that are banning our country. Or, the website is banned through ISP. I'm not sure which is the main reason.

**Comment by josdejong** [comment]
The web application is served via CloudFlare. It seems to be a very common issue, see https://community.cloudflare.com/search?q=iran. Did you try http instead of https?

**Comment by FarhadHP** [comment]
Thankyou.
Problem with HTTP (http://jsoneditoronline.org/) resolved.

**Comment by josdejong** [comment]
:+1:
