### ISSUE TITLE
when i set mode "text" or "code" and "statusBar:false" to jsoneditor, "Cannot read property 'clientHeight' of undefined" error occurs.

### ISSUE THREAD

**Issue by lvnvl** [josdejong/jsoneditor#755]
when i set mode "text" or "code" to jsoneditor, "Cannot read property 'clientHeight' of undefined" error occurs.
options likes: 
`
const options = {
          mode: "tree",
          modes: ['code', 'text', 'tree'],
          statusBar: false,
          onChange: this.handleChange,
        };
`

**Comment by josdejong** [comment]
Thanks for reporting @lvnvl, fixed via 9892249 (not yet published)

**Comment by josdejong** [comment]
Fixed now in `v6.3.0`
