### ISSUE TITLE
onSelectionChange event  does not work

### ISSUE THREAD

**Issue by zhouzhili** [josdejong/jsoneditor#756]
I open examples\15_selection_api.html ,  onSelectionChange event does not work

Has anyone encountered this problem?

**Comment by josdejong** [comment]
The `onSelectionChange` fires when you select multiple lines in tree mode, have you tried that?

**Comment by zhouzhili** [comment]
ok, thank you, in the tree mode, I can see which field I am currently clicking on, there is a display on the status bar, but  no such event in the API.
![image](https://user-images.githubusercontent.com/14259932/62433728-35497880-b768-11e9-9ef4-b1874bb7b187.png)

**Comment by zhouzhili** [comment]
I have solved this problem， thank you

**Comment by josdejong** [comment]
:+1:

**Comment by t4ckermann** [comment]
@zhouzhili i've got the same problem, could you tell me how you solved it?
`onSelectionChange(start, end){
          console.log(start)
          console.log(end)
        }`
Is not logging anything in the console.

**Comment by t4ckermann** [comment]
NVM, i just use the onEvent Method for now.
