### ISSUE TITLE
Unable to paste on GUI fields after saving file

### ISSUE THREAD

**Issue by mp19uy** [josdejong/jsoneditor#76]
After using it for a while, I often have the problem that if I try to paste something on a field in the right side (graphical side), I can't. This happens after I press save and save the file somewhere.

I have some text on the clipboard, I select the field, press Ctrl+V and nothing happens.
Also If I press secondary click on the field, doesn't appear the paste option.
But, if I try to do that in any other place (like the url bar for example) I can.

I "fix it" every time by closing the tab and opening http://jsoneditoronline.org/ again, or the other thing that I found that solves the "paste problem" is clicking with the secondary click on the field and selecting: View Background Image (that takes me to this page: http://jsoneditoronline.org/lib/jsoneditor/img/jsoneditor-icons.png), and right after that, I press BACK button in the  navigator and I'm able to paste things on the fields again.

Another detail, when I'm able to paste by right-click paste, the option "View Background Image" doesn't appear on the menu.

My browser is: Firefox 25.0
My OS: Linux Mint 15 x64

**Comment by josdejong** [comment]
Since I can't really do anything to resolve this, I will close this issue now
