### ISSUE TITLE
 Problem with css code for overriding  

### ISSUE THREAD

**Issue by ppetkow** [josdejong/jsoneditor#760]
[div.jsoneditor ](https://github.com/josdejong/jsoneditor/blob/develop/dist/jsoneditor.css)

Hello, i found this as hough problem. 

Your code start really strange for your application. Our devs used a lot, but we need to change style of this app and hit this css problem. 1st is css not some preprocessor like scss or less (prefer scss). 

2nd in your css code on 4th row you make 2 important in beginning of file!! I think this is to much and is really incorrect. Can you improvе option for overriding by removing !important's and start all styles from one general class name only. 

`<div  class="jsoneditor"> ... </div>`  

And all inside this div depend on this class name. 

Also i strongly suggest you to move it on SCSS. Then the project will be more flexible and good.

**Comment by josdejong** [comment]
Thanks for your input. 

The usage of `!important` is indeed not pretty, though you can still override it for custom styling. 

A PR replacing the usage of `!important` or even move to SCSS would be welcome :)

**Comment by ppetkow** [comment]
Ok i will update project :) and move to SCSS

**Comment by ppetkow** [comment]
More Q :) 

Search box is too complicate with this 2 tables, can i update it and move it to divs. This means also to change display to flex. But you write on website that  the tool support IE8+, but if i want to use flex-box model needs to pump version of IE to 10. If this was compromise from your side i will be happy to upgrade. :)

**Comment by josdejong** [comment]
Thanks for your offer! The IE8+ was a leftover, I've changed that to IE11 now (like JSONEdtior itself already mentioned in the readme: https://github.com/josdejong/jsoneditor#json-editor). 

A small refactoring to use flexbox here and there would be very welcome! That's also needed for the main menu / navigation bar / contents / status bar. Please be careful not to make a _too_ big PR at once, preferrably one PR addresses one thing, else it's hard to review.

**Comment by ppetkow** [comment]
> A small refactoring to use flexbox here and there would be very welcome! That's also needed for the main menu / navigation bar / contents / status bar. Please be careful not to make a _too_ big PR at once, preferrably one PR addresses one thing, else it's hard to review.

know ... to late .. movement from css to scss was big changes for files

**Comment by josdejong** [comment]
@ppetkow is your initial concern resolved with the refactoring to SCSS that you did? Can we close this issue?

**Comment by ppetkow** [comment]
Yes, definitely! Thank you

**Comment by josdejong** [comment]
:+1:
