### ISSUE TITLE
Automatically resize editor height

### ISSUE THREAD

**Issue by dealancer** [josdejong/jsoneditor#762]
Is there a way to automatically resize the editor height based on the numbers of elements?

**Comment by josdejong** [comment]
If you don't give the editor a height it automatically scales, fitting the contents. You can try that out by removing the line `height: 500px;` from for example [01_basic_usage.html](https://github.com/josdejong/jsoneditor/blob/develop/examples/01_basic_usage.html). Is that what you mean?

**Comment by dealancer** [comment]
@josdejong That works as expected, but not when the `mode` is `text`.

**Comment by josdejong** [comment]
Ah, that's true, it won't work for mode `text` and `code`. If you need auto sizing there it will become very hard. I guess you would have to somehow calculate yourself what the height of the contents is and adjust the height of the editor accordingly.

**Comment by dealancer** [comment]
Is there a way to integrate this project https://github.com/jackmoore/autosize into yours?

**Comment by josdejong** [comment]
That could work for the `text` mode, but I guess not for `code` mode (powered by Ace editor). I'm a bit in doubt whether this use case is worth the effort. Normally a finite height makes sense so you can always see the top menu. Can you explain your use case?

**Comment by calsmith-nokia** [comment]
For posterity: 
The above comment works, but I was getting weird behavior with less than ~10 lines (I'm only using code mode). Turns out there's a min-height css that can be overridden with:
```css
.ace-jsoneditor, textarea.jsoneditor-text{
    min-height: 0px;
}
```
