### ISSUE TITLE
Cannot read property 'getPath' of undefined

### ISSUE THREAD

**Issue by Thaina** [josdejong/jsoneditor#763]
https://github.com/josdejong/jsoneditor/blob/3f182a1f0411764fabab1d9bb35bbfbaaa41f67c/src/js/treemode.js#L1496-L1499

If we set `autocomplete.trigger` as `focus` it will go to line 1498 but then `node.getPath()` will thrown if it cannot find node when we press it here

![image](https://user-images.githubusercontent.com/1042507/62611903-ae93c780-b930-11e9-9e4a-4b9f71bf1170.png)

Should we check `node` variable and return when it was not a Node?

**Comment by josdejong** [comment]
Fixed now in `v6.3.0`
