### ISSUE TITLE
sortObjectKeys broken in 6.3.0

### ISSUE THREAD

**Issue by kluthje** [josdejong/jsoneditor#777]
If you turn on sortObjectKeys option in the basic usage example, an exception will be thrown on JSONEditor object initialization because it runs a builtin onChange callback and JSONEditor->node property is still null. Tested in version 6.3.0. I was trying to update from version 5.24.6 where it still worked.

Here is a jsfiddle of the behaviour: https://jsfiddle.net/g0Lsxdk2/

Thrown Exception:
`
Uncaught TypeError: Cannot read property 'findNodeByInternalPath' of null
    at h._onChange (0:37014)
    at h._onAction (0:36992)
    at R.sort (0:43981)
    at R.setValue (0:40707)
    at new R (0:40253)
    at h.set (0:36719)
    at h.setMode (0:8720)
    at h._create (0:8629)
    at new h (0:8579)
    at window.onload ((index):39)
`

**Comment by josdejong** [comment]
Thanks for reporting this bug Klaus!

**Comment by josdejong** [comment]
Created a fix (not yet published)

**Comment by josdejong** [comment]
This issue is fixed now in `v6.4.0`, can you give it a try Klaus?

**Comment by kluthje** [comment]
Yeah seems to be fixed in 6.4.1 which was the current version at this time. Thanks!
