### ISSUE TITLE
Advertising package

### ISSUE THREAD

**Issue by traverseda** [josdejong/jsoneditor#779]
It looks like this project depends on https://github.com/feross/funding, a project intended to show advertising in a projects build log.

I'm not familiar with your project, I'm just looking through a list of projects that depend on `feross/funding`. It's my understanding that right now there aren't any advertising messages actually showing, but if you're uncomfortable with the possibility of advertisements in build logs that's something you might want to look into.

**Comment by josdejong** [comment]
Yes that's a dependency of `standard`. I've seen it. I do not like the ads though I love it that Feross managed to get a discussion rolling about compensation for people contributing to open source.

The `funding` experiment was stopped again: https://feross.org/funding-experiment-recap/

**Comment by traverseda** [comment]
Seeing as it is explicitly over, I don't see any reason to keep this open.
