### ISSUE TITLE
Cannot read property 'session' of null

### ISSUE THREAD

**Issue by samudiogo** [josdejong/jsoneditor#781]
Hi, 
Using with angular em react forms, the solution for issue #730 fires this error:

> Cannot read property 'session' of null

https://github.com/josdejong/jsoneditor/blob/a78adf667634f570d2a4a41af2dc3557b957bd31/src/js/textmode.js#L721

Stackbliz:
https://stackblitz.com/edit/angular-gx54gz

**Comment by josdejong** [comment]
Thanks for reporting, that's an interesting race condition. Should be fixed now in `v7.0.2`.
