### ISSUE TITLE
View-only mode in Active Admin

### ISSUE THREAD

**Issue by tlhinman** [josdejong/jsoneditor#786]
Hello! I'm creating a form in Active Admin/Formtastic, which includes a jsoneditor input. Under some circumstances, though, the JSON should be locked and uneditable, in which case I'd want to use the view mode so it can be read but not changed. Is there a way to do this on the Ruby side? The current code looks something like this.

```
form do |f|
    f.inputs do
      input(:my_data, as: :jsonb)
    end
end
```

**Comment by josdejong** [comment]
I'm not familiar with Active Admin/Formtastic, but in jsoneditor you can set the mode to `view` (readonly) or `tree` (editable, default), and switch afterwards using the method `editor.setMode(mode)`.

**Comment by vasilvalkov** [comment]
I have a similar use case where I switch from 'Form" to 'View' mode until another task completes and then bring back the 'Form' mode. The drawback of this approach is that I lose the history for 'Form' mode.

Is there a way, so I can bring the history back when I return to the 'Form' mode?

**Comment by josdejong** [comment]
Would it be possible to keep the editor with form mode in memory, hide it, and create a second instance of the editor with view mode? To go "back" to form mode you can make the hidden editor visible again.

**Comment by vasilvalkov** [comment]
This is a good workaround but too complex to perform. As there is no built-in functionality fot it I'd prefer not to disable editing and leave the responsibility to the userr.

**Comment by josdejong** [comment]
Will close this issue now, feel free to reopen if needed.
