### ISSUE TITLE
HTML examples in /examples/ folders won't work without dist folder

### ISSUE THREAD

**Issue by vishwasnavadak** [josdejong/jsoneditor#788]
The HTML files in example folder refer the `dist` folder at root for the .css and .js files. Either the folder has to be restored or CDN links can be given in html files. 

Let me know if you need any help doing it.

**Comment by josdejong** [comment]
The dist folder is provided with the published npm package, all examples work fine there (also the react examples, I don't think your fix of #787 is needed). If you checkout the git repository, you can generate the dist folder via `npm install && npm run build`.

**Comment by vishwasnavadak** [comment]
Didn't realize that. Putting instruction to run build in react example readme might help the beginners. 

Great tool though 🔥

**Comment by josdejong** [comment]
Thinking about it, you're right about the React examples. I think most commonly you will copy the react code example and put it somewhere else, where `file:../..` is not pointing to the JSONEditor library. So let's go for your solution :+1:

**Comment by vishwasnavadak** [comment]
> I think most commonly you will copy the react code example and put it somewhere else

That's exactly what I did ✌️

**Comment by josdejong** [comment]
:joy:

**Comment by rwhirn** [comment]
@josdejong Examples not working with npm version downloaded 8/26/19
![image](https://user-images.githubusercontent.com/25158630/64576519-8d166900-d33e-11e9-9468-0576d1845f5d.png)

**Comment by josdejong** [comment]
@rwhirn please read this topic from the start. If you checkout or download the source code of the project, you will first have to build the library before you can run the examples.

**Comment by rwhirn** [comment]
@josdejong I read the whole topic and all the documentation in the repo. I followed all the steps. I have a dist folder. I have node_modules folders (one in repo root, one in examples\react_demo, and one in examples\react_advanced_demo.

**Comment by rwhirn** [comment]
@josdejong As I mentioned at first I downloaded the zip version from 8/25/19 on 8/26/19. It came with a "dist" folder. So to try and figure this out I downloaded today's version (9/11/19) which is without a "dist" folder and ran "npm install". But "npm build" returns
`npm WARN build npm build called with no arguments. Did you mean to npm run-script build?`
