### ISSUE TITLE
[QUESTION] Manipulate JSON via some javascript function

### ISSUE THREAD

**Issue by fdeandao** [josdejong/jsoneditor#79]
I want to edit/update partially a JSON document (not with editor.set(newJSON))  through some javascript function, i see the source but i not found a easy way to do this.

Example:

(Displayed info in editor)

object		{3}
   string	:	a
   string	:	b
   string	:	c

through programming, I want to change the value of the first field

Somebody know how to do this?

**Comment by josdejong** [comment]
I will close this issue now, we can continue discussion in #39
