### ISSUE TITLE
Got a Javascript error when try to open action menu in Chrome

### ISSUE THREAD

**Issue by handre** [josdejong/jsoneditor#790]
In chrome 76.0.3809.132. Tried to open the action menu of a JSON node and got javascript problem
It happens either by clicking or by ctrl+M shortcut.

Tested in firefox 69.0 and it worked fine.

![image](https://user-images.githubusercontent.com/1661143/64484848-94c6f800-d1ee-11e9-844a-67b521f587c7.png)

The error is:
`app.min.js:1 Uncaught TypeError: Cannot read property 'replace' of undefined
    at h (app.min.js:1)
    at R.value (app.min.js:1)
    at R.value (app.min.js:1)
    at R.value (app.min.js:1)
    at p.j._onEvent (app.min.js:1)
    at HTMLDivElement.i (app.min.js:1)`

BTW, thanks for this awesome tool ! It is very helpful I use it on a daily basis. :)

**Comment by josdejong** [comment]
Thanks for your report. I can't reproduce this issue. 

Can you try to refresh your browser with Ctrl+F5? Maybe there is a cache issue or so? Or is it something specific to the JSON document you had loaded?

**Comment by handre** [comment]
Indeed it does not happen with any JSON.
I just managed to surround the breaking scenario:

This worked fine =>                   {"label_names":"Integration"}
This one breaked Javascript => {"label_names":["Integration"]}

Please, let me know if you can reproduce with this info.

**Comment by josdejong** [comment]
hm, no luck reproducing the issue :(

**Comment by josdejong** [comment]
Andre, just an other idea: to figure out if this is some caching issue in Chrome or not, can you open an example of the JSONEditor library that you never opened before and see if the error occurs there too?

For example:
https://unpkg.com/browse/jsoneditor@7.0.3/examples/ -> select and example, click "raw"
https://unpkg.com/jsoneditor@7.0.3/examples/03_switch_mode.html

(or create and open an example locally in your browser)

**Comment by handre** [comment]
I've tried to reproduce the issue again and it seems it is working properly.
Thanks for the attention  @josdejong!

**Comment by josdejong** [comment]
👍

**Comment by brunohenriquebh** [comment]
Hello,

This is an example of json that generates the error mentioned above, I tested in the latest version, and the problem still occurs.

{
  "contactList": {
    "type": "Schema.Types.ObjectId",
    "ref": " 'contact/list' ",
    "required": true
  }
}

**Comment by handre** [comment]
@brunohenriquebh 
The language is a nice catch, my language is also pt-br and I did reproduce the bug with the json you sent.

Here is my recording for that:
[bug_demo.zip](https://github.com/josdejong/jsoneditor/files/4077338/bug_demo.zip)

**Comment by josdejong** [comment]
Thanks, now I can reproduce it :+1: . It was caused by a missing translation field in `pt-br` containing a placeholder field. Fixed now in `v8.3.0`.
