### ISSUE TITLE
+ symbol is ignored when text followed by + is a number

### ISSUE THREAD

**Issue by slash-arun** [josdejong/jsoneditor#794]
When the editor in tree mode and suppose I have countryCode: null in my JSON. I would like to update it to +1. The editor ignores + and simply makes it 1. How do I tell the editor it is a string and not an integer value?

In my opinion +1 should be considered a string as 
```
{
   "code": +1
}
```
is an invalid JSON.

![Screen Shot 2019-09-14 at 5 42 36 AM](https://user-images.githubusercontent.com/54778962/64908258-84ad8d80-d6b2-11e9-866a-42e21e78165b.png)
![Screen Shot 2019-09-14 at 5 42 41 AM](https://user-images.githubusercontent.com/54778962/64908259-88411480-d6b2-11e9-8329-c1382b09d6ee.png)

**Comment by arun-28** [comment]
In my opinion +1 should be considered a string and not an integer as code:+1 is not a valid json

**Comment by josdejong** [comment]
> How do I tell the editor it is a string and not an integer value?

Click on the action menu, and change "Type" to "String". 

`+1` is an interesting case: it's not a valid number in JSON, but it is in JavaScript. We could improve on that in the JSONEditor I think.

**Comment by slash-arun** [comment]
I could work on it and raise a PR, if you are okay with `+1` becoming a string on the editor automatically.

**Comment by josdejong** [comment]
already working on it, will do a release today :)

**Comment by slash-arun** [comment]
Awesome, Thanks!

**Comment by josdejong** [comment]
I was testing with this new approach, and after testing I'm in doubt if this behavior is what we want generally (at least how I implemented it right now). I simply use `JSON.parse` to validate whether something is a valid JSON number. The example `+1` is not something that you typically would enter when you want to enter a number, and you may mean to enter the thumbsup emoticon :+1: . But for example `.25` is also no valid JSON number, but your intention there is probably to enter a number not a string. Maybe just a special case for starting with `+` would be a better approach, not sure yet.

**Comment by josdejong** [comment]
@slash-arun can you explain more about your use case?

**Comment by slash-arun** [comment]
My use case is that we have a country code in the JSON. It becomes a
problem with the country code as it is considered a number instead of a
string, but I got the issue with .1 or .2 that you are talking about though.

**Comment by josdejong** [comment]
Is there a possibility that you can initialize this country code field with an empty string for example to prevent these issues? Or maybe define a JSON schema to warn the user when it's not a string?

**Comment by slash-arun** [comment]
Yeah, we could always work around it, incase, this does not fit into the
editor's roadmap. The schema validation approach seems nicer than spaces.

**Comment by josdejong** [comment]
Thanks for your understanding. I hadn't realized beforehand but I'm afraid this has to many unwanted side effects. If you're ok with it I would like to revert the initial fix I made (8554789aa76a4537a8fa3198a348b0a17cf2a996). It would be great if you can try out solutions in the direction of validation and initialization (maybe even templates can be helpful).

**Comment by slash-arun** [comment]
Sure. Will do

**Comment by josdejong** [comment]
:+1: 

I've reverted my initial solution via a60a1125ea1ce424f4c4b0400e2ed650e03df649.
