### ISSUE TITLE
jsoneditor running in code mode gives warning while running test cases

### ISSUE THREAD

**Issue by risheekeshyadav** [josdejong/jsoneditor#798]
Hi Team,

I have implemented the jsoneditor and it is working fine except the warning coming after running the json editor "code" mode. I have taken your react advanced demo and change the mode to code and tried and getting the same warning. Please help me with this.

Below is attachment:
![image](https://user-images.githubusercontent.com/28145824/65412204-5e9f9000-de0c-11e9-8337-28a9c5b36e3b.png)

**Comment by josdejong** [comment]
I think this is the Ace editor (used in code mode) which tries to create a Web Worker to do validation of the JSON object. In a node.js testing environment there is no Web Worker available. Can that be the case? I _think_ though that the application will just work - ace editor can run fine without web worker. If that's indeed the case, you could either suppress the warning somehow, or try to mock `URL.createObjectURL` and `new Worker(...)` so the warning isn't thrown in the first place.

**Comment by risheekeshyadav** [comment]
Thanks for the update, I tried to mock the URL.createObjectURL and new Worker(...) but it didn't work. For now, I change the mode to other while running test cases dynamically. If you found any solution let me know. Again thanks for the help.

**Comment by josdejong** [comment]
:+1:  will close this issue for now then.

**Comment by josdejong** [comment]
Today I had the exact same issue with Jest, using JSONEdtitor in a React application. 

I worked around the console warnings by creating the following mocks before running tests:

```js
// mock createObjectURL and Worker
window.URL.createObjectURL = () => {}
window.Worker = function Worker () {
  this.postMessage = () => {}
  this.terminate = () => {}
}
```
