### ISSUE TITLE
How may I insert a json to the editor using js?

### ISSUE THREAD

**Issue by Javierimperial** [josdejong/jsoneditor#811]
Hi, I am trying to create an option that help the user to create a json.
The user fill the form  and then with that information I generate a json. 
https://ibb.co/H4RbJM2

I tried several ways to insert that json to the editor but I didn't had luck. Is there any documentation I can use as guide?

**Comment by josdejong** [comment]
The readme contains a section "Documentation" explaining all of that:

**Comment by Javierimperial** [comment]
@josdejong Thank you! 
I found it https://github.com/josdejong/jsoneditor/blob/develop/docs/api.md#user-content-jsoneditorsetjson

**Comment by josdejong** [comment]
:+1:
