### ISSUE TITLE
Console prints an error when editing strings in "code" mode

### ISSUE THREAD

**Issue by Amiryy** [josdejong/jsoneditor#824]
Hello,
While editing `strings` in `code` mode, if the user creates a new line by pressing enter an error appears in the console:
`Uncaught TypeError: Cannot read property '0' of undefined`.

This happens specifically when inserting a new line inside `string` type fields.

Check out this simplified example: https://jsbin.com/metaquc/5/edit?html,output
To reproduce:
1. Open browser console
2. Create a new line in the middle of the string, by pressing Enter, to make the JSON invalid.
3. Check the console to see the error
4. Try to change the JSON to become invalid in different ways, like editing `boolean` or `number` fields or just delete a `"` at the end of a `string` and see that the error does not appear.

This error does not seem related to JSON parsing, it looks like a small bug in source code.

I am using version ^7.0.1

Thanks!

**Comment by josdejong** [comment]
Thanks for reporting Amir, I can reproduce this issue. Shouldn't be too hard to fix

**Comment by josdejong** [comment]
This is fixed now in `v7.2.0`. Thanks again!
