### ISSUE TITLE
Indentation option not working

### ISSUE THREAD

**Issue by eeyshen** [josdejong/jsoneditor#826]
Indentation option is not working even when mode is 'code', 'text', or 'preview'. Thanks.

**Comment by josdejong** [comment]
I tried but the `indentation` option seems to work fine. How can I reproduce your issue?

**Comment by eeyshen** [comment]
For example, the top shows tree mode, the bottom shows the code. I think these should be no indentation when I set it to zero. But these is no difference with indentation equal to two.
<img width="219" alt="截屏2019-10-24上午9 38 01" src="https://user-images.githubusercontent.com/31716017/67446109-098caf00-f642-11e9-9308-64066a377c7b.png">
<img width="192" alt="截屏2019-10-24上午9 38 18" src="https://user-images.githubusercontent.com/31716017/67446110-0abddc00-f642-11e9-9a93-4646a92009e2.png">

**Comment by josdejong** [comment]
Thanks for reporting. This was caused by one of these famous JavaScript pitfalls, see 43e0c129ec83bb92ade2ce7949aed69bfa1cd78c.

**Comment by eeyshen** [comment]
I tried to set indentation equals 10, nothing different happened. Would you show how to change it successfully? Thanks.

**Comment by eeyshen** [comment]
Sorry. It is my fault. As you said, 'Only applicable when mode is 'code', 'text', or 'preview'.'
Is it possible to set it in 'tree' mode? Thanks.

**Comment by josdejong** [comment]
In tree mode, the indentation is hardcoded with 24px per indentation level. To change this you'll have to hack into the editor:

https://github.com/josdejong/jsoneditor/blob/009d896c30427f8eebb5e6773f4f580d1483a1ac/src/js/Node.js#L2137-L2141

**Comment by josdejong** [comment]
Setting indentation to `0` is fixed now in `v7.2.1`.

**Comment by eeyshen** [comment]
Thanks. Would you please make indentation changeable in tree mode as other modes?

**Comment by josdejong** [comment]
The tree mode doesn't have code with indented with characters like the code mode, changing the visual indentation in pixels will not make for a more clear view (currently the buttons of every indentation level are neatly aligned). 

Can you explain why you would like to see the indentation setting reflected in tree mode?

Btw the `getText()` method does respect the `indentation` option with all modes.

**Comment by josdejong** [comment]
Ok so you want to visually align both modes the same way. I understand what you want but I think this is too much of an edge case to build a feature for it. If it turns out this is a much needed feature we can always reconsider.
