### ISSUE TITLE
Collapse or expand node when click node's text in 'Form' mode

### ISSUE THREAD

**Issue by eeyshen** [josdejong/jsoneditor#828]
When choosing text of node in 'Form' mode, the node collapse or expand. It is confusing and inconvenient. It is expected that the node only collapse or expand when click the node's icon as the 'Tree' mode.

**Comment by josdejong** [comment]
Thanks. I think I created it originally as a feature, but I agree with you that this behavior is confusing. I've removed it via 8e15be0f12791398331dc23e8abfd207b2bcd933.

**Comment by eeyshen** [comment]
Thanks. Looking forward to the next release.

**Comment by josdejong** [comment]
Fixed now in `v7.2.1`.
