### ISSUE TITLE
Autocomplete is activated when click on the collapse icon in 'tree' and 'form' mode

### ISSUE THREAD

**Issue by eeyshen** [josdejong/jsoneditor#832]
I found that the autocomplete will be activated when click on the collapse icon in 'tree' and 'form' mode. And the dropdown menu shows. It is better that the autocomplete only be activated when user click or modify texts. Thanks.

**Comment by josdejong** [comment]
Thanks for reporting @eeyshen . How can I reproduce your issue? I tried with the autocomplete examples but I can't get the dropdown to activate when clicking the collapse button.
