### ISSUE TITLE
Warning in Developer Console: window.controllers/Controllers is deprecated.

### ISSUE THREAD

**Issue by MaggiWuerze** [josdejong/jsoneditor#833]
when i use the library in my project i get this warning in the browser dev console:
`window.controllers/Controllers is deprecated. Do not use it for UA detection.`

**Comment by josdejong** [comment]
Thanks for reporting. This was something in older versions of ace editor, is solved since `v7.1.0` I think. Are you using the latest version of JSONEditor?

**Comment by MaggiWuerze** [comment]
just checked (using webjars), the version is really old, still starting with a 5. forget i said anything

**Comment by josdejong** [comment]
The package is only available on npm. You could download the js and css bundles from for example unpkg: https://unpkg.com/browse/jsoneditor@7.2.1/dist/. Generally though it's best to use a package manager so you can easily keep dependencies up to date.

**Comment by MaggiWuerze** [comment]
that's why is use webjar but there's no up to date version there unfortunately, but thanks for the link
