### ISSUE TITLE
code vs tree editor can get out of sync & key sequence incorrectly inserted when copied

### ISSUE THREAD

**Issue by samuelgoff** [josdejong/jsoneditor#842]
Changes made beyond the initial (truncated) view in large objects often do not maintain sequence when editing & copying changes back and forth from `code editor` to `tree editor` (or visa-versa). Newly created/edited values will often get copied to end of object rather than respect proper sequence (causing `code editor` vs `tree editor` to get out of sync until an explicit `sort` is applied to a large object in `tree view`).

1. start with a map of maps, with each nested map being a large object (let's say, an object containing more than 200 keys in `code editor`), like so:
<img width="745" alt="Screen Shot 2019-11-06 at 7 26 19 AM" src="https://user-images.githubusercontent.com/2007084/68302033-ca5d5580-0066-11ea-82bc-ab5040cc2b2c.png">

2. click `copy code to tree editor` to, well, copy the code to `tree editor` pane
<img width="305" alt="Screen Shot 2019-11-06 at 7 11 42 AM" src="https://user-images.githubusercontent.com/2007084/68301041-b9134980-0064-11ea-9282-fc0ca0bf3b1e.png">

3. expand object and scroll to bottom of list of keys where it says `Displaying 100 of 234 keys | _show more_ | _show all_`
<img width="332" alt="Screen Shot 2019-11-06 at 7 08 22 AM" src="https://user-images.githubusercontent.com/2007084/68301107-dcd68f80-0064-11ea-8c52-3fbe463548a6.png">

4. click `show all`

5. insert 3 new key/value pairs into middle of list of key/value pairs in `tree editor`

6. click `copy code to code editor`

7. scroll list of keys on `code editor` to find newly-created entries (sequence may or may not be correct; if incorrect, they will appear at end of object)

8. copy 3 newly-created entries to same sequence in middle of sibling object (e.g. from `en.dictionary` to `fr.dictionary` in example shown in 1 & 2)

9. edit values for newly-created and -copied entries in sibling object (e.g. in `fr.dictionary`)

10. click `copy code to tree editor`

11. expand object that contains newly-created and -edited entries in tree view and scroll to bottom of list of keys where it says `Displaying 100 of 234 keys | show more | show all`

12. click `show all`

13. find newly-created and -edited key/value pairs at end of sequence (even though inserted & edited in middle of sequence in code editor, they often appear at the end of expanded list of keys)

14. click `sort` on parent object (e.g. in `fr.dictionary`) in order for them to appear correctly sorted

15. click `copy code to code editor` in order for sequence to be respected in code editor

**Comment by josdejong** [comment]
Thanks for your detailed report. It requires quite some steps to reproduce, it would be great if we can find a simpler, more minimalisitic way to reproduce the issue.

It could have to do with objects having more than 100 properties, so not all of them are rendered. In that case it should be possible to have a flat object with more than 100 properties, add something in the middle, and get this change in ordering.

Can you share the data that gave this sorting issue? That would make it easier for me to reproduce.

**Comment by josdejong** [comment]
Will close this issue due to inactivity. Feel free to reopen if needed
