### ISSUE TITLE
Should be object

### ISSUE THREAD

**Issue by ankitsinghaniyaz** [josdejong/jsoneditor#845]
![image](https://user-images.githubusercontent.com/11331989/68789756-0fd3e100-066c-11ea-8e78-fcc118f1098e.png)

I'm tyring to pass in an array of object as my default json but it says that it should be object. Any way to disable this warning/error?

**Comment by josdejong** [comment]
It looks like you've loaded a JSON Schema in the editor which prescribes that the contents of the editor should be an object.
