### ISSUE TITLE
How to add two self-defined buttons?

### ISSUE THREAD

**Issue by jiakangning** [josdejong/jsoneditor#849]
可以新增两个自定义按钮嘛？这两个按钮实现切换两种模式

**Comment by josdejong** [comment]
English please?

**Comment by jiakangning** [comment]
How to add two self-defined buttons？

**Comment by josdejong** [comment]
If you mean in the context menu, see option `onCreateMenu`. If you mean in the main menu on top, there is currently no built in option for that. There is an open issue to address this, see #831. 

As a workaround, you can first create the JSONEditor, then get the div of the menu using a querySelector, then add you own buttons to that div.
