### ISSUE TITLE
Error with null value in autocomplete dropdown menu

### ISSUE THREAD

**Issue by eeyshen** [josdejong/jsoneditor#850]
If the autocomplete dropdown menu has item that is 'null', these will be error with 'toLowerCase'.

**Comment by josdejong** [comment]
Thanks for reporting @eeyshen. How can I reproduce this issue exactly?

**Comment by eeyshen** [comment]
If the autocomplete return list like [null, 'a', 'b'], the error will happen. Thanks.

**Comment by josdejong** [comment]
Ah, yes I see, I can reproduce this issue.

**Comment by josdejong** [comment]
I looked a bit into this, and the autocomplete feature simply assumes a list with strings as input. So you can do something like: `['null', '123', 'a', 'b']`. 

I see the docs indeed state that the `options` should be a `string[]`. It would be nice though to make the editor robust against this, either silently convert the inputs to strings, or throw an error on invalid input.

**Comment by josdejong** [comment]
I've made the editor robust against non-string options in 0d4525d3d20dfe538de93ec78d84c2202621c997 (not yet published)

**Comment by josdejong** [comment]
This is fixed now in `v7.4.0`
