### ISSUE TITLE
Parse error on line 1 at column 0: Expected one of: 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '['

### ISSUE THREAD

**Issue by madeeha-khan** [josdejong/jsoneditor#852]
I am getting this error when I do `arc diff develop` from working branch. However, `arc diff develop --create` is working fine. Tried using `arc diff develop --update`, but the same issue is coming with that command.
The issue is, after every review, I am bound to run `arc diff develop --create` which is causing problem in tracking the revisions. 

```
{
  "phabricator.uri": "https://phabricator.noc.tvlk.cloud/",
  "repository.callsign" : "TPXIX",
  "arc.land.onto.default": "develop",
  "load": ["backend-arcanist/src"]
}
```

This is the configuration of my .arcconfig file.

**Comment by josdejong** [comment]
Is this a question about JSONEditor?
