### ISSUE TITLE
Choose specific buttons to be showed

### ISSUE THREAD

**Issue by robertomellocampos** [josdejong/jsoneditor#853]
Hello,

I would like to know if Im be able to choose specific buttons to be showed. For example only the autoformat button.

![image](https://user-images.githubusercontent.com/5216322/69661937-19911780-1062-11ea-852e-df1f15af30db.png)

Is it possible?

Thank you

**Comment by josdejong** [comment]
Yes, you can hide the buttons you don't want using some CSS.
