### ISSUE TITLE
Feature request: add timestampFormat to customize the way formating timestamp

### ISSUE THREAD

**Issue by smallp** [josdejong/jsoneditor#856]
Timestamp in second, such as 1543998137, would not be formated correctly. There is no way to modify the value before it has been formated. So it would be better if I can format the timestamp myself.
I'd like to pull a request if you are too busy to do that.

**Comment by josdejong** [comment]
Thanks, that's a good suggestion @smallp. 

Last week I improved the existing `timestampTag` option to allow customizing what values do contain a timestamp. The function still assumes that timestamps are in milliseconds. You have a good point that it can also be seconds, and that you need to format that differently. We need to give that some more thought: the latest version of JSONEditor will create a wrong tag for fields with a name like "time" or "date" which contain a value in seconds. We need to give that some more thought. Maybe make the built in function more conservative again so at least it will not show wrong tags.

A second option `timestampFormat` can solve that issue. Would be great if you can help with this! What do you think this new option should look like?

**Comment by smallp** [comment]
As the package aims to be out of the box, I believe the default setting is better. Users can disable this feature with `timestampTag`. However, users should be able to exclude certain fields with `timestampTag`. It will be better if this package can fallback to default setting when user return `null` in `timestampTag`.
As for `timestampFormat`, its params are the same with `timestampTag` but return a string or `null`. If the return is `null`, using the default setting.
What do you think?

**Comment by josdejong** [comment]
> As for `timestampFormat`, its params are the same with `timestampTag` but return a string or null. If the return is null, using the default setting.

Passing the same parameters sounds good. I'm not sure about falling back to the default setting, it makes sense, it is nice if you can fallback on default behavior. The behavior should be consistent with `timestampTag` though, so there the behavior should explicitely be: 

- when returning `true` -> a timestamp will be displayed
- when returning `false` -> no timestamp will be displayed
- when returning `null` or `undefined` -> fallback to built-in rules

The third point is not current behavior, so we should change that then. Strictly speaking this is a breaking change, we have to be careful here. Alternatively, we could simply expose the build-in `isTimestamp` function (and `formatTimestamp`) so you can call that yourself when you want to fallback on default behavior. Just thinking aloud here :)

**Comment by smallp** [comment]
#863 Here is the PR. I just add `timestampFormat` and you can change `timestampTag` later. :)
So this issue can be closed then.

**Comment by josdejong** [comment]
:+1: I will pick that up after your PR is merged.

**Comment by josdejong** [comment]
The new `timestampFormat` and the changed behavior of `timestampTag` are now available in `v8.0.0`. Thanks again Small :)
