### ISSUE TITLE
Set default values on conditions

### ISSUE THREAD

**Issue by bturner1273** [josdejong/jsoneditor#859]
This is more of a question if this is already possible:

![image](https://user-images.githubusercontent.com/32464706/70187722-e7646300-16bc-11ea-8acf-1f2752a42019.png)

So I have some strings in my json that aren't filled in. I would like them to default to null as opposed to this 'value' empty box thing.  Is this supposed to be in the options obj I provide?

**Comment by bturner1273** [comment]
These were all supposed to be empty strings^^ i.e. ''/""

**Comment by bturner1273** [comment]
Just noticed you can have a default field if you include a schema (I was doing custom validation)

**Comment by bturner1273** [comment]
Thought it was closed when I found default field for schema but you still can't say:

when loading this json into the editor, if this field is of type string and it is null or whitespace, then set the value to null.

**Comment by josdejong** [comment]
For reference: #862
