### ISSUE TITLE
Feature Request: Add show context menu to options

### ISSUE THREAD

**Issue by vikaskesakar** [josdejong/jsoneditor#864]
In tree mode, context menu is default, so add option to show/hide context menu.

**Comment by josdejong** [comment]
There is a mode `form` which hides the context menu, is that what you're looking for? If not, can you explain your use case?

**Comment by vikaskesakar** [comment]
I was trying to hide context menu, but I haven't found any option like showContextMenu or something like that. So I tried to apply css: display option but it was not able to hide td used to show context menu

**Comment by josdejong** [comment]
You should be able to hide the button with some CSS like 
`div.jsoneditor-tree button.jsoneditor-button { display: none }`

Can you explain though _why_ you need this? When hiding the context menu, you can still do anything like inserting new fields using shortcut keys.

**Comment by vikaskesakar** [comment]
I need JSON editor tree mode without context menu. I just need to edit the values and not the keys also.

**Comment by josdejong** [comment]
Ok, so back to my first question :smile: 

> There is a mode `form` which hides the context menu, is that what you're looking for?

**Comment by vikaskesakar** [comment]
Can you please provide usage details?

**Comment by josdejong** [comment]
You can search the docs and examples on how to set a specific mode. It's like: 
```js
const options: { mode: 'form' }
```

**Comment by vikaskesakar** [comment]
Thanks 👍
