### ISSUE TITLE
Question: Can you disable editing of certain json paths in tree mode

### ISSUE THREAD

**Issue by bturner1273** [josdejong/jsoneditor#865]
I would like to be able to specify a path to a json object (in my json root object) and have JsonEditor disable editing of the object represented by said path. Is there some sort of readonly path option in tree mode?

**Comment by josdejong** [comment]
Yes, see option `onEditable` 😄

**Comment by bturner1273** [comment]
oh wow I didn't see that example muchas gracias!

**Comment by josdejong** [comment]
👍
