### ISSUE TITLE
Key names with single quotes are not being accepted

### ISSUE THREAD

**Issue by rajesh-esaver** [josdejong/jsoneditor#867]
I'm not able to parse the JSON in the editor just because my JSON keys are surrounded by **single quotes**. It would be good if we can pare the JSON which has keys with single quotes.
Ex:
```
{
  '21:47:8f:73:1d:85': {
    'rssi': -46,
    'mac': '21:47:8f:73:1d:85',
    'mac_name': ''
  },
  '33:92:a7:e3:1f:44': {
    'rssi': -38,
    'mac': '33:92:a7:e3:1f:44',
    'mac_name': ''
  }
}
```
The above JSON is not being accepted in the code editor(some other online editors are accepting them).

**Comment by josdejong** [comment]
If you paste your data example in the code editor, you can click the repair button (wrench) to turn your single-quoted JavaScript objects into JSON.

**Comment by rajesh-esaver** [comment]
yes thanks, didn't check it.

**Comment by josdejong** [comment]
:+1: 

I was thinking about showing a hint message when you load invalid JSON which can actually be repaired (not everything can be repaired).
