### ISSUE TITLE
Jsoneditor code mode requires worker-json.js from the absoute path not from the relative

### ISSUE THREAD

**Issue by smartameer** [josdejong/jsoneditor#87]
Hi,
I was using json-editor in "code" mode which is requiring worker-json.js
I have my scripts folder from where ace.min.js is loading, but it requires worker-json.js which is also in scripts directory, but dom error says that it's being requested from absolute url instead of scripts directory. May i know why this worker-json is required when https://github.com/josdejong/jsoneditor/blob/master/examples/03_switch_mode.html says no need of worker-json.js for code mode.

My Script block is

<pre>
        var classContainer = document.getElementById('puppetClassEditor');
        var classOptions = { modes: ['code', 'tree'],
            search: false
        };
        $scope.classEditor = new jsoneditor.JSONEditor(classContainer, classOptions);
        $scope.classEditor.container.style.height = '150px';

        var paramContainer = document.getElementById('puppetParametersEditor');
        var paramOptions = { modes: ['code', 'tree'],
            search: false
        };
        $scope.paramEditor = new jsoneditor.JSONEditor(paramContainer, paramOptions);
        $scope.paramEditor.container.style.height = '150px';
</pre>

I am using angularjs above this editor.

**Comment by andrewboni** [comment]
Anyone have any luck with this? Trying to solve https://github.com/josdejong/jsoneditor/issues/157 and this seems to be related. Thanks!

**Comment by josdejong** [comment]
@smartameer and @tomalec I've just refactored the JSONEditor to CommonJS modules and using [brace]() (see https://github.com/josdejong/jsoneditor/issues/157#issuecomment-76476581). This *could* resolve the problems when using the editor inside Polymer. Could you maybe give the version in the [develop branch](https://github.com/josdejong/jsoneditor/tree/develop) a try?

**Comment by epiphanydigital** [comment]
I'm having essentially the same issue when doing a gulp build from bower packages.  Since the build minifies all vendor code into a single vendor.js file the worker-json.js is included inline, but Ace still tries to load it as a file dynamically and 404s.  Anyone have any ideas on how to get around this?

**Comment by sidthekidder** [comment]
Still getting this error, in angular 5.

**Comment by josdejong** [comment]
How can I reproduce the issue?
