### ISSUE TITLE
Format and compact buttons do not support internationalization

### ISSUE THREAD

**Issue by Iamsuler** [josdejong/jsoneditor#873]
![image](https://user-images.githubusercontent.com/26576925/71446945-f9896c80-2763-11ea-87f0-d28fcbf9bc50.png)

**Comment by josdejong** [comment]
Thanks for reporting Suler, you're right. I'll try to pick it up soon, but any help is very welcome!

**Comment by josdejong** [comment]
I've created a fix for this (not yet published)

**Comment by josdejong** [comment]
This is fixed now in `v8.1.2`
