### ISSUE TITLE
Disable Array Attributes 

### ISSUE THREAD

**Issue by jigardarji318** [josdejong/jsoneditor#874]
How to disable array attributes using onEditable function

json: {
            'array': [1, 2, 3],
            'boolean': true,
            'null': null,
            'number': 123,
            'object': { 'a': 'b', 'c': 'd' },
            'string': 'Hello World'
        }

For this example I want to disable 'array' editing

**Comment by josdejong** [comment]
The option `onEditable` gives you full control over that.

**Comment by jigardarji318** [comment]
Sample JSON 
json: {
'array': [1, 2, 3],
'boolean': true,
'null': null,
'number': 123,
'object': { 'a': 'b', 'c': 'd' },
'string': 'Hello World'
}
onEditable: function (node) {

                switch (node.field) {
                    case 'array':
                        return false
                    default:
                        return true
                }
            }
}

Still, I am able to edit the array

**Comment by josdejong** [comment]
You have to return false too for the childs in the array, not only for the array itself. You could check whether the path starts with `array` for example and if so return false.

**Comment by jigardarji318** [comment]
case 'array':
                    return false
I am returning return false for 'array' node, but still, it's allowing me to edit the value inside the array.

**Comment by josdejong** [comment]
`onEditable` works on a very atomic level. To see this you can add some logging:

```js
const options = {
  onEditable: function (node) {
    console.log(node)
    // ...
  }
}
```

In your case, you've made the `array` property itself readonly, but you still return `true` (editable) for each of it's childs. You have to return `false` (readonly) too for all of the childs of the array (see my previous comment).

**Comment by jigardarji318** [comment]
Thanks 

Closing it.

**Comment by josdejong** [comment]
👍
