### ISSUE TITLE
Freeware or not

### ISSUE THREAD

**Issue by jigardarji318** [josdejong/jsoneditor#875]
Hello,

I have a concern regarding this whether it is free or not?

Can you please help me out?

**Comment by josdejong** [comment]
The JSONEditor is open source and licensed under the Apache License 2.0: https://github.com/josdejong/jsoneditor/blob/master/LICENSE, so you can just use it in commercial and non-commercial applications. Most important is to keep attribution in place. You can read the details in the license.

The web application https://jsoneditoronline.org is not open sourced, only the JSONEditor library.
