### ISSUE TITLE
mouse hover a node, event? How to?

### ISSUE THREAD

**Issue by hoogw** [josdejong/jsoneditor#876]
when user mouse over a node:
    1) trigger a event, I need to do something in this event call back.
    2) highlight this node

when user mouse leave that node:
     1) reverse highlight node.

How to do it?

**Comment by hoogw** [comment]
I know the answer:

must use latest version, v8.1.1 for onEvent to work.
I have middle last year 2018, v5.x not work. 


                   `options = {
                         modes:['tree', 'view', 'form', 'code', 'text'],
                         //"search": false, // default is true

                         onSelectionChange : onSelectionChange,
                         onEvent: onEvent
                        
                        
                        };`


then you need implement the event callback function somewhere else:

                           `function onSelectionChange(start, end) {
      
                console.log(' on selection change event   start, end :  ++++++++ ', start, end) 


          }
      
      
          function onEvent(node, event) {
      
            console.log(' on  event: node, event ---->', node, event) 


          }`

**Comment by josdejong** [comment]
:+1:
