### ISSUE TITLE
v8.1.1 search box css have bug ???

### ISSUE THREAD

**Issue by hoogw** [josdejong/jsoneditor#877]
![jsoneditor-bug-search](https://user-images.githubusercontent.com/419582/71740949-6b238380-2e12-11ea-8970-94ec7b95c755.JPG)
v8.1.1 search box have extra line, not align with menu bar. 

Possible a bug, can you take a look and fix?

**Comment by josdejong** [comment]
Hm. Do you have some CSS which accidentally changes the styling of the search box?

In the library examples I don't see this happen: https://unpkg.com/jsoneditor@8.1.1/examples/01_basic_usage.html

**Comment by hoogw** [comment]
Yes, I do use materialized css,
 [https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/css/materialize.min.css](https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/css/materialize.min.css)


[https://cdn.materialdesignicons.com/3.6.95/css/materialdesignicons.min.css](https://cdn.materialdesignicons.com/3.6.95/css/materialdesignicons.min.css)

But when I use mid last year 2018 v5.x, no such issue with materialized-css, only today, when I update to v8.1.1, css conflict happened.

**Comment by josdejong** [comment]
Ah, it's in combination with materialize. I can indeed reproduce your issue by simply opening [test/test_materialize.html](https://github.com/josdejong/jsoneditor/blob/develop/test/test_materialize.html) (haven't checked that for a long time). Should be doable to fix that.

**Comment by josdejong** [comment]
Fixed via #090d41f8d9cd42bc67acbd019e1257a1180e8f8f (not yet published)

**Comment by hoogw** [comment]
Great.

**Comment by josdejong** [comment]
This is fixed now in `v8.1.2`
