### ISSUE TITLE
[Feature request] API to get JSON-formatted JSON document

### ISSUE THREAD

**Issue by baebb** [josdejong/jsoneditor#886]
I am using JSON Editor Online to collaboratively work on JSON documents and need a way to programmatically consume that data. 

I would like to be able to get the JSON doc, in JSON format, via an API call. I have found `https://jsoneditoronline.herokuapp.com/v1/docs/{id}`, but this returns the data in a format that requires some cleaning. 

It would be super helpful if there was an endpoint I could use to get a JSON-formatted response of the document ID I supply. Perhaps by supplying an additional query param eg. `https://jsoneditoronline.herokuapp.com/v1/docs/{id}?json=true` ?

Thanks for building and hosting this

**Comment by josdejong** [comment]
Thanks baebb :)

There is an unofficial API call https://jsoneditoronline.herokuapp.com/v1/docs/{id}/data to do what you want. Please note that this is an unofficial API and should not be used in production.

**Comment by baebb** [comment]
Thanks a lot 🙏
