### ISSUE TITLE
[Question] Is there any way to change tree nodes names?

### ISSUE THREAD

**Issue by ecoecoe** [josdejong/jsoneditor#888]
Just a question - as in the title - is there a way to change the names of the nodes in the tree view dynamically? 
Like how we change root name, but with specific value taken from one or more tree values.

![Schermata 2020-01-23 alle 11 59 34](https://user-images.githubusercontent.com/20145163/72979201-215a0780-3dd8-11ea-9aca-e93cd9e69445.png)

**Comment by josdejong** [comment]
This name is picked from you JSON Schema, so I think you can change it there?

**Comment by ecoecoe** [comment]
Our JSON Schema call the number of the node: 0, 1, 2 etc.
![Schermata 2020-01-24 alle 10 31 44](https://user-images.githubusercontent.com/20145163/73058842-c63a1a80-3e94-11ea-8b27-21e6cf53543e.png)
We need to change it into:
![Schermata 2020-01-23 alle 11 59 34](https://user-images.githubusercontent.com/20145163/73059791-c1766600-3e96-11ea-94b4-b4f96be89c0a.png)

**Comment by josdejong** [comment]
Ah, I understand you. With JSON schema you can give your properties a title which is then displayed in JSONEditor, but I don't think you can give individual items in an array a different structure and title. Arrays are normally homogeneous, which if I understand you correctly is not the case with your data.

**Comment by ecoecoe** [comment]
Infact, the ROOT title is customizable, but not the Names in the JSON nodes.
It could be a future feature?
I imagine that the node names could be the ID or ID + Some JSON value like the image example.

**Comment by josdejong** [comment]
I'm a bit hesitant to create a feature to basically allow rename array indexes, it feels like quite an edge case to me.

Would it be a solution for you to use `onNodeName`? It doesn't allow rewriting the array index, but you can use it to replace `{13}` with say `{Panel (Name of Panel)}`.

**Comment by ecoecoe** [comment]
Yes, it could be a solution.
Naturally if we are able to make it using also some variable or JSON value. In this example could be <code>{$component ($id)}</code> so the result could be <code>1 {Panel (Name of Panel)}</code>.
This will semplify the structure reading for JSON editors.

**Comment by josdejong** [comment]
Ok cool. Let's close this issue if it works out.
