### ISSUE TITLE
e.canUndo is not a function

### ISSUE THREAD

**Issue by jvallar** [josdejong/jsoneditor#892]
Uncaught TypeError: e.canUndo is not a function
    at v.g._updateHistoryButtons (jsoneditor-minimalist.js:8204)

**Comment by josdejong** [comment]
Thanks for reporting Jameson, this was a regression since`v8.5.0` published yesterday, it was occurring when custom loading an old version of Ace Editor it seems. Fixed now in `v8.5.3`.
