### ISSUE TITLE
not recognizing CORS when trying to write 

### ISSUE THREAD

**Issue by SavedByZero** [josdejong/jsoneditor#894]
My cors file (temporarily set to this briefly, just for testing): 
```
Header add Access-Control-Allow-Origin: "*"
Header add Access-Control-Allow-Methods: "*"
Header add Access-Control-Allow-Headers: "*"
```
(I have also tried using https://jsoneditoronline.org/ instead of *)

I can read the file, but when I write, I automatically get that error telling me it couldn't write and that I might not have CORS enabled.   The url I'm trying to save to is http://www.playmatics.xyz/jsons/modules.json, and I have my .htaccess file in http://www.playmatics.xyz/jsons

**Comment by josdejong** [comment]
These headers should indeed be enough. 

If you try to load from an `https://` website, your data url must also be `https://` though, that's not the case. I tried to load the file http://jsoneditoronline.org (Without SSL!) with a simple:

```js
(await fetch('http://www.playmatics.xyz/jsons/modules.json')).json()
```

in the console but that also fails. I guess you'll have to do some more debugging there to figure out why your backend is not allowing the request, I'm not sure how I can help here.

**Comment by SavedByZero** [comment]
Drat. Maybe it’s dreamhost. 
Okay, if I install and use this locally on my server can I read and write to Json files on my server? I need to let my designers modify game data by editing Jsons with your tree interface.  Do any of your examples show how to use this url saving method when we host your code? I noticed your save and load html example only uploads and saves files on my local machine.

**Comment by josdejong** [comment]
You can of course create your own webserver and your own web application with JSONEditor, and load your documents from your server using REST calls. This is out of scope of JSONEditor itself though, but you can find a lot of documentation on the internet on how to do that (there is also plenty of ways to do it). There are also plenty services that can setup a database+server+client all in one go, like Firebase.

**Comment by SavedByZero** [comment]
Let me see if I understand this -- only part of the functionality of jsoneditoronline is implementable locally by developers on their own servers?  The load/save from URL options that we see online aren't offered as part of the API?

**Comment by josdejong** [comment]
Yes that is right. The open source JSONEditor library contains just the editor component, without anything related to loading/saving from url or disk offered by the online web application.
