### ISSUE TITLE
Cannot read property '$ref' of undefined TypeError: Cannot read property '$ref' of undefined

### ISSUE THREAD

**Issue by alhimik1986** [josdejong/jsoneditor#896]
Hi,
I tried to use jsoneditor using webpack and typescript. And I got the error:

```js
'use strict';
import { JSONEditor } from '@json-editor/json-editor';

export class Config
{
    constructor(configData) {
        const editorElem = document.getElementById('editor');
        const options = {theme: 'bootstrap4'};
        console.log(JSONEditor.defaults);     // {themes: {…}, templates: {…}, iconlibs: {…}, editors: {…}, languages: {…}, …}
        new JSONEditor(editorElem, options);  // Cannot read property '$ref' of undefined TypeError: Cannot read property '$ref' of undefined
    }
}
```

Please, suggest me if I made something wrong. I'm sure this is a bug because JSONEditor.defaults have some value, but creating instance causes an error. I was looking for this problem in the Google and the previous issues, but did not find working solutions.

**Comment by josdejong** [comment]
Is your question about [`@json-editor/json-editor`](https://github.com/json-editor/json-editor) or about this library, [`jsoneditor`](https://github.com/josdejong/jsoneditor)?

**Comment by alhimik1986** [comment]
In my case it's the @json-editor/json-editor, but I think this is a global problem:
```html
<!DOCTYPE html>
<html>
<head>
    <script src="https://cdn.jsdelivr.net/npm/@json-editor/json-editor@latest/dist/jsoneditor.min.js"></script>
    <script type="text/javascript">
        window.onload = function() {
            const editorElem = document.getElementById('editor');
            new JSONEditor(editorElem);  // jsoneditor.min.js:17 Uncaught TypeError: Cannot read property '$ref' of undefined
        };
    </script>
</head>
<body>
    <div id="editor"></div>
</body>
</html>
```

**Comment by alhimik1986** [comment]
Oh no. It's just about the @json-editor/json-editor.
The jsoneditor is working well.

**Comment by alhimik1986** [comment]
I found my problem. It's because I forgot to add the schema:
```html
<!DOCTYPE html>
<html>
<head>
    <script src="https://cdn.jsdelivr.net/npm/@json-editor/json-editor@latest/dist/jsoneditor.min.js"></script>
    <script type="text/javascript">
        window.onload = function() {
            const editorElem = document.getElementById('editor');
            var editor = new JSONEditor(editorElem, {
                schema: {
                    type: "string",
                    title: "Car"
                }
            });
        };
    </script>
</head>
<body>
    <div id="editor"></div>
</body>
</html>
```
This is some kind of unobvious mistake. Maybe it's worth adding protection from the fool here?

**Comment by josdejong** [comment]
Well, can you then report your suggestion at the project [`@json-editor/json-editor`](https://github.com/json-editor/json-editor) itself? I'm not involved with the project you're talking about and it's not related to the project where you've posted your question 😄 .

**Comment by maxrks** [comment]
> I found my problem. It's because I forgot to add the schema:
> 
> ```
> <!DOCTYPE html>
> <html>
> <head>
>     <script src="https://cdn.jsdelivr.net/npm/@json-editor/json-editor@latest/dist/jsoneditor.min.js"></script>
>     <script type="text/javascript">
>         window.onload = function() {
>             const editorElem = document.getElementById('editor');
>             var editor = new JSONEditor(editorElem, {
>                 schema: {
>                     type: "string",
>                     title: "Car"
>                 }
>             });
>         };
>     </script>
> </head>
> <body>
>     <div id="editor"></div>
> </body>
> </html>
> ```
> 
> This is some kind of unobvious mistake. Maybe it's worth adding protection from the fool here?


Intergrated to Angular Project.
firstly, make `npm install @json-editor/json-editor` and add `scriptjs` to app.component.html.
then

`import { JSONEditor } from '@json-editor/json-editor'`

Angular HTML:
```
   <div id="editor_holder">
    </div>
```
TyperScript:

```
 ngAfterViewInit() {
var element = document.getElementById('editor_holder');
    if (element) {
      var editor = new JSONEditor(element, {
        theme: 'html',
        {
                schema: {
                    type: "string",
                    title: "Car"
                }
         });
    }
}
```
this could be working.

**Comment by josdejong** [comment]
@maxrks I think you're posting in the wrong repository, this is not the repository of `@json-editor/json-editor`.

**Comment by maxrks** [comment]
@josdejong oh... sorry, these wonderful repos, your `@josdejong/jsoneditor`,  `@jdorn/json-editor` and `@json-editor/json-editor`   seem the same in `J's json editor`.  I came here for I got the same exception on the title. :)
