### ISSUE TITLE
please make the redirect from 10s to 1 or 0

### ISSUE THREAD

**Issue by liesislukas** [josdejong/jsoneditor#897]
please make the redirect from 10s to 1 or 0
there is no value of current landing page

![image](https://user-images.githubusercontent.com/2733862/74162062-b5c1c800-4c28-11ea-8e9d-6050ce361d47.png)

**Comment by josdejong** [comment]
It would be nice it we would fix this www redirect for real. The reason why this timeout was introduced is described in this discussion: https://github.com/josdejong/jsoneditor/issues/529#issuecomment-390592721

**Comment by liesislukas** [comment]
I read the #529 yet not sure why it can not redirect with just one line of javascript. 

Whatever is making the redirect now, why 10s? why not 10ms? or 0s at all. Just do the redirect and that's it. 

Why someone who wants to manage JSON need to read the message about www redirect stuff? there is no value in it, just do the redirect, never use www version and that's it. A ton of pages has such redirect, yet none shows a message like this.

**Comment by josdejong** [comment]
:joy: seriously, why are you using `www` in the url?

As explained in #529, the proper solution is to do the redirect in the backend. This is not trivial unfortunately.

Redirecting by loading an index.html file and then executing some JavaScript feels dirty. To try it out I've added the following line of JavaScript: 

```html
<script>
  window.location.href = 'https://jsoneditoronline.org/' + window.location.search + window.location.hash
</script>
```
I've left the html redirect there as fallback in case the JavaScript redirect is blocked by the browser for whatever reason:

```html
<meta http-equiv="refresh" content="10; url=https://jsoneditoronline.org" />
```

I'm not sure if there are other side effect I'm overlooking now, I'm not really happy with it but it probably works ok, lets see.

**Comment by liesislukas** [comment]
cause google gave that www and chrome is constantly suggesting that www. Finally, it's fixed, so end of story.
