### ISSUE TITLE
Help required. Dynamically update schema

### ISSUE THREAD

**Issue by timota** [josdejong/jsoneditor#901]
Hi guys, 
probably not an issue but a question, anyway.

Lets say we have such properties
```
          "orcherstration_env": {
            $ref": "#/definitions/_select",
            "title": "Environment",
              "propertyOrder": 40,
              "enum": [
                "first",
                "second"
              ]
          },
         "orcherstration_cloud": {
            "$ref": "#/definitions/_select",
            "title": "Cloud",
            "propertyOrder": 20,
            "enum": [
              "first",
              "second"
            ]
          }
```
Also we have set eventlistener on `orcherstration_env`, like

```
editor.watch('root.orcherstration_env', function() {
   var data = fetch_some_data();
}) 
```

How `orcherstration_cloud` `enum` can be updated dynamically ? 

Thanks in advance.

**Comment by timota** [comment]
Tried this `editor.setSchema(schema)` but it complains 

```
Uncaught TypeError: editor.setSchema is not a function
```

**Comment by josdejong** [comment]
You can indeed set a new or updated schema using the `setSchema` method. I'm not sure why this method is not defined on your `editor`. Is it actually a JSONEditor instance? JSONEditor does not have a method `.watch` so maybe `editor` something different?

see docs: https://github.com/josdejong/jsoneditor/blob/develop/docs/api.md#jsoneditorsetschemaschema-schemarefs

**Comment by timota** [comment]
it works, i did mistake when defined editor in first place. Thanks for help

**Comment by josdejong** [comment]
Good to hear you've managed to fix it 👍
