### ISSUE TITLE
programmatically set content

### ISSUE THREAD

**Issue by chr1st0scli** [josdejong/jsoneditor#902]
Hi.
I am referring to the online editor application.

In the old version I could programmatically set the editor's content by simply calling the following:
app.setData('...');

In the new version there is no app object. Please advise me on how to achieve the same effect in the new version.

Thank you.

**Comment by chr1st0scli** [comment]
I am referring to the online editor application, in case this wasn't clear.

**Comment by josdejong** [comment]
Ah, that's interesting. I can expose the left and right panel editors that if it helps you. Just curious: how and why did you use `app.setData('...')`? Maybe the application is missing some feature that would prevent you from needing `app.setData('...')` in the first place?

**Comment by chr1st0scli** [comment]
Yes please. 

The reason is that in my software department, json editor online is part of our everyday life. So, I am building an automation tool and part of the automation is opening the online editor in a desktop application window and feeding it with our data. I noticed that app.setData used to satisfy this requirement, it used to populate both the left and right panes.

**Comment by josdejong** [comment]
@chinesedfan I've now exposed the two editors in the left and right panel under `window.jsoneditors.LEFT_PANEL` and `window.jsoneditors.RIGHT_PANEL`. It exposes the `JSONEditor` which has methods like `.get()`, `.set()`, `.update()`, `.setText()`, etc. (see API docs of this library.
