### ISSUE TITLE
Can we able to push a word to the json by button?

### ISSUE THREAD

**Issue by Chinna2405** [josdejong/jsoneditor#903]
Hi,
On clicking a button can i able to push a text inside the json editor where the my cursor is lastly positioned.
Thanks in advance.

**Comment by josdejong** [comment]
Hi, I'm not sure what you mean. Are you talking about the `tree` mode or `code` mode? And with "push", do you mean paste something from the clipboard or so?

**Comment by Chinna2405** [comment]
Hi,
Sorry, for the undetailed question.I want to know when the editor is in 'code' mode I can able to paste a json and able to format and compact the json which i have pasted. When I am going to click a button, a text as to be inserted in the jsoneditor cursor position.So, how can I achieve the above mentioned scenario.

Thanks josdejong.

**Comment by josdejong** [comment]
With `JSONEditor.getMode` you can get the current mode to check whether it's `'code'`, and with `JSONEditor.onModeChange` you can listen for changes.

The code mode is running [Ace editor](https://ace.c9.io/), it is exposed via the property `.aceEditor`. I haven't tried out but Ace Editor has options to get the current text selection and replace a certain selection. That should allow you to do what you want I think.
