### ISSUE TITLE
Improve "Repair" to support objects coming from Python

### ISSUE THREAD

**Issue by josdejong** [josdejong/jsoneditor#906]
In https://github.com/josdejong/jsoneditor/issues/891#issuecomment-586190985, @ari-codes suggests an improvement to copy objects coming from Python:

> I can see ' to " can be solved clicking repair button but what about "True","False",None?
As I use python i need to replace manually :(

@ari-codes can you give an example of a typical Python object that you would like to be able to be repaired into valid JSON?

**Comment by ari-codes** [comment]
In python mostly these three needs extra effort.
   ` {
      "age": None,
      "is_verified": True,
      "is_active": False
    }`

**Comment by josdejong** [comment]
Implemented via dcc66d5d8153199fe2d3d3a02744d0c71f022a3e (not yet published)

**Comment by josdejong** [comment]
This new feature is now available in the web application too (v5.1.0, see "About" information top right)
