### ISSUE TITLE
Older Version than this version was more beautiful and great. 

### ISSUE THREAD

**Issue by syedtaha-hyder** [josdejong/jsoneditor#907]

**Comment by josdejong** [comment]
Thanks for your feedback Seyd. I understand you like the old version of the web application https://jsoneditoronline.org better.

Can you explain what you're missing in the new version? Is it just that it looks different, or are you missing functionality?

**Comment by amirasyraf** [comment]
@josdejong I think the biggest flaw with the new one is it doesn't automatically save/persist the data in the browser. Not sure if this is intended or bug.

**Comment by josdejong** [comment]
Thanks for your feedback @amirasyraf. The application does automatically _save_ all your files locally, but it does not _load_ it automatically. You can find all your documents under "Open", "Open recent file". 

You're not the first being confused about it. It it may be possible to simply opens your last file(s) like the old version did, let me think this through.

**Comment by amirasyraf** [comment]
Ah I see, just checked, and they're all there. 

I believe it's definitely better to just open the last available user input automatically, just like how Sublime Text, VSCode and the previous version of this app does.

**Comment by josdejong** [comment]
@amirasyraf the latest version of the application (`v5.2.0`) now loads your last opened documents. Can you give it a try?

**Comment by amirasyraf** [comment]
That's awesome @josdejong!  Works just like it used to. I've tested on both Chrome and Firefox.

**Comment by josdejong** [comment]
Good to hear :+1: .

I will close this issue now, @syedtaha-hyder please re-open if you have more or other feedback.
