### ISSUE TITLE
how can I validate the value of the jsoneditor

### ISSUE THREAD

**Issue by paulovich10** [josdejong/jsoneditor#911]
HI! Before  ang-jsoneditor I had a textarea inside a mat-formfiled with a textare and its matInput. Now with ang-jaosn editor, I have no way to validate the content of this "input", as I guess the tag json-editor is not recognized in angular as an input....

This is what I had before in my htnl:

```
 <form fxLayout="column" [formGroup]="configForm">
  <div fxFlex="1 0 auto" fxLayout="column">
 <mat-form-field appearance="outline" fxFlex="100">
 <mat-error>
 A valid JSON object is required.
 </mat-error>
</mat-form-field>
 </div>
 </form>
```

with the validator in .ts using ValidatorFn from angular

```
private isValidJSON: ValidatorFn = (control: AbstractControl): ValidationErrors | null => {
    if (!control.parent || !control) {
      return null;
    }

    const appConfig = control.parent.get("appConfig").value;
    console.log('appConfig', appConfig)
    try {
      JSON.parse(appConfig.toString());
      return null;
    } catch (error) {
      return { "jsonInvalid": true };
    }
  }

```

Now I have this in my html but even if I introduce the matInput, it doesn't work.

```
 <form fxLayout="column" [formGroup]="configForm">
    <div fxFlex="1 0 auto" fxLayout="column">
<p>JSON File</p>
      <json-editor [options]="editorOptions" formControlName="appConfig">
      </json-editor>
 </div>
  </form>
```
How can I reproduce this behaviour? I mean, How can I validate that the object I'm trying to send is valid? There's no Schema, you can send the content you want as long as it as a valid object body.The goal I want to achieve is to disable the button send  as loong as all the {}, "", etc is well introduced.

Thank you for your help.

**Comment by josdejong** [comment]
I guess you're using an Angular wrapper around the JSONEditor? If so I guess you can best ask the author of the wrapper.

**Comment by nagad814** [comment]
How to implement the same in react? Please

**Comment by josdejong** [comment]
> How to implement the same in react? Please

What exactly?
