### ISSUE TITLE
Separator is not fully adjustable when selecting/editing deep nodes

### ISSUE THREAD

**Issue by yotamboaz** [josdejong/jsoneditor#916]
In my day to day work, I'm editing large json files which are not only long - but also very deep/wide.
This is just a simple example to demonstrate the issue:
![separator](https://user-images.githubusercontent.com/44447624/75370404-b071a800-58cd-11ea-9162-7c4bf31e9ade.gif)

**Comment by josdejong** [comment]
Thanks for reporting, I can reproduce your issue. Will fix it within a few days.

**Comment by josdejong** [comment]
I think it should be fixed now, can you give it a try Yotam? (About information should show `v5.2.4`)

**Comment by josdejong** [comment]
Hm I see there is one more side effect that I need to fix in this regard, the panel changes width when you select a deeply nested path (though you can drag the splitter again)

**Comment by yotamboaz** [comment]
Thanks for the quick response and fix!
Now it does let me adjust the separator freely, which is great.
However it can still jump aside when selecting a deep node, and if it's too deep - it jumps out of the screen (to the right).

**Comment by josdejong** [comment]
ah, two messages at the same time :joy: 

will look into it soon...

**Comment by yotamboaz** [comment]
haha no problem of course. Anyway the option to move it freely is already a big relief.

**Comment by yotamboaz** [comment]
Maybe I got it wrong, sorry, now I can't make it jump out of the screen again, as now the gray "nodes path" begin with "..." when it gets longer and therefore doesn't get too long.
Perhaps it was fixed as part of your first fix.

**Comment by josdejong** [comment]
I could reproduce it still on a smaller screen. It should be fixed now in `v5.2.5`.

**Comment by yotamboaz** [comment]
It works great now - thank you!
