### ISSUE TITLE
Error: Local document with id 'hodoge' not found

### ISSUE THREAD

**Issue by DanielBenniah** [josdejong/jsoneditor#918]
I tried loading jsoneditoronline.org. It automatically redirects to https://jsoneditoronline.org/#left=local.hodoge with the error message Error: Local document with id 'hodoge' not found.

The issue is in Google Chrome. I have already tried clearing the browser cookies and cache. It's working fine in other browsers (Safari).

**Comment by josdejong** [comment]
By default, JSONEditor opens the document you had opened last time. If this document is deleted in the mean time for some reason, you will see this error. You can simply click "New" to open a new document and the issue error should be gone then.

**Comment by josdejong** [comment]
I think it would be nice to simply open an empty document instead of showing this error when opening the web application, I will look into that.

**Comment by DanielBenniah** [comment]
Got it! It's working now. Strange part is, I had never saved a document with the name 'hodoge'.

Also, please let it open the document that was opened the last time, me and my colleagues find that very useful.

**Comment by josdejong** [comment]
Good to hear it's working now. Reopening the document from last time will definitely stay in there, I'm just trying to optimize that a bit more to prevent any confusion like you had :)

As soon as you type something in the editor, it will save your work locally in an in-browser database. It will give the document a unique id (like "hodoge" or "welida") and a name like "New document 5" (which you can change). You can see all documents you ever made via menu "Open", "Open recent file".

**Comment by josdejong** [comment]
I've improved the error message when loading a document failed, it will now show something like:

![image](https://user-images.githubusercontent.com/568626/76703219-5a27a600-66d0-11ea-8295-be4889345365.png)
