### ISSUE TITLE
sortObjectKeys emits onChange events

### ISSUE THREAD

**Issue by oren-l** [josdejong/jsoneditor#921]
According to [API docs](https://github.com/josdejong/jsoneditor/blob/master/docs/api.md#configuration-options) onChange, onChangeJSON and onChangeText are triggered only by user interactions and not by any programmatic changes.

Expected: 
Enabling sortObjectKeys should not cause any onChange to be triggered

Actual:
Enabling sortObjectKeys causes many onChange calls (I guess one per order-change)

jsoneditor version: 8.6.1

Maybe this is related to #583

**Comment by josdejong** [comment]
Thanks for reporting Oren, the onChange should indeed not be triggered by enabling `sortObjectKeys`, this is a bug.

**Comment by josdejong** [comment]
This is fixed now in `v8.6.4`.
