### ISSUE TITLE
root node name not respected in navbar

### ISSUE THREAD

**Issue by herrfrei** [josdejong/jsoneditor#928]
If I change the root name of the JSON object via `options['name'] = 'MyRoot'` or `editor.setName('MyRoot')` it is not shown in the navigation bar ('object' is always printed)

I changed one line in treemode.js to also use the name but I'm unsure if this is correct. In the embedded function of `treemode._updateTreePath = function (pathNodes)`:

```
function getName (node) {
    return node.parent
      ? ((node.parent.type === 'array') ? node.index : node.field)
      : node.type
  }
```

I replaced `node.type` with `node.field` in the last line:
```
function getName (node) {
    return node.parent
      ? ((node.parent.type === 'array') ? node.index : node.field)
      : node.field
  }
```

Works for me. If it is okay, please correct the file!

**Comment by josdejong** [comment]
Thanks for reporting this issue and an idea for a fix Herr Frei, I've fixed this in 854a407 (will publish the fix within a few days I expect).
