### ISSUE TITLE
Characters are not encoded when transfering model into JSON

### ISSUE THREAD

**Issue by Andree643** [josdejong/jsoneditor#93]
When I create model with some text containing accents and transfer it to JSON, the accents are not encoded.
![json-encode](https://f.cloud.github.com/assets/6212595/2510214/1bef5b7a-b403-11e3-8f68-3e15be26575d.PNG)
Expected result:
![json-proper](https://f.cloud.github.com/assets/6212595/2510221/32c4cc2c-b403-11e3-9e74-9ce129d269b9.PNG)

**Comment by josdejong** [comment]
This is fixed now in the `develop` branch.
