### ISSUE TITLE
Values from left side not copied to right side

### ISSUE THREAD

**Issue by spirostz** [josdejong/jsoneditor#932]
![problem](https://user-images.githubusercontent.com/11974067/76975625-7da25900-693b-11ea-8cc9-660f1dcfb497.jpg)

**Comment by josdejong** [comment]
Thanks for reporting Tzoras, this is a regression introduced with the latest version a couple of hours ago. Will fix it asap.

**Comment by josdejong** [comment]
This is fixed now in `jsoneditor@8.6.3` and the web application `v5.3.4`. Sorry for the inconvenience, I thought I had tested it thoroughly but I didn't test good enough.
