### ISSUE TITLE
option.language didn't work when option.mode is 'text'

### ISSUE THREAD

**Issue by Zex158** [josdejong/jsoneditor#946]
It's not work to set option to {language: 'en', mode: 'text'} , The language displayed is still the language set by the browser. How can I change the language in mode 'text'?

**Comment by josdejong** [comment]
Thanks for reporting this bug @Zex158 , I made a fix and hope to publish the fix today.

**Comment by josdejong** [comment]
This is fixed now in `v8.6.4`.
