### ISSUE TITLE
Save to spezific location

### ISSUE THREAD

**Issue by astridx** [josdejong/jsoneditor#953]
I'm actually stuck with a problem.
I would like to make it possible for users to be able to  change and save a specific json file.
I have managed to open the file automatically. This is my code.

`		<script>
			// create the editor
			const options = {
				modes: ['text']
			}
			const editor = new JSONEditor(document.getElementById('jsoneditor'), options);

			loadVar('config.json', function (response) {
				window.JSONconfig = JSON.parse(response);

			});

			setTimeout(function () {
				editor.set(window.JSONconfig);

				// Save a JSON document
				document.getElementById('saveDocument').onclick = function () {
					// Save Dialog
					let fname = window.prompt("Save as...")

					// Check json extension in file name
					if (fname.indexOf(".") === -1) {
						fname = fname + ".json"
					} else {
						if (fname.split('.').pop().toLowerCase() === "json") {
							// Nothing to do
						} else {
							fname = fname.split('.')[0] + ".json"
						}
					}
					const blob = new Blob([editor.getText()], {type: 'application/json;charset=utf-8'})
					saveAs(blob, fname)
				}
			}, 1000);

			function loadVar(file, callback) {
				var xobj = new XMLHttpRequest();
				xobj.overrideMimeType("application/json");
				xobj.open('GET', file, true);
				xobj.onreadystatechange = function () {
					if (xobj.readyState == 4 && xobj.status == "200") {
						callback(xobj.responseText);
					}
				};
				xobj.send(null);
			}
		</script>`

It would be great if exactly this file were saved / changed by clicking on Save.

I can not write to file using XMLHttpRequest. Therefore, the one who changes the file must map the location via network and the file system. Then he can save the file. It would be nice if this would happen automatically when saving.

Is there another possibility? Unfortunately I have no server-side programming language available.

**Comment by josdejong** [comment]
This is a bit off-topic, it's not JSONEditor specific.

Browser are not allowed to write files on arbitrary places of peoples computer, that would be a huge security issue. I don't think it's possible. What comes closest is the obsolete (!) [FileSystemFileEntry.createWriter](https://developer.mozilla.org/en-US/docs/Web/API/FileSystemFileEntry/createWriter) API.

If you want to have control and access to files on disk, you can look into creating a desktop application, for example using https://www.electronjs.org/

**Comment by astridx** [comment]
You're right. That is off-topic. Therefore I thank you all the more for your answer.
i understand the security problem and plan to use it in a local environment. I will look at your suggestions.
