### ISSUE TITLE
Keys are translated before language is set

### ISSUE THREAD

**Issue by PeterBurner** [josdejong/jsoneditor#964]
I added a custom german translation in accordance with the docs.  
Unfortunately for some keys the language set in the `language` property is not respected. The english translations are still beeing displayed.  
The problem is this line: [src/js/Node.js#L4604](https://github.com/josdejong/jsoneditor/blob/develop/src/js/Node.js#L4604)  
The keys are translated before the language from the options is set.  
Could you please fix this?  

EDIT: not sure if there are even more keys that aren't translated correctly 🤔

**Comment by josdejong** [comment]
Ouch, that's a good one. Thanks for reporting Peter. I've gone through all translations to check whether it wasn't loaded statically like the titles of node types. Fixed via # 894af51.

**Comment by josdejong** [comment]
This has been fixed now in `v8.6.5`

**Comment by PeterBurner** [comment]
thank you very much  
great work you do here!
