### ISSUE TITLE
Is it possible to hide draggable menu in tree mode?

### ISSUE THREAD

**Issue by eeyshen** [josdejong/jsoneditor#965]
Is it possible to hide draggable menu in tree mode? Thanks.

**Comment by josdejong** [comment]
I think with some CSS you can hide the context menu button. Is that what you mean? Or are you looking for something like the "form" mode?

**Comment by eeyshen** [comment]
CSS helps, while there will be blank space on the left of context menu button.

**Comment by josdejong** [comment]
The table column has a width of `"24px"`

![image](https://user-images.githubusercontent.com/568626/79683330-9008fe80-8229-11ea-9ec5-32a4c4fb84ee.png)

If you can change that to `0` the column is not visible anymore. I'm not sure if you can do that with CSS though it can be done with JavaScript.

**Comment by eeyshen** [comment]
Thanks.
