### ISSUE TITLE
autocompletion for code mode

### ISSUE THREAD

**Issue by meirotstein** [josdejong/jsoneditor#968]
Hey,

On code mode, when a schema is given, it would be nice to have an autocompletion option like in other code editors.
something like this:
https://imgur.com/a/gZMxYTO
 
ACE already supports the capability for autocomplete and there is some work on the JSON context.

@josdejong - WDYT?

**Comment by josdejong** [comment]
Hi Meir, good to hear from you, it has been a while :)

That is an awesome idea! This never crossed my mind but it makes a _lot_ of sense.

**Comment by meirotstein** [comment]
Thanks @josdejong !
I will start working on it in my spare time - I feel that this would bring a great benefit for the users of my tool (which is based on your awesome jsoneditor)

**Comment by davidhouweling** [comment]
Hello, thought to follow up on this issue... any progress?

**Comment by josdejong** [comment]
Ah, no not yet as far as I know

**Comment by josdejong** [comment]
Thanks for the update Meir 👍 . Take it easy

**Comment by mr-bjerre** [comment]
I'm at the hunt atm. for a JSON editor that gives you autocompletion based on JSON Schema, so I'll be watching!

**Comment by valasatava** [comment]
Hi, this feature is exactly what I'm looking for! Any updates?

**Comment by meirotstein** [comment]
@valasatava I was just returned to it recently and it is currently WIP, trying to do it in between the other many tasks I have. stay tuned :)

**Comment by josdejong** [comment]
Auto completion is available now in v9.9.0. There are still improvements possible (see explanation about "Limitation" in https://github.com/josdejong/jsoneditor/pull/1435#issue-1210223570), but let's open a separate issue to discuss that if there is need for it.

**Comment by valasatava** [comment]
> Auto completion is available now in v9.9.0. There are still improvements possible (see explanation about "Limitation" in [#1435 (comment)](https://github.com/josdejong/jsoneditor/pull/1435#issue-1210223570)), but let's open a separate issue to discuss that if there is need for it.

Thank you! It's a really nice feature to have! One observation: the suggestions do not seem to be provided for the root level properties. Is this an expected behavior?

**Comment by meirotstein** [comment]
@valasatava it should work also for the root level.
can you provide a recent example? A schema and a json

**Comment by valasatava** [comment]
> @valasatava it should work also for the root level. can you provide a recent example? A schema and a json

This can be used as an example: https://github.com/josdejong/jsoneditor/blob/master/examples/26_autocomplete_by_schema.html 

With only one modification: I get the jsoneditor lib from the cdn
```
    <link href="https://cdnjs.cloudflare.com/ajax/libs/jsoneditor/9.9.0/jsoneditor.css" rel="stylesheet" type="text/css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jsoneditor/9.9.0/jsoneditor.js"></script>
```

I get the suggestions from the second level of schema properties:
![image](https://user-images.githubusercontent.com/16787092/174673469-e5b05328-2909-4219-989c-5b7726149411.png)

but not for the root:
![image](https://user-images.githubusercontent.com/16787092/174673618-01553436-a8b7-430e-a864-299cf99a5ca8.png)

**Comment by valasatava** [comment]
@meirotstein were you able to reproduce the same behavior?

**Comment by meirotstein** [comment]
@valasatava Im sorry, but I havnt got the chance to look at it yet, will try to do it soon.
