### ISSUE TITLE
Goes back to the beginning of the line when you write

### ISSUE THREAD

**Issue by Didjynn** [josdejong/jsoneditor#978]
Hello,

I've got this bug for some days only (but it might be older) and I don't know what triggers it.

It happens in tree mode and switching to code and going back to the tree mode fixes it. So everythime I write a letter, the place to write goes back to the beginning of the text box so it make me write backwards. This is quite annoying.
So for example "text" becomes "txet".

I hope it will help,

Cheers

**Comment by josdejong** [comment]
Thanks for reporting. How can I reproduce your issue? Is it happening on https://jsoneditoronline.org, or is it in an application where you use the JSONEditor library?

**Comment by Didjynn** [comment]
It is happening on  https://jsoneditoronline.org

I don't know 100% how to do it, I took 10 minutes to try I reproduced it many times but I can't figure out the how exactly.

I have objects inside object, inside objects. In tree mode I change a key name (I just add some numbers at the end) and then click in another key name to do the same. Try it multiple times, maybe it will happen... When I delete the last letters at the end the bar seems to go back to the beginning sometimes. Might be linked but I'm not sure. It happens quite often but I do not find how exactly. sometimes I have it sometimes not but I never do anything complicated.

Sorry I can't help more so far

**Comment by josdejong** [comment]
Thanks for taking the the time to try reproduce it. Now you say it, it rings a bell. When I was in early stage of developing the new web application, I had something like you describe a few times. After that it didn't occur anymore so I thought it had resolved itself. 

A first wild guess: it may be related to the editor saving the contents in the browser's local storage after a delay of 1 second after making a change. If you type another character right at the moment the editor saves it may possibly cause this issue. I have to see if I can reproduce this and find the cause.

**Comment by Didjynn** [comment]
Well I don't know, the "writing cursor" goes back to the beginning of the line after each string I add (when it begins to happen of course, I can work 10 minutes without having it and then trigger it 3 times in the same minute). However if I'm fast enough I can write 2 strings before it does. I'm not a slow typer if there was this 1 second delay I should have the time to write some more. 

You might be right, I can't say for sure

I have the feeling it happens when I type a string for the first time after clicking on a key where there was already some strings inside and add a new string. I think I got it once in the value of a key string but I mostly copy paste in there and it doesn't seem to trigger the bug.

**Comment by josdejong** [comment]
Thanks for the detailed info! I have some clues to start digging into this issue. Will keep you posted.

**Comment by josdejong** [comment]
I've tried reproducing this issue in many ways, and I found one issue, which is reproducible: 

https://jsbin.com/locibec/edit?html,output

**Comment by josdejong** [comment]
This issue should be fixed now in `jsoneditor@8.6.7`, and https://jsoneditoronline.org `v5.5.3`. Please let me know if you still come across such an issue.

**Comment by Didjynn** [comment]
that's nice thanks, I'll let you know if I have any trouble

Cheers
