### ISSUE TITLE
Title and description in Schema definitions

### ISSUE THREAD

**Issue by vitornesello** [josdejong/jsoneditor#981]
Hello,

I need the functionality of showing the title/description on hover, but it seems it is only working when the `title`/`description` properties are defined directly on the schema. If they are defined in one of the definitions of the schema, it will not work anymore.

If you can give me some guidance, I would be glad to contribute

Related issue : https://github.com/josdejong/jsoneditor/issues/523

Note :  The schema validation works fine in both cases

Examples :

* This works :
```json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "properties": {
        "foo": {
            "properties": {
                "a": {
                    "type": "number",
                    "description" : "A number"
                }
            },
            "required": [
                "a"
            ],
            "type": "object"
        }
    },
    "required": [
        "foo"
    ],
    "type": "object"
}
```

* This does not work :
```json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "definitions": {
        "Foo": {
            "properties": {
                "a": {
                    "type": "number",
                    "description" : "A number"
                }
            },
            "required": [
                "a"
            ],
            "type": "object"
        }
    },
    "properties": {
        "foo": {
            "$ref": "#/definitions/Foo"
        }
    },
    "required": [
        "foo"
    ],
    "type": "object"
}
```

**Comment by josdejong** [comment]
Thanks for reporting Vitor. Looks indeed like references are not resolved.

The title is created in the function `makeFieldTooltip ` in the file `src/js/util.js`:

https://github.com/josdejong/jsoneditor/blob/develop/src/js/util.js#L1234-L1279

and there are tests for it in `test/util.test.js`:

https://github.com/josdejong/jsoneditor/blob/develop/test/util.test.js#L300

Any help in fixing this would be great 👍

**Comment by josdejong** [comment]
In `src/js/Node.js`, there is already some similar code in place resolving references `$ref`, that may be useful, see `Node._findSchema`:

https://github.com/josdejong/jsoneditor/blob/develop/src/js/Node.js#L4387

**Comment by vitornesello** [comment]
Hi,

Thanks for the suggestions, I took a look on the parts of the code that you mentioned and I realised that the function `_findSchema` ignores completely that in the root schema it might exist a `definitions` with the references.

However, if one uses the `schemaRefs` properly (I wasn't using it properly) you can get around this. Do you stil think this is a relevant issue?

Another possible issue is that `schemaRefs` cannot be changed dynamically by the user isn't it? This is an issue for my project, but nothing that I cannot get around.

Here are a few suggestions on how to implement a fix :
* Merge the `definitions` into `schemaRefs`. This would allow for dynamically (and indirectly) updating `schemaRefs` every time the user updates the schema
* Carry the `definitions` object throughout the recursion on `_findSchema`, just like it is done for `schemaRefs`

**Comment by josdejong** [comment]
> Another possible issue is that schemaRefs cannot be changed dynamically by the user isn't it? This is an issue for my project, but nothing that I cannot get around.

You can actually change the `schema` and `schemaRefs` dynamically:

```js
JSONEditor.setSchema(schema [,schemaRefs])
```

Is that what you mean?

> Do you stil think this is a relevant issue?

I'm not sure at this point, I didn't implement this functionality so I'm not sure if I understand the underlying issue, I would have to dive into the code first. Any help would be very welcome!

**Comment by vitornesello** [comment]
Ah ok, we can indeed update the refs. That is great!

So as I said, I can proceed without changing anything on the code. If I really feel the need to improve this feature I will be happy to make a PR :D

Feel free to close this issue,
Thanks!

**Comment by josdejong** [comment]
Ok good to hear! Thanks for your feedback. 

I will close this issue now, please reopen when there is need for it.
