### ISSUE TITLE
Switch Editor Mode 

### ISSUE THREAD

**Issue by ohad1989** [josdejong/jsoneditor#983]
Hi, 

I want my switch editor mode to be similar to the one found in http://jsoneditoronline.org/
![image](https://user-images.githubusercontent.com/15841085/81445721-1dcd6f00-9182-11ea-9a9a-003cb35642c1.png)

I looked in the API and in the example and couldn't find how I can do it (I managed to do it by changing the code but it doesn't feel like the right way).

Thanks in advance!

**Comment by josdejong** [comment]
This is some customization which is not part of JSONEditor, the JSONEditor library only contains a dropdown to select the mode. It was achieved by simply loading a JSONEditor, finding the menu `DIV` using a query selector, and then adding some custom buttons in the menu.

**Comment by lake2** [comment]
same need + 1

**Comment by cmlanche** [comment]
same need + 1

**Comment by Palereed** [comment]
use css (hide .jsoneditor-modes and absolute custom buttons) and api setMode can achieve
