### ISSUE TITLE
Maximum character limit for the jsoneditor

### ISSUE THREAD

**Issue by codepillar91** [josdejong/jsoneditor#986]
I am trying to incorporate a json object which is having characters of around 70000. I can see up to 47411 characters in text mode.
Could you please suggest me if I can fit 70000 characters in jsoneditor and if yes, how?

**Comment by josdejong** [comment]
I'm not sure where the 47411 character limit comes from in your case. I just loaded a 242.6 KB file in text mode which works fine. For documents above something like 10 MB the text mode will not work smoothly anymore, in that case you can use preview mode, which can handle files up to about 500 MB.

How can I reproduce your issue?

**Comment by codepillar91** [comment]
okay. gotcha. I just copied the json in notepad to check the length.
I think it's working for me now. I overlooked the json ending braces.

You can close this issue. Thank you for your time.

**Comment by josdejong** [comment]
👍
