### ISSUE TITLE
Possible piracy?

### ISSUE THREAD

**Issue by nrdlngr** [josdejong/jsoneditor#99]
Hello, I wanted to let you know that I love your web application, but I had to find a local version that I can paste sensitive company data on, so I found this in the Apple App Store: "JSON Editor" by SUN ZHI FENG.

Anyways, I thought it was the same application (because it looks EXACTLY the same as your app), so I paid $10 for it and it REALLY sucks in comparison. Just thought you should know that I think someone has pirated your design and is making money of of your work.

**Comment by josdejong** [comment]
After help of Apple Legal, the author decided to remove the application a few days ago from the app store (its not his only app though, see [website](http://www.romanysoft.com/)). Whilst polite towards Apple Legal, this guy seems to be unhappy and is now spamming the issues section of this project. I have just reported this abuse at Github. I'm sorry for the inconvenience.
